### ISSUE TITLE
Feature request: Indexed records

### ISSUE THREAD

**Issue by ionathanch** [agda/agda#5867] opened 2022-04-20 22:37 UTC
Records currently only allow parameters; I propose being able to define indexed records as well by giving constructors type annotations. For instance, the following `data` definition:
```agda
variable
  A B : Set
data Image (f : A → B) : B → Set where
  image : ∀ x → Image f (f x)
```
could alternatively be defined as
```agda
record Image (f : A → B) : B → Set where
  field x : A
  constructor image : Image f (f x)
```
Another example: the identity type (Martin-Löf style).
```agda
record Id : A → A → Set where
  field x : A
  constructor refl : Id x x
```
Has this been suggested before? Are there any immediate problems with this? Some issues I can think of:
* You're forced to give an indexed record a named constructor (maybe `_` could indicate an unnamed constructor)
* The record definition needs to have no indices in order to declare unannotated constructors
* Not sure how this plays with other features, e.g. record modules and eta laws

**Comment by gallais** [comment] 2022-04-20 22:49
This is a duplicate of #4650 (admittedly it's not easy to find unless you know to look for @txa)

**Closed as not planned by gallais** 2022-04-20 22:49 UTC
Labels: status: duplicate
