### ISSUE TITLE
--interaction doesn't case split properly for `with foo <- bar` or `rewrite`

### ISSUE THREAD

**Issue by JoeyEremondi** [agda/agda#5160] opened 2021-01-31 02:54 UTC
Minimal example 1:
```agda
module Test where


data Bar : Set where
    Baz1 Baz2 : Bar

myfun : Bar -> Bar
myfun x with z <- (λ y -> y) x = {!x!}

```

Doing `C-c C-c` (e.g. `agda2-make-case)` on the whole generates:

```agda
myfun Baz1 | z = ?
myfun Baz2 | z = ?
```
Loading then fails with :
```
Unexpected with patterns | z
when checking the definition of myfun
```

We get the same problem with a rewrite. If instead we have:
```agda
myfun x rewrite refl {x = x} = {!x!}
```
then doing the case-split gives
```agda
myfun Baz1 | refl = ?
myfun Baz2 | refl = ?
```
which gives a similar error.

(Sorry about the open and closing, I accidentally submitted before finishing).

**Comment by jespercockx** [comment] 2021-01-31 20:58
The problem with `rewrite` is a duplicate of https://github.com/agda/agda/issues/513 (which has been open since 2011!)
The first problem seems new (which makes sense since the `<-` is a recent feature).

**Comment by jespercockx** [comment] 2021-01-31 21:06
On second thought, the first problem seems to be a duplicate of https://github.com/agda/agda/issues/3995

**Closed as completed** 2021-01-31 21:06 UTC
Labels: status: duplicate, type: bug, with, ux: case splitting, pattern guards
