### ISSUE TITLE
In record constructor, empty case split returns garbage

### ISSUE THREAD

**Issue by barrettj12** [agda/agda#5570] opened 2021-09-18 10:13 UTC
```agda
record Rec : Set₁ where
  field
    f1 : Set
    f2 : Set

C : Rec
C = record { f1 = {!   !}0 ; f2 = {!   !}1 }

D : Rec
D = record {
    f1 = {!   !}2 ;
    f2 = {!   !}3 }
```
Doing an empty case split on the holes (`C-c` `C-c` `Enter`) screws things up badly. For example, on hole 2, we get
```agda
D = record {
    Rec.f1 D = record { f1 = ? ; f2 = ? }
    Rec.f2 D = record { f1 = ? ; f2 = ? }
    f2 = {!   !} }
```
On hole 0, I get
```agda
Rec.f1 C = record { f1 = ? ; f2 = ? }
Rec.f2 C = record { f1 = ? ; f2 = ? } ; f2 = {!   !} }
```
using VSCode's `agda-mode`, while Emacs `agda-mode` gives
```agda
Rec.f1 C = record { f1 = ? ; f2 = ? }
Rec.f2 C = record { f1 = ? ; f2 = ? }
```
In each case, it should do nothing, since you can't case split on the expected result `Set`. It seems that Agda doesn't realise we're now asking for a `Set` instead of a `Rec`, and tries to apply the copatterns for `Rec`. Even when you *can* case split on the result, it tries to apply the record's copatterns instead:
```agda
record Rec2 : Set₁ where
  field
    f : Set → Set

E : Rec2
E = record { f = {!   !} }
-- gives
--   Rec2.f E = record { f = ? } }
-- instead of
--   E = record { f x = ? }
```

**Comment by andreasabel** [comment] 2021-09-18 15:34
This is a duplicate of #2628 and #2800, I think.

In general, case splitting does not work if the hole is not on the same line as the thing to split (here, `D` or `C`).  
Also, if the rhs is more than a single hole, case splitting in general produces garbage.  But in some cases, if the hole is the last thing on the line, it works.  So I figured it is better to produce garbage in some cases than outlaw the splitting altogether (see work on #2051).

**Closed as not planned** 2022-08-25 14:18 UTC
Labels: status: duplicate, ux: case splitting, record expression
