### ISSUE TITLE
Missing documentation for record types

### ISSUE THREAD

**Issue by mietek** [agda/agda#2143] opened 2016-08-16 15:13 UTC
The wiki says:

> All the components are optional, and can be given in any order. In particular, fields can be given in more than one block, interspersed with other declarations.

Unfortunately, this doesn’t always work:

``` agda
module RecordBug where


record ⊤ : Set where
  instance constructor tt

record _×_ (A B : Set) : Set where
  constructor _,_
  field
    proj₁ : A
    proj₂ : B

data Cx (U : Set) : Set where
  ⌀   : Cx U
  _,_ : Cx U → U → Cx U

data Ty : Set where
  ι   : Ty
  _▻_ : Ty → Ty → Ty


-- This is fine.
record Model₁ : Set₁ where
  field
    [_] : Ty → Set

  field
    ⟨_⟩ : Ty → Set


-- Also fine.
record Model₂ : Set₁ where
  field
    [_] : Ty → Set

  [_]⋆ : Cx Ty → Set
  [ ⌀ ]⋆     = ⊤
  [ Π , A ]⋆ = [ Π ]⋆ × [ A ]


-- This blows up.
record Model₃ : Set₁ where
  field
    [_] : Ty → Set

  [_]⋆ : Cx Ty → Set
  [ ⌀ ]⋆     = ⊤
  [ Π , A ]⋆ = [ Π ]⋆ × [ A ]

  field
    ⟨_⟩ : Ty → Set
```

> Missing definition for `[_]⋆`

**Comment by jmchapman** [comment] 2016-08-16 17:45
I think the problem is that you can't define recursive functions in a record

**Comment by andreasabel** [comment] 2016-08-16 17:57
With Agda 2.5.2, you get a better error message:

```
This declaration is illegal in a record before the last field
when scope checking the declaration
  record Model₃ where
    field [_] : Ty → Set
    mutual
      [_]⋆ : Cx Ty → Set
      [ ⌀ ]⋆ = ⊤
      [ Π , A ]⋆ = [ Π ]⋆ × [ A ]
    field ⟨_⟩ : Ty → Set
```

**Comment by mietek** [comment] 2016-08-16 21:12
I’m sorry, but I don’t understand the problem.

@jmchapman: the `[_]⋆` function is accepted as part of `Model₂` — doesn’t that rule out your explanation?

@andreasabel: the error message doesn’t explain _why_ should this declaration be illegal.

**Comment by jmchapman** [comment] 2016-08-16 21:20
@mietek Sorry, I didn't spot that earlier. I didn't realise it was ok at the end. I think the reason is that definitions in records are desugared to lets and in lets you can only define one line constants not functions by pattern matching. However, it would be nice if you could define functions by pattern matching in lets and everywhere in records, and/or the error message could be better.

**Comment by mietek** [comment] 2016-08-16 21:30
Just to be absolutely clear — the following is accepted without any errors.

``` agda
module AllGoodHere where


record ⊤ : Set where
  instance constructor tt

record _×_ (A B : Set) : Set where
  constructor _,_
  field
    proj₁ : A
    proj₂ : B

data Cx (U : Set) : Set where
  ⌀   : Cx U
  _,_ : Cx U → U → Cx U

data Ty : Set where
  ι   : Ty
  _▻_ : Ty → Ty → Ty


record Model₂ : Set₁ where
  field
    [_] : Ty → Set

  [_]⋆ : Cx Ty → Set
  [ ⌀ ]⋆     = ⊤
  [ Π , A ]⋆ = [ Π ]⋆ × [ A ]
```

**Comment by nad** [comment] 2016-08-17 08:47
See #434, #528, #917, #967, #1570, and perhaps other issues as well. I'm not sure if there is an issue tracking problems with the documentation of this quirk before, so I'm not closing this issue.

**Comment by mietek** [comment] 2016-08-17 10:03
I see the issue has been renamed. While the documentation for records could certainly be improved, the problem I tried to describe here is that two separately valid pieces of code are not valid together.

**Comment by nad** [comment] 2016-08-17 11:12
Isn't the problem you described covered by the other issues I linked to?

**Comment by mietek** [comment] 2016-08-17 13:49
No. The closest related issue seems to be problem 3 in #1720.

**Comment by mietek** [comment] 2016-08-18 00:42
I apologise for making a nuisance, but this issue is quite important to me.

@andreasabel, I would very much appreciate it if you could clarify for me whether:
1. `Model₃` should be accepted by Agda but isn’t and therefore this is a bug;
2. `Model₃` should not be accepted by Agda and isn’t and therefore this is a documentation problem.

**Comment by mietek** [comment] 2016-08-18 01:21
For your information, here’s how I’m working around this issue:

``` agda
record Model : Set₁ where
  field
    [_⊢_]  : Cx Ty → Ty → Set
    [_⊢⋆_] : Cx Ty → Cx Ty → Set

    top[⊢⋆] : ∀ {Γ}     → [ Γ ⊢⋆ ⌀ ] ≡ ⊤
    pop[⊢⋆] : ∀ {Π A Γ} → [ Γ ⊢⋆ Π , A ] ≡ ([ Γ ⊢⋆ Π ] × [ Γ ⊢ A ])

  [_⊢_]⋆ : Cx Ty → Cx Ty → Set
  [ Γ ⊢ ⌀ ]⋆     = ⊤
  [ Γ ⊢ Π , A ]⋆ = [ Γ ⊢ Π ]⋆ × [ Γ ⊢ A ]

  [⊢⋆]→[⊢]⋆ : ∀ {Π Γ} → [ Γ ⊢⋆ Π ] → [ Γ ⊢ Π ]⋆
  [⊢⋆]→[⊢]⋆ {⌀}     {Γ} ps = tt
  [⊢⋆]→[⊢]⋆ {Π , A} {Γ} ps rewrite pop[⊢⋆] {Π} {A} {Γ} = [⊢⋆]→[⊢]⋆ (proj₁ ps) , proj₂ ps

  [⊢]⋆→[⊢⋆] : ∀ {Π Γ} → [ Γ ⊢ Π ]⋆ → [ Γ ⊢⋆ Π ]
  [⊢]⋆→[⊢⋆] {⌀}     {Γ} tt       rewrite top[⊢⋆] {Γ}         = tt
  [⊢]⋆→[⊢⋆] {Π , A} {Γ} (ps , p) rewrite pop[⊢⋆] {Π} {A} {Γ} = [⊢]⋆→[⊢⋆] ps , p
```

**Comment by nad** [comment] 2016-08-18 07:41
> No. The closest related issue seems to be problem 3 in #1720. 

Your problem is that you can't define recursive functions before the last field in a record type declaration, right? This is covered by #434 (see, for instance: https://github.com/agda/agda/issues/434#issuecomment-235684127).

**Comment by andreasabel** [comment] 2016-08-18 10:15
`Model₃` should be ideally accepted by Agda but the current interpretation of record declarations does not support it.  Currently, `Model₃` is not accepted by Agda and therefore this is a documentation problem.

Ideally, someone sits down for a couple of days and changes the interpretation of record declarations as I have outlined in the referenced comment https://github.com/agda/agda/issues/434#issuecomment-235684127.

**Closed as completed** 2016-11-28 14:11 UTC
Labels: scope, records, ux: documentation
