### ISSUE TITLE
Internal error src/full/Agda/TypeChecking/Reduce/Fast.hs:1341

### ISSUE THREAD

**Issue by laMudri** [agda/agda#4495] opened 2020-03-02 14:59 UTC
The code below produces an internal error after a very particular interaction sequence.

1. Load the file.
2. Into the hole, write `? , ?` and **refine**.
3. Into the first hole produced, write `? [QED]` and **refine** or **give**.

The precise refinement in step 2 seems to be important. Furthermore, that `? [QED]` involves a mixfix operator seems to be important. Whether or not this expression has the correct type is not important.

Tested on Agda version 2.6.0.1.

```agda
module OneBug where

module _ {X : Set} where
  infix 10 _~_

  data _~_ (x : X) : X -> Set where
    r~ : x ~ x

  infixr 31 _[QED]

  postulate _[QED] : forall x -> x ~ x

infixr 2 _><_
infixr 2 _,_

record _><_ (S : Set)(T : S -> Set) : Set where
  constructor _,_
  field
    fst : S
    snd : T fst

open _><_ public

data List (X : Set) : Set where
  []     : List X
  _,-_   : X -> List X -> List X
infixr 60 _,-_

module _ {X : Set} where

  data _<:_ : List X -> List X -> Set where
    [] : [] <: []

  infix 50 _<:_

  antisym : forall {xs ys : List X}
             (th : xs <: ys)(ph : ys <: xs) ->
             xs ~ ys >< \ { r~ -> th ~ th }
  antisym {[]} {[]} th ph = r~ , r~
  antisym {x ,- xs} {y ,- ys} th ph = ?
```

**Comment by sattlerc** [comment] 2020-03-02 15:06
This is a duplicate of #4252, #3000.

**Closed as completed** 2020-03-02 16:42 UTC
Labels: status: duplicate, type: bug, ux: interaction, give
