### ISSUE TITLE
A nice way to hide instances?

### ISSUE THREAD

**Issue by ice1000** [agda/agda#3387] opened 2018-11-13 20:33 UTC
Suppose I'm trying to create a module to put some module-local stuff inside so Agda won't get confused when I create things outside the scope of the module.
However, Agda's instance resolution still get confused by module-local instances:

A very small reproducible example:

```agda
module InstanceResolution where
-- Type is an alias to Set https://ice1000.org/lagda/lib.Base.html#1144
-- List is just https://ice1000.org/lagda/lib.types.List.html#197

record Monoid {i} (A : Type i) : Type i where
  inductive
  field
    mempty : A
    _<>_   : A -> A -> A
open Monoid {{...}} public

module IWantToHideSomethingInsideThisModule where
  instance
    {-# TERMINATING #-}
    ThisIsTheInstanceIWantToHide : Monoid (List A)
    ThisIsTheInstanceIWantToHide = record
            { mempty = nil
            ; _<>_ = λ where
              nil b -> b
              (a :: as) b -> a :: (as <> b)
            }

module OkLetUsSeeWhatHappensInThisModule where
  instance
    {-# TERMINATING #-}
    ListMonoid : Monoid (List A)
    Monoid.mempty ListMonoid = nil
    Monoid._<>_   ListMonoid nil b = b
    Monoid._<>_   ListMonoid (a :: as) b = a :: (as <> b)

  _ : List Nat
  _ = mempty <> mempty -- complains that there's two instances, while I didn't find a way to hide the first one
```

Temporary solution: hide the first declaration inside a `where` statement of an arbitrary declaration

**Comment by jespercockx** [comment] 2018-11-13 21:43
This is working as intended: the instance is in scope under its qualified name `IWantToHideSomethingInsideThisModule.ThisIsTheInstanceIWantToHide`, so it's still considered by instance search. However, if you mark the instance as `private` then it's not exported by the module so it's not considered as an instance outside the module (it also works with `where` since everything in a where block is automatically private).

Before we close this issue, I think we should add this to the documentation so people don't run into the same problem in the future.

**Comment by ice1000** [comment] 2018-11-13 22:49
Nice suggestion! I didn't think of that!

**Closed as completed** 2018-11-15 17:41 UTC
Labels: instance, ux: documentation, status: working-as-intended

**Comment by ajrouvoet** [comment] 2020-03-14 13:59
@jespercockx can we perhaps re-open this issue as a place to discuss (again) whether qualified instances should be in scope?

The only way to hide instances from Agda right now is to put them in a separate file or by hiding on import. Both require you to have separate definitions for instances if you ever want to use something without bringing it into the instances scope.

It is currently quite important to have more fine-grained (manual) control over instances, as type-checking times can easily get out of control when too many instances are in scope.
