### ISSUE TITLE
Agda gets confused by changing order of projections

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#2116] opened 2016-07-26 12:24 UTC
An example:

```
open import Agda.Builtin.Nat

record R : Set₁ where
  field
    A : Set
    a : A

test : R
R.a test = {!!}
R.A test = Nat
```

This code is accepted and the type of the hole is `Nat`, but filling in `0` and reloading causes the following error:

```
Nat !=< R.A test of type Set
when checking that the expression 0 has type R.A test
```

I encountered this strange behaviour when looking into #2068.

**Comment by andreasabel** [comment] 2016-07-26 14:33
The equation `R.A test = Nat` is not available when checking the rhs of `R.a test`, since clauses are processed in order.  Thus, reloading should fail.
The problem is that all of the signature is in scope in all interaction points, thus, giving `0` succeeds.
This is an old hat.

``` agda
data D : Set where c : D

T : Set
test : T
test = ?
T = D
```

You can give `c` here but can't reload.

I am closing this, feel free to reopen if you want to do something about it, have an improvement idea, or just want to continue the discussion.

**Closed as completed by andreasabel** 2016-07-26 14:33 UTC
Labels: status: wontfix, type: bug, type-checking, copatterns, mutual

**Comment by jespercockx** [comment] 2016-07-26 14:43
I was thinking we should check the clauses in the order of the projections, not in the order they are given (or alternatively prohibit giving them in a different order). But this would require us to do check _all_ the left-hand sides before checking the right-hand sides, in order to determine the correct order in which to add them.

**Comment by andreasabel** [comment] 2016-07-26 18:38
Yes, if/when we do the "big refactoring" of LHS checking (merging with the coverage checker), then we can do this.
