### ISSUE TITLE
Master fails test "Issue3436"

### ISSUE THREAD

**Issue by mouse07410** [agda/agda#5169] opened 2021-02-04 05:31 UTC
- MacOS 10.15.7, Xcode-12.4.
- GHC-8.10.3, Cabal-3.2.0.0.
- MacTeX-2020.

```
.  .  .  .  .
diff --git a/private/var/folders/_l/4q83bg9j5ysb7qd1n9xpnb4h0000gn/T/Issue343673746-0.golden b/private/var/folders/_l/4q83bg9j5ysb7qd1n9xpnb4h0000gn/T/Issue343673746-1.actual
index 699465fef..84757769d 100644
--- a/private/var/folders/_l/4q83bg9j5ysb7qd1n9xpnb4h0000gn/T/Issue343673746-0.golden
+++ b/private/var/folders/_l/4q83bg9j5ysb7qd1n9xpnb4h0000gn/T/Issue343673746-1.actual
@@ -1,2 +1,7 @@
-AGDA_SUCCESS
+AGDA_UNEXPECTED_FAIL
 
+ret > ExitFailure 42
+out > Issue3436.agda:1,1-39
+out > Warnings for non-fatal errors such as MissingDefinitions cannot be
+out > turned off. See --help=warning.
+out >

Issue3436:                                                    Golden value differs from actual value
.  .  .  .  .
1 out of 1576 tests failed (156.45s)
```

**Comment by gallais** [comment] 2021-02-04 10:22
Yeah [I know](https://github.com/agda/agda/pull/5166#issuecomment-772810317).
I was planning to fix that today.

**Comment by mouse07410** [comment] 2021-02-04 23:13
@gallais  I'm not sure we can close this one yet - the test-run doesn't **stop** now, but it does not complete correctly either.

```
.  .  .  .  .
gmake: *** [Makefile:429: std-lib-test] Error 42
```
There's no more informative message in the captured screen output.

**Comment by gallais** [comment] 2021-02-05 09:45
Can you please link to the run in question?

Everything was green on my local build, on the PR & on my branch so I'm
not sure where I'm supposed to look for this error?

**Comment by mouse07410** [comment] 2021-02-05 15:05
> Can you please link to the run in question?

Here's all I have.  The error is mentioned at the very end of the log, with no further explanation.
And the problem seems related to the `Makefile`.
[make-test-2021-02-04.txt](https://github.com/agda/agda/files/5933318/make-test-2021-02-04.txt)
```make
std-lib-test :
        @$(call decorate, "Standard library test", \
                (cd std-lib && make Everything.agda && \
                                                time $(AGDA_BIN) $(AGDA_OPTS) --ignore-interfaces --no-default-libraries -v profile:$(PROFVERB) \
                                                                                                                 -i. -isrc README.agda \
                                                                                                                 +RTS -s))
```
Error report is for the line next to `std-lib-test :`. I'd say that it fails to execute the target `std-lib-test` at all, based on the log, because it has some issues with the command line Makefile contains.

**Comment by gallais** [comment] 2021-02-05 15:11
> /Users/ur20980/src/agda/std-lib/README/Data/List/Relation/Binary/Equality.agda:7,1-47
Warnings for non-fatal errors such as MissingDefinitions cannot be
turned off. See --help=warning.
when scope checking the declaration
  import README.Data.List.Relation.Binary.Equality

Looks like you have not pulled the updated version of the stdlib before running the test suite.
Do you still get an error on the test suite after running

```shell
make fast-forward-std-lib
```

?

**Comment by mouse07410** [comment] 2021-02-05 17:10
```
$ git submodule update --init --recursive
$ make fast-forward-std-lib 2>&1 | tee make-std-lib-2021-02-05.txt
git submodule update --init --remote std-lib
From https://github.com/agda/agda-stdlib
   3a41d190..277d19b0  gh-pages   -> origin/gh-pages
   d1f45710..52d28eb2  master     -> origin/master
Submodule path 'std-lib': checked out 'adb18526422277b7c9ec4cba5488232d81fba5ca'
cabal clean && cabal build && cabal install
Resolving dependencies...
Build profile: -w ghc-8.10.3 -O1
In order, the following will be built (use -v for more details):
 - agda-stdlib-utils-1.5 (exe:AllNonAsciiChars) (first run)
 - agda-stdlib-utils-1.5 (exe:GenerateEverything) (first run)
Warning: agda-stdlib-utils.cabal:2:25: version with tags
Configuring executable 'AllNonAsciiChars' for agda-stdlib-utils-1.5..
Warning: agda-stdlib-utils.cabal:2:25: version with tags
Configuring executable 'GenerateEverything' for agda-stdlib-utils-1.5..
Preprocessing executable 'AllNonAsciiChars' for agda-stdlib-utils-1.5..
Building executable 'AllNonAsciiChars' for agda-stdlib-utils-1.5..
Preprocessing executable 'GenerateEverything' for agda-stdlib-utils-1.5..
Building executable 'GenerateEverything' for agda-stdlib-utils-1.5..
[1 of 1] Compiling Main             ( AllNonAsciiChars.hs, /Users/ur20980/src/agda/std-lib/dist-newstyle/build/x86_64-osx/ghc-8.10.3/agda-stdlib-utils-1.5/x/AllNonAsciiChars/build/AllNonAsciiChars/AllNonAsciiChars-tmp/Main.dyn_o )
[1 of 1] Compiling Main             ( GenerateEverything.hs, /Users/ur20980/src/agda/std-lib/dist-newstyle/build/x86_64-osx/ghc-8.10.3/agda-stdlib-utils-1.5/x/GenerateEverything/build/GenerateEverything/GenerateEverything-tmp/Main.dyn_o )

GenerateEverything.hs:3:1: warning: [-Wunused-imports]
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’
    To import instances alone, use: import Control.Applicative()
  |
3 | import Control.Applicative
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

GenerateEverything.hs:15:1: warning: [-Wmissing-signatures]
    Top-level binding with no type signature: headerFile :: [Char]
   |
15 | headerFile     = "Header"
   | ^^^^^^^^^^

GenerateEverything.hs:16:1: warning: [-Wmissing-signatures]
    Top-level binding with no type signature: allOutputFile :: [Char]
   |
16 | allOutputFile  = "Everything"
   | ^^^^^^^^^^^^^

GenerateEverything.hs:17:1: warning: [-Wmissing-signatures]
    Top-level binding with no type signature: safeOutputFile :: [Char]
   |
17 | safeOutputFile = "EverythingSafe"
   | ^^^^^^^^^^^^^^

GenerateEverything.hs:18:1: warning: [-Wmissing-signatures]
    Top-level binding with no type signature: srcDir :: [Char]
   |
18 | srcDir         = "src"
   | ^^^^^^

GenerateEverything.hs:112:15: warning: [-Wname-shadowing]
    This binding for ‘mod’ shadows the existing binding
      imported from ‘Prelude’ at GenerateEverything.hs:1:1
      (and originally defined in ‘GHC.Real’)
    |
112 | extractHeader mod = extract
    |               ^^^

GenerateEverything.hs:118:19: warning: [-Wunused-matches]
    Defined but not used: ‘rest’
    |
118 |     , (info, d2 : rest) <- span ("-- " `List.isPrefixOf`) ss
    |                   ^^^^

GenerateEverything.hs:218:1: warning: [-Wmissing-signatures]
    Top-level binding with no type signature: main :: IO ()
    |
218 | main = do
    | ^^^^

GenerateEverything.hs:227:3: warning: [-Wname-shadowing]
    This binding for ‘header’ shadows the existing binding
      defined at GenerateEverything.hs:189:5
    |
227 |   header  <- readFileUTF8 headerFile
    |   ^^^^^^
Linking /Users/ur20980/src/agda/std-lib/dist-newstyle/build/x86_64-osx/ghc-8.10.3/agda-stdlib-utils-1.5/x/AllNonAsciiChars/build/AllNonAsciiChars/AllNonAsciiChars ...
Linking /Users/ur20980/src/agda/std-lib/dist-newstyle/build/x86_64-osx/ghc-8.10.3/agda-stdlib-utils-1.5/x/GenerateEverything/build/GenerateEverything/GenerateEverything ...
Wrote tarball sdist to
/Users/ur20980/src/agda/std-lib/dist-newstyle/sdist/agda-stdlib-utils-1.5.tar.gz
Resolving dependencies...
Up to date
Symlinking 'AllNonAsciiChars'
Symlinking 'GenerateEverything'
cabal exec -- GenerateEverything
Resolving dependencies...
$ 
$
```

Now running tests brings the following errors in `  LaTeXAndHTML`:
```tex
diff --git a/private/var/folders/_l/4q83bg9j5ysb7qd1n9xpnb4h0000gn/T/AccidentalSpacesBeforeEndCode_LaTeX1590-0.golden b/private/var/folders/_l/4q83bg9j5ysb7qd1n9xpnb4h0000gn/T/AccidentalSpacesBeforeEndCode_LaTeX1590-1.actual
index c3a1efb2b..c92cc588c 100644
--- a/private/var/folders/_l/4q83bg9j5ysb7qd1n9xpnb4h0000gn/T/AccidentalSpacesBeforeEndCode_LaTeX1590-0.golden
+++ b/private/var/folders/_l/4q83bg9j5ysb7qd1n9xpnb4h0000gn/T/AccidentalSpacesBeforeEndCode_LaTeX1590-1.actual
@@ -1,13 +1 @@
-\documentclass{article}
-
-\usepackage{agda}
-
-\begin{document}
-
-\begin{code}%
-\>[0]\AgdaKeyword{module}\AgdaSpace{}%
-\AgdaModule{AccidentalSpacesBeforeEndCode}\AgdaSpace{}%
-\AgdaKeyword{where}\<%
-\end{code}
-
-\end{document}
+LATEX_COMPILE_FAILED with lualatex
\ No newline at end of file
```

```tex
diff --git a/private/var/folders/_l/4q83bg9j5ysb7qd1n9xpnb4h0000gn/T/Issue1062_QuickLaTeX1590-8.golden b/private/var/folders/_l/4q83bg9j5ysb7qd1n9xpnb4h0000gn/T/Issue1062_QuickLaTeX1590-9.actual
--- a/private/var/folders/_l/4q83bg9j5ysb7qd1n9xpnb4h0000gn/T/Issue1062_QuickLaTeX1590-8.golden
+++ b/private/var/folders/_l/4q83bg9j5ysb7qd1n9xpnb4h0000gn/T/Issue1062_QuickLaTeX1590-9.actual
@@ -1,379 +1 @@
-\nonstopmode
-\documentclass{article}
-
-\usepackage{agda}
-
-\begin{document}
-\begin{code}%
-\>[0]\<%
-\\
-\>[0]\AgdaSymbol{\{-\#}\AgdaSpace{}%
-\AgdaKeyword{OPTIONS}\AgdaSpace{}%
-\AgdaPragma{--copatterns}\AgdaSpace{}%
-\AgdaPragma{--sized-types}\AgdaSpace{}%
-\AgdaSymbol{\#-\}}\<%
-\\
-%
-\\[\AgdaEmptyExtraSkip]%
-\>[0]\AgdaSymbol{\{-\#}\AgdaSpace{}%
-\AgdaKeyword{BUILTIN}\AgdaSpace{}%
-\AgdaKeyword{SIZE}%
-\>[20]\AgdaPostulate{Size}%
-\>[27]\AgdaSymbol{\#-\}}\<%
-\\
-\>[0]\AgdaSymbol{\{-\#}\AgdaSpace{}%
-\AgdaKeyword{BUILTIN}\AgdaSpace{}%
-\AgdaKeyword{SIZELT}%
-\>[20]\AgdaOperator{\AgdaPostulate{Size<\AgdaUnderscore{}}}\AgdaSpace{}%
-\AgdaSymbol{\#-\}}\<%
-\\
-\>[0]\AgdaSymbol{\{-\#}\AgdaSpace{}%
-\AgdaKeyword{BUILTIN}\AgdaSpace{}%
-\AgdaKeyword{SIZESUC}\AgdaSpace{}%
-\AgdaOperator{\AgdaPostulate{↑\AgdaUnderscore{}}}%
-\>[27]\AgdaSymbol{\#-\}}\<%
-\\
-\>[0]\AgdaSymbol{\{-\#}\AgdaSpace{}%
-\AgdaKeyword{BUILTIN}\AgdaSpace{}%
-\AgdaKeyword{SIZEINF}\AgdaSpace{}%
-\AgdaPostulate{∞}%
-\>[27]\AgdaSymbol{\#-\}}\<%
-\\
-%
-\\[\AgdaEmptyExtraSkip]%
-\>[0]\AgdaKeyword{data}\AgdaSpace{}%
-\AgdaDatatype{List}\AgdaSpace{}%
-\AgdaSymbol{(}\AgdaBound{A}\AgdaSpace{}%
-\AgdaSymbol{:}\AgdaSpace{}%
-\AgdaPrimitive{Set}\AgdaSymbol{)}\AgdaSpace{}%
-\AgdaSymbol{:}\AgdaSpace{}%
-\AgdaPrimitive{Set}\AgdaSpace{}%
-\AgdaKeyword{where}\<%
-\\
-\>[0][@{}l@{\AgdaIndent{0}}]%
-\>[2]\AgdaInductiveConstructor{[]}\AgdaSpace{}%
-\AgdaSymbol{:}\AgdaSpace{}%
-\AgdaDatatype{List}\AgdaSpace{}%
-\AgdaBound{A}\<%
-\\
-%
-\>[2]\AgdaOperator{\AgdaInductiveConstructor{\AgdaUnderscore{}∷\AgdaUnderscore{}}}\AgdaSpace{}%
-\AgdaSymbol{:}\AgdaSpace{}%
-\AgdaSymbol{(}\AgdaBound{x}\AgdaSpace{}%
-\AgdaSymbol{:}\AgdaSpace{}%
-\AgdaBound{A}\AgdaSymbol{)}\AgdaSpace{}%
-\AgdaSymbol{(}\AgdaBound{xs}\AgdaSpace{}%
-\AgdaSymbol{:}\AgdaSpace{}%
-\AgdaDatatype{List}\AgdaSpace{}%
.  .  .  .  .
-\>[26]\AgdaKeyword{in}%
-\>[31]\AgdaBound{l}\AgdaSpace{}%
-\AgdaOperator{\AgdaFunction{++ˢ}}\AgdaSpace{}%
-\AgdaFunction{unfold⁺}\AgdaSpace{}%
-\AgdaBound{step}\AgdaSpace{}%
-\AgdaBound{s′}\<%
-\end{code}
-Problem: The ∷ in the last let statement is not colored with constructor color.
-\end{document}
+LATEX_COMPILE_FAILED with lualatex
\ No newline at end of file
```

Overall:
```
.  .  .  .  .
    Issue1062_LaTeX:                                   OK (6.81s)
    Issue1062_QuickLaTeX:                              Golden value differs from actual value.
                                                       Accept actual value as new golden value? [yn] n
                                                       FAIL
                                                       Golden value does not match actual output.
    Issue1241_HTML:                                    OK (0.81s)
  .  .  .  .  .
    Issue2401_HTML:                                    OK (0.32s)
    Issue2401_LaTeX:                                   Golden value differs from actual value.
                                                       Accept actual value as new golden value? [yn] n
                                                       FAIL
                                                       Golden value does not match actual output.
    Issue2401_QuickLaTeX:                              OK (7.60s)

 UnicodeInput_QuickLaTeX:                           OK (5.06s)
    ltgt_HTML:                                         OK (0.35s)
    ltgt_LaTeX:                                        Golden value differs from actual value.
                                                       Accept actual value as new golden value? [yn] n
                                                       FAIL
                                                       Golden value does not match actual output.
    ltgt_QuickLaTeX:                                   OK (5.97s)
    Σ_HTML:                                            OK (0.86s)
    doc-user-manual-tools-acmart-pdflatex_LaTeX:       Golden value differs from actual value.
                                                       Accept actual value as new golden value? [yn] 
                                                       Invalid answer.
                                                       Accept actual value as new golden value? [yn] n
                                                       FAIL
                                                       Golden value does not match actual output.
    doc-user-manual-tools-acmart-pdflatex_QuickLaTeX:  Golden value differs from actual value.
                                                       Accept actual value as new golden value? [yn] n
                                                       FAIL
                                                       Golden value does not match actual output.
    doc-user-manual-tools-article-pdflatex_LaTeX:      OK (3.92s)
    doc-user-manual-tools-article-pdflatex_QuickLaTeX: OK (3.92s)
    doc-user-manual-tools-beamer-pdflatex_LaTeX:       OK (5.89s)
    doc-user-manual-tools-beamer-pdflatex_QuickLaTeX:  OK (5.90s)

7 out of 215 tests failed (3676.78s)
gmake: *** [Makefile:409: latex-html-test] Error 1
```

**Comment by gallais** [comment] 2021-02-06 16:24
I don't think the remaining errors are related to the changes I made to fix #5029

**Comment by mouse07410** [comment] 2021-02-07 05:44
> I don't think the remaining errors are related to the changes I made to fix #5029

I don't know, and I'm not claiming they are. I'm simply reporting what's occurring on my machine. A bunch of LaTeX-related tests were failing, then they were passing but Issue3436 failed, and then Issue3436 became fine but LaTeX failures came back.

**Comment by gallais** [comment] 2021-02-07 14:33
I was just explaining why I was removing my assignment.
This is more of a #5133 than a #5029 problem AFAIU and I am a bit
too busy to look into that.

**Comment by andreasabel** [comment] 2021-02-08 08:59
Looks like this issue is now a duplicate of #5133.  I am closing this, since #5133 is open.

**Closed as completed by andreasabel** 2021-02-08 08:59 UTC
Labels: infra: test suite, ux: warnings, not-in-changelog
