### ISSUE TITLE
Generalisable variables generate unknown and explicit parameters

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda#3912] opened 2019-07-11 19:29 UTC
I was trying to define dinatural transformation in https://github.com/agda/agda-categories, and I put the code in this gist: https://gist.github.com/HuStmpHrrr/d54d157a4160472d7058f87ec49e3c21

In this two lines I was trying to define a function 

```agda
_<∘_ : NaturalTransformation G H → DinaturalTransformation F G → DinaturalTransformation F H
_<∘_ = {!!}
```

I expect that there are only two explicit variables. however, in the hole, I can see the following:

```
Goal: (C.1 : Set C.o) (C.2 : Relation.Binary.Core.Rel C.1 C.ℓ)
      (C.3 : {A B : C.1} → Relation.Binary.Core.Rel (C.2 A B) C.e)
      (C.4 : {A : C.1} → C.2 A A)
      (C.5 : {A B C : C.1} → C.2 B C → C.2 A B → C.2 A C)
      (C.6
       : {A B C : C.1} {D = D₁ : C.1} {f : C.2 A B} {g : C.2 B C}
         {h : C.2 C D₁} →
         C.3 (C.5 (C.5 h g) f) (C.5 h (C.5 g f)))
      (C.7 : {A B : C.1} {f : C.2 A B} → C.3 (C.5 C.4 f) f)
      (C.8 : {A B : C.1} {f : C.2 A B} → C.3 (C.5 f C.4) f)
      (C.12
       : {A B C : C.1} {f h : C.2 B C} {g i : C.2 A B} →
         C.3 f h → C.3 g i → C.3 (C.5 f g) (C.5 h i))
      (C.9 : {A B : C.1} → Relation.Binary.Core.Reflexive C.3)
      (C.10 : {A B : C.1} → Relation.Binary.Core.Symmetric C.3)
      (C.11 : {A B : C.1} → Relation.Binary.Core.Transitive C.3)
      {F H G
       : Bifunctor
         (Category.op
          (record
           { Obj = C.1
           ; _⇒_ = C.2
           ; _≈_ = C.3
           ; id = C.4
           ; _∘_ = C.5
           ; assoc = C.6
           ; identityˡ = C.7
           ; identityʳ = C.8
           ; equiv =
               λ {A} {B} → record { refl = C.9 ; sym = C.10 ; trans = C.11 }
           ; ∘-resp-≈ = C.12
           }))
         (record
          { Obj = C.1
          ; _⇒_ = C.2
          ; _≈_ = C.3
          ; id = C.4
          ; _∘_ = C.5
          ; assoc = C.6
          ; identityˡ = C.7
          ; identityʳ = C.8
          ; equiv =
              λ {A} {B} → record { refl = C.9 ; sym = C.10 ; trans = C.11 }
          ; ∘-resp-≈ = C.12
          })
         D} →
      NaturalTransformation G H →
      DinaturalTransformation F G → DinaturalTransformation F H
————————————————————————————————————————————————————————————
D   : Category D.o D.ℓ D.e  (not in scope)
D.e : Level  (not in scope)
D.ℓ : Level  (not in scope)
D.o : Level  (not in scope)
C.e : Level  (not in scope)
C.ℓ : Level  (not in scope)
C.o : Level  (not in scope)
```

This is strange: why `C` cannot be generalized? Is it a bug or limitation?

**Comment by HuStmpHrrr** [comment] 2019-07-11 19:38
If the definition explicitly mentions `C` then it is fine. (notice that `D` remains generalized.)

```agda
_<∘_ : ∀ {C : Category o ℓ e} {F G H : Bifunctor (Category.op C) C D} → NaturalTransformation G H → DinaturalTransformation F G → DinaturalTransformation F H
_<∘_ = {!!}
```

**Comment by UlfNorell** [comment] 2019-12-04 12:17
Most likely a duplicate of #3695. Reopen if required.

**Closed as completed by UlfNorell** 2019-12-04 12:17 UTC
Labels: generalize
