### ISSUE TITLE
Add erased annotations automatically (e.g. to parameters of projections)

### ISSUE THREAD

**Issue by nad** [agda/agda#5057] opened 2020-11-13 23:42 UTC
In the following code `works` is accepted, but not `fails`:
```agda
{-# OPTIONS --without-K #-}

open import Agda.Builtin.Sigma

postulate
  F : (@0 A : Set) (B : A → Set) (x : A) → B x → Set

Works : (@0 A : Set) (B : A → Set) → Σ A (λ x → B x) → Set
Works A B (x , y) = F A B x y

Fails : (@0 A : Set) (B : A → Set) → Σ A (λ x → B x) → Set
Fails A B p = F A B (fst p) (snd p)
```
I thought that `Works` was supposed to be syntactic sugar for `Fails`. If that is the case, then both definitions should be treated in the same way.

**Comment by UlfNorell** [comment] 2020-11-14 08:31
It's not syntactic sugar. Record patterns are still around in the case trees. That doesn't necessarily mean that they both shouldn't work though.

*Meta comment: A lot of your bug reports are very terse, in many cases (like this) just giving some code and saying that it doesn't work, without even providing the error message. It would be very helpful if you could elaborate a bit on the failure and provide some preliminary analysis/theories as to what the problem might be.*

**Comment by nad** [comment] 2020-11-15 19:00
Things that are defined as syntactic sugar in the specification of a language do not have to be implemented by simple expansion.

Anyway, Agda fails to solve some implicit arguments in `Fails`: the `A` arguments of `fst` and `snd`, and the `fst` argument of `snd`. This is not surprising, because `A` is erased, and the `A` arguments of `fst` and `snd` are not erased. One way to fix the discrepancy between `Works` and `Fails` might be to make the `A` arguments erased (but it is not entirely obvious how to accomplish this, see #4786).

**Comment by andreasabel** [comment] 2020-11-16 16:29
> I thought that `Works` was supposed to be syntactic sugar for `Fails`.

I agree, but making that work requires effort in the type checker.  (Unfortunately, the checkable typing judgment does not have all the nice properties of the semantic typing judgement---thinking of subject reduction, eta reduction/expansion and the like.)

[My comment does not contribute anything towards a solution of this issue and can be ignored.]

**Comment by UlfNorell** [comment] 2021-02-03 14:19
Currently we are not adding any "erased" annotations other than what the user puts in, but this is something we might consider doing.

**Comment by UlfNorell** [comment] 2021-02-03 15:14
Duplicate of #4786

**Closed as completed by UlfNorell** 2021-02-03 15:14 UTC
Labels: status: duplicate, type: enhancement, erasure
