### ISSUE TITLE
Proof search bug

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#1628] opened 2015-08-15 12:14 UTC
``` agda
open import Relation.Binary.Core using (_≡_ ; refl)

Transitive : ∀ {ℓ} {t : Set ℓ} → (t → t → Set) → Set _
Transitive f = ∀ a b c → f a b → f b c → f a c

trans≡ : {t : Set} → Transitive (λ (x : t) y → x ≡ y)
trans≡ a .a .a refl refl = ?

```

When I do a proof search on `?` with `C-C C-A`, it says `An internal error has occurred. Please report this as a bug.`

**Comment by asr** [comment] 2015-08-15 15:55
Please add the error message complete.

**Comment by identicalsnowflake** [comment] 2015-08-15 16:19
Ah, that would probably be helpful, wouldn't it. It says `Location of the error: src/full/Agda/TypeChecking/Monad/Trace.hs:55`.

**Comment by asr** [comment] 2015-08-15 16:59
The issue is already fixed. Duplicate of https://github.com/agda/agda/issues/1623.

**Closed as completed by asr** 2015-08-15 16:59 UTC
Labels: auto
