### ISSUE TITLE
emacs24: "selecting deselected buffer" triggered by agda2-mode in unrelated modes

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2698] opened 2017-08-16 13:23 UTC
I see the following behavior:
1. Start emacs24, loading the desktop which contains .agda files (and much more).
2. Before I have located to any .agda buffer, I do a `C-c C-c LaTeX` in a .tex buffer.
3. After compilation returns, I get tons of `error in process buffer: selecting deselected buffer`.  They are coming in 1sec intervals.

I can stop this by locating an `.agda` buffer, doing a `C-c C-x C-r` (as `C-c C-l` does not work right away, see #2421) and a `C-c C-l`.

When I return to my `.tex` buffer, and call latex again, I get no more `selecting deselected buffer` errors.

Googling for this error I found some hints that this error is caused by invokations of `with-current-buffer`.  We have plenty of these calls in our emacs mode (see agda2.el).

**Comment by nad** [comment] 2017-08-22 19:14
Can you construct a reproducible test case? Does this not affect GNU Emacs 25?

**Comment by andreasabel** [comment] 2017-08-23 06:59
I have not tried Emacs 25,  my system is on 24.
Constructing a test case would take some time I do not have right now.

**Comment by andreasabel** [comment] 2017-08-28 11:51
Maybe related to this issue: The .agda buffers restored with the desktop are not in agda2-mode.

**Comment by nad** [comment] 2018-01-30 19:55
I'm closing this issue due to the lack of a concrete test case. Feel free to open it again if a test case is constructed.

**Closed as completed by nad** 2018-01-30 19:55 UTC
Labels: status: info-needed, type: bug, ux: emacs

**Comment by andreasabel** [comment] 2018-11-07 13:33
Issue still exists.
