### ISSUE TITLE
Agda fails to build with happy 1.19.6

### ISSUE THREAD

**Issue by Blaisorblade** [agda/agda#2731] opened 2017-09-04 18:19 UTC
The full error is in Happy generated output, and shown here:
https://gist.github.com/Blaisorblade/99db535d414e3011f0d9f647bca9f2a9.

It appears similar to simonmar/happy#94, but I haven't tried confirming it's the same issue.

Building Agda with Stackage LTS 8.24 (and happy 1.19.5) does not trigger the error, but building Agda 2.5.2 with Stackage LTS 9.3 (and happy 1.19.6) does. Which is a bit surprising since that Agda version is part of that Stackage snapshot. If Stackage built Agda, I suspect it had an old happy lying around.

Warning for would be reproducers: Between builds, I had to remove the generated `Parser.hs` from the build folder, and more in general `.stack-work/dist/` to prevent mixing incompatible outputs.

To reproduce, specify LTS 9.3 in `stack.yaml` and call `stack build`. Sample console log:

```
$ cat stack.yaml
resolver: lts-9.3

# Local packages, usually specified by relative directory name
packages:
- '.'

$ stack build
[... errors above ...]
```

**Comment by nad** [comment] 2017-09-04 19:16
Perhaps this issue should be fixed before the next release (#2659).

**Comment by asr** [comment] 2017-09-04 19:19
I could reproduce the problem using the latest versions of alex, cabal-install, GHC and happy.

**Comment by asr** [comment] 2017-09-04 19:20
> Perhaps this issue should be fixed before the next release (#2659).

I agree.

**Comment by Blaisorblade** [comment] 2017-09-05 02:05
simonmar/happy#94 (due to https://github.com/simonmar/happy/pull/49) seems now indeed related; it *seems* a workaround might be to add type signatures to productions that have none.

**Comment by asr** [comment] 2017-09-05 04:57
> it *seems* a workaround might be to add type signatures to productions that have none.

@Blaisorblade, you were absolutely right. Thanks!

**Comment by asr** [comment] 2017-09-05 05:03
Oops, I should add a flag to avoid that the issue occurs again.

**Comment by asr** [comment] 2017-09-05 05:16
It wasn't possible because happy generates top-level functions without type signatures.

**Closed as completed by asr** 2017-09-05 05:16 UTC
Labels: type: bug, build-failure, happy

**Comment by asr** [comment] 2017-09-10 16:40
> Which is a bit surprising since that Agda version is part of that Stackage snapshot.

I agree. Agda 2.5.2 and Happy 1.19.6 shouldn't be include in the same LTS. I filed https://github.com/fpco/stackage/issues/2851.
