### ISSUE TITLE
Wrongly fully qualified constructors on pattern matching when importing from a parametrized module

### ISSUE THREAD

**Issue by carlostome** [agda/agda#3804] opened 2019-05-24 09:21 UTC
Given a parametrized module:

```agda
open import Level
import Algebra as A
module Type (𝓛 : A.Monoid 0ℓ 0ℓ) where

  data Type  : Set where
    Int : Type
    Bool : A.Monoid.Carrier 𝓛 → Type
```
After importing this module passing the parameter, if I try to define a function
by pattern matching on a value of type `Type`:
```agda
open import Level
import Algebra as A
module Term (𝓛 : A.Monoid 0ℓ 0ℓ) where

  open import Type 𝓛

  foo : Type → Type
  foo x = {!!}
```
Then I get the constructors from `Type` wrongly qualified and an error:
```agda
  foo : Type → Type
  foo Type.Type.Int = ?
  foo (Type.Type.Bool x) = ?
```

I'm using Agda compiled from the master branch on commit: 

`ae72a869d63e21c39e50da262212db5e32018f56`

**Comment by gallais** [comment] 2019-05-24 09:34
This is a duplicate of #3209 I believe.

**Closed as completed** 2019-05-24 09:34 UTC
Labels: status: duplicate
