### ISSUE TITLE
Case-split generates code containing internal module name

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#896] opened 2015-08-08 18:05 UTC
```
What's the problem?

I have two modules, each in a separate file, as follows:

module Other (parameter : Set) where
  data Foo : Set where
    foo : Foo

module Bug where
  postulate
    something : Set

  open import Other something

  bar : Foo → Foo
  bar x = {!x!}                       -- I do C-c C-c here
  -- bar .#Other-230273218.foo = ?    -- I get this
  -- bar foo = ?                      -- I want this

Problem: If I do a case split in the hole in module Bug, I get some internal 
name instead of just foo. Seems to be related to "open import" vs "open" and 
then "import" as well as importing a module with parameters.

What version of Agda are you using?

Agda HEAD (Agda version 2.3.3).
```

Original issue reported on code.google.com by `ren...@informatik.uni-tuebingen.de` on 6 Sep 2013 at 4:08

**Comment by andreasabel** [comment] 2015-08-27 16:05
Duplicate of #1635.

**Closed as completed by andreasabel** 2015-08-27 16:05 UTC
Labels: type: bug, modules, ux: display
