### ISSUE TITLE
MAlonzo hits IMPOSSIBLE

### ISSUE THREAD

**Issue by phile314** [agda/agda#1839] opened 2016-02-14 23:00 UTC
As reported by Sergei (https://lists.chalmers.se/pipermail/agda/2016/008534.html):

<pre>
-----------------------------
Compiling Structures1
in /home/mechvel/agda/tosave/bugs/feb14-2016/Structures1.agdai
to /home/mechvel/agda/tosave/bugs/feb14-2016/MAlonzo/Code/Structures1.hs
Unbound name: Structures1.OfMonoidHomo.recCon-NOT-PRINTED
[157]@263218534
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Reduce/Monad.hs:174
-----------------------------

This is for  ghc-7.10.2, MAlonzo, Debian Linux.

Main.agda  is made by  agda -c,  
it is only  

-------------------------------------------- Main.agda ---
open import Foreign.Haskell
open import IO.Primitive
open import Data.String using (toCostring)

open import Structures1 

main : IO Unit
main = putStrLn (toCostring "done")
----------------------------------------------

But if I merge  Main.agda  to  Structures1.agda  then it is compiled
(!).
</pre>

I also encountered this when compiling the stdlib (4d435230c99ca97cd295b5475a38c45dd39b89f3):

<pre>
Compiling Category.Monad.Partiality in /home/philipp/Projects/agda/agda/std-lib/src/Category/Monad/Partiality.agdai to /home/philipp/Projects/agda/agda/std-lib/MAlonzo/Code/Category/Monad/Partiality.hs
Unbound name: Category.Monad.Partiality._.EqA.Rel.now [0,2,4,1028,1042,150,1078]@27349703
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Reduce/Monad.hs:174
</pre>

It only seems to happen for imported files, the main file doesn't cause this error. Some chaotic bisection points to the commt  4ec8443a61a0c574ba03977652dbbb764b1a1447 , but I might have made a mistake.

@UlfNorell

**Comment by asr** [comment] 2016-02-15 02:13
> I also encountered this when compiling the stdlib

I couldn't reproduce the issue in maint-2.4.

**Comment by UlfNorell** [comment] 2016-02-15 05:48
Looks like a problem with the dead code elimination since it's only when compiling and not if you merge modules. 4ec8443 shouldn't have affected that, but it's not impossible. I'll check it out.

**Comment by UlfNorell** [comment] 2016-02-15 10:50
Shrunk test case:

``` agda
module _ where

module M (A : Set₁) where
  data D : Set where
    d : D

private open module EqA = M Set using ()
```

It does indeed look like 4ec8443 is the culprit. Investigation continuing...

Note that it only fails when you compile from an existing `.agdai` file.

**Comment by UlfNorell** [comment] 2016-02-15 11:36
The problem was that dead-code elimination didn't look inside display forms, so there could be display forms mentioning names that had been eliminated. 4ec8443 introduced display forms for constructors and for some reason the problem only shows up for constructor display forms.

Fixed by removing display forms involving dead names during dead-code elimination.

**Comment by asr** [comment] 2016-02-15 11:54
@UlfNorell add a test case, please.

**Comment by UlfNorell** [comment] 2016-02-15 12:13
I don't know how to do that in the current test framework. To provoke the bug you need to first type check the file and then, in a separate call, compile it.

**Comment by asr** [comment] 2016-02-15 12:36
> I don't know how to do that in the current test framework. To provoke the bug you need to first type check the file and then, in a separate call, compile it.

@phile314 could you help us here?

**Comment by UlfNorell** [comment] 2016-02-15 15:37
My pruning of display forms was a little too aggressive, also removing display forms mentioning names from other modules. This I can make a test case for though...

**Closed as completed** 2016-02-15 15:50 UTC
Labels: type: bug, backend: ghc, regression on master, dead-code
