### ISSUE TITLE
Proposal: start shipping stack (or Cabal) configuration for reproducible builds

### ISSUE THREAD

**Issue by Blaisorblade** [agda/agda#2005] opened 2016-06-06 16:15 UTC
I'd like to contribute stack configs to support reproducible builds of Agda, so that I can ensure an Agda codebase can be rechecked in the future by simply copying the stack config from github.

If using Stack is controversial, I understand reproducible builds could also be provided through cabal via `cabal freeze`.

Here's a Stack config for Agda 2.5.1/2.5.2:
https://gist.github.com/Blaisorblade/071aa2014f31e417d0c09f9ae4584e0b
# Motivation

We all know that Agda codebases aren't guaranteed to be portable across Agda versions (and the porting can be quite hard). What I also learned is that building old Agda versions can be extremely hard, simply because (as we know) by default Cabal doesn't offer reproducible builds — I've also gained concrete experience with that, even ignoring #2000 (which is related though).
## Experience building old Agdas

Concretely, I've set up Travis integration for my Agda 2.4.0.2 codebase — which first builds Agda. However, Hackage changes often break the build, and the easiest fix was to switch to Stack.
https://travis-ci.org/inc-lc/ilc-agda/builds/118602448

**Comment by mietek** [comment] 2016-06-06 16:41
I’m in favour of providing a `cabal freeze` file together with each Agda release.

**Comment by scott-fleischman** [comment] 2016-06-06 17:08
I've had people successfully build Agda 2.5.1 by installing `stack` then running `stack install --resolver nightly-2016-05-08 Agda`. I imagine it should work now with `--resolver lts-6.2` but I haven't tried it.

**Comment by asr** [comment] 2016-06-08 02:35
I'm not familiar with `stack`. The latest released version (2.5.1) is in Stackage, isn't it enough?

**Comment by asr** [comment] 2016-06-08 02:38
> I’m in favour of providing a cabal freeze file together with each Agda release.

Agda currently supports four versions of GHC. Can I use the same `cabal freeze` file for different versions of GHC?

**Comment by scott-fleischman** [comment] 2016-06-08 14:24
Yes, I believe having released versions of Agda in Stackage is enough. I guess my point was that since Agda is in Stackage, it's a one-line command at the terminal to build and install Agda using the [stack](http://haskellstack.org/) tool.

The following command should build/install Agda 2.5.1. This works because Agda-2.5.1 is in Stackage [LTS Haskell 6.2](https://www.stackage.org/lts-6.2)
`stack install --resolver lts-6.2 Agda`

This should build/install Agda 2.4.2.5. See [LTS 5.18](https://www.stackage.org/lts-5.18)
`stack install --resolver lts-5.18 Agda`

**Comment by Blaisorblade** [comment] 2016-06-08 15:35
## Regarding stack

> Yes, I believe having released versions of Agda in Stackage is enough. I guess my point was that since Agda is in Stackage, it's a one-line command at the terminal to build and install Agda using the stack tool.

I agree this helps a lot for some scenarios, but is not enough in other ones. I'd volunteer to support them with at least Stack.
- We can debate whether to support the other ones I list below — and you might decide you don't are about all the advantages I list (which would be reasonable).
- Or you can accept contributions and then I can contribute the build files and even maintain them. The care for reproducible builds is not so strong, so if I care I should contribute them. Also, I guess most people aren't as picky as me and colleagues on Agda versions.

I'd propose to go all the way to fully reproducible builds also for developments.
The killer apps are:
- it ensures you can bisect regressions down to the original commit automatically, with sth. like `git bisect run "stack build && path/to/built/agda Testfile.agda"`.
- it ensures you can keep checking an Agda codebase as soon as the author specifies which exact Agda version he used (which many careful authors already do and which is required).
  That would have helped me bisecting #1985; without reproducible builds, bisecting regressions might not be worth the time.

Agda on Stackage helps in some scenarios, probably the most common ones, but it doesn't ensure a user can check a codebase unless authors collaborate. Even if they specify the Agda version they used, you need to:
- hope it was a release (seldom the case for me)
- hope it is on Stackage
- find the right Stackage snapshot.

Now, authors could do that for you, and having Agda on Stackage can make that easier, but doesn't guarantee it.

## Regarding cabal freeze

> Agda currently supports four versions of GHC. Can I use the same cabal freeze file for different versions of GHC?

I think no, because the point of a reproducible build is to prevent changing the version of any dependency, so that you compile the same sources (also for dependencies) and get essentially the same binary. Technically, the cabal freeze output would pick a version of `base` ([as in this example in the announcement](http://blog.johantibell.com/2014/04/announcing-cabal-120.html)), which picks a version of GHC. I'd expect the rest of the file to change a lot as well.

So, if you want to support reproducible builds for all those versions, you need a bit more effort (though it can be automated to some extent).

With Stack, it'd be easier to support reproducible builds for only one GHC version: if a stack user has another GHC version, stack will still install the needed one automatically*. (Modulo a few caveats, but they apply seldom).

But you could at least test those files in continuous integrations, or even generate them when the old one stops working. You'd need to upgrade to cabal 1.20 though apparently [since cabal freeze was introduced there](http://blog.johantibell.com/2014/04/announcing-cabal-120.html), at least for generating the configs (maybe not for reading them), instead of 1.18 as you use for old GHCs (https://github.com/agda/agda/blob/master/.travis.yml#L100).

**Comment by asr** [comment] 2016-06-08 15:56
> I can contribute the build files and even maintain them.

Dear `stack` configuration maintainer :-) 

Please create a PR using the stable-2.5 branch.

**Comment by andreasabel** [comment] 2016-06-09 07:13
@Blaisorblade Please go ahead and add this feature! Please be prepared to maintain it as well.

**Comment by asr** [comment] 2016-06-10 14:38
@Blaisorblade Shouldn't  `stack.yaml` be added to the `extra-source-files` field in `Agda.cabal`?

**Comment by asr** [comment] 2016-06-20 15:15
@Blaisorblade please add the new stack support to the section "Installation and infrastructure" of `doc/release-notes/2.5.2.txt`.

**Comment by nad** [comment] 2016-06-21 11:21
@Blaisorblade: I guess it would be a good idea to also document this in the manual (along with use cases).

**Comment by Blaisorblade** [comment] 2016-06-21 13:24
Docs in the manual is a good idea. Since I can't do this right now, reopening the issue.

**Comment by asr** [comment] 2017-02-13 02:21
> Docs in the manual is a good idea. Since I can't do this right now, reopening the issue.

One year later...

**Comment by EdNutting** [comment] 2019-08-24 14:15
@Blaisorblade + others:

What's the status of "docs in the manual"? Would you like some help? 
And how well maintained is Stack support?

**Comment by Blaisorblade** [comment] 2019-08-24 14:48
@EdNutting Sorry for dropping the ball on the docs. Stack is still used in Travis.
IIRC, what I wanted to document was why and how, to make your Agda codebase reproducible, you could just include a stack.yaml pointing to the commit you wanted, for any version with a stack.yaml. My documentation plans overshot, but probably you just need something like this in `stack.yaml` (like [here](
https://github.com/inc-lc/ilc-agda/blob/a71750d1237319a7c156f2aa6512315b702bb827/stack.yaml)):
```yaml
resolver: lts-6.2 # Copied from the relevant version
packages:
- '.'
- location:
    git: https://github.com/agda/agda
    commit: e3472d7c1441c0d6db66be9e094e9dbcb7c33735
```
and to prepend `stack exec --package Agda --` to Agda invocations (like [here](https://github.com/inc-lc/ilc-agda/blob/39bb081c6f192bdb87bd58b4a89291686d2d7d03/agdaCheck.sh)).

**Comment by L-TChen** [comment] 2019-08-24 15:35
> @Blaisorblade + others:
> 
> And how well maintained is Stack support?

I am glad that you ask, and I have been using Stack to compile Agda all the time. 

There is one stack configuration for each supported GHC version, e.g., `stack-8.6.5.yaml`. After renaming `stack-8.6.5.yaml` to `stack.yaml`, you can compile Agda with stack as normally you would do it. It is also fine to specify `.yaml` using the option `--stack-yaml`. The current makefile compiles with `cabal` or `stack` if `stack.yaml` exists.

I think we need to write it up ...

**Comment by EdNutting** [comment] 2019-08-24 19:52
Okay, I'm working on overhauling the installation instructions in my fork, and I'll include stack instructions at the same time.

(Overhauling = keeping what's there, adding info about stack etc, and cleaning everything up / checking things work - because honestly it's very unclear and tricky to navigate all the possible installation routes/options at the moment).

**Comment by L-TChen** [comment] 2019-08-24 20:35
Yeah, it is clear to Haskell programmers only, I guess... at least I didn’t read anything on the user manual or Agda wiki to install. So, your work on revising installation instructions will be much appreciated.

**Comment by Blaisorblade** [comment] 2020-07-04 19:12
Unassigned myself — which I should have done years ago. I haven't found the time to finish this earlier, and with my new job, I assume I won't.

**Comment by EdNutting** [comment] 2020-07-04 19:32
Oh dear, looks like I dropped the ball on this one too - never quite got around to finishing the write up somehow (one disk failure later and I have no idea where it has ended up.)

If it's okay with others, I'll assign myself to this so it enters my Assigned Issue List and deal with it over the coming week :)

**Comment by EdNutting** [comment] 2020-07-05 10:23
This ticket has turned into a duplicate of #4665

**Comment by L-TChen** [comment] 2020-12-23 08:20
I am closing this issue since we do ship stack configurations and test them on all platforms and with selected ghc versions via GitHub workflow ([here](https://github.com/agda/agda/actions?query=workflow%3A%22Stack+build%22)). 

Adding Agda to Stackage is done recently via #4672, and one can build Agda with the nightly resolver `stack build Agda --resolver nightly` already. 

What we do not have is a proper installation instruction and it has another ticket #4665.

**Closed as completed by L-TChen** 2020-12-23 08:20 UTC
Labels: status: wontfix, type: enhancement, ux: installation, stackage, ghc support
