### ISSUE TITLE
Auto does not work well with record types

### ISSUE THREAD

**Issue by ice1000** [agda/agda#2853] opened 2017-11-16 09:06 UTC
My code here (removed irrelevant part):

```agda
bin-op : ∀ {ℓ} (A : Set ℓ) → Set ℓ
bin-op A = A → A → A

private
  record S3 {ℓ} (A : Set ℓ) : Set ℓ where
    infixl 5 _×_
    field
      x y {e} : A
      _×_ : bin-op A
      assocₗ : ∀ a b c → a × b × c ≡ a × (b × c)      

    assocᵣ : ∀ a b c → a × (b × c) ≡ a × b × c
    assocᵣ a b c rewrite assocₗ a b c = {!!}
```

I typed <kbd>C-c C-a</kbd> at the hole. Nothing happens.

Even Agda has correctly displayed the type of the hole (`?0 : a × (b × c) ≡ a × (b × c)`).

It should obviously been filled with a `refl` but it says `no solution found`. Why? Is this a bug?

**Comment by ice1000** [comment] 2017-11-16 09:07
P.S. After filling the hole with `refl`, everything goes fine.

**Comment by andreasabel** [comment] 2017-11-16 14:44
Auto is currently not maintained.

In such situations, where the next thing is a constructor, `refine` <kbd>C-c C-r</kbd> can solve your goal.

It seems that Auto does not deal well with record fields.  Here is a simplified case:
```agda
open import Agda.Builtin.Equality

-- WORKS with f defined outside of the record
-- postulate
--   f : ∀{A : Set} → A → A

postulate
  irr : (A : Set) (f : A → A) (a b : A) → f a ≡ f b

-- Agsy does not deal with field f well:

module Method where

  record R (A : Set) : Set where
    field
      f : A → A

    test : (a b : A) → f a ≡ f b
    test a b rewrite irr A f a b = {!!}  -- Auto fails

-- It fails also in this situation:

record R (A : Set) : Set where
  field
    f : A → A

module M (A : Set) (r : R A) where
  open R r

  test : (a b : A) → f a ≡ f b
  test a b rewrite irr A f a b = {!!}  -- Auto fails

-- And even here:

postulate
   A : Set
   r : R A

open R r

test : (a b : A) → f a ≡ f b
test a b rewrite irr A f a b = {!!}  -- Auto fails
```

**Comment by ice1000** [comment] 2017-11-17 06:02
<kbd>C-c C-r</kbd>.. thanks.


Ok. Get it. So should this be closed or keep open until auto is updated?

**Comment by andreasabel** [comment] 2017-11-18 09:36
Let's keep it open. I did not find a duplicate of this issue (although Auto might be broken for 4 years already).

**Comment by ice1000** [comment] 2017-11-18 11:48
> 4 years 

:fearful:

**Comment by jespercockx** [comment] 2017-11-18 11:57
Maybe we should advertise an open position? Wanted: Haskell developer willing to refactor and/or build from scratch a proof search algorithm for a dependently typed programming language (Agda). Payment: honorary membership of the Agda development team, free tickets for the next 10 AIM's*, Agda t-shirt and coffee mug**. 

(*) travel, accomodation, and food not included.
(**) once we decide on a logo.

**Comment by ice1000** [comment] 2017-11-18 12:01
:joy: But let's take a look at this 
![image](https://user-images.githubusercontent.com/16398479/32980082-2bcc099e-cc9b-11e7-98a2-1d267ea1f3fb.png)

**Comment by ice1000** [comment] 2017-11-18 12:02
Shouldn't `Auto` be just combination of some other keys? (I've read this on [learnyouanagda](http://learnyouanagda.liamoc.net/pages/proofs.html#how-does-this-all-relate-to-agda)

> Another feature worth mentioning is Agsy, an automatic proof searcher for Agda. Simply type `C-c C-a` in any hole and Agsy will search for an appropriate term to fill it. It’s not guaranteed to find anything, but it can be useful (it works well in this case).

**Comment by andreasabel** [comment] 2017-11-18 16:41
The more relevant chart can be maybe found here: https://github.com/frelindb/

**Comment by ice1000** [comment] 2017-11-19 09:26
> No solution found after timeout (1s)

Can I make the search time longer? @andreasabel

**Comment by identicalsnowflake** [comment] 2017-11-19 12:30
I wonder how viable it would be to do this through Agda's reflection API instead of making it a built-in Agda command?

**Comment by UlfNorell** [comment] 2017-11-19 15:16
@ice1000: You can change the timeout to `N` seconds by writing `-t N` in the hole before invoking Auto. Although, I would be surprised if you could find a problem that can be solved in 5s, but not in 1s.

@identicalsnowflake: The use cases are slightly different. I occasionally use Auto in cases where there are multiple type correct solutions, so manual inspection of the solution is required. See https://github.com/wenkokke/AutoInAgda an the accompanying paper for an attempt though.

**Comment by identicalsnowflake** [comment] 2017-11-19 16:04
@UlfNorell That paper was half of what I had in mind, actually! Another thing that could be promising for propositional equality proofs on inductive data types (and maybe more?) is simply performing a supercompilation pass and tracing the equality proof each step of the way. The nice thing about this approach is it has some principled direction and predictability to it, both from a developer and user perspective. I think the current reflection API should have everything necessary for this.

But yes, for cases with more than one type-correct solution, I see your point. But maybe if there were a way to run a macro in a hole and print the resulting term into the user's code, much like the builtin Auto does currently?

I just think people might be more likely to contribute to a library-level solution in Agda than to dive into the builtin Auto code in Haskell. I can only speak for myself, but I definitely find the reflection API much more approachable.

**Comment by ice1000** [comment] 2017-11-20 01:21
@UlfNorell Thanks! :+1:

**Closed as completed** 2024-02-02 07:34 UTC
Labels: type: bug, auto, projections

**Comment by andreasabel** [comment] 2024-07-13 12:07
Works with Mimer now, I am adding a test to `test/interaction/Mimer-Misc`.
