### ISSUE TITLE
char escape error loading on emacs 30.0

### ISSUE THREAD

**Issue by Plisp** [agda/agda#6672] opened 2023-05-29 06:47 UTC
emacs version: 30.0.5, agda 2.6.4 built today

The `\x` occurrences in `agda-input.el` appear to break loading

Replacing these with lambda fixes the issue but I'm unsure as to style

**Comment by gallais** [comment] 2023-05-29 08:20
Duplicate of #6525

**Closed as not planned by gallais** 2023-05-29 08:20 UTC
Labels: status: duplicate, ux: emacs
