### ISSUE TITLE
Agda2-mode is broken on Emacs 30

### ISSUE THREAD

**Issue by patrick-nicodemus** [agda/agda#6956] opened 2023-11-06 19:17 UTC
I am using agda 2.6.4 and Emacs 30.0.50.
My GHC version is 8.8.4.
I installed agda via cabal, cabal is version 3.0.0.0, cabal library is version 3.0.1.0.
OS Ubuntu 22.04

Problem:
When I open an agda file in Emacs, I get the "Agda" toolbar on the top of the screen and "Agda" mode appears at the bottom of the screen. There is no syntax highlighting and none of the commands do anything. For example, when I click "Load file" it just prints the message "menu-bar Agda Load".

The hello world agda file from the Agda tutorial suffices to demonstrate this problem.

I discussed this with @jpoiret on the Zulip chat for Agda and they characterized the bug as follows:

> The offending function is `agda2-string-quote`, `pp-to-string` has changed and now always inserts a newline at the end, borking communication with the agda process. I patched it to use `(format "%S" s)` instead and it works ok, but i have doubts about the `\xNN` escapes. In the meantime, if you put `(defun agda2-string-quote (s) (format "%S" s))` in the scratch buffer and evaluate it using `C-M-x` (control+alt+x), then restart agda, does it work?

Indeed, this proposed solution fixed all the problems I had noticed.

**Comment by UlfNorell** [comment] 2023-11-06 19:30
Duplicate of #6953. Should be fixed by #6954.

**Closed as completed by UlfNorell** 2023-11-06 19:30 UTC
Labels: status: duplicate
