### ISSUE TITLE
Agda loops on TERMINATING

### ISSUE THREAD

**Issue by m0davis** [agda/agda#2202] opened 2016-09-20 21:52 UTC
Agda loops forever typechecking this.

```
open import Prelude

{-# TERMINATING #-}
bar : Set
bar = bar

postulate
  foo : Set → Nat

qux : Nat
qux = suc $ foo bar
```

(Fwiw, replacing the import statement with the following avoids looping.)

```
open import Agda.Builtin.Nat
open import Prelude using (_$_)
```

**Comment by m0davis** [comment] 2016-09-20 21:57
Btw, I've found that this still happens in an example where `bar` actually terminates (although, in that example, the TERMINATING flag is still necessary to get Agda to typecheck).

**Comment by UlfNorell** [comment] 2016-09-21 04:54
The `TERMINATING` pragma makes Agda treat the function as if it has passed the termination checker. It's expected that you can get the type checker to loop if it's not actually terminating. In that case you should use `NON_TERMINATING` instead.

> I've found that this still happens in an example where bar actually terminates

Are you sure it was terminating also on open terms? For instance, the following function, while terminating at runtime, does not terminate under evaluation on open terms.

``` agda
fac : Nat → Nat
fac n = if n == 0 then 1 else n * fac (n - 1)
```

Closing for now, reopen if you find the example where the type checker shouldn't loop.

**Comment by andreasabel** [comment] 2016-09-21 06:52
I would like to understand why Agda loops here.  But I cannot reproduce it, as `open import Prelude` gives an import error.

This program type checks fine:

``` agda
data Nat : Set where
  suc : Nat → Nat

_$_ : {A : Set}{B : A → Set} (f : (x : A) → B x) (x : A) → B x
f $ x = f x

{-# TERMINATING #-}
bar : Set
bar = bar

postulate
  foo : Set → Nat

qux : Nat
qux = suc $ foo bar
```

**Comment by UlfNorell** [comment] 2016-09-21 07:23
It loops when `suc` is overloaded:

``` agda
data Nat : Set where
  suc : Nat → Nat

data Dummy : Set where
  suc : Dummy

_$_ : {A : Set}{B : A → Set} (f : (x : A) → B x) (x : A) → B x
f $ x = f x

{-# TERMINATING #-}
bar : Set
bar = bar

postulate
  foo : Set → Nat

qux : Nat
qux = suc $ foo bar -- loops
```

The particular culprit is [this line](https://github.com/agda/agda/blob/ac5f903d2de4ddf7916bb689ba97d395b3fbca11/src/full/Agda/TypeChecking/MetaVars.hs#L939) (introduced in 6e9a0def).

**Comment by andreasabel** [comment] 2016-09-21 13:38
Ok, I understand now.  A non-dependent version of `$` would avoid the looping.

**Closed as completed by andreasabel** 2016-09-21 13:38 UTC
Labels: termination, meta, conversion, overloading

**Comment by asr** [comment] 2016-09-21 14:01
> But I cannot reproduce it, as open import Prelude gives an import error.

The example is using the [agda-prelude](https://github.com/UlfNorell/agda-prelude) library.
