### ISSUE TITLE
Agda finds proof in hole depending on instance field, but fails subsequently

### ISSUE THREAD

**Issue by ajrouvoet** [agda/agda#4562] opened 2020-04-03 09:14 UTC
The following is a fairly simple demonstration of what I think is a bug involving instance search.

```agda
open import Relation.Binary.Structures
open import Relation.Binary.PropositionalEquality

record R (A : Set) : Set₁ where
  field
    {_≤ₐ_}   : A → A → Set

open R {{...}}

record S (A : Set) : Set₁ where
  field
    {{r}} : R A
    zero  : A
    min   : ∀ (a : A) → zero ≤ₐ a

open S {{...}}




open import Data.List
open import Data.Nat

instance [r] : ∀ {A} → R (List A)
R._≤ₐ_   [r] xs ys = length xs ≤ length ys

instance [s] : ∀ {A} → S (List A)
S.zero [s] = []
S.min [s] s = ?

-- Agda will find z≤n if you 'refine' in the whole, but a subsequent 'load' errors with:
--
-- ℕ.zero ≤ _n_22 !=< (S.r [s] R.≤ₐ S.zero [s]) s
-- when checking that the expression z≤n has type
-- (S.r [s] R.≤ₐ S.zero [s]) s
--
-- if you give the field r explicitly, all is well
```

**Comment by jespercockx** [comment] 2020-04-03 10:02
Version without dependency on the stdlib:
```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.List

length : {A : Set} → List A → Nat
length [] = 0
length (x ∷ xs) = 1 + length xs

data _≤_ : Nat → Nat → Set where
  z≤n : ∀ {n}                 → zero  ≤ n
  s≤s : ∀ {m n} (m≤n : m ≤ n) → suc m ≤ suc n

record R (A : Set) : Set₁ where
  field
    {_≤ₐ_}   : A → A → Set

open R {{...}}

record S (A : Set) : Set₁ where
  field
    {{r}} : R A
    zer   : A
    min   : ∀ (a : A) → zer ≤ₐ a

open S {{...}}

instance [r] : ∀ {A} → R (List A)
R._≤ₐ_   [r] xs ys = length xs ≤ length ys

instance [s] : ∀ {A} → S (List A)
S.zer [s] = []
S.min [s] s = z≤n
```

**Comment by jespercockx** [comment] 2020-04-03 10:05
This is a duplicate of #2557. Workaround: add an extra clause `S.r [s] = it` to the definition of `[s]`.

**Closed as completed by jespercockx** 2020-04-03 10:05 UTC
Labels: status: duplicate, type: bug, instance, constraints
