### ISSUE TITLE
Memory consumption of Agda JS compiler is too high

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#684] opened 2015-08-08 18:02 UTC
```
Agda failed to compile standard library's Data.Bool.Properties module with js 
compiler on Win32 machine with 2 GB of RAM. The meodule still can be compiled 
with MAlonzo compiler. Agda version is 2.3.1
```

Original issue reported on code.google.com by `schernic...@gmail.com` on 13 Aug 2012 at 6:14

**Comment by phile314** [comment] 2017-03-22 19:26
Could not reproduce this, most likely fixed by the new Treeless JS backend.

**Closed as completed by phile314** 2017-03-22 19:26 UTC
Labels: type: bug, backend: js
