### ISSUE TITLE
case-split and parametric modules

### ISSUE THREAD

**Issue by lclem** [agda/agda#5116] opened 2020-12-29 14:58 UTC
Hello! I have the following issue. There are two source files. The first one is `Module1.agda` and looks as follows:

```agda
module Module1 (T : Set) where

data One : Set where
    uniq : One
```

The second one is `Module2.agda` (hurray) and it looks as follows:

```agda
module Module2 where
data Empty : Set where

open import Module1 Empty

id : One → One
id x = {! x !}
```

The issue is that by case-splitting in the hole I get

```agda
id Module1.One.uniq = ?
```

instead of the desired

```agda
id uniq = ?
```

Not only the current behaviour creates ugly code,
but it actually generates wrong code,
since I then get the error

```
Cannot pattern match on non-constructor Module1.One.uniq
when scope checking the left-hand side id Module1.One.uniq in the
definition of id
```

Would it be possible to patch the case-splitter to return beautiful and correct code?
Thanks!

**Comment by gallais** [comment] 2021-01-01 09:59
This is a duplicate of #3209

**Closed as completed** 2021-01-01 10:00 UTC
Labels: status: duplicate
