### ISSUE TITLE
removing final empty implicit argument changes behaviour

### ISSUE THREAD

**Issue by MirceaS** [agda/agda#4140] opened 2019-10-16 13:05 UTC
Hi!
I was working in Agda and I found a weird scenario where putting in an empty implicit argument `{_}` at the end of a function definition was accepted by agda while removing it made the whole program not type-check.
https://github.com/agda/agda-categories/blob/2eb7858ec634a2fe44767528014b4ac21f5ef061/Categories/Category/Monoidal.agda#L68
Here is the repository and file that I was working on. At the specified line I defined the term:
```  
    ⊗-distrib-over-∘ : ((f ∘ h) ⊗₁ (g ∘ i)) ≈ ((f ⊗₁ g) ∘ (h ⊗₁ i))
    ⊗-distrib-over-∘ = homomorphism
```
which didn't type check corectly.
After some experimentation, I found that
```
    ⊗-distrib-over-∘ : ((f ∘ h) ⊗₁ (g ∘ i)) ≈ ((f ⊗₁ g) ∘ (h ⊗₁ i))
    ⊗-distrib-over-∘ {_} = homomorphism {_ , _} {_ , _} {_ , _}
```
does actually work but removing the initial `{_}` resulting in
```
    ⊗-distrib-over-∘ : ((f ∘ h) ⊗₁ (g ∘ i)) ≈ ((f ⊗₁ g) ∘ (h ⊗₁ i))
    ⊗-distrib-over-∘ = homomorphism {_ , _} {_ , _} {_ , _}
```
doesn't.
This looks really odd and I don't think that should happen. Maybe someone can look into why this happens.

**Comment by guillaumebrunerie** [comment] 2019-10-16 13:21
Your issue is identical to #4131.
The problem is because definitions between fields of record types are translated to let-expressions, and let-expressions have several problems, including some related to implicit arguments.

**Comment by guillaumebrunerie** [comment] 2019-10-16 13:32
A slightly shorter workaround is
```agda
⊗-distrib-over-∘ : ((f ∘ h) ⊗₁ (g ∘ i)) ≈ ((f ⊗₁ g) ∘ (h ⊗₁ i))
⊗-distrib-over-∘ {_} = homomorphism
```

**Comment by andreasabel** [comment] 2019-10-21 14:48
Thanks for reporting @MirceaS, and for analysing, @guillaumebrunerie.  I am closing this as duplicate of #4131.

**Closed as completed by andreasabel** 2019-10-21 14:48 UTC
Labels: status: duplicate, hidden arguments
