### ISSUE TITLE
Binding two identifiers using user-defined syntax

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#536] opened 2015-08-08 17:59 UTC
```
As it was reported in the Agda mailing list

http://article.gmane.org/gmane.comp.lang.agda/3416

the following syntax declaration (using Jean-Philippe suggestion) yields a 
parse error

  postulate D

  data ∃₂ (P : D → D → Set) : Set where
    _,_,_ : (x y : D) → P x y → ∃₂ P

  syntax ∃₂ (λ x y → e) = ∃₂[ x , y ] e

```

Original issue reported on code.google.com by `andres.s...@gmail.com` on 1 Dec 2011 at 2:46

**Comment by UlfNorell** [comment] 2018-05-24 14:39
Duplicate of #394.

**Closed as completed by UlfNorell** 2018-05-24 14:39 UTC
Labels: status: duplicate, type: enhancement, syntax
