### ISSUE TITLE
Print shadowed identifiers as such, reloaded

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2948] opened 2018-02-02 13:06 UTC
```agda
test : (x : Set) (x : x) -> Set
test x = \ x -> {!x!}
```
`C-c C-.` shows the confusing
```
Goal: Set
Have: x
—————————————————————————————————————
x : x
x : Set
```

**Comment by UlfNorell** [comment] 2018-05-27 10:17
Duplicate of #572. See also #998.

**Closed as completed by UlfNorell** 2018-05-27 10:17 UTC
Labels: status: duplicate, type: enhancement, ux: printing, shadowing
