### ISSUE TITLE
Internal error when importing a module with a hole in a type

### ISSUE THREAD

**Issue by JLimperg** [agda/agda#4051] opened 2019-09-03 05:15 UTC
Test case:

In `bug1.agda`:

```agda
{-# OPTIONS --allow-unsolved-metas #-}
module bug1 where

x : {!!}
x = {!!}
```

In `bug2.agda`:

```agda
module bug2 where

open import bug1
```

Loading `bug2` leads to an internal error with reported location `src/full/Agda/TypeChecking/Serialise/Instances/Internal.hs:148`.

Agda versions: 2.6.0.1 and master@957f54f8405c0add88391fca543a71fe14c89795.

**Comment by UlfNorell** [comment] 2019-11-28 11:51
Duplicate of #3730

**Closed as completed by UlfNorell** 2019-11-28 11:51 UTC
Labels: serialization, regression in 2.5.4, allow-unsolved-metas
