### ISSUE TITLE
Performance: Instantiated meta-variables in interface files

### ISSUE THREAD

**Issue by nad** [agda/agda#5731] opened 2022-01-11 11:41 UTC
I'm currently working on some code for which Agda fails to create the interface. I think my code should be optimised, but I want to document the problem. Agda spends a lot of time instantiating meta-variables when eliminating dead code, before running out of memory:

https://github.com/agda/agda/blob/ff89bebacb6e8710dde125993e8c91dbe9282413/src/full/Agda/TypeChecking/DeadCode.hs#L23-L29

Note that meta-variables are also instantiated before the interface is stored (presumably this piece of code could be optimised):

https://github.com/agda/agda/blob/ff89bebacb6e8710dde125993e8c91dbe9282413/src/full/Agda/Interaction/Imports.hs#L1198-L1200

Would it make sense to have instantiated meta-variables in interfaces? Could this lead to any problems? I can imagine that the problem with the freezing code (#5388) could be made worse.

**Comment by nad** [comment] 2022-01-12 13:07
> Note that meta-variables are also instantiated before the interface is stored (presumably this piece of code could be optimised):

I have optimised this piece of code. However, the main problem remains.

**Comment by nad** [comment] 2022-01-12 14:17
> Would it make sense to have instantiated meta-variables in interfaces? Could this lead to any problems?

One should at least also include bindings for the instantiated meta-variables in the interfaces.

Are meta-variable identifiers only unique within a single module? In that case that should also be addressed in some way.

**Comment by jespercockx** [comment] 2022-01-12 14:24
Yes, metavariables are currently only unique within the same top-level module, so they should be qualified properly.

One more advantage of allowing metas in interfaces would be that it would allow us to get rid of the current ugly hack in the implementation of `--allow-unsolved-metas`, which is turning unsolved metavariables into postulates.

**Comment by nad** [comment] 2022-01-12 19:33
I was wondering how much of the `MetaStore` we need to include in the interfaces. If we restrict ourselves to instantiated meta-variables, then I guess it would suffice to have only the instantiations:

https://github.com/agda/agda/blob/1fe6beb76160fbc7e1f430f57823ad7c78761c43/src/full/Agda/TypeChecking/Monad/Base.hs#L1312

A `MetaStore` contains a number of other things:

https://github.com/agda/agda/blob/1fe6beb76160fbc7e1f430f57823ad7c78761c43/src/full/Agda/TypeChecking/Monad/Base.hs#L1272-L1284

Do we need any of this, except for the instantiation, for instantiated meta-variables from other modules? Such meta-variables could be seen as shorthand notation for their instantiations, and the code that replaces instantiated meta-variables with their instantiations only uses `mvInstantiation`:

https://github.com/agda/agda/blob/1fe6beb76160fbc7e1f430f57823ad7c78761c43/src/full/Agda/TypeChecking/Reduce.hs#L142-L172

It might be easier to just store the entire `MetaStore` in the interface, but from a performance perspective that could be suboptimal. Furthermore I guess that meta-variables from other modules should be treated differently from meta-variables from the current module. For instance, the following code in `createInterface` should presumably not unfreeze meta-variables from other modules (I don't know if this would have any effect, but with the current implementation of `unfreezeMetas` it could be costly):

https://github.com/agda/agda/blob/1fe6beb76160fbc7e1f430f57823ad7c78761c43/src/full/Agda/Interaction/Imports.hs#L1006

An alternative might be to treat instantiated meta-variables differently from other ones.

**Comment by nad** [comment] 2022-01-13 10:47
I located some pieces of code that are at least linear in the size of the meta-store (if everything is evaluated strictly).

* The following four pieces could be improved by having separate meta-stores for open and closed meta-variables:

  https://github.com/agda/agda/blob/e204c14c3261c188c089d60b9c685303af8a55f3/src/full/Agda/Interaction/BasicOps.hs#L822-L825

  https://github.com/agda/agda/blob/e204c14c3261c188c089d60b9c685303af8a55f3/src/full/Agda/TypeChecking/MetaVars.hs#L1663-L1670

  https://github.com/agda/agda/blob/e204c14c3261c188c089d60b9c685303af8a55f3/src/full/Agda/TypeChecking/Monad/MetaVars.hs#L550-L556

  Note that `getMetaVariables` is now only used by `getOpenMetas`.

  https://github.com/agda/agda/blob/e204c14c3261c188c089d60b9c685303af8a55f3/src/full/Agda/TypeChecking/Monad/MetaVars.hs#L608-L609

  I guess there is no point in unfreezing instantiated meta-variables.

* I wonder if it would suffice for `metasCreatedBy` to return open metas:

  https://github.com/agda/agda/blob/e204c14c3261c188c089d60b9c685303af8a55f3/src/full/Agda/TypeChecking/Monad/MetaVars.hs#L129-L135

  I think the answer is yes if it suffices to have open metas in the argument `allmetas` to `computeGeneralization`:

  https://github.com/agda/agda/blob/e204c14c3261c188c089d60b9c685303af8a55f3/src/full/Agda/TypeChecking/Generalize.hs#L149-L154

  @UlfNorell, @jespercockx: Does that suffice?

* The following piece of code could be removed (note that conversion of a map to a set takes time):

  https://github.com/agda/agda/blob/e204c14c3261c188c089d60b9c685303af8a55f3/src/full/Agda/TypeChecking/Monad/MetaVars.hs#L547-L548

**Comment by jespercockx** [comment] 2022-01-13 12:10
> I think the answer is yes if it suffices to have open metas in the argument allmetas to computeGeneralization: [...]
> @UlfNorell, @jespercockx: Does that suffice?

In general, no: the closed metas are used in that function (grep for `generalizableClosed`) for finding metavariables that should be transitively generalized because they occur in the solution of a generalizable meta. However, perhaps this could be done more eagerly by marking all metas in the solution of a generalizable meta as being generalizable *when solving that meta*. But I'm not 100% that this wouldn't have unintended side effects.

**Comment by nad** [comment] 2022-01-13 12:29
OK, perhaps one could replace (the relevant instance of) `metasCreatedBy` by a mechanism that records created meta-variables as they are created. Then one could perhaps also address the following TODO note:

https://github.com/agda/agda/blob/3a6394332780458125230d684bb4111cfd0ab03a/src/full/Agda/TypeChecking/Generalize.hs#L161-L164

Do you know if `createMetasAndTypeCheck` is ever invoked recursively?

https://github.com/agda/agda/blob/3a6394332780458125230d684bb4111cfd0ab03a/src/full/Agda/TypeChecking/Generalize.hs#L129-L136

Given code like the following (inside `isType_`) the answer might be yes (the argument to `generalizeType s` is supplied as part of the `typecheckAction` argument to `createMetasAndTypeCheck`):

https://github.com/agda/agda/blob/3a6394332780458125230d684bb4111cfd0ab03a/src/full/Agda/TypeChecking/Rules/Term.hs#L131-L132

Another question: Is all the information in `MetaVariable` needed for instantiated meta-variables, or would it suffice with only the instantiation?

**Comment by nad** [comment] 2022-01-13 12:55
> OK, perhaps one could replace (the relevant instance of) `metasCreatedBy` by a mechanism that records created meta-variables as they are created.

I found a simple way to optimise `metasCreatedBy`, making use of the fact that `MetaId`s are always increasing (as long as they do not wrap around).

**Comment by UlfNorell** [comment] 2022-01-13 13:08
Don't forget to add a test case to test what happens when they wrap around!

**Comment by nad** [comment] 2022-01-13 13:16
Some things that remain to be done:

* Have a separate meta-store for closed meta-variables.
* Optimise the pieces of code listed above. (One could also add `openMetasCreatedBy`, and use that in some cases.)
* Make it possible to refer to meta-variables from other modules without ambiguity.
* Store meta-variables in interfaces.
* Stop using `instantiateFull` when eliminating dead code, and when creating interfaces.

**Comment by nad** [comment] 2022-01-19 20:28
> Another question: Is all the information in `MetaVariable` needed for instantiated meta-variables, or would it suffice with only the instantiation?

Sometimes there are interaction points corresponding to solved meta-variables. I guess that `getInteractionScope` can be invoked for such meta-variables.

**Comment by nad** [comment] 2022-01-19 22:37
> Make it possible to refer to meta-variables from other modules without ambiguity.

I'm thinking of changing the representation of `MetaId` so that it contains two `Word64` values, like `NameId`:

https://github.com/agda/agda/blob/382861b1967b7ced0806343b8410709b2ce91df0/src/full/Agda/Syntax/Common.hs#L2331-L2333

What promises do we make about the results of the following functions?

https://github.com/agda/agda/blob/382861b1967b7ced0806343b8410709b2ce91df0/src/data/lib/prim/Agda/Builtin/Reflection.agda#L83-L84

**Comment by nad** [comment] 2022-01-21 21:57
@jespercockx, @UlfNorell: Do we not make any promises (other than injectivity)?

**Comment by jespercockx** [comment] 2022-01-22 10:00
I think the "promise" (if you want to call it that) is that the `TC` primitives do roughly the same as the actual Agda typechecker itself, so the numbers/names ought to correspond to what the user sees in error messages and such. I am not sure how important it is to keep this promise, though.

**Comment by UlfNorell** [comment] 2022-01-24 07:15
I think it would be good if you could still use those functions to implement a pretty printer for `Term` that matches (more or less) how Agda prints terms.

**Comment by nad** [comment] 2022-01-25 16:25
I suppose that the implementations should match the implementations in `Agda.Compiler.MAlonzo.Primitives` (but I don't know if you can construct a `Meta` that can be used at runtime without using the FFI).

**Comment by jespercockx** [comment] 2022-01-25 16:38
Well, about that...
```agda
open import Agda.Builtin.IO
open import Agda.Builtin.List
open import Agda.Builtin.Reflection renaming (bindTC to _>>=_)
open import Agda.Builtin.String
open import Agda.Builtin.Unit

macro
  getMeta : Term → TC ⊤
  getMeta hole@(meta m _) = quoteTC m >>= unify hole
  getMeta _ = typeError []

myMeta : Meta
myMeta = getMeta

postulate putStrLn : String → IO ⊤
{-# FOREIGN GHC import qualified Data.Text as T #-}

main : IO ⊤
main = putStrLn (primShowMeta myMeta)
```
Trying to compile this with the GHC backend this produces an internal error:
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/Compiler/MAlonzo/Compiler.hs:1097:18 in Agda-2.6.3-2GgStRv6exQAe2hnultIdP:Agda.Compiler.MAlonzo.Compiler
```

**Comment by nad** [comment] 2022-01-25 16:45
Please open a separate issue for that bug.

**Comment by nad** [comment] 2022-01-25 17:10
Is it a problem if the numbers created by `primMetaToNat` are large (2^64 times the module name hash plus the sequential meta-variable number)? Are there any reasonable tactics that do something recursive with the natural numbers that you obtain from this function? Using the equality and ordering tests from `Agda.Builtin.Nat` should be fine.

**Comment by jespercockx** [comment] 2022-01-25 17:15
> Are there any reasonable tactics that do something recursive with the natural numbers that you obtain from this function?

I think they're just meant to be unique identifiers, so I would really hope no-one ever recurses on them.

**Comment by nad** [comment] 2022-01-25 20:31
In order to avoid getting horrible error messages (with things like `_1@10189251152579365012` instead of `_1`) I made the module name hash "optional", and omit it for the current module. An alternative would have been to replace the `Pretty` instance for `MetaId` with a `PrettyTCM` instance, so that the pretty-printer could see if the `MetaId` was from the current module, but I expect that this would require a fair amount of work. The idea is to insert the module name hash when interfaces are serialised. However, `primShowMeta` is a pure function, and always prints the same thing, regardless of how the meta-variable is represented.

The JSON API uses `MetaId`, so that API has changed. Is the API documented anywhere?

Some things that remain to be done:

* Make it possible to omit most of the information contained in `MetaVariable` for instantiated meta-variables from other modules, so that one does not have to store `Closure`s in interfaces.

* Stop using `instantiateFull` when eliminating dead code, and when creating interfaces.

* Store reachable instantiated meta-variables in interfaces, along with the instantiations.

* Test the performance of the new implementation.

* Document the change to the JSON API (at least in the changelog).

**Comment by nad** [comment] 2022-01-26 23:20
I've started implementing the things above, and unsurprisingly my first attempt did not work. An internal error is raised when the result of type-checking the following code is serialised:
```agda
open import Agda.Primitive

variable
  a : Level
  A : Set a
  f : A → A
```
The problem is that the definition of `f` contains `__DUMMY_TERM__`:
```
defType           =
  {.1 : Agda.Primitive.Level} ->
    {A : Set (_5
                (Test.mkGeneralizeTel
                   {@0}
                   {(dummyTerm: __DUMMY_TERM__, called at src/full/Agda/TypeChecking/Generalize.hs:656:111 in Agda-2.6.2-e31a3bf9f390593017b1d3ec01f6df877761fd8713b2928e774ed98e914dae57:Agda.TypeChecking.Generalize)}))} ->
      @0 -> @0
```
As you can see I obtained the result above for Agda 2.6.2. I suppose that this is not a problem for Agda 2.6.2 because of the use of `instantiateFull` before serialisation. A simple fix is to serialise dummy terms, but perhaps that could hide other problems down the line. Is there some better fix? I don't know too much about the implementation of generalisable variables.

**Comment by UlfNorell** [comment] 2022-01-27 08:14
The way generalisation works is it checks a type to be generalised in scope of a variable `genTel : ?G`. Once we know what metavariables to generalise over `?G` is instantiated with a record type packing them up and the metas are instantiated with the corresponding projections from `genTel`. Finally we perform the substitution unpacking the record type giving us a type that depends on the telescope of generalised variables.

The dummy terms are used when constructing the types of the record fields. For instance, suppose you are generalising over `x : A` and `y : B x`. When generalising they are represented by metas
```agda
  ?x : ?G -> A
  ?y : (genTel : ?G) -> B (?x genTel)
```
The problem is to construct the telescope `(x : A) (y : B x)` from the types `A` and `B (?x genTel)` where `genTel : ?G` and `?G` will be instantiated to the record type we are building and `?x` and `?y` to projections from that type. The way we do that is to substitute partial record values for `genTel`. So we'd start with `(x : A)` then construct `B x` as
```agda
B (?x genTel) [genTel := record{x = x, y = __DUMMY_TERM__}]
```
and rely on the fact that we've done the dependency analysis to guarantee that the dummy term will not leak.

Perhaps a solution to your problem is to do a pass over the generalised type at the end, specifically unfolding the instantiations of generalised metas.

**Comment by jespercockx** [comment] 2022-01-27 08:55
Doing a pass to instantiate all metavariables that were generalized right after generalization seems like it would be a reasonable thing to do: the instantiations are always just variables, so it does not blow up the size of the term.

**Comment by nad** [comment] 2022-01-31 22:40
I made serialisation of meta-variables optional. The feature is *disabled* by default, and can be controlled using the pragma options `--save-metas` and `--no-save-metas`.

Some notes about the implementation:

* Perhaps I managed to fix the problem with `__DUMMY_TERM__` that we discussed above (meta-variables are now instantiated using the new procedure `instantiateWhen`). That fix also fixed a performance problem that I encountered. However, I encountered `__DUMMY_TYPE__` as well, so I decided to serialise dummy terms and sorts.
* I decided to not go with the "optional module name hash" hack that I mentioned above, and instead changed some pretty-printers. The `size-solver` program no longer prints error messages (because the error type changed from `String` to `TCM Doc`).
* A limited amount of information is stored with remote meta-variables: the instantiation, the judgement, and the modality. For "local" meta-variables one can still access all the usual information using `lookupLocalMeta`, but that procedure raises an internal error for remote meta-variables. The test suite does not complain, but perhaps the internal error could be triggered by some inputs. I am especially uncertain about the code under `Agda.Auto`, which I have mostly ignored, and which we have few tests for.
* I use the `NamesIn` code to decide which meta-variables to omit when creating interfaces, and encountered some bugs because the `NamesIn` instances did not traverse all of their input. The `NamesIn` instances still do not traverse everything, so if Agda complains about missing meta-variables, then that might be a reason.
* The backends still use `instantiateFull` (in `Agda.Compiler.Backend.compileModule`).
* The flags `--save-metas` and `--no-save-metas` are only used in one test case, that just checks that the options can be parsed. Otherwise the test suite only tests the default.

Some notes about performance:

* The code that I mentioned in the OP is accepted with `--save-metas` (with `-M4G` on a 64-bit system, and with Agda built without `optimise-heavily`), whereas Agda 2.6.3-72e26d4 runs out of memory (under the same circumstances).
* I find it hard to get consistent numbers from our standard benchmark (the standard library test), but limited testing suggests that type-checking the standard library takes about as much time as before (with `--save-metas` or `--no-save-metas`, and where "before" refers to version 2.6.3-72e26d4), with the interface files being roughly 3% larger (with `--save-metas`).
* Agda became much slower for some of my code (with `--save-metas`).

Things that one may want to look into:

* I think it would be nice with a small test case that illustrates that `--save-metas` can make Agda much faster.
* I don't know why Agda became much slower for some of my code when I turned on `--save-metas`.
* Perhaps it would make sense to avoid serialising dummy terms and sorts.
* Sometimes the Haskell code generated by the GHC backend is really large, perhaps this could be partly addressed through the elimination of `instantiateFull` in `Agda.Compiler.Backend.compileModule`. However, meta-variables are not let expressions, they all live at the top-level, so I don't know how well this would work.

**Comment by andreasabel** [comment] 2022-02-01 17:21
Your last remark should find a more visible home, e.g. as a commentary in the Agda code base.

**Comment by nad** [comment] 2022-02-01 18:44
I don't think it makes sense to put all of that text in the code, but I can integrate some parts:

> * I am especially uncertain about the code under `Agda.Auto`, which I have mostly ignored, and which we have few tests for.

I can add some comments to the relevant files.

> * I use the `NamesIn` code to decide which meta-variables to omit when creating interfaces, and encountered some bugs because the `NamesIn` instances did not traverse all of their input. The `NamesIn` instances still do not traverse everything, so if Agda complains about missing meta-variables, then that might be a reason.

I can add a note to the documentation of `lookupMeta`.

**Comment by nad** [comment] 2022-02-02 11:11
> > * I am especially uncertain about the code under `Agda.Auto`, which I have mostly ignored, and which we have few tests for.
> 
> I can add some comments to the relevant files.

I opted to replace the calls to `lookupLocalMeta` with a variant that notes that the auto command does not support remote meta-variables, and that suggests the use of `--no-save-metas`.

> I can add a note to the documentation of `lookupMeta`.

Done.

**Closed as completed** 2022-02-04 11:37 UTC
Labels: type: enhancement, meta, performance, documented-in-changelog, save-metas

**Comment by andreasabel** [comment] 2023-11-21 23:00
AIMXXXVII: @AndrasKovacs is working on sharing metas and, to this end, printing of interfaces, and noticed that there are no metas in definitions even with `--save-metas`.  Maybe not surprising because the clauses are fully instantiated:
https://github.com/agda/agda/blob/4460544ab7c4845bde24f534f16ed7daa6042a81/src/full/Agda/TypeChecking/Rules/Def.hs#L357-L362
The absence of metas would explain the lack of performance gain by `--save-metas`, and the slight increase of the size of the interface files.  Meta solutions are then stored, taking some space, but since no meta solutions are reused, there are no savings.

**Comment by nad** [comment] 2023-11-22 11:49
> AIMXXXVII: @AndrasKovacs is working on sharing metas and, to this end, printing of interfaces, and noticed that there are no metas in definitions even with `--save-metas`. Maybe not surprising because the clauses are fully instantiated:

@UlfNorell and I added that call to `instantiateFull` in 2010. The commit message contains some motivation: d6d50f4ef50d879b9f907bc91bf6db44c93fbd71.
