### ISSUE TITLE
Refining on user defined syntax mixes up the order of the subgoals

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#488] opened 2015-08-08 17:58 UTC
Rearranging arguments with the syntax keyword leads to types ending up in the wrong position after refining. Having custom syntax rewritten is somewhat surprising in the first place, so i'm sympathetic with emacs-mode. 

```agda
data ℕ : Set where
  ze : ℕ
  su : ℕ → ℕ

f : (ℕ → ℕ) → ℕ → ℕ
f g n = g n

syntax f g n = g , n

h : ℕ
h = f ?
```
enter ? , ? and refine to get to a surprising state:
```
  h = f { }2 { }1

  ?1 : ℕ → ℕ
  ?2 : ℕ
```
at this point emacs accepts
```
  h = f {ze }2 {su }1
```
but refuses
```
  h = f {su }2 {ze }1
```
reloading lines up everything as expected
```
  h = f { }0 { }1

  ?0 : ℕ → ℕ
  ?1 : ℕ
```

Original issue reported on code.google.com by `w...@kulturtragwerk.de` on 3 Oct 2011 at 10:32

**Comment by asr** [comment] 2018-05-23 04:06
The issue is fixed in the current `stable-2.5` so I added a test case and I'm closing it.

The issue also was fixed in 2.5.3 and 2.5.4 RC 1 (I didn't test other versions).

**Closed as completed by asr** 2018-05-23 04:06 UTC
Labels: type: bug, ux: emacs, syntax, ux: interaction, status: already-fixed
