### ISSUE TITLE
Fix broken compatibility with agda-bench

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#5167] opened 2021-02-04 01:39 UTC
The commit https://github.com/agda/agda/commit/de6aed5d341e366fdf7efa9b44a447ede731cba8 means that `Agda.Interaction.CommandLine` no longer exports `withCurrentFile` leading to the following error when I try to install [agda-bench](https://github.com/UlfNorell/agda-bench):
```
Main.hs:24:38: error:
    Module
    ‘Agda.Interaction.CommandLine’
    does not export
    ‘withCurrentFile’
   |
24 | import Agda.Interaction.CommandLine (withCurrentFile)
   |                                      ^^^^^^^^^^^^^^^
```

**Comment by andreasabel** [comment] 2021-02-05 18:46
Maybe the greater harm is that `withCurrentFile` no longer lives in `TCM` but in the `ReplM`.

I suppose this issue is better fixed in https://github.com/UlfNorell/agda-bench, so I reported https://github.com/UlfNorell/agda-bench/issues/1.

I am removing the "regression on master" tag, since we'll not likely going back to the old API.

**Closed as completed by andreasabel** 2021-02-05 18:46 UTC
Labels: api
