### ISSUE TITLE
Unsolved metas when types contain records with irrelevant fields

### ISSUE THREAD

**Issue by msuperdock** [agda/agda#4643] opened 2020-05-08 18:57 UTC
## Issue

I ran into a confusing situation where Agda fails to solve for a meta which it should be able to solve; at the end of this post is code that can be used to reproduce the error (using either 2.6.0.1 or 2.6.1, at least). Unfortunately, I haven't been able to reduce the code below ~200 lines; any further simplification I make seems to enable Agda to solve for the meta, without any clear reason why. Here's the function where the unsolved meta occurs:

```agda
trivial-maybe-eq
  : {C : Category}
  → {A : Set}
  → {F : DependentFunctor C A}
  → (G : Trivial F)
  → trivial-maybe G ≡ trivial-maybe G
trivial-maybe-eq _
  = refl
```

The unsolved meta is tagged to characters 23-36 of the line `→ trivial-maybe G ≡ trivial-maybe G` and refers to `_irrelevant_101 : Category.Arrow C → ⊤`. There is an irrelevant field, `irrelevant :  ⊤`, of a record called `Functor`, and then the `DependentFunctor` record contains a field `lift : Category.Arrow C → Functor A`. So agda seems to be expanding the `lift` field to individual fields for each field of `Functor`, one of which produces the unsolved meta.

To check the function declaration, agda needs to check that `trivial-maybe G` and `trivial-maybe G` have the same type, which should be no problem, but it seems to fail somewhere in the process of checking this. The problem goes away (that is, the meta is solved) if you replace the conclusion with `trivial-maybe G ≡ trivial-maybe {F = F} G`. This tells the `trivial-maybe` function that `G` has type `Trivial F`, which it should be able to infer from the type of `G` in `trivial-maybe-eq`.

As mentioned, the error disappears under certain simplifications of the code; for example:
* Removing the `maybe-map` function and defining the `map` field of `functor-maybe` directly.
* Using the built-in unit type rather than a user-defined unit type.

Excuse the misused category-language; it's an artifact of my attempt to produce a somewhat minimal example starting from the code where I first encountered the issue.

## Code

```agda
module Test where

-- ## Prelude

open import Agda.Builtin.Equality
  using (_≡_; refl)

data ⊤ : Set where
  tt : ⊤

data Maybe (A : Set) : Set where
  nothing : Maybe A
  just : A → Maybe A

maybe-map
  : {A B : Set}
  → (A → B)
  → Maybe A
  → Maybe B
maybe-map _ nothing
  = nothing
maybe-map f (just x)
  = just (f x)

-- ## Category

record Category
  : Set₁
  where

  field

    Arrow
      : Set

    identity
      : Arrow

module CategoryMaybe
  (C : Category)
  where

  Arrow
    : Set
  Arrow
    = Maybe (Category.Arrow C)

  identity
    : Arrow
  identity
    = just (Category.identity C)

category-maybe
  : Category
  → Category
category-maybe C
  = record {CategoryMaybe C}

-- ## Functor

record Functor
  (A : Set)
  : Set
  where

  field
    
    map
      : A
      → A

    .irrelevant
      : ⊤

module _
  {A : Set}
  where

  module FunctorMaybe
    (F : Functor A)
    where

    map
      : Maybe A
      → Maybe A
    map
      = maybe-map (Functor.map F)

    .irrelevant
      : ⊤
    irrelevant
      = tt

  functor-maybe
    : Functor A
    → Functor (Maybe A)
  functor-maybe F
    = record {FunctorMaybe F}

-- ## FunctorIdentity

record FunctorIdentity
  {A : Set}
  (F : Functor A)
  : Set
  where

  field

    map
      : (f : A)
      → Functor.map F f ≡ f

module _
  {A : Set}
  {F : Functor A}
  where

  module FunctorIdentityMaybe
    (p : FunctorIdentity F)
    where

    map
      : (f : Maybe A)
      → Functor.map (functor-maybe F) f ≡ f
    map nothing
      = refl
    map (just f)
      rewrite FunctorIdentity.map p f
      = refl

  functor-identity-maybe
    : FunctorIdentity F
    → FunctorIdentity
      (functor-maybe F)
  functor-identity-maybe p
    = record {FunctorIdentityMaybe p}

-- ## DependentFunctor

record DependentFunctor 
  (C : Category)
  (A : Set)
  : Set
  where

  field

    lift
      : Category.Arrow C
      → Functor A

    lift-identity
      : FunctorIdentity (lift (Category.identity C))

module _
  {C : Category}
  {A : Set}
  where
  
  module DependentFunctorMaybe
    (F : DependentFunctor C A)
    where

    lift
      : Category.Arrow C
      → Functor (Maybe A)
    lift f
      = functor-maybe
        (DependentFunctor.lift F f)

    lift-identity
      : FunctorIdentity (lift (Category.identity C))
    lift-identity
      = functor-identity-maybe
        (DependentFunctor.lift-identity F)

  dependent-functor-maybe
    : DependentFunctor C A
    → DependentFunctor C (Maybe A)
  dependent-functor-maybe F
    = record {DependentFunctorMaybe F}

-- ## Test

record Trivial
  {C : Category}
  {A : Set}
  (F : DependentFunctor C A)
  : Set
  where

trivial-maybe
  : {C : Category}
  → {A : Set}
  → {F : DependentFunctor C A}
  → Trivial F
  → Trivial (dependent-functor-maybe F)
trivial-maybe _
  = record {}

trivial-maybe-eq
  : {C : Category}
  → {A : Set}
  → {F : DependentFunctor C A}
  → (G : Trivial F)
  → trivial-maybe G ≡ trivial-maybe G
trivial-maybe-eq _
  = refl
```

**Comment by andreasabel** [comment] 2020-05-08 20:37
This is an unfortunate interplay between eta-equality and irrelevance.  It goes away, for instance, if you add `no-eta-equality` to the `Functor` record declaration.

In the OP, if you modify the last target type to
```
trivial-maybe {F = ?} G ≡ trivial-maybe {F = ?} G
```
and then look at the constraints with `C-c C-=`, you can see that Agda has solved the first meta by `F` but the second by a record expression that contains the unsolved meta `_irrelevant_101`.  Agda eta-expanded the second meta into some record expression containing new metas and then managed to solve all metas except for the irrelevant one.  This is because equating two irrelevant things does not give any new information.
There are some heuristics in Agda to improve this situation a bit, but they do not seem to get invoked here.

I wonder whether some more lazy eta-expansion of metas would help here, but this is likely not an easy fix.

**Comment by jespercockx** [comment] 2020-05-08 21:40
There is no guarantee of when Agda solves irrelevant metavariables, it only does so on a best-effort basis (the problem is undecidable in general so doing better is impossible). So I'm not sure if this can actually be fixed. Of course, concrete suggestions for improving the current heuristics are welcome.

**Comment by msuperdock** [comment] 2020-05-09 12:37
Thanks for both of your responses. @andreasabel, the `no-eta-equality` approach is really helpful; I am having the issue in my original post with several modules with irrelevant fields, and this handles the issue everywhere. @jespercockx, I assume that is the case for all metavariables, not just irrelevant ones, or is there something particularly tricky about irrelevant metavariables?

As for suggestions, my wish is that agda would do some preliminary passes to see if the types check without fully expanding them. For example,
* First unfold just the types of identifiers (not data/records) used explicitly in the current definition.
* If type-checking fails, unfold types of other identifiers (not data/records) defined in current module.
* If type-checking still fails, unfold everything.

For example, for the `trivial-maybe-eq` function in my code example, the first step would consist of only unfolding the `trivial-maybe` function, after which both sides would have type `Trivial (dependent-functor-maybe F)`, and checking would succeed. The function `dependent-functor-maybe` would not unfold here, but in general would unfold as a next step.

An approach like this would have the benefit of ensuring that definitions that are "obviously" correct to the programmer ("obviously" meaning that they can be seen to be correct just by inspecting the types of the idenitifiers used explicitly) type-check, and type-check quickly. In such cases I've never seen agda fail to type-check, except in the example above with irrelevant fields. But I've run into a number of cases where agda is very slow to type-check a definition that is "obviously" correct, even with no irrelevant fields involved; I generally assume this is because agda is fully reducing the terms in the types. Sometimes I can speed up type-checking by supplying implicit arguments explicitly, but figuring out which implicit arguments will speed things up is very non-systematic. I've also found that sometimes replacing records with equivalent data types speeds things up drastically, which breaks my mental model that a record is essentially a data type with one constructor.

An alternative idea would be to supply a mechanism like `abstract`, but local. Declaring a definition `abstract` tells the type-checker not to expand the definition anywhere it is used, and you can't tell the type-checker elsewhere that it's OK to expand it. It would be nice to be able to tell the type-checker not to expand (or perhaps, to _try_ not to expand) certain definitions within the current module. This could perhaps be done with an `abstract` keyword within an `open` statement, e.g.:

`open import OtherModule abstract using (ident)`

**Comment by nad** [comment] 2020-05-11 11:17
There is a shortcut that identifies syntactically equal things. However, "syntactic equality" includes implicit arguments. If the implicit arguments of the two expressions have been solved in different ways, then it might take a long time for Agda to verify that two "obviously equal" things are actually equal.

I suspect that irrelevance can make it harder to solve meta-variables, because there are fewer restrictions. If you compare the two irrelevant expressions `meta` and `4`, then it might be OK to solve `meta` using `4`, but maybe not, because `meta` might also be involved in some other constraint.

For a local variant of `abstract`, see #433.

**Comment by andreasabel** [comment] 2020-05-11 18:22
@msuperdock 
> I've also found that sometimes replacing records with equivalent data types speeds things up drastically, which breaks my mental model that a record is essentially a data type with one constructor.

If this is how you see records, you should add `no-eta-equality` always.  The difference between records and data types with one constructor is precisely that records are up to eta but data is not.

There is even an option `--no-eta-equality` to make this the default.

**Comment by jespercockx** [comment] 2020-05-22 09:43
This issue identifies a lot of different problems and has some vague suggestions of how things could be improved, but it is not clear what actionable items there are. Hence I will close this issue, but if you would like to discuss one of your suggestions in more detail feel free to open a new issue about that one specific suggestion.

**Closed as completed by jespercockx** 2020-05-22 09:43 UTC
Labels: type: enhancement, eta, meta, performance, irrelevance, faq
