### ISSUE TITLE
JS backend hangs when compiling Data.Bool.Properties

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#1627] opened 2015-08-14 22:10 UTC
`Data.Bool.Properties` from the standard library causes the compiler to hang indefinitely when using the JS backend. I'm on 64-bit Linux, with a fairly recent version of Agda.

**Comment by asr** [comment] 2015-08-15 00:42
In https://github.com/agda/agda/issues/1072 the problem is in maint-2.4.2.4, in this issue the problem is in master, i.e. 

``` Agda
module Test where

open import Data.Bool.Properties
```

doesn't hang in maint-2.4.2.4 but in master.

**Comment by phile314** [comment] 2015-09-28 10:05
There is currently no maintainer for the JS backend. The best long-term strategy is probably to port the JS backend to the Treeless syntax, but that requires somebody to actually do the work...

I doubt this will be fixed in 2.4.4, but if anyone plans on fixing this feel free to move it again.

For the bug itself, my best guess would be that this bug has to do with singleton detection/smashing optimization in the JS backend.

**Comment by identicalsnowflake** [comment] 2015-09-28 19:49
Not sure exactly what the problem is, but I do know exactly where it is: it happens on lines 249/250

``` agda
module XorRingSolver =
  Solver (ACR.fromCommutativeRing commutativeRing-xor-∧) _≟_
```

If I comment these two lines, it compiles. It's a bit strange, since the code on lines 109/110 is very similar, but doesn't cause problems.

Can you point me somewhere where I can read about how Agda backends work? I have a lot of interest in this. I'm certainly not the ideal maintainer for a backend, but perhaps with some effort I could be better than nobody.

**Comment by phile314** [comment] 2015-09-29 07:27
Contributions are more than welcome :-)

There is a paper describing the JS backend: http://ect.bell-labs.com/who/ajeffrey/papers/padl13.pdf
All JS backend code is in src/full/Agda/Compiler/JS.

For Agda backends bugs in general, I normally do debug it using Agda's verbose mode (e.g. "-v 10") and/or insert trace expressions in the code I'm looking at.  This should at least give a hint which part
of the backend is responsible for hanging.

In general, it's also a problem that we don't have any tests for the JS backend which are actually run. Adding support for the JS backend in the existing compiler tests would already go a long way to make the JS backend more viable in the future. For this, one would have to add the necessary COMPILED_JS pragmas in the test/Common/... files and decide how Javascript files are to be run (e.g. node, rhino?).

That are the things I could think of right now. If you have questions or need any help, just ask.

**Comment by identicalsnowflake** [comment] 2015-09-29 18:55
So I should be able to get a lot of free (well, cheap) mileage by just implementing the existing tests in JS? That sounds straightforward enough.

You also mentioned converting to a newer "treeless" syntax. Do you have any information on that?

**Comment by phile314** [comment] 2015-09-29 19:41
Yes, I think adding support for the JS backend in the tests should be more or less straightforward. The tests themselves are in ./test/Compiler/simple/, but ./test/Common contains some common stuff like Bool, Nats, IO etc.

To see how it works for the MAlonzo backend, you can do "make && make compiler-test" and it should execute the tests for the MAlonzo backend. So the goal would be that "make compiler-test" also runs the JS-backend tests.

I wrote most of the compiler-test stuff, so if you run into any problems feel free to ask. I think it would make sense if you focus on getting e.g. the ./test/Compiler/simple/HelloWorld.agda test case to run with JS and calling Agda manually, we can discuss hooking it up with the test infrastructure after that. (The ./test/Compiler/Tests.hs test runner needs to be extended for that)

About Treeless Syntax, porting JS to it would give it support for copatterns and maybe also fix a bug
related to some corner cases in pattern matching. It would also make maintenance of the JS backend easier in the long run, and maybe you would get some optimizations for free at some point. Porting shouldn't be too difficult, but we really need the tests before trying to do this.

**Comment by asajeffrey** [comment] 2015-09-29 20:26
There are also tests for the JS back end in test/js, but they're showing 
their age a bit (e.g. using rhino rather than node.js for execution).

There's also a test suite that runs in the browser, over in 
https://github.com/agda/agda-frp-js

A.

**Comment by np** [comment] 2015-09-29 22:16
Adapting the tests to node.js is also part of the ongoing changes I have...

**Comment by phile314** [comment] 2015-09-30 07:51
@np :+1: Do you mean the test/js or the test/Compiler tests? Any idea when you get round to push the test changes?

**Comment by np** [comment] 2015-10-12 13:21
The general issue I have is unfinished changes which ends up bitrotting.
I'm willing to spend some time to rebase these changes.
Some issues would definitely go away by switching to your treeless syntax, I started doing so one day but got distracted by what was duplicated among the backends.
A quick glance at the code tells me that this seems to be resolved, still there is potentially some functions in Agda.Compiler.UHC.FromAgda which are not specific to UHC but could be moved in Treeless. What do you think @phile314 ?

**Comment by phile314** [comment] 2015-10-12 13:44
Can you maybe push your unfinished changes to a branch, then I could give them a quick look.

The Treeless -> UHC Core / MAlonzo Haskell translation mostly does three things:
- Replace De Bruijn indices by names.
- Replace Agda names by valid JS/HS/UHC Core names. This is somewhat target language specific, e.g. is Unicode allowed?
- Translate Case expressions. If I remember correctly, the Javascript backend does something special
  to emulate case expressions in JS? Anyway, I think this shouldn't be terribly difficult either.

The main reason why I haven't ported the JS backend myself are that there are not that many tests, and I don't want to break stuff.

What JS interpreter are you using to actually run the JS code? How can I install that?

**Comment by miikka** [comment] 2016-07-22 22:00
Out of curiosity, I spent some time today looking at making the compiler tests under `test/Compiler/simple` runnable with Node.js. You can execute a test case with something like this:

```
agda --js --compile-dir tmp/ HelloWorld.agda 
NODE_PATH=tmp/ node tmp/jAgda.HelloWorld.js
```
- Getting `HelloWorld.agda` pass with Node is as easy as to add `{-# COMPILED_JS putStr function (x) { return process.stdout.write(x); } #-}` to `Common/IO.agda`.
- When you want to use more than one module: Agda generates AMD modules, but Node expects Common.js modules. Either you need to make Node load AMD modules or make Agda generate Common.js (or [UMD](https://github.com/umdjs/umd)) modules.

Beyond that, you would add `COMPILED_JS` pragmas until the tests pass. It seems that so far Agda does not contain almost any JS implementations for the primitives, so few of the tests will pass. I'm not sure if this intentional or lack of resources. Is the user meant to provide their own implementations?

You can see my (quite rough) experiment [here](https://github.com/miikka/agda/commit/6277ebb72c9723ff8c733499a5c4502153134301).

**Comment by phile314** [comment] 2016-07-25 11:32
Thank you for your contribution, this makes hacking on the JS backend much more pleasant :-)

I started porting the JS backend to use the intermediate Treeless Syntax as input, you can see my WIP branch here:
https://github.com/agda/agda/tree/treeless-js

The basic stuff works, but quite a few primitives are still missing. The good news is that almost half the tests already work. If somebody wants to help, feel free to pick a test case and start adding the missing primitives.

**Comment by phile314** [comment] 2016-09-20 20:59
Could not reproduce this on current stable ( 7e0d7b323cb36bce0643d82fddbffee8f76daa89 ) or master ( c9065360ab8695bf71956ba75db2985b8c78634e ). Probably fixed by https://github.com/agda/agda/pull/2157 .

**Closed as completed by phile314** 2016-09-20 20:59 UTC
Labels: type: bug, backend: js, master
