### ISSUE TITLE
Travis GHC 8.0 Cabal compilation times out frequently

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4177] opened 2019-11-07 06:36 UTC
Often the compilation of Agda on ghc 8.0 with cabal does not finish on travis, running out of time or memory.  This has the effect that the tests of the subsequent phase (haddock and user manual) are not run.
Example: https://travis-ci.org/agda/agda/builds/608463955

@L-TChen: could we move the 8.0/cabal test out of the block "Main" on which the "Documentation" block depends?

Re: #4025

**Comment by L-TChen** [comment] 2019-11-07 13:07
Yes. That's absolutely fine. 

However, I failed to see why cabal with GHC 8.0.2 takes much longer than stack with GHC 8.0.2. Travis only caches dependencies not the local build of Agda, so they should take roughly the same time to compile Agda itself. It seems there is some other issue involved.

**Comment by andreasabel** [comment] 2019-11-08 07:56
Well, the last words on travis are usually:
```
[336 of 373] Compiling Agda.TypeChecking.Coverage ( src/full/Agda/TypeChecking/Coverage.hs, /home/travis/dist/build/Agda/TypeChecking/Coverage.o )


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated.
```
My first guess is that compilation on ghc 8.0 needs more memory than travis supplies, so the compilation stalls in thrashing.  Just a guess, of course.

One thing we could try is to split `Coverage.hs` into several smaller modules and see if this improves compilation times.

**Comment by L-TChen** [comment] 2019-11-08 17:14
I was talking about the difference between stack and cabal compilation. However, I forgot that the stack compilation does not apply optimisation.

As @UlfNorell mentioned, it seems unnecessary to run the Agda test suite against every supported GHC version, so we shall compile only one Agda with optimisation enabled to run tests and others without it. It would also make the testing time much shorter too. We can run full testing only on release branches. 

If the above solution makes sense, then the question is which GHC version to compile Agda for testing.

**Comment by asr** [comment] 2019-11-08 17:21
Which optimisation are you talking about?

**Comment by L-TChen** [comment] 2019-11-08 17:23
Stack compilation uses `-O0` and cabal uses the default option.

**Comment by nad** [comment] 2019-11-08 19:32
> If the above solution makes sense, then the question is which GHC version to compile Agda for testing.

I'd suggest to use the latest version, as I imagine that this one is typically most representative of future versions of GHC.

**Comment by JacquesCarette** [comment] 2019-11-08 19:40
I would counter-suggest using the "latest version fully supported by cabal and stack". There can sometimes be up to 2 months of delay between a shiny new GHC release and the stabilization of the library ecosystem so that things are reliably buildable.

**Comment by nad** [comment] 2019-11-08 21:25
Sure, I don't think we should use a version of GHC that fails to build Agda.

**Comment by L-TChen** [comment] 2019-11-09 16:19
Alright, the consensus seems to be the latest GHC version which is fully supported by the ecosystem and is able to compile Agda successfully. 

I will get this change in soon.

**Comment by andreasabel** [comment] 2019-11-13 07:19
> If the above solution makes sense, then the question is which GHC version to compile Agda for testing.

Note that the current problem is that already the _compilation_ of Agda stalls on GHC 8.0; it never gets to run the test suite.  

For the compilation tests (GHC backend) it does matter which GHC version we are testing Agda on.  (See #4100, #4018, #3792.)  However, we could restrict to only running the compiler tests on each GHC version, and run the full testsuite only on one version.

**Comment by L-TChen** [comment] 2019-11-13 11:48
> Note that the current problem is that already the compilation of Agda stalls on GHC 8.0; it never gets to run the test suite.

If it is not for testing, we can use `-O0` to turn off optimisation, so it will take only about 10 mins to compile in total for each compilation. I turn on Travis cabal ghc 8.0 test with a longer waiting time for now. 

I am currently working on another configuration as proposed above. The progress is a bit slow as it is not possible to run Travis locally to try out different configurations. 

[This](https://travis-ci.org/L-TChen/agda/builds/611106524) is what I have so far:

1. The local build of Agda for testing is cached, so that it can be reused.
2. Each compilation is with `-O0` (i.e. `--fast` for stack) and takes less than 10 mins in general. 

It should shorten the total time of Travis testing significantly later.

**Comment by L-TChen** [comment] 2019-11-13 15:29
https://travis-ci.org/L-TChen/agda/builds/611387067 

Almost there. I’m not sure if it makes sense to test `agda-bisect` and `size-solvers` in the last stage. It is probably better to have another repos for them with their own Travis configurations and to include these two as submodules.

**Comment by nad** [comment] 2019-11-13 22:40
I don't think `agda-bisect` should be moved to another repository.

**Comment by andreasabel** [comment] 2019-11-17 20:43
Haha, quite ironically, after I commented out the ghc 8.0 cabal test, it is now the 8.2 cabal test that breaks, running out of memory for ghc: https://travis-ci.org/agda/agda/jobs/613179836

**Comment by L-TChen** [comment] 2019-11-17 21:46
🤦‍♂ I will try to finish the new configuration soon when available.

**Comment by WolframKahl** [comment] 2019-11-17 22:27
> it is now the 8.2 cabal test that breaks, running out of memory for ghc

Consider passing maximum heap settings also to GHC?

**Comment by L-TChen** [comment] 2019-11-19 17:58
I don't know why I got the following error message on Travis while I cannot reproduce on my machine either with ghc 8.8.1 or 8.6.4:
```
make[2]: Entering directory `/home/travis/build/L-TChen/agda/src/hTags'
521cabal v1-install --only-dependencies
522cabal: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with
523Cabal. Use the flag --package-db to specify a package database (it can be used
524multiple times).
```
This only happens when `make TAGS`, `make test-size-solver`, and `make install-agda-bisect`. 

The configuration file is [here](https://github.com/L-TChen/agda/blob/issue4177/.travis.yml).

Did anyone experience this? 

(working with Docker and run Travis locally ...)

**Comment by L-TChen** [comment] 2019-11-19 23:20
No help is needed. After running Travis locally, I managed to solve the problems. I am waiting for Travis running on my branch to finish. It should be ready in a few days. 

The new configuration should shorten the testing time by few hours.

**Comment by L-TChen** [comment] 2019-11-22 03:45
The maximum heap settings has now been passed to GHC.
Also, on non-`master` branches, only one Agda is built with GHC 8.8.1 without the `-O0` option to run test suites. Others are built with `-O0` by GH Actions. The change should resolve the issue.

**Comment by asr** [comment] 2020-02-26 20:54
Note that we are running the full tests _only_ on releases branches. The problem described in the OP came back after merging `master` on `release-2.6.1`, see Travis [job](https://travis-ci.org/agda/agda/jobs/655404938).

**Comment by nad** [comment] 2020-02-28 11:34
Is this something that has to be fixed before the release of 2.6.1? I guess it would be possible to run the test suite locally.

One option might be to only turn on the heavy optimisation settings (`-fexpose-all-unfoldings` and `-fspecialise-aggressively`) for GHC 8.2 and later, if this does not hurt performance too much.

**Comment by asr** [comment] 2020-03-02 14:51
@L-TChen, I'm testing a fix for this issue using `travis_wait`. Why was necessary the file [.travis/header.sh](https://github.com/agda/agda/blob/f275daf2443ac348c287e08cb53ffec7db59625d/.travis/header.sh) ?

**Comment by L-TChen** [comment] 2020-03-02 14:59
@asr Travis CI exports some shell functions, but they are not in the scope of a shell script, which I used to hide details `.travis/cabal_install`. There were more scripts before moving to GitHub. Since there are only two scripts, it should be fine to get rid of them completely.

I will assess the possibility and the benefit of moving the rest of testing to GitHub after the release of 2.6.1.

**Comment by asr** [comment] 2020-03-02 15:03
> @asr Travis CI exports some shell functions, but they are not in the scope of a shell script, which I used to hide details `.travis/cabal_install`.

Thanks for the explanation.

**Closed as completed** 2020-03-03 14:17 UTC
Labels: travis, ghc-8.0.2, not-in-changelog

**Comment by asr** [comment] 2020-03-03 14:20
> One option might be to only turn on the heavy optimisation settings (`-fexpose-all-unfoldings` and `-fspecialise-aggressively`) for GHC 8.2 and later, if this does not hurt performance too much.

Thanks. I removed the heavy optimisation settings when testing with GHC 8.0.2.
