### ISSUE TITLE
Case splitting patterns that span across multiple lines

### ISSUE THREAD

**Issue by ashinkarov** [agda/agda#5009] opened 2020-10-26 01:17 UTC
The following code is happily accepted by Agda:
```agda
data X : Set where c : X → X
f : X → X
f (c
      x
  ) = {! x !} 
```
However, if I try to case-split on `x` in Emacs, I get the following output:
```agda
data X : Set where c : X → X
f : X → X
f (c
      x
  f (c (c x)) = ?
```
and the following parsing error:
```
/tmp/bug.agda:5,17-17
/tmp/bug.agda:5,17: Parse error
<EOF><ERROR>
...
```
If inspect the output of `--interaction-json` when case splitting (`kind: MakeCase`), we only obtain the new clauses, and the location of the hole, but not the location of the clause that this hole refers to.  Shall we track the clause that the hole "belongs" to?

**Comment by jespercockx** [comment] 2020-10-26 07:33
I believe this is a duplicate of https://github.com/agda/agda/issues/2628 and/or https://github.com/agda/agda/issues/1146

Quoting @andreasabel from that issue:

> I think with the current infrastructure the emacs mode cannot do much better. After the load the user is allowed to shift holes around and freely add Agda text and comments. Agda does only knows the state of the last load action, but contents of the emacs buffer may have diverged from that when the user calls the case split tactics. Agda sends the new clauses back and the emacs-mode has to integrate them somehow into the text which is different from what Agda perceived it was.
> 
> For this to work, the emacs-mode would have to keep track of the boundaries of a clause to be able to substitute it completely. Agda could, after parsing, communicate to emacs where the clause boundaries are, and emacs puts some invisible markers there which move along with the text the user adds.
> 
> However, even then case split is not safe. It could overwrite stuff the user put inside the clause boundaries.
> 
> I'd speculate the current buggy behavior predates Agda 2 and existed even in Agda 1. As far as I know, the interaction model of Agda 2 was inherited from Agda 1.

**Closed as completed** 2020-10-26 08:58 UTC
Labels: status: duplicate
