### ISSUE TITLE
Internal error with missing type signature in `interleaved mutual` type

### ISSUE THREAD

**Issue by phijor** [agda/agda#5638] opened 2021-11-09 12:09 UTC
## Bug

I mistyped a definition and `agda` crashed with an internal error.

A minimum working (=crashing) example is:

```agda
interleaved mutual
  data Foo where -- note the missing signature `: Set`
      bar : Foo
```

This produced the following error (pointing [here](https://github.com/agda/agda/blob/246a229faea2ef2fa53caf491ff8a2d72dd7510c/src/full/Agda/Syntax/Concrete/Definitions.hs#L851)):

```
Checking min (/tmp/min.agda).
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/Syntax/Concrete/Definitions.hs:851:18 in Agda-2.6.2-5jc1iNTuYyE88p7NRZUfQI:Agda.Syntax.Concrete.Definitions
```

Without the `interleaved mutual` block, the above type checks.

## Agda version

```sh
$ agda --version
Agda version 2.6.2
```

## Related issues

I tried looking for existing issues, maybe this is related to #4881?

**Comment by andreasabel** [comment] 2021-11-16 08:27
Thanks for reporting @phijor!
This is already fixed on `master`:
```
The following names are defined but not accompanied by a
declaration: Foo
```
Looks like a duplicate of #5558.
We close issues once they are fixed on master, so if you want to find related issues, you also have to look through the closed ones...

**Closed as completed by andreasabel** 2021-11-16 08:27 UTC
Labels: status: duplicate, status: already-fixed, regression in 2.6.2, interleaved mutual
