### ISSUE TITLE
Incorrect split for overlapping patterns

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#191] opened 2015-08-08 17:53 UTC
``` agda
module Bug where

data T (A : Set) : Set → Set1 where
  c₁ : {B : Set} → T A B
  c₂ :             T A A

foo : {A B C : Set} → T A (B → C) → T A B → Set₁
foo c₁ y = Set
foo x  y = {!y!}

-- Perform the indicated case split. Agda will happily replace the
-- last clause with two separate clauses, one for each constructor
-- of T, but the resulting file is not type correct:

-- Bug.agda:8,1-10,13
-- Cannot split on the constructor c₂
-- when checking the definition of foo

-- In this case Agda should not modify the source file, it is
-- preferable to just give an error indicating that the split cannot
-- be performed.

```

Original issue reported on code.google.com by `nils.anders.danielsson` on 24 Aug 2009 at 3:01

**Comment by andreasabel** [comment] 2016-06-20 10:08
New behavior: Agda refuses to split. (As wished by reporter.)

**Comment by jespercockx** [comment] 2019-08-08 16:35
The underlying issue here was never really fixed, my changes just happened to produce the right error for this particular test case.

**Comment by jespercockx** [comment] 2021-05-17 20:29
I'm not sure anymore what I meant by that comment and I'm not sure if the problem is even still there, so I'm closing this. There should be a new issue if the problem still exists.

**Closed as completed by jespercockx** 2021-05-17 20:29 UTC
Labels: type: bug, coverage, ux: case splitting, unification
