### ISSUE TITLE
Nested anonymous modules and anonymous definitions do not mix

### ISSUE THREAD

**Issue by davdar** [agda/agda#3477] opened 2018-12-26 15:13 UTC
Here is a small example to demonstrate the bug:

`````
module Bug.Underscore where

postulate undef : ∀ (A : Set) → A
  
-- WORKS

module _ {A : Set} where
  module _ {B : Set} where
    _ : A → B
    _ = undef (A → B)
  _ : A
  _ = undef A

-- DOES NOT WORK

{-
module _ {A : Set} where
  _ : A
  _ = undef A
  module _ {B : Set} where
    _ : A → B
    _ = undef (A → B)
-}
`````

The DOES NOT WORK part fails with:

`````
Ambiguous name _. It could refer to any one of
  .Underscore._ bound at
    <path>/Underscore.agda:20,5-6
  .Underscore._ bound at
    <path>/Underscore.agda:17,3-4

`````

I expect the behavior to work just the same as the WORKS example.

**Comment by gallais** [comment] 2018-12-26 17:00
Works for me with Agda 2.6.0-b5beca5. Could it be a duplicate of #3302 which was
fixed by #3310?

**Closed as completed** 2018-12-26 17:03 UTC
Labels: scope, status: already-fixed, not-in-changelog
