### ISSUE TITLE
Restore sharing of no-argument constructors without turning BUILTIN ZERO into `Lit (LitInt _ 0)`.

### ISSUE THREAD

**Issue by mechvel** [agda/agda#1691] opened 2015-10-18 14:05 UTC
This is on  Development Agda October-17, 2015.

``` agda
open import Relation.Binary.PropositionalEquality as PE using (_≡_)
open import Data.Nat.Base using (ℕ; suc; pred; _∸_)

∸1≗pred :  ∀ {n} → n ∸ 1 ≡ pred n
∸1≗pred {0}     = PE.refl
∸1≗pred {suc _} = PE.refl
```

```
  `agda $agdaLibOpt --sharing Nat0.agda`
```

reports

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/CompiledClause/Match.hs:189
```

**Comment by andreasabel** [comment] 2015-10-18 18:20
Without the std-lib, we require an import to reproduce the error:

``` agda
module Issue1691.Nat where

data ℕ : Set where
  zero : ℕ
  suc  : (n : ℕ) → ℕ

{-# BUILTIN NATURAL ℕ #-}

_∸_ : ℕ → ℕ → ℕ
m     ∸ zero  = m
zero  ∸ suc n = zero
suc m ∸ suc n = m ∸ n

pred : ℕ → ℕ
pred zero    = zero
pred (suc n) = n
```

Main module:

``` agda
module Issue1691 where

open import Common.Equality
open import Issue1691.Nat  -- works if we inline this module

∸1≗pred :  ∀ n → n ∸ suc 0 ≡ pred n  -- works if zero is replaced by 0
∸1≗pred zero    = refl
∸1≗pred (suc _) = refl
```

Command (if above reside in test/bugs):

```
agda -i. -i.. --sharing Issue1691.agda -v impossible:10 
```

Error:

```
Incomplete pattern matching when applying Issue1691.Nat._∸_
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/CompiledClause/Match.hs:189
```

**Comment by andreasabel** [comment] 2015-10-18 18:32
With -v 100 we see that Agda chokes on a shared literal:

```
*** reduced definition:  _∸_
    result .n ∸ 0
    raw    Shared #198{Def Issue1691.Nat._∸_ [Apply r(Var 0 []),Apply r(Shared #197{Lit (LitInt 0)})]}
reducing case _∸_ $ .n $ 0
trying clause case 1 of
  Issue1691.Nat.ℕ.zero -> done[r("m")] Var 0 []
  Issue1691.Nat.ℕ.suc -> ...
Incomplete pattern matching when applying Issue1691.Nat._∸_
```

**Comment by andreasabel** [comment] 2015-10-18 19:21
With --sharing, the constructorForm of literal 0 is still literal 0, where it should be the constructor zero.  My suspicion is that builtins like builtinZero are shared, and reducing something using that shared builtinZero turns it into literal 0.

@UlfNorell: I really think side effects like sharing via IORefs are a perfect tool to shoot yourself into the foot.  Even more so given long-term development with a changing developer team...

**Comment by andreasabel** [comment] 2015-10-18 21:36
My fix is quite crude, there might be a better fix.  But anyway, the current sharing implementation with IORefs is not there to stay.  Fixing this issue places a test case into the test suite which further changes to the sharing mechanism can be tested against.

The problem was that `BUILTIN (Con "zero" [])` was overwritten by `(Lit (LitInt _ 0))` due to the sharing introduced by deserialization and the reduce magic which reconstructs literals.  This caused `constructorForm` not to produce `(Con "zero" [])` for the literal 0 anymore, leading to a match failure.  The fix I ended up implementing is not to share constructors without arguments anymore (which includes `zero`).

**Comment by WolframKahl** [comment] 2015-10-19 03:58
When certain leaves are not shared, many inner nodes cannot be shared either. This fix therefore effectively disables sharing for constructor-heavy applications, as confirmed by some typechecking timings:

```
Main.lagda    Alloc (MB)  Max.Res.(MB)  AllocRate     real     productivity
--no-sharing  791,375       4,006    1,048,247,839  14m43.813s    85.7%
--sharing     811,281       5,215      992,390,776  15m43.641s    86.9%  (no -v)
--sharing     817,433       4,190      985,611,191  15m47.847s    87.8%

AContext2 (probably no zero-ary constructors)
--no-sharing 1,048,519      2,348    1,205,560,521  15m39.950s    92.6%
--sharing      736,966      3,257    1,204,222,374  11m31.774s    88.5%

Data/SUList/ListSetMap/FinRel/NatSumProps.lagda
  (pulls in most of the constructor-heavy material used by Main.lagda):
--no-sharing   366,346      1,817   1,071,006,086    6m32.807s    87.2%
--sharing      366,501      2,040     936,084,337    7m25.373s    88.0%
```

(2015-10-19: Fixed Max.Res. numbers in summary.)

[2015-10-18_sharing-noconst.txt](https://github.com/agda/agda/files/16022/2015-10-18_sharing-noconst.txt)

**Comment by andreasabel** [comment] 2015-10-19 08:19
This means that this issue has to be fixed in another way, but I won't do it, maybe @UlfNorell can come up with a better fix, given the documentation of the problem I have given above.

**Comment by mechvel** [comment] 2015-10-19 11:03
I compare  Agda-oct8 --no-sharing   and  

Agda-oct19  --sharing    (after the "fix" of Oct 19)
on  type-checking  Goal.agda  (after all  other modules are checked) :

-MGb    time[sec]
         --no-sharing   --sharing
12       448              436  
11       488  
10       626             460  
 9      1246             485  
 8                           556
 7                           746

It looks like  --sharing  somewhat helps -- for this example, and when it is close to the lower space bound.
I shall see this further, for the example where the proofs are returned from postulated.
It is desirable to get it within, say,  10 Gb   and  15 minutes.

On the other hand, the cost of  (space \* time)  remains unnaturally great.

I do not understand the subject of sharing IORefs, literals and such. 
But consider a naive question:

if  Agda "shares everything" (as before this fix), and the language requires to write
Nat.zero  and   (suc (suc ... Nat.zero)...)   everywhere instead  of    <literal> : Nat,
then
will   --sharing   have a real cost effect?

**Comment by mechvel** [comment] 2015-10-19 11:08
The the table needs to be printed this way:
-MGb time[sec]
--no-sharing --sharing
12 448 436
11 ----  488
10 626 460
9  1246 485
8 ------- 556
7 ------- 746

**Comment by WolframKahl** [comment] 2015-10-21 22:29
Sergei,

   I recommend that you try Andrea's patch from https://github.com/agda/agda/issues/1625#issuecomment-132196576 --- with that and with --no-sharing I am getting the best results so far.

Wolfram

**Comment by mechvel** [comment] 2015-10-22 08:38
On Wed, 2015-10-21 at 15:29 -0700, WolframKahl wrote:

> Sergei,
> 
> I recommend that you try Andrea's patch from #1625 (comment) --- with
> that and with --no-sharing I am getting the best results so far.
> 
> Wolfram
> 
> —
> Reply to this email directly or view it on GitHub.

Thank you.
So far,  Dev Agda of Oct.19   has a bug #1695, so that I cannot use it
in my program neither under  --no-sharing  nor under  --sharing.

Do you suggest to apply this patch to  Development Agda of October 19 ? 

May be, I need to wait for the development version to become a bit more
stable. 

---

Sergei

**Comment by WolframKahl** [comment] 2015-10-22 15:46
You can try it on the last version that woks for you (don't worry about sharing problems).

**Comment by mechvel** [comment] 2015-10-25 10:21
On Wed, 2015-10-21 at 15:29 -0700, WolframKahl wrote:

> Sergei,
> 
> I recommend that you try Andrea's patch from #1625 (comment) --- with
> that and with --no-sharing I am getting the best results so far.

I see in #1625 a patch in a comment by  

Saizan commented Aug 18, 2015 :

---

--- a/src/full/Agda/TypeChecking/Conversion.hs
...
...

##   assign dir x es v = do

On the other hand, you refer to a patch by A.Vezzosi.
Where precisely the needed patch resides?

Thanks,

---

Sergei

**Comment by WolframKahl** [comment] 2015-10-25 16:33
On Sun, Oct 25, 2015 at 03:21:50AM -0700, mechvel wrote:

> On Wed, 2015-10-21 at 15:29 -0700, WolframKahl wrote:
> 
> > I recommend that you try Andrea's patch from #1625 (comment) --- with
> > that and with --no-sharing I am getting the best results so far.
> 
> I see in #1625 a patch in a comment by  
> 
> Saizan commented Aug 18, 2015 :
> 
> ---
> 
> --- a/src/full/Agda/TypeChecking/Conversion.hs
> ...
> ...
> 
> ##   assign dir x es v = do
> 
> On the other hand, you refer to a patch by A.Vezzosi.
> Where precisely the needed patch resides?

You are looking at the right patch:
If you follow the link to `Saizan'' (from his`avatar'' icon),
you'll understand why... ;-)

Wolfram

**Comment by UlfNorell** [comment] 2018-05-28 14:57
The `--sharing` flag has been discontinued.

**Closed as completed by UlfNorell** 2018-05-28 14:57 UTC
Labels: status: wontfix, type: enhancement, literals, sharing
