### ISSUE TITLE
no documentation for `..{n} -> `  irrelevance syntax  -- or in the manual

### ISSUE THREAD

**Issue by cartazio** [agda/agda#2635] opened 2017-07-09 15:51 UTC
eg in https://github.com/UlfNorell/agda-prelude/blob/master/src/Prelude/Fin.agda#L13

```agda
data Fin : Nat → Set where
  | zero : ∀ ..{n} → Fin (suc n)
  | suc  : ∀ ..{n} (i : Fin n) → Fin (suc n)
```

also  theres no docs on irrelevance and current syntax in the docs... just in the change logs :)

**Comment by andreasabel** [comment] 2017-07-11 17:56
I think Ulf's use of the `..` modality isn't quite safe yet, see #2640.
And mine neither: #2595.

**Comment by UlfNorell** [comment] 2017-07-12 09:57
For future reference, #2640 is a problem with `..` in general and not with my particular use.

**Comment by jespercockx** [comment] 2017-09-14 15:39
This is a duplicate of #1114.

**Closed as completed** 2017-09-14 15:39 UTC
Labels: status: duplicate, irrelevance, ux: documentation, type: task

**Comment by andreasabel** [comment] 2017-09-18 21:28
We should document `..` once we have resolved #2757 (and actually know what `..` is).

**Comment by jespercockx** [comment] 2017-09-19 08:44
Well, $..$ is related to $.$ the same way $#$ is related to regular relevant functions. So in principle, once we know how parametricity works, explaining $..$ shouldn't be hard.
