### ISSUE TITLE
Implicit arguments break record-module creation

### ISSUE THREAD

**Issue by omelkonian** [agda/agda#5171] opened 2021-02-04 11:08 UTC
Creating a record from a module does not work when a field definition contains implicit arguments, but works with explicit arguments.

```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

Symmetric : ∀ {A : Set} → (A → A → Set) → Set
Symmetric _≈_ = ∀ {x} y → x ≈ y → y ≈ x
-- Symmetric _≈_ = ∀ x y → x ≈ y → y ≈ x

record Signature : Set₁ where
  field
    A : Set
    _≈_ : A → A → Set
    ≈-sym : Symmetric _≈_

module Implementation where
  record A : Set where
    field
      x : Nat
      .pr : x ≡ 0
  open A

  _≈_ : A → A → Set
  a ≈ b = x a ≡ x b
  -- _≈_ = _≡_

  postulate
    ≈-sym : Symmetric _≈_

test : Signature
test = record {Implementation}
-- YELLOW: _pr_25 : Implementation.A.x x ≡ 0
```

- NB1: Replacing any of the commented alternatives fixes the issue.
- NB2: The irrelevance of field `pr` does not really matter.

**tested in Agda 2.6.1**

**Comment by andreasabel** [comment] 2021-02-05 16:29
It does not seem specific to record-from-module, you get the same yellow if you assign the fields manually:
```agda
test2 : Signature
test2 = record
  { A     = Implementation.A
  ; _≈_   = Implementation._≈_
  ; ≈-sym = Implementation.≈-sym
  }
```

**Comment by gallais** [comment] 2021-02-05 16:32
We have a lot of eta-expanded field assignments to avoid similar problems
in the stdlib. Implicits are eagerly introduced and then cannot be solved
because the solution may not be unique.

**Comment by andreasabel** [comment] 2021-02-05 16:41
Here is the shrunk test:
```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality
open import Agda.Builtin.Sigma

A : Set
A = Σ Nat (_≡ 0)

_≈_ : A → A → Set
a ≈ b = Σ.fst a ≡ Σ.fst b

Reflexive : Set
Reflexive = ∀ {x} → x ≈ x

postulate
  ≈-reflexive : Reflexive

works : Reflexive
works {x} = ≈-reflexive {x}

test : Reflexive
test = ≈-reflexive
```
This is a duplicate of the recent #5110 user question, see #1079 for the whole story.

**Closed as completed by andreasabel** 2021-02-05 16:41 UTC
Labels: hidden arguments, faq
