### ISSUE TITLE
Same name in function type does not return an error.

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#2869] opened 2017-12-14 12:37 UTC
Shouldn't this return an error?

```agda
module test where

data Test : Set where

fun : (a : Test) → (a : Test) → Test
fun = {!!}
```

**Comment by ice1000** [comment] 2017-12-14 14:36
Why should this return an error?

```agda
fun : (a : Test) → (a : Test) → Test
fun () ()
```

What's the problem?

**Comment by ice1000** [comment] 2017-12-14 14:40
Maybe it's just a kind of shadowing.

```agda
data A : Set where
  a : A
  b : A

fun : (a : A) → (a : A) → A
fun x _ = x

fun₂ = fun a a
fun₃ = fun a b
```

This code checks, seems that same name doesn't mean they should be the same.

**Comment by andreasabel** [comment] 2017-12-15 07:31
Sometimes it is convenient to allow this kind of shadowing, e.g.:
```
id : {a : Level} {A : Set a} (a : A) -> A
id a = a
```

**Comment by ice1000** [comment] 2017-12-15 08:32
I think this should be closed.

**Comment by andreasabel** [comment] 2017-12-15 08:43
Duplicate of #2284.

**Closed as completed by andreasabel** 2017-12-15 08:43 UTC
Labels: shadowing
