### ISSUE TITLE
Built Agda fails test Issue4967

### ISSUE THREAD

**Issue by mouse07410** [agda/agda#5130] opened 2021-01-14 23:09 UTC
MacOS-10.15.7, GHC-8.10.3, Cabal-3.2.0.0, current master.

<img width="555" alt="Screen Shot 2021-01-14 at 18 05 48" src="https://user-images.githubusercontent.com/5923577/104659906-89fa5e00-5693-11eb-8f7c-887371d5b4aa.png">

Complete logs:
[make-out-2021-01-14.txt](https://github.com/agda/agda/files/5817445/make-out-2021-01-14.txt)
[make-test-2021-01-14.txt](https://github.com/agda/agda/files/5817446/make-test-2021-01-14.txt)

**Comment by L-TChen** [comment] 2021-01-15 03:00
Duplicate of #5131.

**Closed as completed by L-TChen** 2021-01-15 03:00 UTC
Labels: status: duplicate, infra: test suite
