### ISSUE TITLE
Printer needs to parenthesize atom if there is an operator of the same name

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1616] opened 2015-08-08 18:20 UTC
```
-- The printer of Agda seems to be forgetting parentheses

data One : Set where
  z : One

_∘_ : One → One → One
z ∘ z = z

data Ctx : Set where
  ∘ : Ctx

data Bug : Set where
  trick : One → Ctx → One → Bug

bug : Bug
bug = trick z (∘) z
-- Auto produces trick z ∘ z which can't be parsed
```

Original issue reported on code.google.com by `theo.win...@gmail.com` on 23 Jul 2015 at 4:50

**Comment by nad** [comment] 2015-08-14 12:39
Duplicate of #1455.

**Closed as completed by nad** 2015-08-14 12:39 UTC
Labels: type: bug, ux: display
