### ISSUE TITLE
__IMPOSSIBLE__ triggered in conApp

### ISSUE THREAD

**Issue by Blaisorblade** [agda/agda#1712] opened 2015-11-05 01:52 UTC
I have a non-minimized bug report on a codebase of mine, that I wanted to port from Agda 2.4.0.2 to Agda 2.4.2. For now I fear I'll have to suspend the effort, because of this Agda crash.

With [this commit](https://github.com/inc-lc/ilc-agda/commit/52d780fa6fc41420c5854ec8cf38978b0671285c), with Agda 2.4.2.4, I get

```
  Checking Parametric.Change.Validity (/Users/pgiarrusso/AeroFS/Repos/ilc-agda-bluevelvet/Parametric/Change/Validity.agda).
conApp: constructor Base.Change.Algebra.ChangeAlgebraFamily.family with fields [Base.Change.Algebra.ChangeAlgebraFamily.change-algebra] projected by Base.Change.Algebra.ChangeAlgebra.Change
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Substitute.hs:108
```

[Relevant location](https://github.com/agda/agda/blob/2.4.2.4/src/full/Agda/TypeChecking/Substitute.hs#L108).

With 2.4.2, I think I get the same error:

```
  Checking Parametric.Change.Validity (/Users/pgiarrusso/AeroFS/Repos/ilc-agda-bluevelvet/Parametric/Change/Validity.agda).
conApp: constructor Base.Change.Algebra.ChangeAlgebraFamily.family with fields [Base.Change.Algebra.ChangeAlgebraFamily.change-algebra] projected by Base.Change.Algebra.ChangeAlgebra.Change
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Substitute.hs:92
```

[Relevant location](https://github.com/agda/agda/blob/2.4.2/src/full/Agda/TypeChecking/Substitute.hs#L92).

Both traces are reproducible in a checkout with

```
agda-2.4.2.4 +RTS -s -RTS -i . -i $AGDA_LIBRARY_PATH Parametric/Change/Validity.agda
```

with the Agda standard library for 2.4.2.4, commit agda/agda-stdlib@f071e972bbf01f778545df88fcf3fa0465ebc1e2.

Should this be relevant, this codebase uses instance parameters, heavily parameterized modules, and lots of reexports.

**Comment by andreasabel** [comment] 2015-11-05 09:27
Could be #1407, which is fixed on the github version (both master and maint-2.4.2 branch).  Can you try the github version?

**Comment by asr** [comment] 2015-11-05 12:27
I could reproduce the issue using the maint-2.4.2 branch. The issue is fixed in the master branch:

``` bash
$ agda -i ... Parametric/Change/Validity.agda
...
Unsolved metas at the following locations:
  /tmp/ilc-agda/Base/Denotation/Environment.agda:67,20-59
  /tmp/ilc-agda/Base/Denotation/Environment.agda:67,40-41
  /tmp/ilc-agda/Base/Denotation/Environment.agda:67,20-37
  /tmp/ilc-agda/Base/Denotation/Environment.agda:67,20-39
  /tmp/ilc-agda/Base/Denotation/Environment.agda:67,42-48
  /tmp/ilc-agda/Base/Denotation/Environment.agda:67,42-59
  /tmp/ilc-agda/Base/Denotation/Environment.agda:68,21-25
  /tmp/ilc-agda/Base/Denotation/Environment.agda:69,51-56
  /tmp/ilc-agda/Base/Denotation/Environment.agda:69,57-60
  /tmp/ilc-agda/Base/Denotation/Environment.agda:69,51-60
  /tmp/ilc-agda/Base/Denotation/Environment.agda:69,51-86
  /tmp/ilc-agda/Base/Denotation/Environment.agda:70,51-69
  /tmp/ilc-agda/Base/Denotation/Environment.agda:71,39-57
  /tmp/ilc-agda/Base/Denotation/Environment.agda:74,19-29
  /tmp/ilc-agda/Base/Denotation/Environment.agda:74,21-27
  /tmp/ilc-agda/Base/Denotation/Environment.agda:74,19-31
  /tmp/ilc-agda/Base/Denotation/Environment.agda:75,19-23
  /tmp/ilc-agda/Base/Denotation/Environment.agda:76,29-57
  /tmp/ilc-agda/Base/Denotation/Environment.agda:81,20-60
  /tmp/ilc-agda/Base/Denotation/Environment.agda:81,42-43
  /tmp/ilc-agda/Base/Denotation/Environment.agda:81,20-39
  /tmp/ilc-agda/Base/Denotation/Environment.agda:81,20-41
  /tmp/ilc-agda/Base/Denotation/Environment.agda:81,44-49
  /tmp/ilc-agda/Base/Denotation/Environment.agda:81,44-60
  /tmp/ilc-agda/Base/Denotation/Environment.agda:83,47-51
  /tmp/ilc-agda/Base/Denotation/Environment.agda:84,51-74
  /tmp/ilc-agda/Base/Denotation/Environment.agda:85,47-73
  /tmp/ilc-agda/Base/Denotation/Environment.agda:86,51-81
when scope checking the declaration
  import Base.Denotation.Environment as .#Base.Denotation.Environment-249894085
```

**Comment by Blaisorblade** [comment] 2015-11-05 14:57
Thanks for both replies, and for trying this out (!).

> The issue is fixed in the master branch:

Really? That's the message you get on master, right? But that seems very much Agda stopping earlier — if I add by hand an unsolved meta to that module (still in 2.4.2.4), I also don't get Agda to crash.

I might have time to try again later, after Agda builds.

If anybody tries again, later commits on https://github.com/inc-lc/ilc-agda/compare/topic/2.4.2 are relevant.

**Comment by asr** [comment] 2015-11-05 15:25
> That's the message you get on master, right? 

Right.

**Comment by Blaisorblade** [comment] 2015-11-05 17:25
I can confirm that Agda on master is just stopping earlier; the new instance search is pretty much never working in `Base.Denotation.Environment.agda`; after fixing those, I get other problems with instances, so I don't know yet if the bug is fixed in `master`. Thank @asr, we still know it's not fixed in `maint-2.4.2`.

Worse, after introducing `meaningOf≼`, not even `meaningOfVar` is found. Somehow, I fail to get a list of candidates, while I could earlier with <kbd>C-c C-=</kbd>

The change is also not mentioned in docs — Agda fails to pick `meaningOfVar` even though that's an explicit instance, not a constructor. Trying out all instances in scope would work (sounds like the old exponential algorithm?).

I expect that's due to the interaction with unification — until I supply the desired instance argument, all other implicit params aren't deduced. That makes some sense, because our "typeclass" is pretty crazy anyway.

https://github.com/inc-lc/ilc-agda/commit/ed2b8f7c86f336c9f4b7dd96a5e07d486970ac10

**Comment by asr** [comment] 2015-11-05 18:23
> > The issue is fixed in the master branch
> 
> Really?

You are right. I neither know if the issue is fixed in master.

**Comment by andreasabel** [comment] 2015-11-10 10:34
Test case needs shrinking.

**Comment by andreasabel** [comment] 2015-12-02 18:58
Can you try this again with current master (Agda-2.4.3)?

**Comment by Blaisorblade** [comment] 2015-12-04 03:03
On my TODO list — the changes in instance resolution are still there, so I need to find time to change definitions or reduce the bug.

In particular, it appears that to resolve an instance argument of type T, there can't be unresolved metavariables in T — it looks as if before resolving the instance could fix the values to such metavariables. Is that plausible? I wrote something like that before (quote below), but this is now happening on a much more sensible instance.

> The change is also not mentioned in docs — Agda fails to pick meaningOfVar even though that's an explicit instance, not a constructor. Trying out all instances in scope would work (sounds like the old exponential algorithm?).
> 
> I expect that's due to the interaction with unification — until I supply the desired instance argument, all other implicit params aren't deduced. That makes some sense, because our "typeclass" is pretty crazy anyway.

**Comment by Blaisorblade** [comment] 2015-12-04 04:00
Here's my progress with the new master (24e4deef6b5fe3cff91d2faf69d5faad508ada45). Right now I'm unable to sort this into more bugs, apologies.

I got farther, but there's a new bug:

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/InstanceArguments.hs:229
```

If I comment out the offending definition, I see tons of unresolved metas.
But more importantly, again on instance resolution, please take a look to inc-lc/ilc-agda@77b5caa6a6605ebaf46108a64d89b1b9b358ea0c.

**Comment by andreasabel** [comment] 2016-01-20 08:53
I confirm that on this commit of your development

```
abel@agda2:~/agda/test/bugs/ilc-agda$ git branch
* (detached from 52d780f)
```

in `module Parametric.Change.Validity` Agda (current maint, 2016-01-20) crashes with:

```
conApp: constructor Base.Change.Algebra.ChangeAlgebraFamily.family with fields [Base.Change.Algebra.ChangeAlgebraFamily.change-algebra] projected by Base.Change.Algebra.ChangeAlgebra.Change
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Substitute.hs:116
```

**Comment by asr** [comment] 2016-02-04 13:18
Using the master branch and https://github.com/inc-lc/ilc-agda/compare/topic/2.4.2, I could type-check the Parametric.Change.Validity module:

``` bash
$ agda -i ... Parametric/Change/Validity.agda
...
Finished Parametric.Change.Validity.
```

**Closed as completed by asr** 2016-02-04 13:18 UTC
Labels: type: bug, instance, regression on master

**Comment by asr** [comment] 2016-02-04 14:31
@Blaisorblade I would appreciate if you write-down a [MWE](https://en.wikipedia.org/wiki/Minimal_Working_Example). I would like to add a test case for this issue.

**Comment by Blaisorblade** [comment] 2016-05-18 18:51
@asr I'm sorry I never answered; I finally got back to this, and `Parametric.Change.Validity` typechecks on 2.5.1, but I got stuck on an error on the next file, https://github.com/agda/agda/blob/2.5.1/src/full/Agda/TypeChecking/Substitute.hs#L93 — essentially, on any use of the code in https://github.com/inc-lc/ilc-agda/commit/bc0f697e345522fad65844eed07cba984158e3b7. I should check what exactly failed on which version, but it's not obvious how fixed this ever was.

But I'll first take a look at #1985, which <s>seems</s>EDIT: is _much_ easier to minimize than this.
