### ISSUE TITLE
Can/should we increase sharing by always using serialised interfaces?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda#4316] opened 2019-12-20 22:04 UTC
I have this feeling that doing a topological sort (by hand) of one's project files, then calling `agda` on each, as a separate process, may at times be faster and use less memory than creating an `Everything.agda` file that `import`s everything.

I've just now had the clearest symptom of that: ran out of heap on trying to typecheck my `Everything.agda` in agda-categories. What did I do? Restarted it. That worked.

Perhaps the problem is related to sharing, or more precisely, non-sharing?

I'm willing to conduct all sorts of experiments wrt gathering profiling information on agda-categories -- but I need a little guidance for what to try.

**Comment by asr** [comment] 2019-12-20 23:28
I have had the same experience several times. The last one was testing the `agda-categories` repository. Thanks for reporting it.

**Comment by nad** [comment] 2019-12-30 21:50
I suspect that we could fix this problem by making Agda read in the newly created interface file (or rather, decode the created bytestring) after a file has been type-checked. I think we used to do something like this (f3131bc255ada9f4571e083c26b9d778071334bd). @UlfNorell, do you know why we no longer do this?

@JacquesCarette, perhaps you could experiment with some variants of this optimisation.

**Comment by xekoukou** [comment] 2019-12-30 22:22
@JacquesCarette I have already [done](https://github.com/xekoukou/agda-mt) what you propose. It had a similar performance with the use of a single core. The cost of serialization - deserialization of the .agdai might be the problem.

Of course, you could use the same graph and only execute agda in a single thread, so as to limit memory usage.

**Comment by nad** [comment] 2019-12-30 23:29
@xekoukou, the thing you experimented with is in the worst case (at least) quadratic in the number of files, due to repeated processing of the same interface files.

**Comment by JacquesCarette** [comment] 2019-12-31 13:50
@nad : One item that I am not sure about - you point to `Agda.Interaction.Imports` but the report above is about command-line access, and emacs is not involved at all.  Does it still go through this code? Or was your suggestion for me to add a similar caching strategy to the command-line version?

**Comment by nad** [comment] 2019-12-31 16:31
> Does it still go through this code?

Yes.

**Comment by nad** [comment] 2020-01-20 19:30
For some libraries that are not so tightly connected there might be a point in dropping some modules from the cache when they are not needed any more, and perhaps also scheduling the type-checking of modules with an eye to reducing memory consumption. However, I think we should start with what I suggested [above](https://github.com/agda/agda/issues/4316#issuecomment-569806456).

**Comment by nad** [comment] 2020-02-20 11:57
I have implemented my suggestion. See https://github.com/agda/agda/issues/4457#issuecomment-588971007 for some benchmarks for the standard library.

@JacquesCarette, can you benchmark with your code? Try with and without `--compact-regions`.

**Comment by JacquesCarette** [comment] 2020-02-20 13:52
Thanks.  I'm travelling right now, but I will test it as soon as I can.  I'll cross-list this on agda-categories, maybe someone else will beat me to it.

**Comment by nad** [comment] 2020-02-21 13:23
I tried with eleven of my own projects. The execution times were mostly similar, but in one case substantially lower with `--compact-regions`, and memory consumption was consistently substantially lower with `--compact-regions`.

**Comment by nad** [comment] 2020-02-22 11:20
I failed to get agda-categories to type-check, despite trying with several different versions of the standard library.

**Comment by nad** [comment] 2020-02-22 13:59
I have removed the `--compact-regions` option, compact regions are always active for GHC 8.4 and later. If you want to test with and without compact regions, check out a suitable commit first.

> I have this feeling that doing a topological sort (by hand) of one's project files, then calling `agda` on each, as a separate process, may at times be faster and use less memory than creating an `Everything.agda` file that `import`s everything.

That approach should at least not use more memory. However, as long as there is plenty of memory available I would expect that it is no longer faster. Can you verify this? Can we close this ticket now?

**Comment by JacquesCarette** [comment] 2020-02-22 14:37
About the failure to type-check: it should work with agda 2.6.0.1 with stdlib-1.2. If it doesn't, that's a bug which should fix. [There were issues with 2.6.1 previously, but these were fixed, I think.] If you can document any specific configuration that you tried and didn't work, we'll investigate.

I'll check on the other stuff as soon as I can - and then hopefully this ticket can be closed.

**Comment by nad** [comment] 2020-02-22 17:07
With version 1.2 of the standard library and Agda 2.6.1-556be02 I get the following error:
```
[…]/Categories/Category/Instance/Properties/Posets.agda:252,54-55
Poset a a a !=< _C_1608 ⇒ _A_1603
when checking that the expression f has type _C_1608 ⇒ _A_1603
```
My guess is that this problem was caused by a fix of an ordering bug in the generalisation machinery (#3779). When I use generalisable variables I bind implicit arguments by name, to avoid surprises if the order of the arguments is changed (primarily due to changes in the program, not changes in Agda).

**Comment by JacquesCarette** [comment] 2020-02-22 17:32
Thanks, I'll post this on the agda-categories issues.  Yes, we've had to fix a few occurrences of this with previous instances of 2.6.1, all to do with ordering of implicit generalizable variables.

**Comment by nad** [comment] 2020-02-22 17:41
When I fixed this bug I could type-check all of agda-categories (with no part of agda-categories or the standard library already type-checked, and Agda compiled using GHC 8.8.2):
```
Total                        693,321ms            
Miscellaneous                  2,404ms            
Typing                        54,409ms (402,748ms)
Typing.CheckRHS              264,721ms            
Typing.TypeSig                32,408ms            
Typing.OccursCheck            23,308ms            
Typing.Generalize             21,793ms            
Typing.CheckLHS                4,249ms   (5,766ms)
Typing.CheckLHS.UnifyIndices   1,516ms            
Typing.With                      339ms            
Serialization                 93,127ms (130,363ms)
Serialization.BuildInterface  22,293ms            
Serialization.BinaryEncode    11,697ms            
Serialization.Compress         1,905ms            
Serialization.Sort             1,338ms            
Positivity                    60,373ms            
DeadCode                      45,640ms            
Deserialization               18,258ms  (20,573ms)
Deserialization.Compaction     2,315ms            
Termination                      206ms   (8,361ms)
Termination.RecCheck           8,069ms            
Termination.Compare               72ms            
Termination.Graph                 12ms            
Parsing                        1,090ms   (7,748ms)
Parsing.OperatorsExpr          5,692ms            
Parsing.OperatorsPattern         965ms            
Scoping                        4,474ms   (6,240ms)
Scoping.InverseScopeLookup     1,765ms            
Coverage                       4,254ms            
Highlighting                   2,139ms            
ProjectionLikeness             1,209ms            
Import                           961ms            
Injectivity                      299ms            

   2,478,545,368 bytes allocated in the heap
  80,382,700,584 bytes copied during GC
     851,024,748 bytes maximum residency (295 sample(s))
         890,004 bytes maximum slop
             811 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0     382046 colls,     0 par   160.874s  162.154s     0.0004s    0.0131s
  Gen  1       295 colls,     0 par   50.214s  53.681s     0.1820s    1.8526s

  TASKS: 4 (1 bound, 3 peak workers (3 total), using -N1)

  SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

  INIT    time    0.000s  (  0.001s elapsed)
  MUT     time  474.220s  (479.539s elapsed)
  GC      time  211.088s  (215.835s elapsed)
  EXIT    time    0.001s  (  0.005s elapsed)
  Total   time  685.309s  (695.381s elapsed)

  Alloc rate    5,226,572 bytes per MUT second

  Productivity  69.2% of total user, 69.0% of total elapsed
```
Without compaction Agda ran out of memory (I did not use any RTS flags except for `-s` and the default ones, i.e. `-M3.5G -I0`, and used a variant of Agda compiled using GHC 8.6.5).

**Comment by JacquesCarette** [comment] 2020-02-22 18:11
That is excellent news!  That is a **very** substantial reduction in memory use, thank you.

I now can't help but wonder if, because very clearly there was a lot of sharing to be had, if maybe the type-checker is doing a lot of extra work because it doesn't have access to that same sharing?

**Comment by nad** [comment] 2020-02-22 19:27
> That is excellent news! That is a **very** substantial reduction in memory use, thank you.

Note that I use a 32-bit system.

> I now can't help but wonder if, because very clearly there was a lot of sharing to be had, if maybe the type-checker is doing a lot of extra work because it doesn't have access to that same sharing?

#4464.

**Closed as completed** 2020-02-26 17:39 UTC
Labels: type: enhancement, performance, documented-in-changelog
