### ISSUE TITLE
Internal error when pattern matching on refl without K over a goal where the type is a hole

### ISSUE THREAD

**Issue by szumixie** [agda/agda#6061] opened 2022-08-30 16:14 UTC
In the master branch version of Agda
```agda
{-# OPTIONS --without-K #-}

open import Agda.Builtin.Equality

data A : Set where a : A

f : (x : A) → a ≡ x → {!!}
f .a refl = {!!}
```
throws
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/EtaContract.hs:46:17 in Agda-2.6.3-5FGLjZMJMIQ5Cbo8ycPFeg:Agda.TypeChecking.EtaContract
```

**Comment by andreasabel** [comment] 2022-08-30 17:14
This has regressed from 2.6.2.2 (succeeds) over `master` of around 2022-08-15
```
Users/abel/play/agda/bugs/Issue6061.agda:8,1-17
Panic: Pattern match failure in 'do' block at
src/full/Agda/TypeChecking/Primitive/Cubical.hs:2310:7-21
```
https://github.com/agda/agda/blob/b52180812845647b57ca3cfbd5d03f68d6f8e802/src/full/Agda/TypeChecking/Primitive/Cubical.hs#L2310
to current `master`:
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/EtaContract.hs:46:17
```
https://github.com/agda/agda/blob/efa6fe4cc65132bcc375f608542154674a37f1ba/src/full/Agda/TypeChecking/EtaContract.hs#L46

It looks like the latest regression has been introduced by https://github.com/agda/agda/commit/0a75063e5f267486df45110adcd7767eec4bf557.  Ping @jespercockx

**Comment by plt-amy** [comment] 2022-08-31 14:14
Dupe of  #6001, part of #6049

**Closed as not planned** 2022-08-31 14:14 UTC
Labels: without-K, regression on master, cubical, internal-error
