### ISSUE TITLE
Missing highlighting

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#869] opened 2015-08-08 18:05 UTC
```
module Bug where

postulate
  A B : Set

-- If the file is first touched, and then loaded, then "Set" is not
-- highlighted (if interactive highlighting is used).

```

Original issue reported on code.google.com by `nils.anders.danielsson` on 12 Jun 2013 at 7:30

**Comment by nad** [comment] 2016-09-09 12:16
Duplicate of #1314.

**Closed as completed by nad** 2016-09-09 12:16 UTC
Labels: type: bug, ux: highlighting

**Comment by andreasabel** [comment] 2016-09-09 14:55
I cannot reproduce this issue.

**Comment by nad** [comment] 2016-09-09 15:19
```
$ cat Bug.agda 
postulate
  A B : Set
$ echo 'IOTCM "Bug.agda" Interactive Direct (Cmd_load "Bug.agda" [])' | agda --interaction --ignore-interfaces
Agda2> (agda2-status-action "")
(agda2-info-action "*Type-checking*" "" nil)
(agda2-highlight-clear)
(agda2-info-action "*Type-checking*" "Checking Bug (/tmp/Bug.agda).\n" t)
(agda2-highlight-add-annotations '(1 10 (keyword) nil) '(17 18 (symbol) nil) '(19 22 (primitivetype) nil))
(agda2-highlight-add-annotations '(1 10 (keyword) nil) '(13 14 (postulate) nil ("/tmp/Bug.agda" . 13)) '(15 16 (postulate) nil ("/tmp/Bug.agda" . 15)) '(17 18 (symbol) nil) '(19 22 (primitivetype) nil))
(agda2-highlight-add-annotations '(19 22 (typechecks) nil))
(agda2-highlight-add-annotations '(19 22 () nil))
(agda2-highlight-add-annotations '(19 22 (typechecks) nil))
(agda2-highlight-add-annotations '(19 22 () nil))
(agda2-highlight-add-annotations '(13 14 (postulate) nil ("/tmp/Bug.agda" . 13)) '(17 18 (symbol) nil) '(19 22 (primitivetype) nil))
(agda2-highlight-add-annotations '(19 22 (typechecks) nil))
(agda2-highlight-add-annotations '(19 22 () nil))
(agda2-highlight-add-annotations '(19 22 (typechecks) nil))
(agda2-highlight-add-annotations '(19 22 () nil))
(agda2-highlight-add-annotations '(15 16 (postulate) nil ("/tmp/Bug.agda" . 15)))
(agda2-highlight-add-annotations '(1 10 (keyword) nil))
(agda2-info-action "*Type-checking*" "Finished Bug.\n" t)
(agda2-status-action "Checked")
(agda2-info-action "*All Goals*" "" nil)
((last . 1) . (agda2-goals-action '()))
Agda2> 
```

Note that the last annotation applied to `Set` (positions 19-22) is `()`, not `(primitivetype)`.

If `B` is removed, then the situation is different:

```
$ cat Bug.agda
postulate
  A : Set
$ echo 'IOTCM "Bug.agda" Interactive Direct (Cmd_load "Bug.agda" [])' | agda --interaction --ignore-interfaces
Agda2> (agda2-status-action "")
(agda2-info-action "*Type-checking*" "" nil)
(agda2-highlight-clear)
(agda2-info-action "*Type-checking*" "Checking Bug (/tmp/Bug.agda).\n" t)
(agda2-highlight-add-annotations '(1 10 (keyword) nil) '(15 16 (symbol) nil) '(17 20 (primitivetype) nil))
(agda2-highlight-add-annotations '(1 10 (keyword) nil) '(13 14 (postulate) nil ("/tmp/Bug.agda" . 13)) '(15 16 (symbol) nil) '(17 20 (primitivetype) nil))
(agda2-highlight-add-annotations '(17 20 (typechecks) nil))
(agda2-highlight-add-annotations '(17 20 () nil))
(agda2-highlight-add-annotations '(17 20 (typechecks) nil))
(agda2-highlight-add-annotations '(17 20 () nil))
(agda2-highlight-add-annotations '(13 14 (postulate) nil ("/tmp/Bug.agda" . 13)) '(15 16 (symbol) nil) '(17 20 (primitivetype) nil))
(agda2-highlight-add-annotations '(1 10 (keyword) nil))
(agda2-info-action "*Type-checking*" "Finished Bug.\n" t)
(agda2-status-action "Checked")
(agda2-info-action "*All Goals*" "" nil)
((last . 1) . (agda2-goals-action '()))
Agda2> 
```

Did you forget to activate interactive highlighting?
