### ISSUE TITLE
`Set != Set lzero` in with-abstraction with copatterns

### ISSUE THREAD

**Issue by Saizan** [agda/agda#4570] opened 2020-04-06 12:54 UTC
With a recent agda/master I get the error

```
Set != Set lzero
when checking that the type
(m n : ωGr .Obj) (w : Bool) (f : Hom ωGr m n | w) →
?2 (m = m) (n = n)
of the generated with function is well-formed
```

with the following code

```agda
open import Agda.Builtin.Bool
open import Agda.Builtin.Nat
open import Agda.Primitive

record Graph ℓv ℓe : Set (lsuc (ℓv ⊔ ℓe)) where
  field
    Obj : Set ℓv
    Hom : Obj → Obj → Set ℓe

open Graph public

postulate
  t : Nat → Nat → Bool

ωGr : Graph lzero lzero
Obj ωGr = Nat
Hom ωGr m n with t m n
... | true = ? -- if n ≡ (suc m)
... | false = ? -- otherwise

foo : ∀ m n → Hom ωGr m n → { }0
foo m n f with t m n
... | z = { }1
```

@jespercockx can you check if this is related to your recent perf changes?

**Comment by gallais** [comment] 2020-04-06 13:03
Yep: https://github.com/agda/agda/pull/4566#issuecomment-609471854

I have the same error.

**Comment by jespercockx** [comment] 2020-04-06 14:54
Ok, thanks for the example. I saw the build error on Travis but could not reproduce on my own PC. I'll take a look...

**Comment by jespercockx** [comment] 2020-04-06 15:01
Agda's last words from the debug output:
```agda
equalLevel
  Max 0 []
  ==
  Max 0 [Plus 0 (NeutralLevel ReallyNotBlocked (Def Agda.Primitive.lzero []))]
```
It is very suspicious that `Def Agda.Primitive.lzero []` is marked as a `NeutralLevel`, it should really have been recognized as a primitive level.

**Comment by jespercockx** [comment] 2020-04-06 15:48
I managed to find the cause: when reducing a term with only a few `AllowedReduction`s enabled, Agda would still mark `Level` expressions it reduces as `NeutralLevel` even if they might still be reduced when all reductions are enabled. So the problem was already there before, but it seems my new uses of `AllowedReductions` exposed it.

I'm working on a fix now by only marking levels as `NeutralLevel` if all reductions are actually enabled, otherwise Agda should keep it as an `UnreducedLevel`.

I am also wondering why levels get a special treatment where Agda caches whether they have already been reduced, but other terms in general do not. Is there any evidence that this actually speeds things up in the case of levels? And if it *does* speed things up, could we perhaps apply this technique of labeling things as meta/blocked/neutral/unreduced more generally to all terms? @UlfNorell @nad

**Comment by UlfNorell** [comment] 2020-04-06 16:07
I don't think there's any evidence readily available. Levels were added after the other things, and as I remember, I wanted to experiment with extending the `Blocked`/`NotBlocked` logic used for normal terms.

**Closed as completed** 2020-04-06 17:04 UTC
Labels: type: bug, levels, regression on master
