### ISSUE TITLE
Feature Request: Emacs Mode generates definition from type

### ISSUE THREAD

**Issue by mdnahas** [agda/agda#5630] opened 2021-11-03 19:37 UTC
I just spent a few days learning Agda.  I translated proofs from my [tutorial on Coq](https://mdnahas.github.io/doc/nahas_tutorial).  

I would write a type like:
`forallExistsSet : (A : Set) → (P : A → Set) → (∀ x → ¬ P x) → ¬ (∃ (\ x → P x))`
And then spend a lot of time typing in the definition: 
`forallExistsSet A P forallxnotPx x,Px = ?`

I think it would be a useful feature for Agda Emacs Mode to generate the second line from the first. 

I did find a handy shortcut that if I typed:
`forallExistsSet = ?`
and then, in the hole, typed "C-c C-c Enter", it would generate most of the variables for me.   You can probably implement this feature request using that code.

This feature has zilch to do with writing a proof.  It is just to relieve tedium from some of your users.

**Comment by gallais** [comment] 2021-11-03 20:05
This seems like a duplicate of #1711

**Closed as completed by gallais** 2021-11-03 20:05 UTC
Labels: status: duplicate, ux: emacs
