### ISSUE TITLE
More details in “I'm not sure if there should be a case for the constructor” desired

### ISSUE THREAD

**Issue by WolframKahl** [agda/agda#1889] opened 2016-03-03 18:15 UTC
I am used to seeing the error message “I'm not sure if there should be a case for the constructor” as response to C-c C-c, but now I get it also for C- C-l, in the definition of a function taking two arguments of the same type, and with no information that would help me to find out which argument it refers to ─ I already have the constructor in question in both argument positions...

**Comment by andreasabel** [comment] 2016-03-08 09:36
Could you give a test case?  Also, is this a regression w.r.t. 2.4.2?

**Comment by WolframKahl** [comment] 2016-03-08 15:40
On Tue, Mar 08, 2016 at 01:36:01AM -0800, Andreas Abel wrote:

> Could you give a test case?

Not easily, since the case where I saw it depends on a ton of other stuff.

> Also, is this a regression w.r.t. 2.4.2?

I'd be surprised --- this error message has always been too poor in the information it provided.

But I would only be able to test that if I could construct a test case outside of my developments, since I adapted to the fix of #1759, which makes my developments, already at very low levels, incompatible with 2.4.2.

However, I hope that my description clearly indicates at least one shortcoming that should be not too hard to fix: The argument position where Agda is  “not sure if there should be a case for the constructor” should be indicated, since that constructor might be legal in several argument positions. (Also, I think it would be better to say “not sure whether there should be a case for the constructor”.)

(In the case where I was puzzled, I already had cases matching that constructor in both questionable argument positions, so even more information might be appropriate. I have since switched one of the types involved in constructor arguments from `Fin n -> A` to `Vec A n`, which avoids the problem.)

Wolfram

**Comment by gallais** [comment] 2016-04-06 10:01
Potentially related: [PatternFail.agda.txt](https://github.com/agda/agda/files/206160/PatternFail.agda.txt)

**Comment by UlfNorell** [comment] 2016-04-06 11:28
Here's `PatternFail.agda`:

``` agda
module PatternFail where

open import Data.Unit
open import Data.Nat
open import Data.Fin
open import Data.Vec
open import Data.Product
open import Relation.Binary.PropositionalEquality

data Type : Set where
  a b c : Type

data HasType : {n : ℕ} (γ : Vec Type n) (k : Fin n) (σ : Type) → Set where
  z : ∀ {n} {γ : Vec Type n} {σ}   → HasType (σ ∷ γ) zero σ
  s : ∀ {n} {γ : Vec Type n} {k σ τ} → HasType γ k τ → HasType (σ ∷ γ) (suc k) τ

Functional :
  {RI : Set}      -- Relevant Input
  {II : RI → Set} -- Irelevant Input
  {O  : RI → Set} -- Output
  (R  : (ri : RI) → II ri → O ri → Set) → Set
Functional {RI} {II} {O} R =
  (ri : RI) {ii₁ ii₂ : II ri} {o₁ o₂ : O ri} →
  R ri ii₁ o₁ → R ri ii₂ o₂ → o₁ ≡ o₂

RHasType : (ri : Σ[ n ∈ ℕ ] Vec Type n × Fin n) (ii : ⊤) (o : Type) → Set
RHasType (_ , γ , k) _ σ = HasType γ k σ

functionalHasType : Functional RHasType
functionalHasType ri k l = {!!}

{- `C-c C-c k RET` yields:
=================================================================
I'm not sure if there should be a case for the constructor z,
because I get stuck when trying to solve the following unification
problems (inferred index ≟ expected index):
  {_} ≟ {_}
  σ ∷ γ ≟ proj₁ (proj₂ ri₁)
  zero ≟ proj₂ (proj₂ ri₁)
  σ ≟ o₁
when checking that the expression ? has type .o₁ ≡ .o₂
=================================================================

But manually expanding the cases works fine:
-}

functionalHasType′ : Functional RHasType
functionalHasType′ _ z     z     = refl
functionalHasType′ _ (s k) (s l) = functionalHasType′ _ k l

{- If we turn `functionalHasType`'s `ri` into `_` then `C-c C-c k RET`
succeeds but the resulting expression does not typecheck: -}

functionalHasType′′ : Functional RHasType
functionalHasType′′ _ k l = {!!}

{- Indeed, we get:

functionalHasType′′ : Functional RHasType
functionalHasType′′ r z l = ?
functionalHasType′′ r (s k₁) l = ?

which yields:
=================================================================
suc n != proj₁ r of type ℕ
when checking that the pattern z has type
HasType (proj₁ (proj₂ r)) (proj₂ (proj₂ r)) o₁
=================================================================
-}
```

**Comment by andreasabel** [comment] 2016-04-12 13:36
@jespercockx The problem seems to be that `ri` (`r` resp.) is not eta-expanded in the unifier.  Can the new unifier be improved (easily) to handle this?  (I somehow remember doing these eta-expansions was part of the new features of the unifier).

**Comment by jespercockx** [comment] 2016-04-12 15:14
Strange, I don't have any problem case splitting on k on my computer with the latest master (7ba987b9870173a6a362b59fa6488222239a4eb7). Eta-expansion of the first visible argument happens automatically in both cases:

```
functionalHasType : Functional RHasType
functionalHasType (_ , _ , .zero) z l = {!l!}
functionalHasType (_ , _ , _) (s k₁) l = {!!}

functionalHasType′′ : Functional RHasType
functionalHasType′′ (_ , _ , .zero) z l = {!!}
functionalHasType′′ (_ , _ , _) (s k₁) l = {!!}
```

**Comment by UlfNorell** [comment] 2018-05-28 19:15
Ignoring the attempts to hijack the issue, here's a case where you don't get enough information:
```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

data Tree : Nat → Set where
  tip : ∀ {n} → Tree n
  bin : ∀ {m n} → Tree m → Tree n → Tree (m + n)

t : ∀ {n} → Tree (n + n) → Nat
t tip = ?
-- t (bin l r) = ?

-- Error location: entire lhs `t tip`
-- I'm not sure if there should be a case for the constructor bin,
-- because I get stuck when trying to solve the following unification
-- problems (inferred index ≟ expected index):
--   m + n₁ ≟ n + n
-- when checking the definition of t
```
I you write the `bin` case you get a helpful error location indicating the `bin l r` argument.

**Comment by andreasabel** [comment] 2023-09-26 13:09
I don't see actionable items here.  
@UlfNorell gave a MWE, but didn't indicate a solution.  I don't see here a better error location than the existing lhss for an absent lhss that can't be well-typed because of stuck unification problems.

Hence, closing.
Welcome to reopen with a more concrete plan for a solution.

**Closed as not planned** 2023-09-26 13:09 UTC
Labels: type: enhancement, ux: error reporting, unification
