### ISSUE TITLE
Internal error when parsing as-pattern

### ISSUE THREAD

**Issue by subttle** [agda/agda#2538] opened 2017-04-10 00:03 UTC
Good day,

I'm using Agda 2.5.2 and I momentarily forgot to add parenthesis to some code involving an as-pattern, and I received an internal error.

> An internal error has occurred. Please report this as a bug.
> Location of the error: src/full/Agda/TypeChecking/Rules/LHS.hs:496

https://github.com/agda/agda/blob/v2.5.2/src/full/Agda/TypeChecking/Rules/LHS.hs#L496

Here is a small snippet which reproduces the error
```
open import Data.List
open import Data.Product
f : ∀ {a} {A : Set a} → (List A × List A) → List A
f (_ , list@h ∷ t) = {!   !}
f _ = {!   !}
```
When parentheses are added, everything is fine. Also it is worth noting that the error only seems to occur when the pattern matching is nested. That is to say, the following code

```
g : ∀ {a} {A : Set a} → List A → List A
g list@h ∷ t = {!   !}
g _ = {!   !}
```
throws the expected (non internal) parsing error

> Could not parse the left-hand side g list@h ∷ t

Also, in case it is relevant, I am using agda-stdlib 0.13.

Thank you for your time.

**Comment by andreasabel** [comment] 2017-04-10 06:48
Thanks for reporting.
I cannot reproduce this internal error with the current development versions of Agda.
I think this was bug #2413 which I fixed recently.
Closing, please reopen if you can produce the bug with either 2.5.3 or 2.6.0 (current development versions).

**Closed as completed by andreasabel** 2017-04-10 06:48 UTC
Labels: status: duplicate, as-patterns
