### ISSUE TITLE
Reflection primitive `inContext` does not respect module parameters

### ISSUE THREAD

**Issue by nad** [agda/agda#4598] opened 2020-04-16 19:12 UTC
The following code raises an error:
```agda
{-# OPTIONS --show-implicit -vbug:2 #-}

open import Agda.Builtin.List
open import Agda.Builtin.Reflection
open import Agda.Builtin.Unit

variable
  A B : Set

foldl : (B → A → B) → B → List A → B
foldl _⊕_ ε []       = ε
foldl _⊕_ ε (x ∷ xs) = foldl _⊕_ (ε ⊕ x) xs

reverse : List A → List A
reverse = foldl (λ xs x → x ∷ xs) []

macro

  print-context : Term → TC ⊤
  print-context _ =
    bindTC getContext λ c → inContext [] (print (reverse c))
    where
    print : List (Arg Type) → TC ⊤
    print []                 = returnTC _
    print (a@(arg _ t) ∷ ts) =
      bindTC (reduce t) λ t →
      bindTC (quoteTC t) λ t′ →
      bindTC (debugPrint "bug" 2 (termErr t ∷ [])) λ _ →
      bindTC (debugPrint "bug" 2 (termErr t′ ∷ [])) λ _ →
      extendContext a (print ts)

record R₁ : Set₁ where
  field
    C : Set

record R₂ : Set₁ where
  field
    r₁ : R₁

module M (r₂ : R₂) where

  open R₁ (R₂.r₁ r₂)

  _ : C → Set
  _ = λ _ → print-context
```
Error message:
```
de Bruijn index 2 is not in scope in the context (_ : R₂)
when checking that the expression unquote print-context has type
Set
```
Should the code raise an error? Does `print-context` traverse the context in a correct way?

If the first line containing `debugPrint` is commented out, then we get the following debug output:
```
def (quote R₂) ([] {_} {_})
def (quote R₁.C)
(_∷_ {_} {_}
 (arg {_} {_} (arg-info visible relevant)
  (def (quote R₂.r₁)
   (_∷_ {_} {_}
    (arg {_} {_} (arg-info visible relevant) (var 2 ([] {_} {_})))
    ([] {_} {_}))))
 ([] {_} {_}))
```

**Comment by jespercockx** [comment] 2020-04-17 07:52
To me your tactic looks fine, so I think this is a bug in Agda. It looks like the problem is caused by the call to `reduce`:
```agda
  print-context : Term → TC ⊤
  print-context _ =
    bindTC getContext λ c →
    inContext [] (print (reverse c))
    where
    print : List (Arg Type) → TC ⊤
    print []                 = returnTC _
    print (a@(arg _ t) ∷ ts) =
      bindTC (quoteTC t) λ t′ →
      bindTC (debugPrint "bug" 2 (strErr "before reduce" ∷ termErr t′ ∷ [])) λ _ →
      bindTC (debugPrint "bug" 2 (termErr t ∷ [])) λ _ →
      bindTC (reduce t) λ t →
      bindTC (quoteTC t) λ t″ →
      bindTC (debugPrint "bug" 2 (strErr "after reduce" ∷ termErr t″ ∷ [])) λ _ →
      bindTC (debugPrint "bug" 2 (termErr t ∷ [])) λ _ →
      extendContext a (print ts)
```
This prints:
```
before reduce def (quote R₂) ([] {_} {_})
R₂
after reduce def (quote R₂) ([] {_} {_})
R₂
before reduce def (quote C) ([] {_} {_})
C
after reduce
def (quote R₁.C)
(_∷_ {_} {_}
 (arg {_} {_} (arg-info visible relevant)
  (def (quote R₂.r₁)
   (_∷_ {_} {_}
    (arg {_} {_} (arg-info visible relevant) (var 2 ([] {_} {_})))
    ([] {_} {_}))))
 ([] {_} {_}))
```
so before the call to `reduce` the type of the `_` in the lambda is still `C` as it is supposed to be, but after reduction it is (quoted):
```
def (quote R₁.C)
(_∷_ {_} {_}
 (arg {_} {_} (arg-info visible relevant)
  (def (quote R₂.r₁)
   (_∷_ {_} {_}
    (arg {_} {_} (arg-info visible relevant) (var 2 ([] {_} {_})))
    ([] {_} {_}))))
 ([] {_} {_}))
```
The correct result should use the variable `r₂`, which is `var 1` rather than `var 2`. Maybe the problem is that `reduce` does not respect the context changes by `inContext` and `extendContext` somehow?

**Comment by jespercockx** [comment] 2020-04-17 09:24
I think I'm starting to understand what's the cause of this problem. The term `C` in the type of the `_` declaration is really only valid in its proper context where `r₂` is in scope, since it comes from the `open R₁ (R₂.r₁ r₂)`. This means that once you do `inContext []`, it is no longer valid and anything you do with it (getting its type or reducing it) will result in bogus (or rather, will result in something that only made sense in the old context). 

So really the thing that is causing the issue is the interaction between definitions coming from a module application relying on the context in an indirect manner and `inContext` just blatantly ignoring this (since it calls `unsafeInTopContext` internally).

To fix this, I think the most straightforward thing to do would be to remove or deprecate the current `inContext`, and instead expose the safe function `updateContext`: https://github.com/agda/agda/blob/faca04a71eca18ac5fba9857adc523f72b34c359/src/full/Agda/TypeChecking/Monad/Context.hs#L162

**Comment by jespercockx** [comment] 2020-04-17 09:26
To help with your concrete problem of printing the context here: I think you should try to avoid using `inContext`, and instead properly raise the types you get from `getContext` so they can be printed without changing the context.

The moral of the story is: after using `inContext`, do not expect *any* terms you got before to be still valid. The only valid use-case of the current `inContext` is if you construct a new term completely from scratch.

**Comment by L-TChen** [comment] 2020-05-22 03:25
This makes me believe that a quoted term should either be closed (like in Davies & Pfenning) or open with a context packed (like in Nanevski et al.)...

**Comment by jespercockx** [comment] 2022-08-26 13:17
The current design of the reflection API is awkward, but there does not seem to be a concrete actionable proposal here, so I'm closing this issue.

**Closed as not planned by jespercockx** 2022-08-26 13:17 UTC
Labels: type: bug, reflection, de-Bruijn
