### ISSUE TITLE
Cubical triggers internal error when normalizing ua/equivToPath

### ISSUE THREAD

**Issue by ssomayyajula** [agda/agda#2818] opened 2017-10-25 04:18 UTC
[Here](https://github.com/ssomayyajula/cubism/blob/master/Cubical/Bug.agda) is a small example that triggers the error. I've been copying & editing @Saizan 's [`cubical-demo`](https://github.com/Saizan/cubical-demo) for my own purposes. However, when I attempt to normalize the expression `not-ua true`, I get the following error.
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Primitive.hs:909
```
Strangely enough, when I run `coe (equivToPath idEquiv) true` in `cubical-demo`, I get `true`, as expected. It is possible that I have not copied over primitives correctly, etc.
 
For reference, I've built Agda from [this](https://github.com/agda/agda/commit/f1ee4764d7c5a8cf3acd95e021c03ed6571af8dc) version of the repository.

Thanks.

**Comment by andreasabel** [comment] 2017-10-25 06:53
Test case without standard library:
```agda
{-# OPTIONS --cubical #-}

open import Agda.Primitive
open import Agda.Primitive.Cubical
open import Common.Product

uncurry : ∀ {a b c} {A : Set a} {B : A → Set b} {C : Σ A B → Set c} →
          ((x : A) → (y : B x) → C (x , y)) →
          ((p : Σ A B) → C p)
uncurry f (x , y) = f x y

infix 30 ~
~ = primINeg

infixr 20 _∧_ _∨_
_∧_ = primIMin
_∨_ = primIMax

postulate
  PathP : ∀ {ℓ} (P : I → Set ℓ) → P i0 → P i1 → Set ℓ
{-# BUILTIN PATHP PathP #-}

_==_ : ∀ {ℓ} {A : Set ℓ} → A → A → Set ℓ
_==_ {A = A} = PathP (λ _ → A)

module _ {ℓ} {A : Set ℓ} {x : A} where
  -- 3.1
  refl : x == x
  refl _ = x

  isContr-Singleton-lem : {y : A} (p : x == y) → (x , refl) == (y , p)
  isContr-Singleton-lem p i = p i , λ j → p (i ∧ j)

-- TAKEN FROM SAIZAN
transp : {ℓ : I → Level} (P : (i : I) → Set (ℓ i)) → P i0 → P i1
transp P ai0 = primComp P i0 (λ x → isOneEmpty) ai0

module _ {ℓ} {A : Set ℓ} {x : A} where
  -- TAKEN FROM SAIZAN
  J : ∀ {ℓ'} (P : (y : A) → x == y → Set ℓ') → P x refl → {y : A} (p : x == y) → P y p
  J P r p = transp (λ i → uncurry P (isContr-Singleton-lem p i)) r

isContr : ∀ {ℓ} → Set ℓ → Set ℓ
isContr A = Σ A (λ x → (y : A) → x == y)

module _ {ℓ₁ ℓ₂} {A : Set ℓ₁} {B : Set ℓ₂} (f : A → B) where
  fiber : (y : B) → Set (ℓ₁ ⊔ ℓ₂)
  fiber y = Σ A (λ x → y == f x)

isEquiv : ∀ {ℓ₁ ℓ₂} (A : Set ℓ₁) (B : Set ℓ₂) → (A → B) → Set (ℓ₁ ⊔ ℓ₂)
isEquiv _ B f = (y : B) → isContr (fiber f y)

{-# BUILTIN ISEQUIV isEquiv #-}

infix 4 _≃_
_≃_ : ∀ {ℓ₁ ℓ₂} → Set ℓ₁ → Set ℓ₂ → Set (ℓ₁ ⊔ ℓ₂)
A ≃ B = Σ (A → B) (isEquiv A B)

ide : ∀ {ℓ} {A : Set ℓ} → A ≃ A
ide = (λ x → x) , λ y → (y , refl) , λ z → isContr-Singleton-lem (proj₂ z)

primitive
  primGlue : ∀ {ℓ₁ ℓ₂} (A : Set ℓ₁) (φ : I)
    → (T : Partial (Set ℓ₂) φ) → (f : PartialP φ (λ o → T o → A))
    → (pf : PartialP φ (λ o → isEquiv (T o) A (f o))) → Set ℓ₂

-- TAKEN FROM SAIZAN
Glue : ∀ {ℓ₁ ℓ₂} (A : Set ℓ₁) → (φ : I) → (T : Partial (Set ℓ₂) φ)
  (f : (PartialP φ (λ o → T o ≃ A))) → Set ℓ₂
Glue A φ T f = primGlue A φ T (λ o → proj₁ (f o)) (λ o → proj₂ (f o))

-- TAKEN FROM SAIZAN
ua : ∀ {ℓ} {A B : Set ℓ} → A ≃ B → A == B
ua {A = A} {B} f i = Glue B (~ i ∨ i)
  (λ {(i = i0) → A ; (i = i1) → B})
  (λ {(i = i0) → f ; (i = i1) → ide})

data Bool : Set where
  true false : Bool

not : Bool → Bool
not true  = false
not false = true

coe : ∀ {ℓ₁} {A B : Set ℓ₁} → A == B → A → B
coe {A = A} {B} p = J (λ B _ → A → B) (λ x → x) p

id-ua : Bool → Bool
id-ua = coe (ua ide)

test = not (id-ua true)  -- C-c C-n

-- An internal error has occurred. Please report this as a bug.
-- Location of the error: src/full/Agda/TypeChecking/Primitive.hs:909
```

**Comment by Saizan** [comment] 2017-10-25 07:17
@ssomayyajula Apparently you forgot to declare the COMPGLUE builtin.

It's a big definition in PathPrelude
{-# BUILTIN COMPGLUE compGlue #-}

**Comment by ssomayyajula** [comment] 2017-11-04 00:37
Thanks! That fixes it.

**Comment by andreasabel** [comment] 2018-09-04 15:53
This should give a proper error, not an internal error!

**Comment by jespercockx** [comment] 2018-11-15 12:41
Same problem as #3212 ?

**Comment by Saizan** [comment] 2018-11-15 12:45
yes, this is a duplicate of #3212

**Closed as completed by Saizan** 2018-11-15 12:45 UTC
Labels: status: duplicate, type: bug, cubical, not-in-changelog
