### ISSUE TITLE
Display form/pragma bugs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1494] opened 2015-08-08 18:17 UTC
Bug-helper.agda:

``` agda
module Bug-helper where

record Record : Set₁ where
  field _≡_ : {A : Set} → A → A → Set

module Module (r : Record) where

  open Record r public
```

Bug.agda:

``` agda
module Bug where

open import Bug-helper

module M (r : Record) where

  open Module r

  postulate
    A   : Set
    a b : A

  Foo : a ≡ b
  Foo = {!!}

-- Bug 1
-- -----
--
-- The goal is displayed in a nice way if Agda is restarted and
-- Bug.agda is loaded:
--
--   ?0 : a ≡ b
--
-- However, if Bug.agda is reloaded, then we get the following result:
--
--   ?0 : (r Record.≡ a) b

-- Bug 2
-- -----
--
-- Let's try to work around the bug by adding a DISPLAY pragma just
-- before Foo:
--
--   {-# DISPLAY Record._≡_ _ x y = x ≡ y #-}
--
-- Result if the module is first loaded without the pragma and is then
-- reloaded with the pragma:
--
--   ?0 : _≡_ b
--
-- Result if the module is reloaded again:
--
--   ?0 : (r Record.≡ a) b
--
-- Result if Agda is restarted and the module is loaded:
--
--   ?0 : a ≡ b
--
-- If "open Module r" is replaced by "open Record r", then the last
-- result above is replaced by the following one:
--
--   ?0 : _≡_ b
--
-- In case it is relevant: I have disabled sharing.
```

Original issue reported on code.google.com by `nils.anders.danielsson` on 29 Apr 2015 at 4:40

**Comment by UlfNorell** [comment] 2016-02-08 13:39
This is working as intended. Display pragma right-hand sides are checked in the empty context (i.e. outside the module telescope), so if you want to use names from a parameterised module in the right-hand side of a display pragma you need to supply values for the module parameters as well. If you didn't it's not at all clear what to do outside the module. For instance,

``` agda
postulate
  F : Set → Set
  D : Set

module M (A : Set) where

  postulate G : Set → Set
  {-# DISPLAY F X = G X #-}  -- this should be F X = G e X, for some e, but if it wasn't...

  foo : F A
  foo = {!!}  -- ...and we wanted this to print as G A

open M

bar : F D
bar = {!!}   -- then what do we do here? G ?? A
```

**Closed as completed by UlfNorell** 2016-02-08 13:39 UTC
Labels: type: bug, ux: display, caching, display pragma
