### ISSUE TITLE
Agda fails to compile files without --local-interfaces in nixos

### ISSUE THREAD

**Issue by alexarice** [agda/agda#4613] opened 2020-04-20 15:50 UTC
I'm not sure if this is a nixos problem or an agda problem but currently if you try to compile an empty file with agda 2.6.1 which is not in a library, agda tries to build the interface file in `/nix/store/_build` which is read only. The problem seems to go away with `--local-interfaces`

Would be good if anyone has any ideas as to what is causing this.

**Comment by turion** [comment] 2020-04-20 16:11
Example setup to reproduce:

```
$ cd /tmp
$ cat mylib/mylib.agda-lib 
name: mylib
include: src

$ cat mylib/src/TestModule.agda 
module TestModule where
import IO

$ cat TestUserLibrary.agda 
import TestModule

$ agda -l standard-library -l mylib -i . TestUserLibrary.agda -v 10000
Importing the primitive modules.
Library dir = "/nix/store/7hbp89vwrih5hhdja12warhh5s8svn4n-Agda-2.6.1-data/share/ghc-8.8.3/x86_64-linux-ghc-8.8.3/Agda-2.6.1/lib"
SetRange is setting the current range to /nix/store/7hbp89vwrih5hhdja12warhh5s8svn4n-Agda-2.6.1-data/share/ghc-8.8.3/x86_64-linux-ghc-8.8.3/Agda-2.6.1/lib/prim/Agda/Primitive.agda:5,8-22 which is outside of the current file Nothing
/nix/store/_build: createDirectory: permission denied (Read-only
file system)
```

**Comment by alexarice** [comment] 2020-04-20 16:49
For me I can reproduce just by:
```
cd $(mktemp -d)
touch test.agda
agda test.agda
```

**Comment by gallais** [comment] 2020-04-20 20:29
This is very strange. `_build` directories should only be created at the root
of an Agda project. Surely you don't have an `.agda-lib` file in `/nix/store/`?

(Note that there is another, unrelated, issue with nix that should get fixed in
a minor release: #4526)

**Comment by alexarice** [comment] 2020-04-20 20:31
I think there probably is a .agda-lib file in my nix store but It was my understanding that it shouldn't matter because as it's in a different directory to my temp directory?

**Comment by gallais** [comment] 2020-04-20 20:45
With the (new) project-based interface stashes, we do not dump the .agdai files
next to the corresponding source file anymore if we can find a project root
(i.e. an `.agda-lib` file somewhere up in the hierarchy).
This allows us to avoid retypechecking a project from scratch every time a user
switches between versions of Agda.

Here the presence of an `.agda-lib` file in `/nix/store` leads Agda to believe
that the root project for the primitives is `/nix/store` and so it tries to
regenerate the `agdai` files for the builtins there (well, in `_build/2.6.1`
to be exact).

I think this demonstrates we do need to ship an `.agda-lib` for the builtins
and get them compiled into the appropriate `_build/VERSION` at installation
time.

**Comment by alexarice** [comment] 2020-04-20 20:47
Ah I forgot about the primitives, that makes perfect sense

**Comment by turion** [comment] 2020-04-20 20:48
So we could patch this quickly by distributing our own `.agda-lib` for builtins in Nixos I guess?

**Comment by alexarice** [comment] 2020-04-20 20:51
That might be the best solution

**Comment by gallais** [comment] 2020-04-20 20:59
If you do so, you need to make sure that the `.agdai` files for the builtins
end up in the corresponding `_build/2.6.1` directory. At the moment `Setup.hs`
compiles the builtins using `--local-interfaces` so they are dumped next to the
source file (the assumption was that there would never be an `.agda-lib` file
for Agda to find but that was a really bad assumption to make in retrospect.
Sorry about that! :sob:).

So you could:

* [ ] add an `.agda-lib` file for the builtins
* [ ] remove `--local-interfaces` from `Setup.hs`

and hopefully that should do it? :crossed_fingers:

**Comment by alexarice** [comment] 2020-04-20 21:03
Should the .agda-lib file just go in the same folder as the builtins?

**Comment by gallais** [comment] 2020-04-20 21:07
I would put a file `agda-builtins.agda-lib` in `lib/prim/`:

```
name: agda-builtins
include: .
```

**Comment by laMudri** [comment] 2020-04-21 08:51
> I think there probably is a .agda-lib file in my nix store

Wait, surely not? I thought everything directly in `/nix/store/` was a directory or a `.drv`.

**Comment by alexarice** [comment] 2020-04-21 10:08
> 
> 
> > I think there probably is a .agda-lib file in my nix store
> 
> Wait, surely not? I thought everything directly in `/nix/store/` was a directory or a `.drv`.

Ah, this only started when we started trying to write tests, this is why it took so long to notice

**Comment by alexarice** [comment] 2020-04-21 10:10
```
$ ls | grep ".agda-lib"
blxg8dm9ipq86028q9qp8qij2j4rr8rn-mylib.agda-lib
bqp854jr20z2y9x9v0391hm6cjswyska-mylib.agda-lib.drv
hlyi5ims19lca5rmzhhgxwkfjrmaaklq-mylib.agda-lib.drv
qcfx5glrzps4mf67clrknsw551f7bms7-mylib.agda-lib
```

**Comment by laMudri** [comment] 2020-04-21 10:11
Aah, are `blxg8dm9ipq86028q9qp8qij2j4rr8rn-mylib.agda-lib` and `qcfx5glrzps4mf67clrknsw551f7bms7-mylib.agda-lib` actually directories whose names happen to end with `.agda-lib`?

**Comment by alexarice** [comment] 2020-04-21 10:12
no they are files, A derivation can be a single file

**Comment by laMudri** [comment] 2020-04-21 10:13
Oh okay, I suppose this should be a won't-fix from the Agda side, then.

**Comment by gallais** [comment] 2020-04-21 10:14
> Oh okay, I suppose this should be a won't-fix from the Agda side, then.

I think our fix should be to add an `.agda-lib` file to the `lib/prim`.

**Comment by alexarice** [comment] 2020-04-21 14:18
As a side note, Agda also seems to recognise directories as agda-lib files for the purposes of determining what a library is

**Comment by guilhermehas** [comment] 2020-04-23 01:40
In my machine, it compiles, but it takes a very long time.

**Comment by turion** [comment] 2020-04-23 07:23
> In my machine, it compiles, but it takes a very long time.

What system do you have?

**Comment by guilhermehas** [comment] 2020-04-23 10:40
> What system do you have?

Nixos too.

**Comment by alexarice** [comment] 2020-04-23 10:41
The problem only occurs if you end up with an .agda-lib file in your nix store. This only happened to us when we tried to make some nixos tests

**Comment by gallais** [comment] 2020-04-23 10:43
@guilhermehas is probably suffering from #4526

**Comment by alexarice** [comment] 2020-04-30 22:44
@gallais I believe you have fixed this issue now so this can probably be closed?

**Comment by gallais** [comment] 2020-04-30 23:07
The fix (#4616) is not ready yet: `Setup.hs` is not properly installing the
new `.agdai` files.

**Comment by alexarice** [comment] 2020-04-30 23:08
ah my bad, I just saw the commit and assumed it was merged

**Comment by jespercockx** [comment] 2021-03-17 14:34
Could someone using NixOS test if this is still a problem? I introduced a caching mechanism for .agda-lib files which should make it a lot faster, but I'm not sure if that's enough to fix the issue here.

**Comment by alexarice** [comment] 2021-03-17 14:35
Is this caching in a release or on master?

**Comment by jespercockx** [comment] 2021-03-17 19:00
It is only on master at the moment.

**Comment by alexarice** [comment] 2021-03-17 19:21
Ok, I'll get that compiling

**Comment by guilhermehas** [comment] 2021-03-17 20:14
Agda test in NixOS maybe can help:
https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/agda.nix

**Comment by alexarice** [comment] 2021-03-17 20:17
Running it now, but I can't see how the change will help with issue as the problem was another .agda-lib file being upstream from the primitives files. Perhaps you meant to test the issue with agda being very slow without --local-interfaces @jespercockx ?

**Comment by alexarice** [comment] 2021-03-17 20:22
No change with this issue between 2.6.1.3 and master. In summary this issue occurs when there is an .agda-lib file in the nix store. Agda then notices this as being upstream from the primitives files (which have no .agda-lib) and tries to use the nix-store as their upstream library. This breaks everything.

To reproduce:
```
touch test.agda-lib
nix store add-file test.agda-lib
touch test.agda
nix-shell -p haskellPackages.Agda
agda test.agda
```
Fails with the error:
```
/nix/store/_build: createDirectory: permission denied (Read-only
file system)
```

**Comment by alexarice** [comment] 2021-03-17 20:48
wrt https://github.com/NixOS/nixpkgs/issues/83864, I can confirm that some combination of changes on master vastly speed up loading of primitive modules without --local-interfaces (assuming there is no .agda-lib file in the nix store).

**Comment by andreasabel** [comment] 2021-04-21 14:07
Can we assume this is fixed?  Please reopen if issues remain.

**Comment by turion** [comment] 2021-04-21 14:27
From the rest of the thread I don't see why it should be fixed, but I think @alexarice will be able to confirm?

**Comment by alexarice** [comment] 2021-04-21 14:36
This was not fixed last time I checked

**Comment by turion** [comment] 2021-04-21 17:25
@alexarice I can't even reproduce on the released version 2.6.1.3:

```
$ ls /nix/store/  | grep ".agda-lib"

$ touch test.agda-lib

$ nix-store --add test.agda-lib 
/nix/store/462pdhbmn0qn2xdjqyazwh59wdq5jwg9-test.agda-lib

$ touch test.agda

$ agda test.agda
Checking test (/home/turion/nix/nixpkgs/test.agda).

$ ls /nix/store/  | grep ".agda-lib"
462pdhbmn0qn2xdjqyazwh59wdq5jwg9-test.agda-lib

$ agda --version
Agda version 2.6.1.3
```

Am I reproducing incorrectly?

**Comment by laMudri** [comment] 2021-04-21 17:56
IIRC, Agda from Nixpkgs has `--local-interfaces` on by default. On my setup:

```
$ cat $(which agda)
#! /nix/store/jdi2v7ir1sr6vp7pc5x0nhb6lpcmg6xg-bash-4.4-p23/bin/bash -e
exec "/nix/store/mnwqhh0cdvz7gi175p5fmd6ynqg2ijsh-Agda-2.6.1.3/bin/agda"  --with-compiler=/nix/store/2vmgrz5bcy5112f16mh4mn4ivqqhsl8q-ghc-8.10.4-with-packages/bin/ghc --library-file=/nix/store/dck3i0gmr2fanlfgzshqwzwqp9630v0w-libraries --local-interfaces "$@"
```

**Comment by turion** [comment] 2021-04-22 09:25
Yes true, I forgot about that. I'm currently unable to patch this in a way that I can test this.

**Comment by jespercockx** [comment] 2021-05-19 14:22
Unless we get feedback from someone who uses NixOS and can actually reproduce this in the next few days, we won't take action on this before the next release.

**Comment by alexarice** [comment] 2021-05-19 14:32
I can reproduce the error with revision 1bac8797a5987e07ec28284807f57e0cddeb2ba9, though this is 24 days old now so I could try building the latest master if this will help

**Comment by jespercockx** [comment] 2021-05-24 08:55
Unfortunately it seems no-one with sufficient knowledge about NixOS has been able to find a fix for this yet. Since this is the only remaining open issue for 2.6.2 and I do not want to postpone the release any longer, I am bumping the milestone on this one.

**Comment by alexarice** [comment] 2021-05-24 08:59
I don't mind postponing this problem as we have a workaround, but I also know what causes it.

The problem is that when there is an `.agda-lib` file in a parent directory of where agda is installed, Agda thinks the primitive files are part of the directory the `.agda-lib` file is in. In nixos, this directory is readonly, causing the error. A fix discussed somewhere was to include an `.agda-lib` file for the primitives but I believe this was tried and there was some difficulty with it

**Comment by jespercockx** [comment] 2021-05-24 09:12
Ah, you mean https://github.com/agda/agda/pull/4616? I'm not sure what the problem with that one was, but if that would actually fix this issue I'll take a look.

**Comment by jmchapman** [comment] 2021-05-24 09:34
I think there is another related problem: the nix agdaWithPackages package doesn't allow you to use libraries that are not packaged by nix. @laMudri shared a workaround with me to wrap adhoc libraries.

In a way I think both of these problems are part of a single one: an inability to manage read-only 'global' packages and read-write 'local' packages. This sounds like a typical package manager problem.

**Comment by alexarice** [comment] 2021-05-24 10:07
I think these problems are seperate. The primitives are precompiled as part of the packaging process, but are compiled with the interface files next to the primitives files. However if we later try to typecheck anything, it sees the upstream `.agda-lib` file and looks for a `_build` directory in this folder. When it can't find it, it tries to rebuild.

An an aside, If there's enough interest it will be easy to make a PR for having an option for extra modifyable libraries. I originally put this in when building the infrastructure but it was deemed to be not the nix way of doing things.

**Comment by alexarice** [comment] 2021-05-24 10:08
> 
> 
> Ah, you mean #4616? I'm not sure what the problem with that one was, but if that would actually fix this issue I'll take a look.

I believe fixing that issue will fix this one

**Comment by nad** [comment] 2021-11-09 12:48
> I think this demonstrates we do need to ship an `.agda-lib` for the builtins

We still do not do this. Is there a reason for this (other than lack of time)?

**Comment by gallais** [comment] 2021-11-09 13:30
IIRC Setup.hs is using its own separate compilation & installation recipe and that conflicts with .agda-lib
Cf. my attempt in #4616

**Comment by andreasabel** [comment] 2024-02-08 14:10
@gallais : Is this fixed by this PR?
- #6988

**Comment by gallais** [comment] 2024-02-23 10:39
I don't know, I'm not a nix user. :D

**Comment by andreasabel** [comment] 2024-02-23 10:44
Ok, I'll remove it from the milestone again.  I also removed your assignment.
We would need new input from users whether this is still a problem.

**Comment by alexarice** [comment] 2024-02-23 10:47
I'll check this now, though need to built the release candidate

**Comment by alexarice** [comment] 2024-02-23 12:13
As far as I can tell, everything is working with release candidate 2, with or without the `--local-interfaces` flag

**Closed as completed** 2024-02-23 17:35 UTC
Labels: type: bug, platform: nix, workaround exists
