### ISSUE TITLE
Better error message for out-of-scope deBruijn index in tactics

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2006] opened 2016-06-06 16:26 UTC
``` haskell
open import Data.Unit
open import Reflection
open import Data.String

printTerm : Term → String
printTerm (var x args) = "0"
printTerm _ = "1"

macro
  comp : Term → Term → TC ⊤
  comp x t = unify t (quoteTerm (printTerm x))

test : String
test = comp tt
```

`printTerm` causes Agda to panic here, but if I just comment out the pattern-matching line `printTerm (var x args) = "0"` (and leave the rest unchanged), it works. I'm using `master` branch from within the last day or so.

**Comment by UlfNorell** [comment] 2016-06-07 18:37
Here's a simpler example:

``` agda
open import Common.Reflection
open import Common.Prelude

macro
  foo : Term → TC ⊤
  foo = unify (var 0 [])

bar : Set
bar = foo
```

There should be a better error message when tactics produce out-of-scope deBruijn variables.

The reason the `var`-clause of `printTerm` makes a difference in your example is that without it `printTerm x` reduces to `"1"`. When it's there `quoteTerm (printTerm x)` will be `def (quote printTerm) (var 1 [] :: [])`, which has an out-of-scope deBruijn index. Note that `quoteTerm` is syntactic quoting (so `x` is quoted to `var 1 []`). If you want to quote whatever `x` is bound to at macro application time, use `quoteTC`.

**Comment by identicalsnowflake** [comment] 2016-06-07 19:32
> Note that quoteTerm is syntactic quoting (so x is quoted to var 1 []).

Ah, nice! Ok, using the above, I changed my original example to this:

``` haskell
open import Data.Unit
open import Reflection
open import Data.String

printTerm : Term → String
printTerm (var _ _) = "0"
printTerm _ = "1"

macro
  comp : Term → Term → TC ⊤
  comp x t = bindTC (quoteTC (printTerm x)) (λ y → unify t y)

test : String
test = comp tt
```

which behaves as expected. However, something still isn't right near here -- it's probably a different issue, but it's triggered by almost the same example. The first thing I tried to do was redefine `printTerm` to `printTerm x = ?` and case split with `C c x`. Agda tells me "An internal error has occurred, please report this as a bug."

EDIT: and `Location of the error: src/full/Agda/Interaction/MakeCase.hs:88`

**Comment by UlfNorell** [comment] 2016-06-07 20:31
Wow, that's funny. The problem is that the hole in the right hand side of `printTerm` is also exactly the same hole that's in the right hand side of `test`, since it got quoted by the macro. The case split then gets confused since it doesn't know which function to split.

@andreasabel has been itching to fix that code for the last 6 years, so I'll leave it up to him.

**Comment by andreasabel** [comment] 2016-06-08 05:47
Well, I was itching to make a hole remember which clause it belongs to (and that might be easy to fix), but I do not know about duplication/sharing of holes...
I will fix the 6 year old issue.

**Comment by UlfNorell** [comment] 2016-06-08 06:13
If the hole knows which clause it belongs to duplication won't be a problem. You always want the split in the original location (`printTerm` not `test`).

**Comment by andreasabel** [comment] 2016-06-08 09:56
I guess we can close this issue.  Reopen if necessary!

**Closed as completed by andreasabel** 2016-06-08 09:56 UTC
Labels: ux: case splitting, reflection
