### ISSUE TITLE
Discuss: function equality via code content

### ISSUE THREAD

**Issue by bbarker** [agda/agda#4590] opened 2020-04-15 21:53 UTC
First, I must note I'm not a language theorist but more of an enthusiast, but I'll try to keep up with the relevant points. Also, I'm very new to Agda.

I somehow came across [this blogpost](https://semantic-domain.blogspot.com/2016/03/agda-is-not-purely-functional-language.html?m=1). The basic idea is that this doesn't check out in Agda:

```agda
f : Bool → Bool
f true = true
f false = false

g : Bool → Bool
g true = true
g false = false

wat : f ≡ g 
wat = refl
```

In fact, this wouldn't work in most programming languages I know of, though there is one language where I think it would: [Unison]. And the interesting thing there is that isn't achieved by any deep theoretical insights, but instead a very clever idea of [hashing the abstract syntax tree](https://www.unisonweb.org/docs/tour#%F0%9F%A7%A0-the-big-technical-idea) (AST). I wonder if this approach could be used in Agda. Alternatively maybe there is currently a workaround to this already.

**Comment by gallais** [comment] 2020-04-15 22:19
This would be really helpful when using anonymous pattern-matching functions.
The following does not hold for instance:

```agda
_ : \ { x -> x } ≡ \ { x -> x }
_ = refl
``` 

A more concrete example: in the standard library we have [equational proofs of
bisimilarity](http://agda.github.io/agda-stdlib/Codata.Stream.Properties.html#1914) where some of the subterms simply *cannot* be written because the
functions we would like to talk about have been defined using anonymous
copattern-matching functions and they only have an internal name that is bound
to be different from that of any other anonymous function written using exactly
the same code.

**Comment by xekoukou** [comment] 2020-04-16 00:09
I was having a similar thought , the last days, for a different reason. I was thinking how one could look at the different versions of the same function. The only way to differentiate them is to hash their content.

The main benefit of this is that the functions are immutable objects with regard to revisions.

edit : 
It appears that [Unison](https://www.unisonweb.org/) has a similar motivation as me for this : 
" allowing a single Unison program to describe entire elastic distributed systems."

**Comment by UlfNorell** [comment] 2020-04-16 07:19
I would be a wary of adding syntactic equalities to theory. Consider
```agda
f : Bool → Bool
f true = true
f false = false

g : Bool → Bool
g true = true
g false = not true  -- *
```
Suddenly `f` and `g` are no longer equal (unless we normalize bodies before hashing, which would be prohibitively expensive). This breaks referential transparency, which doesn't feel like a price worth paying to get `f ≡ g`.

**Comment by L-TChen** [comment] 2020-04-16 07:20
> This would be really helpful when using anonymous pattern-matching functions.
> 
> The following does not hold for instance:
> 
> 
> 
> ```agda
> 
> _ : \ { x -> x } ≡ \ { x -> x }
> 
> _ = refl
> 
> ``` 

You can get the desired equality by quotation since they have the same intension / code. But, the converse (the same intension should imply equal unquoted terms ...) should always be true as well...

**Comment by L-TChen** [comment] 2020-04-16 07:36
> Suddenly `f` and `g` are no longer equal (unless we normalize bodies before hashing, which would be prohibitively expensive). This breaks referential transparency, which doesn't feel like a price worth paying to get `f ≡ g`.

Can you elaborate on referential transparency about this case?

Shouldn’t definitional equality include at least syntactic equality (up to alpha-conversion)?

**Comment by jespercockx** [comment] 2020-04-16 07:45
Definitional equality includes syntactic equality of the *elaborated* code in internal syntax. It just so happens to be the case that `\ { x -> x }` and `\ { x -> x }` are not elaborated to the same internal syntax.

**Comment by L-TChen** [comment] 2020-04-16 07:49
Totally confused. How so?

**Comment by jespercockx** [comment] 2020-04-16 08:00
See https://agda.readthedocs.io/en/v2.6.1/language/lambda-abstraction.html:


> This means that anonymous pattern matching functions are generative. For instance, refl will not be accepted as an inhabitant of the type
> ```
> (λ { true → true ; false → false }) ==
> (λ { true → true ; false → false })
> ```
> because this is equivalent to extlam1 ≡ extlam2 for some distinct fresh names extlam1 and extlam2.

**Comment by fredrikNordvallForsberg** [comment] 2020-04-16 09:36
> The following does not hold for instance:
>
> ```
> _ : \ { x -> x } ≡ \ { x -> x }
> _ = refl
> ```

Not the main point, but note that `refl` **does** prove the above equality (if you put in some more brackets, and specify the type of the equality), because Agda checks definitional equality of functions by applying them to fresh variables and comparing the results. The problem is with pattern-matching lambdas that actually match on their arguments, as in the example quoted by @jespercockx.

```agda
_ : {A : Set} -> ((A → A) ∋ \ { x -> x }) ≡ (\ { x -> x })
_ = refl
```

**Comment by andreasabel** [comment] 2020-04-16 18:59
Agda is nominal, not structural, by design.  Two functions/data types with different names are distinguished even if they have identical definitions.  This isn't different from other programming languages like Java for instance.  If you copy a class `A` into `B`, then these classes will not be subtypes of each other even though they have identical definitions.  _Nominal_ means equality is by name.

_Structural_ equality would equate things that have identical definitions.  I think Cayenne did that.  It is a nightmare for users that want to understand error messages, because too much unfolding takes place.

Some structural equality is of course realized by definitional equality with its extension by eta-equality.

That extended lambdas are treated in a nominal way even though there are no names is an accident.  They were not part of the original design of Agda 2 but hacked into Agda at an Agda meeting around 11 years ago, by reducing them to ordinary function definitions via a generated name.  This wart still waits to be healed.

**Comment by andreasabel** [comment] 2020-04-20 20:40
Closing for now, welcome to reopen if there is more to discuss.

**Closed as completed by andreasabel** 2020-04-20 20:40 UTC
Labels: status: wontfix, type: discussion

**Comment by HeinrichApfelmus** [comment] 2023-11-06 13:09
I would like to discuss more. 🙂

(I recently hit on this issue when trying to formalize `Data.Map.Map a b` as functions `a → Maybe b` and attempting to do equational reasoning.)

> Agda is nominal, not structural, by design. Two functions/data types with different names are distinguished even if they have identical definitions. 

Strictly speaking, this is true only for declarations that involve pattern matching. In essence, the declarations of `f` and `g` above add two new inhabitants, `f` and `g`, to the function type `Bool → Bool`. In other words, it is *not true* that every inhabitant `h : Bool → Bool` has the shape `h = λ x → …` — very far from it.

In contrast, a definition in terms of the canonical eliminator of the `Bool` type, such as

```agda
Bool-elim
    : ∀ {P : Bool → Set}
    → (b : Bool)
    → P true → P false → P b
Bool-elim true x y = x
Bool-elim false x y = y

f' : Bool → Bool
f' = λ bib → Bool-elim bib true false

g' : Bool → Bool
g' = λ bob → Bool-elim bob true false

eq' : f' ≡ g'
eq' = refl
```

works as intended.

> Structural equality would equate things that have identical definitions. I think Cayenne did that. It is a nightmare for users that want to understand error messages, because too much unfolding takes place.

I tend to agree that *not* unfolding definitions like `f` makes the proof system more useable.

However, I also believe that adding new inhabitants to function types on the fly is problematic. I think the expectation on `f` and `g`, and also on anonymous lambdas such as `λ { true → true; false → false }` is that they get translated into applications of the canonical eliminators, such as `Bool-elim`. This automatically ensures soundness of the system, because I can always Church-encode `Bool` as the function type corresponding to its canonical eliminator; adding no new inhabitants to any type.

Perhaps a constructive variant of phrasing the issue is the following: Is it possible to translate an Agda program into an "Agda-core" program with a more structural lambda calculus, such that the "Agda-core" program can be verified with a small kernel? The issue is then when I make a new definition by pattern matching, I have to trust that the Agda code (written in Haskell) contains no bug and produces a new inhabitant which is sound, whereas by mapping to a more structural lambda calculus, I don't have to trust the code written in Haskell; I only have to trust that the translation result type checks.

**Comment by jespercockx** [comment] 2023-11-07 16:25
> Is it possible to translate an Agda program into an "Agda-core" program with a more structural lambda calculus, such that the "Agda-core" program can be verified with a small kernel? 

In theory this should be possible (for some subset of what the current implementation of Agda allows) but at the moment there is nothing like this implemented. If you don't want to rely on Agda's implementation of pattern matching, you can turn it off using `--no-pattern-matching` and write your definitions by hand using eliminators.

> I can always Church-encode Bool as the function type corresponding to its canonical eliminator; adding no new inhabitants to any type.

Note that a Church encoding won't give you the dependent eliminator, only the non-dependent recursion principle. If you want to use lambda-encoded data with dependent eliminators, the only way that works is to follow the approach taken by Cedille (https://cedille.github.io/), which adds a dependent intersection type which you can use for this purpose.

If you want to have a "small trusted core" then the current version of Agda is probably not your best bet, and you would be better off looking into Coq, Lean, or indeed Cedille.

**Comment by HeinrichApfelmus** [comment] 2023-11-12 23:34
> Note that a Church encoding won't give you the dependent eliminator, only the non-dependent recursion principle.

Fair point — I can't even write down the dependent eliminator `: ∀ {P : Bool → Set} → (b : Bool) → P true → P false → P b` if I do not know how `true` and `false` are defined.

> If you want to have a "small trusted core" then the current version of Agda is probably not your best bet, and you would be better off looking into Coq, Lean, or indeed Cedille.

… or wait for the results of the grant [“A Trustworthy and Extensible Core Language for Agda.”][1]. 😜

  [1]: https://jesper.sikanda.be/posts/veni-announcement.html

**Comment by jespercockx** [comment] 2023-11-13 07:59
That's why I said "the current version of Agda" :)
