### ISSUE TITLE
Unsolved metas

### ISSUE THREAD

**Issue by mechvel** [agda/agda#1666] opened 2015-09-23 18:59 UTC
Please, download it from
http://www.botik.ru/pub/local/Mechveliani/agdaNotes/question-sep23-2015-2.zip

I split the closed issue #1649  to  #1665  and to this one.

This is on  Agda 2.4.2.3.20150913  (ghc-7.10.1).

> unzip
> agda $agdaLibOpt +RTS -M4G -RTS Foo.agda

reports

```
/home/mechvel/doconA/0.04/reports/sep23-2015-2/Foo ...

Expected a visible argument, but found a hidden argument
when checking that the expression
=asdReflexive (PE.cong Π' (PE.sym $ map-compose ps')) has type
Π' (map asd (map ((λ {.x} → pairValue) ∘ pairFromAsd) ps')) ='
Π' (map ((λ {.x} → asd) ∘ (λ {.x} → pairValue) ∘ pairFromAsd) ps')
```

Then,
take   Foo.agda,  and uncomment the line marked by  "debug (2)".

Then it reports  Unsolved metas  at the two lines marked with  `**'.

1) The line  "debug (2)"  is local in the function which is later than
   "debug (1)".  And uncommenting returns the `unsolved' report for the
   line "debug (1)".
   This looks strange.

(and the Agda developers have  confirmed earlier that it is strange).

2) I do not find of how to fix  fromMultiset'.
   For it looks like all implicit things are named.

Is this a bug in Agda ?
If it is not, then how to fix my code?
(so that to prove the equation e in the end).

**Comment by asr** [comment] 2015-09-23 21:55
> Then,
> take Foo.agda, and uncomment the line marked by "debug (2)".
> 
> Then it reports Unsolved metas at the two lines marked with `**'.

Using Agda 2.4.2.4 RC I can see the unsolved metas (highlighted in yellow) without commenting out the line marked by "debug (2)". Don't you?

> 1) The line "debug (2)" is local in the function which is later than
> "debug (1)". And uncommenting returns the `unsolved' report for the
> line "debug (1)".
> This looks strange.

Since the unsolved metas always are indicated, 1) is not a valid problem.

**Comment by asr** [comment] 2015-09-23 23:49
Can you write down the implicit argument required in

``` agda
fromMultiset' : Multiset' → Multiset                    -- debug (1)
fromMultiset' M' =  mapMultiset fromAsd M' (injOn-ks' {{!!}})    -- **
```

?

**Comment by asr** [comment] 2015-09-24 03:53
Using Agda 2.4.2.3 I also got the unsolved metas without commenting out the line marked by "debug (2)". 

I'm seeing two different problems reported in this issue:
1.  How to fix the unsolved metas in `fromMultiset'`?
   
     Since this problem is reproducible using Agda 2.4.2.3 and Agda 2.4.2.4 RC, this problem is not related to the release candidate.
2. Why does Agda 2.4.2.4 RC generate the error
   
   `Expected a visible argument, but found a hidden argument when checking that the expression...`
   
   ?

From the code in http://www.botik.ru/pub/local/Mechveliani/agdaNotes/question-sep23-2015-2.zip it seems both problems are not related.

If you agree with what I said, please close this issue and open a new issue for each problem.

**Comment by mechvel** [comment] 2015-09-24 08:39
asr   commented  Sep 23, 2015

> >  Then,
> >    take Foo.agda, and uncomment the line marked by "debug (2)".
> >    Then it reports Unsolved metas at the two lines marked with `**'.
> 
> Using Agda 2.4.2.4 RC I can see the unsolved metas (highlighted in yellow) without commenting 
> out the line marked by "debug (2)". Don't you?

Currently I fail to use the interactive Agda (something is broken in my settings).
I apply Agda from the command line.
And sometimes its report differs from the one of the interactive.
In this example, the command line type check is silent about the first "unsolved" place which is highlighted by interactive.
(I think this difference to interactive  is an old and known bug).

**Comment by andreasabel** [comment] 2015-09-24 08:45
If you have a type error you do not see the warnings, like unsolved metas, in the command-line version of Agda.

**Comment by mechvel** [comment] 2015-09-24 09:46
asr   commented  Sep 23, 2015

> Can you write down the implicit argument required in
> 
> fromMultiset' : Multiset' → Multiset                                           -- debug (1)
> fromMultiset' M' =  mapMultiset fromAsd M' (injOn-ks' {{!!}})    -- **
> ?

  fromMultiset' M' =  mapMultiset fromAsd M'  (\ {x} {y} → injOn-ks' {x} {y})

I have forgotten of implicits in  injOn-ks'.  Thank you.  
Now, it remains "unsolved metas" furrther, in 

```
       where
       ...
       injOn-ks' : InjectiveOnList ks' fromAsd
       injOn-ks' = injective→injectiveOnList  fromAsd  
                                                                  (\ {x} {y} → fromAsd-injective {x} {y}) ks'
```

And itt helps
           injOn-ks' {z} {u} = injective→injectiveOnList fromAsd  -- *\*  
                                                                  (\ {x} {y} → fromAsd-injective {x} {y}) ks'  {z} {u}

-- the two levels of prasitic arguments of the kind  (\ {...}  →).

Thank you very much.
I am sorry for the noise.
On the other hand, these multilevel parasitic arguments are awful.

**Comment by mechvel** [comment] 2015-09-24 09:54
andreasabel   commented  Sep 24, 2015

> If you have a type error you do not see the warnings, like unsolved metas, in the command-line 
> version of Agda.

This was a _report _of a type error caused by unsolved metas found earlier. In interactive, this unsolved metas is highlighted, and it is not notices by the command line type checker.

**Comment by mechvel** [comment] 2015-09-24 10:13
asr   commented  Sep 24, 2015

>  Since this problem is reproducible using Agda 2.4.2.3 and Agda 2.4.2.4 RC, this problem is not 
> related to the release candidate.

I thought that if something  is reproduced by the two, it is related to both.
(?)
Suppose that the user has  A and A-next-RC, and is mainly interwested in A-next-RC (because, for example, A takes too much space).
Do you mean that the user needs to report a problem for A, and after it is fixed in A, to report the same for A-next-RC ?

Again, I am sorry for  missing a couple of implicit arguments in my code.
I would like to close the issue
(after you read the  my notes above).

Thanks,
/ Sergei

**Comment by UlfNorell** [comment] 2015-09-24 11:39
What Andres was saying was that "My program checks in 2.4.2.2 but not in 2.4.2.4-RC1" is a valid bug report that we would hold off the release for, but "My programs doesn't check in 2.4.2.4-RC1 or in 2.4.2.2" is not. In the latter case the default assumption would be that there's simply a type error in your code, and even if it is a bug it has to be a serious one to stop the release.

**Closed as completed by UlfNorell** 2015-09-24 11:39 UTC

**Comment by asr** [comment] 2015-09-24 14:49
Since the issue fixed was how to fix the unsolved metas in fromMultiset', I'll rename the issue.
