### ISSUE TITLE
Interactive mode unconditionally raises Windows timer resolution to maximum value

### ISSUE THREAD

**Issue by yuriy0** [agda/agda#1758] opened 2015-12-26 21:36 UTC
For those not familiar, the timer resolution is roughly how often the CPU is interrupted to check if Windows timers have "fired". I don't know how, if at all, this affects other platforms. Setting this value very high is bad because:

> The default timer resolution on Windows 7 is 15.6 milliseconds (ms). Some applications reduce this to 1 ms, which reduces the battery run time on mobile systems by as much as 25 percent.
> - [Timers, Timer Resolution, and Development of Efficient Code](http://download.microsoft.com/download/3/0/2/3027D574-C433-412A-A8B6-5E0A75D5B237/Timer-Resolution.docx)

More importantly, the timer resolution for the entire system is set to the maximum requested amount by any program. To reproduce, run `agda --interaction` (give agda no commands, tested with 2.4.2 and latest master - abff803 as of this post), then run `powercfg -energy` on Win7 or `powercfg /energy` on Win8, Win10 (although latter versions of Windows supposedly do not suffer from the timer resolution problem?) to generate an energy consumption report. This report will contain something like the following:

```
Platform Timer Resolution:Timer Request Stack
The stack of modules responsible for the lowest platform timer setting in this process.
Requested Period        10000
Requesting Process ID   4808
Requesting Process Path \Device\HarddiskVolume4\stuff\path\agda.exe
Calling Module Stack    \Device\HarddiskVolume3\Windows\System32\ntdll.dll
                        \Device\HarddiskVolume3\Windows\System32\winmm.dll
                        \Device\HarddiskVolume4\stuff\path\agda.exe
                        \Device\HarddiskVolume3\Windows\System32\kernel32.dll
                        \Device\HarddiskVolume3\Windows\System32\ntdll.dll
```

(The "Requested Period: 10000" refers to 10000 \* 100ns = 1ms)

This issue is especially problematic with interaction mode, since in this mode agda is generally idle, while the timer resolution is still set unconditionally and the system is constantly wasting power. Is there really a reason that agda needs this? Even if it does need to set the timer resolution to a higher value, does it need to do that while idling in interaction mode?

**Comment by UlfNorell** [comment] 2015-12-28 08:42
We don't have any Windows-specific code so the problem is likely in some ghc library. The relevant code in Agda is in [Agda.Interaction.EmacsTop](https://github.com/agda/agda/blob/master/src/full/Agda/Interaction/EmacsTop.hs#L40-L69). Essentially we do

``` haskell
hSetBuffering stdout NoBuffering
hSetEncoding  stdout utf8
hSetEncoding  stdin  utf8
getLine
```

All functions from `System.IO`.

**Comment by WolframKahl** [comment] 2015-12-28 14:20
Perhaps it is the machinery involved in supporting `-v profile=7`?

**Comment by Blaisorblade** [comment] 2016-06-19 09:31
Looking at the Word document that @yuriy0 posted reveals that the culprit is `timeBeginPeriod`. After grepping for it (through GitHub!) in repos for [`base`](https://github.com/ghc/packages-base/search?utf8=%E2%9C%93&q=timeBeginPeriod), [`win32`](https://github.com/haskell/win32/search?utf8=%E2%9C%93&q=timeBeginPeriod), [`time`](https://github.com/ghc/packages-time/search?utf8=%E2%9C%93&q=timeBeginPeriod) and [`ghc`](https://github.com/ghc/ghc/search?utf8=%E2%9C%93&q=timeBeginPeriod) I found it in GHC: https://github.com/ghc/ghc/blob/5d98b8bf249fab9bb0be6c5d4e8ddd4578994abb/rts/win32/IOManager.c#L313. IIUC, that code queries the possible time resolutions with `timeGetDevCaps` and selects the most accurate one (with `wPeriodMin`). Implementating ["Non-blocking / asynchronous I/O for Win32"](https://github.com/ghc/ghc/blob/5d98b8bf249fab9bb0be6c5d4e8ddd4578994abb/rts/win32/IOManager.c#L3).

I'd suggest @yuriy0 takes this up to GHC developers.

**Comment by Blaisorblade** [comment] 2016-06-19 09:35
BTW, that code was introduced in https://github.com/ghc/ghc/commit/8c8e959fdf86281c01e3392a3860ab64524d37df. To sum up:
it seems possible those calls to `timeBeginPeriod` on Windows prevent laptop CPUs from saving power, as removed by @yuriy0 in this issue a while ago.

**Comment by UlfNorell** [comment] 2018-05-28 15:15
Given that there's really nothing we can do about this and the fact that later versions of Windows (maybe) doesn't have this problem I'm closing this.

**Closed as completed by UlfNorell** 2018-05-28 15:15 UTC
Labels: platform: windows
