### ISSUE TITLE
Type checking does not take instances properly when defining a record term

### ISSUE THREAD

**Issue by L-TChen** [agda/agda#5687] opened 2021-12-07 09:20 UTC
Type checking does not seem to take instances into account during type-checking a field in a record type properly in the following example.

```agda
open import Agda.Primitive
open import Agda.Builtin.Equality
open import Agda.Builtin.List

private variable
  a : Level
  A B : Set a

record Functor (F : Set a → Set a) : Set (lsuc a) where 
  field
    fmap : (A → B) → F A → F B
open Functor ⦃...⦄ public 

record FunctorLaw (F : Set a → Set a) : Set (lsuc a) where
  field
    overlap ⦃ super ⦄ : Functor F
    fmap-id  : (x : F A) → fmap {_} {F} ⦃ super ⦄ (λ x → x) x ≡ x
open FunctorLaw ⦃ ... ⦄ public

instance
  FunctorList : Functor {a} List
  fmap ⦃ FunctorList ⦄ f []       = []
  fmap ⦃ FunctorList ⦄ f (x ∷ xs) = f x ∷ fmap f xs

FunctorLawList : FunctorLaw {a} List
fmap-id ⦃ FunctorLawList ⦄ []       = {! refl !} -- (1)
fmap-id ⦃ FunctorLawList ⦄ (x ∷ xs) = {!!}
```

If I press `C-u C-u C-c C-,` in the hole (1), then it shows `Goal: [] ≡ []` and I can refine it with `refl` by `C-c C-r`. However, by reloading, Agda complains that 
```agda
Functor.fmap (FunctorLaw.super FunctorLawList) (λ x → x) [] != []
of type List A
when checking that the expression refl has type
Functor.fmap (FunctorLaw.super FunctorLawList) (λ x → x) [] ≡ []
```
where the LHS should be reduced to get the judgemental equality `[] = []`.

P.S. Please change the subject line if you have a better way to describe the problem. Thanks.

**Comment by jespercockx** [comment] 2021-12-07 09:43
This looks to me like it is a duplicate of https://github.com/agda/agda/issues/2557 (which I *really* need to get around to fixing, but...)

**Comment by jespercockx** [comment] 2021-12-07 09:45
To confirm, could you try to give the `.super` field explicitly in the definition of `fmap-id` and see if it works then?

**Comment by L-TChen** [comment] 2021-12-08 06:23
Yes, it works if `⦃ super ⦄` is given explicitly using copattern. That is, 
```agda
instance
  FunctorLawList : FunctorLaw  {a} List
  super   ⦃ FunctorLawList ⦄ = FunctorList
  fmap-id ⦃ FunctorLawList ⦄ []       = refl
  fmap-id ⦃ FunctorLawList ⦄ (x ∷ xs) = {!cong (x ∷_)!}
```
does work. But, the following without using copattern also works
```agda
instance
  FunctorLawList : FunctorLaw  {a} List
  FunctorLawList = record
    { fmap-id = λ where
        []       → refl
        (x ∷ xs) → {!!}
    }
```

I am more confused now.

**Comment by jespercockx** [comment] 2021-12-08 09:15
`record` expressions use a different algorithm for inserting the implicit/instance fields than definitions by copattern matching. The problem is that the one for copatterns inserts the clause *too late* so you are already getting a type error before it is inserted.

I'm closing this issue now, please continue in #2557 if there's more.

**Closed as duplicate by jespercockx** 2021-12-08 09:15 UTC
Labels: status: duplicate, type: bug, instance

**Comment by L-TChen** [comment] 2021-12-08 09:29
Right, that makes sense. Thanks.
