### ISSUE TITLE
refine fails for records with >9 fields and explicit constructor

### ISSUE THREAD

**Issue by JLimperg** [agda/agda#4058] opened 2019-09-05 13:51 UTC
Here's a fun one. ;) Test case:

```agda
record R : Set₁ where
  constructor R+
  field
    f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 : Set

r : R
r = {!!}
```

Trying to `refine` the hole yields 'Cannot refine'. With one less field or without the `constructor R+`, `refine` succeeds. Tested with Agda 2.6.0.1 and master@957f54f8405c0add88391fca543a71fe14c89795.

**Comment by gallais** [comment] 2019-09-05 13:55
Duplicate of #3532

**Closed as completed** 2019-09-05 13:55 UTC
Labels: status: duplicate
