### ISSUE TITLE
Don't put highlighting for imported warnings in current buffer

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4019] opened 2019-08-20 19:51 UTC
When I open a file that has already an .agdai file, like opening `test/Succeed/ImportWarnings.agda`, it puts highlighting stemming from the ranges of warnings in the imported files onto the current file.

This looks as in the attached screenshot.
<img width="522" alt="Screenshot 2019-08-20 at 21 50 11" src="https://user-images.githubusercontent.com/1155218/63379425-9726f680-c394-11e9-9d35-696ad21f5dc5.png">

**Comment by fredrikNordvallForsberg** [comment] 2020-05-26 14:50
I cannot reproduce this; might have been fixed by https://github.com/agda/agda/commit/7018c303a9363c2622383a1206c2a7191069c496?

**Closed as completed by fredrikNordvallForsberg** 2020-05-26 14:50 UTC
Labels: type: bug, ux: emacs, ux: highlighting, status: already-fixed, ux: warnings

**Comment by andreasabel** [comment] 2020-05-26 15:26
I haven't seen the faulty behavior in a long time either.  Seems to be fine.
