### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by nad** [agda/agda#4040] opened 2019-08-28 12:04 UTC
One part of one of my developments type checks about 30% slower using Agda 2.6.1-037b495 compared to Agda 2.6.0.1 (both built using GHC 8.4.4).

**Comment by nad** [comment] 2019-08-28 19:32
Bisection points to 3f9d17fb13cc122cc91d1e1e47cb8c0d185b177e ("[ fix #3774 ] Use the right context for eta-expanding metas"). The [test case](https://github.com/agda/agda/files/3552529/Benchmark.agda.txt) I used type-checked roughly 50% slower after this commit compared to just before.

The commit apparently fixes a bug. Perhaps Agda used to be faster because it was "cheating", or perhaps we can learn something from this regression. I don't know.

**Comment by jespercockx** [comment] 2019-09-20 07:25
It seems the problem is caused by bad performance of `addContext`. We should revisit this issue once #4044 is fixed.

**Comment by nad** [comment] 2019-09-25 18:01
I tried to comment out the [problematic lines in `addCtx`](https://github.com/agda/agda/issues/4044#issuecomment-527126084), and with that change the difference in performance between 2.6.1-6df563c and 2.6.1-3f9d17f seems to be small for the test case mentioned above. (I used GHC 8.4.4 for the test.)

**Comment by nad** [comment] 2019-09-27 09:43
Oops, I should have compared 3f9d17fb13cc122cc91d1e1e47cb8c0d185b177e and 941d94b59aa77f88097136828614257560c466ff… I'll rerun the tests.

**Comment by nad** [comment] 2019-09-27 10:36
2.6.1-3f9d17f seems to be about 17 % slower than 2.6.1-941d94b (for the same test as above, with the lines commented out). Thus it seems as if some of the slowdown can be explained by the problem discussed in #4044, but not all of it.

**Comment by jespercockx** [comment] 2019-10-07 12:11
I pushed a fix for #4044, could you please try again to see how large the difference is now?

**Comment by nad** [comment] 2019-10-08 12:18
2.6.1-4c04c65 seems to be about 8 % slower than 2.6.0.1 (for the same test as above).

**Comment by UlfNorell** [comment] 2019-11-28 11:50
8% seems acceptable to me.

**Closed as completed by UlfNorell** 2019-11-28 11:50 UTC
Labels: performance, regression on master
