### ISSUE TITLE
New handling of module parameters breaks size solving

### ISSUE THREAD

**Issue by nad** [agda/agda#2046] opened 2016-06-16 14:43 UTC
The following code, which is accepted by Agda 2.5.1, is rejected by the current development version:

``` agda
open import Agda.Builtin.Size using (Size; Size<_)

data _×_ (A B : Set) : Set where
  _,_ : A → B → A × B

record Always {A : Set} (P : A → Set) : Set where
  field
    always : ∀ x → P x

postulate
  A : Set

module M (P : A → Set) where

  record R₁ (i : Size) (x : A) : Set where
    coinductive
    field
      force : {j : Size< i} → R₁ j x

  record R₂ (i : Size) (x : A) : Set where
    inductive
    constructor ⟨_,_⟩
    field
      f₁ : P x
      f₂ : P x → R₁ i x

data P : A → Set where
  c : (x : A) → P x → P x

postulate
  p : (x : A) → P x
  a : (i : Size) → Always (M.R₁ P i)

module _ (Unused : Set) where

  open M P

  rejected : ∀ i x → R₂ i x
  rejected i x =
    ⟨ p x
    , (λ { (c _ _) → Always.always (a _) x})
    ⟩
```

Error message:

```
i !=< Unused of type Size
when checking that the expression Always.always (a _) x has type
R₁ i x
```

Note that `i` and `Unused` do not even have the same type.

The code is accepted if the unused argument `Unused` is removed from the final module's telescope.

Bisection suggests that the bug was introduced by @UlfNorell in the commit "[ refine param ] allow module parameters to be refined by pattern matching" (943e9bee0a1fc58575b8e292e28d03c0ba98bbc8).

**Comment by andreasabel** [comment] 2016-06-16 16:16
The code is also accepted if sized types are not used, instead the fake types

``` agda

data Size : Set where

Size<_ : Size → Set
Size< i = Size
```

This confirms that there is a bad interaction between sized types and Ulf's new parameter refinement feature.

**Comment by andreasabel** [comment] 2016-06-16 16:20
It also works if the extended lambda is replaced by an auxiliary function:

``` agda

  test : ∀ i x → R₂ i x
  test i x = ⟨ p x , aux ⟩
    where
    aux : P x → R₁ i x
    aux (c _ _) = Always.always (a _) x
```

**Comment by UlfNorell** [comment] 2016-06-26 16:03
It looks like the size constraint solver is doing something wrong. With `-v tc.size.solve:20 -v tc.conv.size:10`:

```
Comparing sizes
  i =< _42 x Unused i .x
solution  _42  :=  Unused
```

Note that the invariant that module parameters are the first arguments to metas, which held in `2.5.1`, is violated for `_42`. Reassigning to @andreasabel since it seems clear that the size solver is misbehaving regardless of any bugs I might have introduced.

**Comment by andreasabel** [comment] 2016-07-06 13:48
`Agda.TypeChecking.SizedTypes.Solve` relied on an invariant that is violated now:

``` haskell
  -- We rely on the fact that contexts are only extended...
  -- Just take the longest context.
  let HypSizeConstraint gamma hids hs _ = maximumBy (compare `on` (length . sizeContext)) cs
  -- Length of longest context.
  let n = size gamma
  -- Now convert all size constraints to the largest context.
      csL = for cs $ \ (HypSizeConstraint cxt _ _ c) -> raise (n - size cxt) c
```

With the effect:

```
Solving constraint cluster
i ≤ _i_43 Unused i x
_i_43 Unused i x ≤ _47 x Unused i .x
Canonicalized constraints
Unused ≤ _i_43 x Unused i
_i_43 Unused i x ≤ _47 x Unused i .x
solution  _i_43  :=  Unused
```

**Comment by andreasabel** [comment] 2016-07-06 14:31
However, if printed with arguments, the solution for `_i_43` does not look bad:

```
solution  _i_43 x Unused i  :=  Unused
  xs = [3,2,1]
  u  = Var 2 []
```

It is, correctly, the second projection.

```
solution  _47 x Unused i z  :=  Unused
  xs = [3,2,1,0]
  u  = Var 2 []
```

Only the one for `_47`, that should be the lowered solution for `_i_43` not the same.
It should be the third projection, not the second.

**Comment by andreasabel** [comment] 2016-07-06 15:04
We start out with

```
Unused, i, x |- @1 <= _i_43 @2 @1 @0
x, Unused, i, z |- _i_43 @2 @1 @3 <= _47 @1 @3 @2 @0
```

The violated invariant leads to metas applied to their arguments in permuted order.  The size solver assumes the order is always the same.  There is already code to fix this, namely `canonicalizeConstraint`.  But it triggers issue #1914, thus, it is commented out.  So the actual issue is to fix #1914 (and finally settle WW1).

**Comment by nad** [comment] 2016-08-16 08:08
> So the actual issue is to fix #1914 (and finally settle WW1).

#1914 is closed, and has been closed since before you wrote the comment above.

**Comment by andreasabel** [comment] 2016-09-27 13:01
Brief discussion with Ulf: Look at the module parameter substitutions associated with the constraints (see `envCurrentModule . clEnv`) and see if you can fix the constraint contexts.

**Comment by andreasabel** [comment] 2016-12-12 18:02
The module parameter substitution is insufficient to solve this issue.  Instead, we now use CtxIds and variable names (shame on me) to match contexts of different constraints.  This fixes this regression, but a proper solution has still to be found.

**Comment by andreasabel** [comment] 2016-12-12 18:03
Fix is in https://github.com/agda/agda/commit/9a6128647a13b57d8a42590125af259196e9a743

**Closed as completed** 2016-12-12 18:03 UTC
Labels: type: bug, modules, sized types, extended lambdas, regression on master, parameter-refinement
