### ISSUE TITLE
Regression: Rewrite rule involving constructors rejected in parametrized module

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3538] opened 2019-02-02 09:00 UTC
The rewrite rule below is accepted in Agda-2.5.4.2:
```agda
{-# OPTIONS --rewriting #-}

open import Agda.Builtin.Equality
{-# BUILTIN REWRITE _≡_ #-}

module _ (Form : Set) where  -- FAILS
-- postulate Form : Set -- WORKS

data Cxt : Set where
  ε : Cxt
  _∙_ : (Γ : Cxt) (A : Form) → Cxt

data _≤_ : (Γ Δ : Cxt) → Set where
  id≤ : ∀{Γ} → Γ ≤ Γ
  weak : ∀{A Γ Δ} (τ : Γ ≤ Δ) → (Γ ∙ A) ≤ Δ
  lift : ∀{A Γ Δ} (τ : Γ ≤ Δ) → (Γ ∙ A) ≤ (Δ ∙ A)

postulate lift-id≤ : ∀{Γ A} → lift id≤ ≡ id≤ {Γ ∙ A}
{-# REWRITE lift-id≤ #-}
```
It is also fine if the module parameter `Form` is removed in favor of a postulate.

**Comment by jespercockx** [comment] 2019-02-11 13:48
The problem is that inside a parametrized module, parameters are considered as 'rigid symbols' for the purpose of rewriting, i.e. they have to match exactly for the rewrite rule to fire. However, as constructors don't store their parameters, it is impossible to check whether the parameter actually has the right value. A workaround is to declare the rewrite rule outside of the parametrized module.

I'm anyway not sure whether rewriting on constructors is something we really want to support. It is not very hard to break type safety with them, even if you restrict to homogeneous rewrite rules:
```agda
{-# OPTIONS --rewriting #-}

open import Agda.Builtin.Bool
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

{-# BUILTIN REWRITE _≡_ #-}

data D : Set₁ where
  c : Set → D

unD : D → Set
unD (c X) = X

id : unD (c (Nat → Nat))
id x = x

postulate rew : c (Nat → Nat) ≡ c (Nat → Bool)
{-# REWRITE rew #-}

0' : Bool
0' = id 0
```
(note also that the type of `rew` is not inconsistent)

**Comment by jespercockx** [comment] 2019-02-12 08:54
See also the discussion in https://github.com/agda/agda/issues/3211 where this behaviour was introduced after @nad raised concerns about my (unsafe) fix.

**Comment by jespercockx** [comment] 2019-02-13 15:37
Closing as working-as-intended.

**Comment by andreasabel** [comment] 2019-03-16 03:07
I do not agree that this is working as intended.

I do not understand why the parameters are not fully general, module parameter `Base` looks fully general to me:
```
lift-id≤  is not a legal rewrite rule, since the constructor parameters are not fully general:
  Constructor:  lift
  Parameters:  [Base]
when checking the pragma REWRITE lift-id≤
```

**Comment by jespercockx** [comment] 2019-06-05 14:05
Note that this works when you add the rewrite rule *outside* of the parametrized module:
```agda
{-# OPTIONS --rewriting #-}

open import Agda.Builtin.Equality
{-# BUILTIN REWRITE _≡_ #-}

module _ where

module _ (Form : Set) where  -- FAILS

  data Cxt : Set where
    ε : Cxt
    _∙_ : (Γ : Cxt) (A : Form) → Cxt

  data _≤_ : (Γ Δ : Cxt) → Set where
    id≤ : ∀{Γ} → Γ ≤ Γ
    weak : ∀{A Γ Δ} (τ : Γ ≤ Δ) → (Γ ∙ A) ≤ Δ
    lift : ∀{A Γ Δ} (τ : Γ ≤ Δ) → (Γ ∙ A) ≤ (Δ ∙ A)

  postulate lift-id≤ : ∀{Γ A} → lift id≤ ≡ id≤ {Γ ∙ A}

{-# REWRITE lift-id≤ #-}
```

**Closed as completed** 2020-06-17 14:41 UTC
Labels: rewriting, regression in 2.6.0
