### ISSUE TITLE
Shadowed identifiers should be preceded by a dot when printed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#572] opened 2015-08-08 18:00 UTC
```agda
postulate P : Set -> Set

test : (B : Set) -> P B -> P B
test = λ p p -> {!!}
```
When doing C-c C-. one gets:
```
Goal: P p
————————
p : P p
p : Set
```
The shadowed p should be printed as .p to get
```
Goal : P .p
p : P .p
.p : Set
```
But what about doubly-shadowed identifiers?  ..p ...p ....p ?

Original issue reported on code.google.com by `andreas....@gmail.com` on 21 Feb 2012 at 4:22

**Comment by jespercockx** [comment] 2018-11-14 15:02
I think a better solution would be to apply the standard renaming scheme and rename one of the two variables to `p1` (not entirely sure which one would be the best candidate for renaming).

**Comment by nad** [comment] 2018-11-14 15:43
And mark it as being out of scope, as discussed in #3127?

**Comment by jespercockx** [comment] 2018-12-06 14:40
I have a plan that will fix both this and #3127. In the example from the OP, it would rename the existing variable when adding the new `p` to the context, so you would see the following:
```
Goal: P p
————————
p : P p₁
p₁ : Set
```

**Comment by nad** [comment] 2018-12-07 11:13
I think the fresh name should also be marked as being out of scope.

**Comment by jespercockx** [comment] 2018-12-09 23:39
With #3446, the goal looks as follows:
```
Goal: P p₁
————————————————————————————————————————————————————————————
p      : P p₁
p = p₁ : Set  (not in scope)
```

**Comment by nad** [comment] 2018-12-10 08:43
Looks good to me.

**Comment by jespercockx** [comment] 2018-12-10 09:22
We should also make it visible somehow to the user that a top-level name is shadowed by a local variable. For example:
```agda
postulate A : Set

test₂ : Set → A
test₂ A = {!!}
```
currently shows the goal as follows:
```
Goal: A
————————————————————————————————————————————————————————————
A : Set
```
which is not good.

**Comment by jespercockx** [comment] 2018-12-10 12:20
I changed the printer so it prints the qualified name for shadowed definitions, for example:
```
Goal: Issue572.A
————————————————————————————————————————————————————————————
A : Set
```

**Closed as completed** 2018-12-10 13:29 UTC
Labels: type: enhancement, ux: printing, shadowing

**Comment by Saizan** [comment] 2019-03-25 15:51
@jespercockx Would it make sense to move the ```ConcreteNames``` and ```ShadowingNames``` maps to ```TCEnv``` so that they stay in sync with the ```Context```? It would help wrt ```build/enterClosure```.

**Comment by jespercockx** [comment] 2019-03-25 16:59
Well the point of putting them in the `TCState` is exactly because they must survive after exiting from an `addContext`, so putting them in the `TCEnv` would defeat the purpose. Can you explain what is the problem you're trying to solve?

**Comment by Saizan** [comment] 2019-03-25 20:22
Ok, I guess I was making wrong assumptions about how this is supposed to work. (Is it written somewhere?)

Anyhow I'm getting shadowing problems for constrains generated by HITs

```agda
data Grpd : Set where
  trunc : (x₄ y₂ : Grpd) (x₅ y₃ : x₄ ≡ y₂) (x₆ y₄ : x₅ ≡ y₃) → x₆ ≡ y₄

test2 : Grpd → Grpd
test2 (trunc a b c d e f i j k) = { }0
```

The code above generates 6 constrains for ```?0```, the last two get printed as

```agda
  test2 (x₆ i₁ i₁)
    = ?0 (a = x) (b = x₁) (c = x₅) (d = y₃) (e = x₆) (f = y₄) (i = i0)
      (j = i₁) (k = i₁)
    : Grpd
  test2 (y₄ i₁ i₁)
    = ?0 (a = x) (b = x₁) (c = x₅) (d = y₃) (e = x₆) (f = y₄) (i = i1)
      (j = i₁) (k = i₁)
    : Grpd
```

while I'm pretty confident that, e.g., the two ```i₁``` in ```test2 (x₆ i₁ i₁)``` are different variables.

Also because the following typechecks

```agda
test3 : Grpd → Grpd
test3 (trunc a b c d e f i j k) = trunc _ _ _ _ (\ i j → test3 (e i j)) (\ i j → test3 (f i j)) i j k
```

**Comment by jespercockx** [comment] 2019-03-26 09:39
Unfortunately I haven't written anything about the new handling of shadowing, no. The implementation relies on a fair dose of magic (or its closest equivalent, mutable state). Below is a (probably not very successful) attempt at explaining how it works.

The idea is that we keep track of which variables are added in which order to the context during typechecking (using addContext), in order to later come up with better names for them. For example, we don't want to pick `x` for the name of a hidden (system-generated) variable if another variable named `x` by the user shadows it. Likewise, if the user gave *two* variables the same name `x` then we must rename the one that is shadowed into something else (it's fine to rename it because the user can anyway not refer to it anymore). This information about which (abstract) names could potentially shadow other (abstract) names is stored in the `ShadowingNames`. But then there's another problem that we don't want to change how we print a given abstract name after we already showed it to the user, which is why we keep track of the concrete name associated to abstract names in the `ConcreteNames` map. Except that in the situation where the *user* explicitly shadows a name, we must rename it even if we already printed it. So we keep for each abstract name not just one concrete name, but a *list* of concrete names which are tried in order until one is found that is not shadowed by a user-written name.

I'm not sure what's going on in your example, but maybe you're never using `addContext` (or similar function) to add all the variables to the context, thus circumventing the shadowing machinery? The relevant magic is happening at https://github.com/agda/agda/blob/87fb8278650472a3c9d93badd7888ced15b51240/src/full/Agda/TypeChecking/Monad/Context.hs#L151-L155, you could try to add some debug output to see if that part of the code is actually run for the variables in your example.

**Comment by Saizan** [comment] 2019-03-26 10:00
I think part of my problem is that through ```build/enterClosure``` the ```ScopeInfo``` gets out of sync. But still it's weird that only interval variables seem affected by this.

**Comment by Saizan** [comment] 2019-04-02 14:46
Ok, so I think the problem is triggered when ```takenVarNames``` in the ```AbsToCon``` environment has some names that are not covered by ```ScopeInfo``` but they do have entries in ```stConcreteNames``` that would shadow each other.

It seems what's going wrong is that ```toConcreteName``` will happily use a name from ```stConcreteNames``` even if it shadow another name used for a "takenVar" as long as it doesn't shadow something from ```ScopeInfo```.

```chooseName``` correctly avoids any name that could be used for a ```takenVar```, but the loop in ```toConcreteName``` doesn't get to that point in this scenario.

Maybe the shadowing check in ```toConcreteName``` needs to be more clever?

**Comment by jespercockx** [comment] 2019-04-02 15:01
How are you ending up in a situation where the `takenVarNames` contains names that are not in the `currentScope`? That should ordinarily not be possible (or some internal invariant is broken). Are you not using `addBinding` to add variables to the scope during printing?

**Comment by Saizan** [comment] 2019-04-02 15:14
Doesn't the documentation for ```Env``` explicitly allow for vars in ```takenVarNames``` that are not in ```ScopeInfo```?

```agda
data Env = Env { takenVarNames :: Set A.Name
                  -- ^ Abstract names currently in scope. Unlike the                                                                                                                   
                  --   ScopeInfo, this includes names for hidden                                                                                                                       
                  --   arguments inserted by the system.               
```

Anyway, I'm not writing any ```AbsToCon``` code, this is just constraints getting stored as a closure and then printed.

**Comment by Saizan** [comment] 2019-04-02 16:57
Here's another example, this time the problem shows up when printing goal types.


```agda
open import Agda.Builtin.Sigma
open import Agda.Builtin.Equality

postulate
  A : Set
  B : A → Set
  a : A

Pi : (A → Set) → Set
Pi B = {x : A} → B x

foo : Pi \ y →  Σ (B y) \ _ → Pi \ z → Σ (y ≡ a → B z) \ _ → B y → B z → A
foo = { }0 , (\ { refl → { }1 }) , { }2
```

The goal type for ```?2``` then gets printed with both variables as ```x```:

```agda
?0 : B x
?1 : B x
?2 : B x → B x → A
```

**Comment by jespercockx** [comment] 2019-04-03 08:24
I'll open a new issue for that.
