### ISSUE TITLE
Internal error when trying to prove things about lengths of lists

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#1816] opened 2016-02-04 12:59 UTC
When trying to compile the following (leaving aside that the theorem itself is false):

``` agda
open import Data.Nat using (_≤_) 
open import Data.List using (List; []; _∷_; filter; length)
open import Data.List.Any as Any using ()
open import Relation.Binary

open import Relation.Nullary.Negation using (contradiction)

module Proof.Test {c ℓ} (setoid : Setoid c ℓ) where

  open Any.Membership (setoid) using (_⊆_)

  -- Length
  ⊆-length : ∀ (xs ys : List (Setoid.Carrier setoid)) → xs ⊆ ys → length xs ≤ length ys
  ⊆-length []     []          xs⊆ys = ?
  ⊆-length []     (y ∷ ys)    xs⊆ys = ?
  ⊆-length (x ∷ xs) []        xs⊆ys = contradiction ? ?
  ⊆-length (x ∷ xs) (y ∷ ys)  xs⊆ys = ?
```

Agda reports:

> An internal error has occurred. Please report this as a bug.
> Location of the error: src/full/Agda/TypeChecking/Records.hs:216

However if you either 
1.  change `open import Relation.Binary` to `open import Relation.Binary using (Setoid)`
2.  change `⊆-length (x ∷ xs) []        xs⊆ys = contradiction ? ?` to `⊆-length (x ∷ xs) []        xs⊆ys = ?`

the error disappears.

**Comment by asr** [comment] 2016-02-04 13:30
Agda version?

**Comment by MatthewDaggitt** [comment] 2016-02-04 14:00
Version 2.3.2.2

**Comment by asr** [comment] 2016-02-04 14:21
You are using an old version of Agda. I couldn't reproduce the internal error using Agda 2.4.2.5, so I'm closing the issue.

**Closed as completed by asr** 2016-02-04 14:21 UTC

**Comment by MatthewDaggitt** [comment] 2016-02-04 17:17
Ah okay, apologies. I'll update my version.
