### ISSUE TITLE
More illtyped meta solutions

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2791] opened 2017-10-05 13:19 UTC
Related to #2709. Here we get `?Y : Nat := true`.

```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Bool
open import Agda.Builtin.Equality

IF : Bool → Set → Set → Set
IF true  X Y = X
IF false X Y = Y

postulate
  F : (A : Set) (x : A) (B : Set) (y : B) → Set

mutual
  ?b : Bool
  ?b = _

  IFb = IF ?b Nat Bool

  ?X : IFb
  ?X = _

  ?Y : Nat
  ?Y = _

  foo : F Bool true Nat ?Y ≡ F IFb ?X IFb ?X
  foo = refl

-- ?Y gets solved with 'true'
error : ?Y + 1 ≡ 3
error = refl
```

**Comment by nad** [comment] 2017-10-05 16:41
Does this give us a new opportunity to prove that the empty type is inhabited?

**Comment by UlfNorell** [comment] 2017-10-05 16:43
No, you can only have illtyped terms if there are unsolved inconsistent constraints.

**Comment by vlopezj** [comment] 2018-08-10 14:06
@UlfNorell This seems to be fixed now:

![deepinscreenshot_select-area_20180810160410](https://user-images.githubusercontent.com/1593773/43962103-17f9df80-9cb7-11e8-9de8-b7099a028b09.png)

Agda version 2.5.5-fe99851

**Comment by andreasabel** [comment] 2018-08-11 06:11
I pushed the test case. @UlfNorell, please close this issue if things work as intended.

**Closed as completed** 2018-11-15 08:09 UTC
Labels: type: bug, meta, conversion, constraints
