### ISSUE TITLE
Record declarations cannot contain data type declarations

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1570] opened 2015-08-08 18:19 UTC
```
The pattern...

record R₂ : Set₁ where
  field 
    A : Set
  data B : Set where
    a : A → B
  field 
    C : B → Set

...is invalid, throwing:

Not a valid let-declaration
when scope checking 

    let mutual 
    data B : Set
    data B where
    a : A → B
    in (C : Set) → Set₀

However, the pattern below, which to me has exactly the same effect, is valid:

module _ where
  private 
    module B (A : Set) where
      data B : Set where
        a : A → B
  record R₁ : Set₁ where
    field
      A : Set
    open B A public
    field
      C : B → Set 
```

Original issue reported on code.google.com by `Pepijn.K...@gmail.com` on 15 Jun 2015 at 9:09

**Comment by UlfNorell** [comment] 2018-05-28 12:57
Duplicate of #434.

**Closed as completed by UlfNorell** 2018-05-28 12:57 UTC
Labels: status: duplicate, type: enhancement, let, records
