### ISSUE TITLE
Investigate highlighting failures

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5204] opened 2021-02-13 07:43 UTC
I experienced yesterday that jump-to-definition doesn't work in the same file even if type-checking succeeded.  This should be looked at before the release.
TODO: MWE.

**Comment by jespercockx** [comment] 2021-05-08 12:34
@andreasabel Since you didn't post a concrete issue, I'm going to close this. Please reopen if you have a reproducible test case.

**Closed as completed by jespercockx** 2021-05-08 12:34 UTC
Labels: status: info-needed, type: bug, ux: highlighting
