### ISSUE TITLE
Expand function goals to extended lambda syntax.

### ISSUE THREAD

**Issue by capn-freako** [agda/agda#4875] opened 2020-08-27 00:54 UTC
Currently, when initially expanding a goal that is a function, using `C-c C-r`, `agda2-mode` expands to:

    \ x -> { }1

(i.e. - _simple_ lambda syntax).

However, the interactive goal solving assistant seems to be more capable and powerful when _extended_ lambda syntax is used:

    \{ x -> { }1 }

So, could we change the behavior to expand a function goal to _extended_ lambda syntax when the user hits `C-c C-r`?

**Comment by gallais** [comment] 2020-08-27 08:04
I think I would prefer using a cheap lambda by default but also
allowing users to case-split on `x` in which case Agda should
automatically turn the lambda into a pattern-matching one.

**Comment by nad** [comment] 2020-08-27 09:59
In some cases you have a choice between different kinds of pattern matching:
```agda
open import Agda.Builtin.Equality

record R : Set where
  no-eta-equality
  pattern
  constructor c

works : _≡_ {A = R → R} (λ (c) → c) (λ (c) → c)
works = refl

fails : _≡_ {A = R → R} (λ { c → c }) (λ { c → c })
fails = refl

f : R → R
f = λ (c) → c

works₂ : ∀ x → f x ≡ x
works₂ = λ { c → refl }

fails₂ : ∀ x → f x ≡ x
fails₂ = λ (c) → refl
```

**Comment by jespercockx** [comment] 2022-08-26 18:37
Duplicate of #4315

**Closed as not planned by jespercockx** 2022-08-26 18:37 UTC
Labels: status: duplicate, type: enhancement, extended lambdas, ux: interaction, record-lambda
