### ISSUE TITLE
Pattern matching on no-eta record bug?

### ISSUE THREAD

**Issue by martinescardo** [agda/agda#5697] opened 2021-12-14 08:47 UTC
A record in a `where` clause of a definition has eta disabled:
```agda
module self-contained (X : Set) where

f : X → X
f x = h (c x)
 where
  record r : Set where
    constructor
     c
    field
     a : X

  h : r → X
  h (c a) = a

-- The above definition of h gives "Pattern matching on no-eta record of type r.

-- But the following works:

record r : Set where
  constructor
   c
  field
   a : X

g : X → X
g x = h (c x)
 where
  h : r → X
  h (c a) = a
```
For further discussion see https://agda.zulipchat.com/#narrow/stream/238741-general/topic/Pattern.20matching.20on.20no-eta.20record.20bug.3F

**Comment by andreasabel** [comment] 2021-12-15 12:01
The problem here is that the positivity checker sees some mutuality (`X` mutual with`r`?) and thus eta is switched off for `r`.  Solutions are to either label the `record` with
- `eta-equality`
- or `pattern`, to enable pattern-matching on the constructor (as opposed to allow co-pattern matching on the field).  

In the latter case, you have a record type with `no-eta-equality`. 


Btw, highlighting seems broken in 2.6.2:
![Screenshot 2021-12-15 at 11 42 26](https://user-images.githubusercontent.com/1155218/146172419-436223f7-a100-4dac-ae9e-603472343a4f.png)

**Comment by martinescardo** [comment] 2021-12-15 12:41
Thanks. (But isn't `X` an assumption rather than something being defined? In which case it doesn't make sense for it to be mutual with `r`.)

**Comment by andreasabel** [comment] 2021-12-15 14:54
Actually, my vage explanation was wrong.
What is going on (I think) is that because `r` is mutual with `h`, the clauses for `h` are checked before eta-equality is confirmed for `r`. Thus, when checking pattern `c`, Agda complains.  Only after `h` is defined, the positivity checker runs on `r` and `h` and confirms everything is ok.  But, too late...

**Comment by martinescardo** [comment] 2021-12-15 15:26
Makes sense. But why does this happen *only* when a record is defined inside a `where` clause? Outside a where clause we never have this problem.

**Comment by andreasabel** [comment] 2021-12-15 15:35
You get the same problem in a plain mutual block.  Inside `where`, you are automatically in a mutual block.
```agda
mutual
  record r : Set where
    constructor
     c
    field
     a : X

  h : r → X
  h (c a) = a
```
Same error here.

**Comment by martinescardo** [comment] 2021-12-15 15:40
I see. I didn't know that inside `where` we are always in a mutual block.

**Comment by jespercockx** [comment] 2022-08-25 14:35
It's not clear what we can do here to improve the current situation, so I'm closing this issue.

**Closed as not planned by jespercockx** 2022-08-25 14:35 UTC
Labels: positivity, eta, records, mutual, workaround exists
