### ISSUE TITLE
Compilation of Parser.y depends on the locale on Debian too

### ISSUE THREAD

**Issue by edrx** [agda/agda#5465] opened 2021-07-02 17:21 UTC
The latest version of the Agda Manual from

https://readthedocs.org/projects/agda/downloads/pdf/latest/

mentions a certain error as something that can only happen on M$ Windows. It says:

```
Warning: If you are installing Agda using Cabal on Windows,
depending on your system locale setting, cabal install Agda may fail
with an error message:

hGetContents: invalid argument (invalid byte sequence)

If this happens, you can try changing the console code page to UTF-8
using the command:

CHCP 65001
```

I'm on Debian stable and I got something similar. I tried to install Agda with

```
cabal update
cabal install Agda
```

and it failed with:

```
happy: src/full/Agda/Syntax/Parser/Parser.y: hGetContents: invalid
argument (invalid byte sequence)
cabal: Failed to build Agda-2.6.2. See the build log above for
details.
```

My default value for $LC_ALL is "C" and the only uncommented line in my /etc/locale.gen is this one:

```
en_GB.UTF-8 UTF-8
```

If I run this

```
export LC_ALL=en_GB.UTF-8
cabal install Agda
```

instead of just "cabal install Agda" the compilation succeeds.

This is a copy of this bug report that I sent to the mailing list:

https://lists.chalmers.se/pipermail/agda/2021/012689.html

**Comment by andreasabel** [comment] 2021-07-14 18:29
The problem is upstream: https://github.com/simonmar/happy/issues/157.

**Comment by andreasabel** [comment] 2021-07-16 05:56
In `head.hackage` this is fixed by simply avoiding unicode characters in `Parser.y`:
https://gitlab.haskell.org/ghc/head.hackage/-/commit/6d0a6c46777414b3f85c59f7c2525bb07348b3ae

**Closed as completed** 2021-07-17 18:39 UTC
Labels: type: bug, ux: installation, happy, upstream
