### ISSUE TITLE
Remove "--experimental" from "--experimental-lossy-unification"

### ISSUE THREAD

**Issue by WolframKahl** [agda/agda#1625] opened 2015-08-13 03:45 UTC
In the [AContext-2.1 Agda sources](http://relmics.mcmaster.ca/RATH-Agda/AContext-2.1.tar.gz)
(available under GPL, linked from [the RATH-Agda page](http://relmics.mcmaster.ca/RATH-Agda/#AContext-2.1)),
there are two modules `Categoric.OCC.CSL.ToFromAContext` and `Categoric.OCC.CSL.FromToAContext`
which each only consist of imports and three lines of the shape:

```
ComposedFunctorName : Functor CatX CatX
ComposedFunctorName = Functor1 functorCompose Functor2

module ComposedFunctorName = Functor ComposedFunctorName
```

Typechecking these is slower than typechecking the whole development these depend on,
and the time is spent on the second line --- commenting out the first and the third line
does not change the typechecking time significantly.
Since the functors in question have previously been typechecked as going from `CatX` to `CatY` respectively vice versa, it is not intuitive that this should take any time at all...

There are more unreasonably slow modules in that package, with more detailed information about the slowness on page 184 of [the accompanying PDF literate document](http://relmics.mcmaster.ca/RATH-Agda/AContext-2.1.pdf). The only update since writing that: For `ToFromAContextNatIso`, 52GB of heap are not sufficient (90 hours).

**Comment by Saizan** [comment] 2015-08-13 15:17
In Categoric.OCC.CSL.ToFromAContext the two functors get inferred types that do not match "on the nose" on the category in the middle, and agda is taking a lot of time to figure out whether the two are actually equal.

If you can arrange for them to be equal on the nose like you do for ACSL-OpCategory then you can probably get typechecking to be much faster, since checking that the other two endpoints match ACSL-OpCategory is pretty fast.

```
-- CSL→Ctx : Functor ACSL-OpCategory                                                                                                                           
-- (.Data.AContext.Category.ACH-Category occ leftResOp rightResOp                                                                                              
--  (.Categoric.OCC.CSL.ToAContext._.powerOp occ leftResOp rightResOp                                                                                          
--   syqOp directPower))                                                                                                                                       

-- Ctx→CSL : Functor                                                                                                                                           
-- (.Data.AContext.Category.ACH-Category occ leftResOp rightResOp                                                                                              
--  (.Categoric.OCC.CSL.FromAContext.ℙ.powerOp occ leftResOp rightResOp                                                                                        
--   syqOp directPower splitSymIdempot))                                                                                                                       
-- ACSL-OpCategory      
```

On the other hand Agda should probably get smarter about _not_ unfolding definitions so much if the resulting terms get larger?

**Comment by Saizan** [comment] 2015-08-18 12:50
The following patch which naively tries to avoid unfolding when checking equality between applications of the same function makes the example typecheck in a reasonable time, however it makes computation-heavy examples like test/interaction/Issue637.agda much slower.
Afaiu, both lean and Coq have some heuristics for when to do delta reductions, we could try to steal some of those.

```
--- a/src/full/Agda/TypeChecking/Conversion.hs
+++ b/src/full/Agda/TypeChecking/Conversion.hs
@@ -171,6 +171,15 @@ compareTerm cmp a u v = do
                              | otherwise = (assign rid y vs u, assign dir x us v)
         (MetaV x us, _) -> unlessSubtyping $ assign dir x us v `orelse` fallback
         (_, MetaV y vs) -> unlessSubtyping $ assign rid y vs u `orelse` fallback
+        (Def f [], Def f' []) | f == f' -> return ()
+        (Def f es, Def f' es') | f == f' -> unlessSubtyping $ do
+                def <- getConstInfo f
+                -- To compute the type @a@ of a projection-like @f@,
+                -- we have to infer the type of its first argument.
+                if projectionArgs (theDef def) <= 0
+                  then do pol <- getPolarity' cmp f
+                          compareElims pol (defType def) (Def f []) es es' `orelse` fallback
+                  else fallback
         _               -> fallback
   where
     assign dir x es v = do
```

**Comment by WolframKahl** [comment] 2015-10-21 22:18
Only now I got around to try this out --- I applied it to the current development version, and it works wonders! It is not slower on any of the large chunks I tried it on, and it is a lot faster on abstract theories with nested instantiations, checking quite a few things that were infeasible before.

Thanks a lot, Andrea!
[2015-10-20_AndreaVezzosi-patch.txt](https://github.com/agda/agda/files/18109/2015-10-20_AndreaVezzosi-patch.txt)

Summary of the attached typechecking timing log:

Using Andrea Vezzosi's patch from  https://github.com/agda/agda/issues/1625#issuecomment-132196576 on top of 6ede17d362450d520076e53916277eeba311dc28 --- my Agda-2.4.3.15:
- A lot faster on AContext2.
- Finishes FromToAContext2 (containing one version of the whole ContextDuality) in no time.
- With sharing a bit slower on Data.SUList.ListSetMap.FinRel.NatSumProps, but with --no-sharing essentially the same.
  In both cases still a bit faster on the whole of Main.
- A lot faster on Data.ADHG3.GSMonCat.
- --sharing is slower throughout (this is in the presence of the ``brutal fix'' for https://github.com/agda/agda/issues/1691 )
- For proving things in an instantiation of Data.ADHG3.GSMonCat with Data.Vec.Repr.DepObj (three levels of Category), this is a life-saver.

---

Agda-2.4.3.15: 6ede17d362450d520076e53916277eeba311dc28 with Andrea's patch:

```
              Alloc (MB)  Max.Res.(MB)  AllocRate     real    productivity
AContext2 (probably no zero-ary constructors) from scratch:
--no-sharing  460,058       2,178     1,126,200,262   7m56.924s   85.8%
--sharing     572,454       2,447     1,163,042,777   9m32.276s   86.1%

Categoric/OCC/CSL/FromToAContext2.lagda after AContext2:
--no-sharing   17,725       1,341       785,065,023   0m29.613s   77.4%
--sharing      26,057       1,381       854,393,457   0m40.394s   76.4%

Data/SUList/ListSetMap/FinRel/NatSumProps.lagda from scratch:
  (pulls in most of the constructor-heavy material used by Main.lagda):
--no-sharing  365,714       2,147      1,070,270,155  6m38.167s   85.9%
--sharing     371,647       2,044       908,592,705   7m43.854s   88.3%

Main.lagda from scratch:
--no-sharing  720,914       3,919     1,028,839,312  13m48.927s   84.9%
--sharing     742,319       3,719       937,780,272  15m10.234s   87.3%

Data.ADHG3.GSMonCat after Main:
--no-sharing  612,397       4,945     1,354,857,457   9m59.956s   76.0%
--sharing     701,640       3,852     1,368,009,039  11m25.875s   74.8%
```

---

Comparison numbers with Agda-2.4.3.14, 759a4dc500629270ec04c378a724a038217a439f, including the ``brutal fix'' to https://github.com/agda/agda/issues/1691:

```
AContext2 (probably no zero-ary constructors) from scratch:
--no-sharing 1,048,519      2,348    1,205,560,521  15m39.950s    92.6%
--sharing      736,966      3,257    1,204,222,374  11m31.774s    88.5%

Categoric/OCC/CSL/FromToAContext2.lagda after AContext2:
--no-sharing   infeasible
--sharing      infeasible

Data/SUList/ListSetMap/FinRel/NatSumProps.lagda:
--no-sharing   373,498      2,156   1,081,997,881    6m38.028s    86.8%
--sharing      373,730      2,046     962,428,868    7m26.366s    87.1%

Main.lagda from scratch:
--no-sharing   798,857      3,959   1,062,274,544   14m40.153s    85.8%
--sharing      825,001      3,786     981,424,079   16m06.113s    87.3%

Data.ADHG3.GSMonCat after Main:
--no-sharing 2,033,594      4,638   1,399,425,947   27m18.846s    88.7%
--sharing    1,363,971      5,069   1,364,790,162   19m15.642s    86.8%
```

**Comment by Saizan** [comment] 2015-10-27 06:47
Oh! Then we should really do this in a way that passes the test-suite.

I wonder though if we might gain the same just by changing syntactic equality so that it dereferences definitions made by opening a module as we said in Leuven.

**Comment by jespercockx** [comment] 2018-11-14 10:01
@Saizan any plans to integrate this before the next release?

**Comment by Saizan** [comment] 2018-11-14 14:21
@jespercockx it would require some careful study. So maybe best for next milestone.

Mainly we cannot just try unifying the arguments, because that could lose solutions. We could block unification while comparing the arguments but we need to verify if that would still solve the original problem.

Even then it might slow down other examples: if the expressions being compared are both ```const cheap costly``` then comparing the WHNFs is much cheaper than comparing the arguments. Maybe a strictness analysis could help though.

**Comment by WolframKahl** [comment] 2018-11-15 14:30
From extensive experience using this patch: Losing solutions only raises the problem that some metas are resolved with this patch that wouldn't be resolved without it.

Practically that means that developments done with this patch enabled may need to have underscores expanded and implicit arguments supplied for checking without this pach enabled.

However, since what is found still are solutions, I don't think that this patch is unsound in any way.

Would you consider enabling it via a command-line flag?

I haven't tried this out in a while, but there is a big development that just had no chance of being typechecked otherwise.

**Comment by jespercockx** [comment] 2018-11-15 14:34
Adding it under a flag seems like a good idea.

**Comment by tomdjong** [comment] 2020-06-04 15:08
I experimented with @Saizan's `--experimental-lossy-unification` and it works wonderfully for me. Before this flag, my code was pretty slow and when I tried to continue my development it simply became too slow for me to do anything. With the flag, I've been happily writing new proofs and continuing the development without any problems, so I'm very happy with it!

Specifically, I experimented with the file [DcpoDinfinity.lagda](https://github.com/tomdjong/TypeTopology/blob/7138bd23b961a3bb8da3457123c5c030c7a15947/source/DcpoDinfinity.lagda) in commit tomdjong/TypeTopology@7138bd2. The results of running `agda` `2.6.1` and `2.6.2-82228cd` (with and without the flag) are attached.

In short: 

- the `2.6.1` version took almost 2.5 minutes on my laptop;
- the `2.6.2-82228cd` version with `--experimental-lossy-unification` finished in under 10 seconds(!);
- the `2.6.2-82228cd` version without `--experimental-lossy-unification` took almost 6 minutes.

And there are very significant differences in memory usage.

I believe that `2.6.2-82228cd` without `--lossy-unification` is so slow, because while I was writing the file on `2.6.1`, I often had to write types precisely as Agda wanted/expected them. Otherwise, it would trigger these huge normalisations. But I guess that the newer Agda expects (slightly) different types, triggering huge normalisations again. Writing the types precisely as Agda expects them is a bit silly (for instance changing `0` to `zero` in some code) and frustrating (as it is time-consuming). Basically, the `--experimental-lossy-unification` allows me to just write the types that I think are clear without having to worry whether Agda will like it. This also means that the code is not as tightly coupled to the specific Agda version used when writing it.

As in @WolframKahl's original problem, I developed some abstract stuff and then I instantiate it with a particular concrete (and relatively complicated) example/object. The types then do not match on the nose and Agda starts normalising like crazy, reducing the complicated example/object all the way down, which is slow.

[2.6.1.txt](https://github.com/agda/agda/files/4730840/2.6.1.txt)
[2.6.2-82228cd-with-lossy-unification.txt](https://github.com/agda/agda/files/4730841/2.6.2-82228cd-with-lossy-unification.txt)
[2.6.2-82228cd-without-lossy-unification.txt](https://github.com/agda/agda/files/4730842/2.6.2-82228cd-without-lossy-unification.txt)

**Comment by nad** [comment] 2020-06-05 10:07
Note that, while `--experimental-lossy-unification` is faster in these cases, it could lead to unexpected behaviour if Agda instantiates a meta-variable with a solution that is not definitionally equal to the one you had in mind. I think Coq uses something like `--experimental-lossy-unification`, and Ziliani and Sozeau [argue](https://doi.org/10.1017/S0956796817000028) that this is more in line with what users expect (page 4), but they also argue for a predictable unification algorithm which does not postpone constraints.

**Comment by nad** [comment] 2020-06-05 10:08
If we keep the new flag, then it should be documented in the manual and in the changelog.

**Comment by martinescardo** [comment] 2020-06-12 21:00
I am trying to integrate @tomdjong 's work described above in his fork of my Agda development.

So I installed the development version of Agda and tried it on my own repository before any attempt to integrate. I want to describe what happened.

  * First, the 57k lines in my repository take 2m 50s to type check in the released version of Agda 2.6.1, in a core i7 desktop computer, which is very good, with relatively low memory consumption. Moreover, it can be typed checked in a core i3 tablet with 4gb of ram and no swap in about 15 minutes.

  * The file UF-Classifiers-Old.lagda takes infinitely long (more than 24 hours before I give up) to type check in the development version of Agda. It takes 4s in the current released version of Agda. With the flag --experimental-lossy-unification, it also takes 4s in the development version of Agda.

  * The file UF-InjectiveTypes.lagda gives a universe checking error with --experimental-lossy-unification, and without this flag in type checks fast.

 * The file UF-InjectiveTypes-article (1) takes infinitely long to type check without the experimental flag, and (2) gives a universe error with the flag. With the help of @tomdjong , we identified and side-stepped (1) by making a trivial change: give an auxiliary definition of a subterm in a where-clause (https://github.com/martinescardo/TypeTopology/commit/8f534a94c61cd86d373c8e23693f222847882f7e). However, this works only *without* the experimental flag.

  * After fixing this to make my development compatible with the development version of Agda, the type checking time of the whole repository (without the file UF-Classifiers-Old, which takes an infinitely long time) is 3min 30s (rather than 2m 50s as in the released version of Agda, including UF-Classifiers-Old).

After extensive experimentation, I have more details to give on request, if you are interested. For the moment, I am working with the released version of Agda, but this prevents me from merging @tomdjong 's work on Scott's D-infinity, which requires the development version of Agda with the experimental flag to be able to be type checked in finite time.

**Comment by martinescardo** [comment] 2020-06-13 06:40
I have now made modifications to make UF-Classifiers-Old to type check in finite time in the development version of Agda (and fast in both the current version and the development version).

With the changes I've made, now the type checking time of the whole development is nearly identical in both versions of Agda, the current one and the development one (but slightly slower in the development version).

**Comment by nad** [comment] 2020-06-27 13:14
> The file UF-Classifiers-Old.lagda takes infinitely long (more than 24 hours before I give up) to type check in the development version of Agda. It takes 4s in the current released version of Agda.

Perhaps this regression should be investigated. Can you produce a small test case? In that case, please open a new ticket for it.

**Comment by martinescardo** [comment] 2020-06-29 06:51
@nad It is difficult to make a small test case. It is not clear at all, to me, why the modifications I made to make this faster in the development version (it was already fast in the current version) should make it fast. This example deals with univalence, and I don't see how to shorten this, as even the formulation of univalence in itself is long. You can see that lines I changed to make it fast here, but I am not sure this will be useful to you: https://github.com/martinescardo/TypeTopology/commit/e34acaafddc0b0bff4ce60871aff652dd5fb0c89

**Comment by nad** [comment] 2020-06-29 14:21
OK, thanks.

**Comment by Saizan** [comment] 2020-10-29 08:19
A case where the flag improves speed by ~10x https://github.com/agda/cubical/pull/467

**Comment by nad** [comment] 2020-11-03 19:03
I looked at the example that you linked to. One slow part involved checking that `GroupHom (coHomGr 1 (A ⋁ B)) (×coHomGr 1 (typ A) (typ B))` was convertible to `GroupHom (coHomGr 1 (Pushout (λ _ → pt A) (λ _ → pt B))) (×coHomGr 1 (typ A) (typ B))`, where you can transform the first expression into the second by unfolding `A ⋁ B`. I don't think any meta-variables were involved. Does it make sense to always do this kind of thing when the two terms do not contain any meta-variables?

**Comment by martinescardo** [comment] 2021-03-17 00:50
I am still having trouble with this issue. 

The files that @tomdjong mentions above in his experiments now take forever without the flag --experimental-lossy-unification in Agda 2.6.2 9599ddf (I waited for 30min), whereas in agda 2.6.1 the *whole* repository type checks in 3 min 30 sec only (without that flag, which is not available).

Moreover, the behaviour of this experimental flag is a bit strange: *with* the flag, some files don't type check. So the way to get everything to type check with the current development version of Agda 2.6.2 9599ddf is to alternate between running with and without the flag until everything type checks, with appropriate uses of ctrl-c for the modules that take a long time and need the flag. Something like this:
```
$ rm *.agdai
$ agda-2.6.2-2021-03-16 --version
Agda version 2.6.2-9599ddf
$ agda-2.6.2-2021-03-16 AllModules.lagda
<ctrl-c after a module gets stuck for several minutes>
$ agda-2.6.2-2021-03-16 --experimental-lossy-unification AllModules.lagda
<we get an error in another module>
$ agda-2.6.2-2021-03-16 AllModules.lagda
<success>
```

So at the moment the development version of Agda is not usable in this repository. (To make things a bit worse, in Agda 2.6.1, I can't import a module that uses --cubical and the cubical library, as this needs 2.6.2.)

Moreover, as many of you know, I (deliberately) use a tiny fragment of Agda, and except for one module that disables non-termination and another that enables --type-in-type (to prove the famous contradiction), all modules are --safe. (By the way,  the module that uses type-in-type gives an error with this experimental flag.)

Additional information: I also had to change a few modules to make the above type checking succeed, to fix a number of unsolved constraints with Agda 2.6.2 9599ddf. The modified version still works with the current version 2.6.1.

**Comment by Saizan** [comment] 2021-03-17 09:41
@martinescardo We should investigate the regression, you should know though that you can apply the flag to a module by including it into the `{-# OPTIONS ... #-}` pragma at the top.

**Comment by martinescardo** [comment] 2021-03-17 09:53
Many thanks for investigating this. 

(Because I am using 2.6.1, where the flag is not available, it would be inconvenient to add this in the offending modules to test 2.6.2. I am testing 2.6.2 because it is intended to be released in May - is that correct?)

**Comment by jespercockx** [comment] 2021-05-08 12:15
Since #5279 has been fixed, I'm bumping this to 2.6.3.

**Comment by UlfNorell** [comment] 2022-04-07 12:47
Flag is documented, so I think this can be closed?

**Comment by martinescardo** [comment] 2022-04-07 12:53
Could we rename the flag to "--lossy-unification". It is not reassuring to have an "experimental" flag in a formalization behind a paper one submits for publication.

**Comment by andreasabel** [comment] 2022-04-13 13:28
> Could we rename the flag to "--lossy-unification"

I think that would be fine. `--lossy-unification` already shows a red flag, not need to double this up with `experimental`.

**Comment by andreasabel** [comment] 2022-08-31 14:42
~~Alternatives: ~~`--optimistic-unification`~~, `--speculative-unification`.~~

**Closed as completed** 2022-09-03 16:07 UTC
Labels: performance, ux: options, constraints, documented-in-changelog
