### ISSUE TITLE
Name in scope is claimed to be out of scope

### ISSUE THREAD

**Issue by nad** [agda/agda#1804] opened 2016-01-28 13:00 UTC
``` agda
record R : Set₁ where
  field F : Set

postulate r : R

open R r using (F)

S : Set
S = F

-- Run "Explain why a particular name is in scope" (C-c C-w) for F.
-- Result:
--
--   F is not in scope.
```

**Comment by andreasabel** [comment] 2016-01-28 14:21
It works if you `open public`.
It also works if you do `C-c C-w` inside hole

``` agda
test = {! F !}
```

appended to the end of the file (without `public`).

Currently, you are only in the `insideScope` inside a hole, otherwise you are in the scope exported by the module.  With this definition, Agda behaves correctly.

Maybe you want to be in the `insideScope` also on top-level?!

**Comment by nad** [comment] 2016-01-28 16:55
> otherwise you are in the scope exported by the module.

For the module

```
open import Data.Nat
```

I get an in-scope answer if I ask why ℕ is in scope, so this explanation doesn't seem correct to me.

> Maybe you want to be in the insideScope also on top-level?!

Maybe.

**Comment by andreasabel** [comment] 2016-01-29 14:38
You could have a look in Interaction.Imports on where private etc. things are removed from the scope.  Maybe this bug has been introduced there.

**Comment by andreasabel** [comment] 2016-02-02 15:52
Caused by removing private things before serialization. Fix: keep private things.

**Comment by andreasabel** [comment] 2016-02-02 16:01
Fixed on maint-2.4, but open on master.  Ulf mentioned something with dead code removal which could cause this.

**Comment by andreasabel** [comment] 2016-02-02 16:03
For master, over to @UlfNorell.

**Comment by UlfNorell** [comment] 2016-02-02 21:45
This is working as intended.

**Comment by nad** [comment] 2016-02-03 08:08
> This is working as intended.

Perhaps, but it doesn't seem very consistent that, in the following example, `ℕ` is in scope, but not `F`:

```agda
open import Data.Nat using (ℕ)

record R : Set₁ where
  field F : Set

postulate r : R

open R r using (F)

S : Set
S = F
```

Furthermore I think the workaround where you create a goal at the end of the file is less than ideal:
- Hard to discover for the user. (Could be fixed by adding a hint to the output of `C-c C-w`.)
- Need to edit the file, invalidating any .agdai file.
- Perhaps the top-level `C-c C-w` gives you some, but not all, instances of a name, leading to confusion if you forget to create a goal.

A suggested design: The top-level command gives you either exactly the names exported from the module, or the names visible in a goal at the end of the file, depending on the presence of a prefix argument (like `C-u`). The output clearly states what names are considered, and indicates how you can affect the names under consideration.

**Comment by UlfNorell** [comment] 2016-02-03 09:35
We could certainly do this for `C-c C-w`, but then you'd get an inconsistency with `C-c C-n` (for instance) where we absolutely cannot let private things be in scope.

**Comment by nad** [comment] 2016-02-03 10:08
> where we absolutely cannot let private things be in scope.

Why? And why is there a difference between `ℕ` and `F`?

**Comment by UlfNorell** [comment] 2016-02-03 10:36
The difference is that `ℕ` is a public entity from a different module and `F` is a private entity from the current module. The dead-code elimination removes unused private entities from a module before writing the interface file, so if you're loading the module from an interface, `F` might not exist (in this case it does, since it's used, but the scope checker can't know that) .

**Comment by nad** [comment] 2016-02-05 16:46
In that case, wouldn't it be more consistent to hide `ℕ` as well?

**Comment by UlfNorell** [comment] 2016-02-06 07:51
I don't know about more consistent, but it would make all top-level commands completely unusable, since you could never refer to things from other modules.

**Comment by nad** [comment] 2016-02-09 18:21
Is there any reason why the top-level commands aren't executed "in a hole at the end of the file", except for efficiency? And in that case, how important is this optimisation? (I've forgotten the details.)

**Comment by UlfNorell** [comment] 2016-02-09 18:32
The dead-code elimination reduced some of Wolfram's interfaces by a factor 5, so I'd say pretty important.

**Comment by asr** [comment] 2016-02-09 21:06
> Perhaps, but it doesn't seem very consistent that, in the following example, ℕ is in scope, but not F:
> 
> open import Data.Nat using (ℕ)
> 
> record R : Set₁ where
>  field F : Set
> 
> postulate r : R
> 
> open R r using (F)
> 
> S : Set
> S = F

I see `F` in scope in the current master:

``` bash
F is in scope as

  * a record field Test._.F brought into scope by
    - the application of R at /tmp/Test.agda:8,6-7
    - its definition at /tmp/Test.agda:4,9-10
```

**Comment by nad** [comment] 2016-02-09 22:58
> I see F in scope in the current master:

I don't:

```
F is not in scope.
```

**Comment by asr** [comment] 2016-02-09 23:10
My bad. I was using the `public` keyword in the example.

**Closed as completed** 2016-02-15 13:23 UTC
Labels: type: enhancement, scope, ux: interaction, serialization, master, dead-code

**Comment by txa** [comment] 2020-05-13 10:46
Maybe better to add a pragma "strip-private-definitions" for Wolfram? Instead of making C-c C-n behave in an unexpected way.
