### ISSUE TITLE
CI fails to build user manual (TeX Live installation issue)

### ISSUE THREAD

**Issue by rwe** [agda/agda#5107] opened 2020-12-19 20:49 UTC
Noted here: https://github.com/agda/agda/pull/5106#issuecomment-748180263 about which @L-TChen [comments](https://github.com/agda/agda/pull/5106#issuecomment-748474309):
> The failure is caused by the previous step of installing TeX Live. Not sure why, but it points to the following url
>
> http://ftp.math.purdue.edu/mirrors/ctan.org/systems/texlive/tlnet
>
> which does not exist any more.

**Comment by rwe** [comment] 2020-12-19 20:51
An example build failure here: https://github.com/agda/agda/runs/1582619615
includes the following relevant log (prior to the actually-failing build step):

> ```
>   export PATH=$HOME/texlive/bin/x86_64-linux:$PATH
>   curl -Lo /tmp/texlive.tar.gz jimhester/ubuntu-bin@latest texlive.tar.gz (download)
>   tar xzf /tmp/texlive.tar.gz -C ~
>   tlmgr update --self
>   tlmgr install latex anyfontsize bbm capt-of cmap dvipng fncychap keystroke latexmk needspace
>   shell: /bin/bash -e {0}
>   env:
>     pythonLocation: /opt/hostedtoolcache/Python/3.7.9/x64
>     LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.9/x64/lib
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100   638  100   638    0     0   5853      0 --:--:-- --:--:-- --:--:--  5853
> 
>  81 88.6M   81 72.3M    0     0  79.0M      0  0:00:01 --:--:--  0:00:01 79.0M
> 100 88.6M  100 88.6M    0     0  81.6M      0  0:00:01  0:00:01 --:--:-- 95.3M
> No connection to the internet.
> Unable to download the checksum of the remote TeX Live database,
> but found a local copy so using that.
> 
> You may want to try specifying an explicit or different CTAN mirror;
> see the information and examples for the -repository option at
> http://tug.org/texlive/doc/install-tl.html
> (or in the output of install-tl --help).
> 
> tlmgr: package repository http://ftp.math.purdue.edu/mirrors/ctan.org/systems/texlive/tlnet (not verified: unknown)
> tlmgr: saving backups to /home/runner/texlive/tlpkg/backups
> tlmgr: no self-updates for tlmgr available.
> No connection to the internet.
> Unable to download the checksum of the remote TeX Live database,
> but found a local copy so using that.
> 
> You may want to try specifying an explicit or different CTAN mirror;
> see the information and examples for the -repository option at
> http://tug.org/texlive/doc/install-tl.html
> (or in the output of install-tl --help).
> ```

**Comment by L-TChen** [comment] 2020-12-29 14:00
Installing TeX packages on Ubuntu is not easy, as one has to locate which apt package contains the desired tex package. Even worse, it usually packs more packages than we need. Using a 3rd-party docker image with a complete TeX Live installed might be a choice.

**Comment by andreasabel** [comment] 2021-02-08 09:38
Seems like the problem is [now](https://github.com/agda/agda/pull/5180/checks?check_run_id=1853285915) that LaTeX package `bm` and style file `anyfontsize.sty` are not found.

**Comment by andreasabel** [comment] 2021-02-08 10:06
I notice that CI uses the TeXLive distro of 2017, maybe Sphinx wants a newer version?

**Comment by L-TChen** [comment] 2021-02-08 10:15
As far as I remember (I don't use Ubuntu), TeX packages are managed by Ubuntu's own package manager which does not seem to provide an `apt` package for each tex package on CTAN. I might be wrong anyway ...

**Comment by asr** [comment] 2021-02-08 15:12
I used TeX Live in Travis because LaTeX on Ubuntu was too old. It seems the problem is a missing repository when running `tlmgr`. I'll take a look.

**Comment by asr** [comment] 2021-02-08 16:01
Fixed by the above commit (I don't know why the issue wasn't close automatically).

**Closed as completed by asr** 2021-02-08 16:01 UTC
Labels: backend: latex, build-failure, ux: documentation, infra: github workflows
