### ISSUE TITLE
Unable to refine correct solution.

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#2817] opened 2017-10-22 10:28 UTC
Trying to refine the hole with ```eqc``` is not possible but removing the hole 
and doing it by hand works.

```agda
module test where

open import Relation.Binary.PropositionalEquality
open import Size
open import Level public renaming (suc to lsuc ; _⊔_ to _l⊔_ ; zero to lzero) 
open import Data.Nat
open import Data.Product
open import Relation.Nullary

module _ where

  open import Data.Vec 



  genT : ∀{u} {n : ℕ} -> Vec (Set u) n -> Set (lsuc u)
  genT {u} [] = Set u
  genT (x ∷ xs) =  x -> genT xs



  mutual
    data LinLogic (i : Size) {u} : Set (lsuc u) where
      ∅    :                                       LinLogic i
      τ    : ∀{n} {dt : Vec (Set u) n} → genT dt → LinLogic i
      call : ∞LinLogic i {u}                     → LinLogic i
      il[_]  : LinLogicI i {u}                     → LinLogic i

    data LinLogicI (i : Size) {u} : Set (lsuc u) where
      _∧_  : LinLogic i {u} → LinLogic i {u}     → LinLogicI i
      _∨_  : LinLogic i {u} → LinLogic i {u}     → LinLogicI i
      _∂_  : LinLogic i {u} → LinLogic i {u}     → LinLogicI i

    record ∞LinLogic (i : Size) {u} : Set (lsuc u) where
      coinductive
      field
        step : {j : Size< i} → LinLogic j {u = u}


data IndexLLCT : Set where
  ic←∧ : IndexLLCT 
  ic∧→ : IndexLLCT
  ic←∨ : IndexLLCT
  ic∨→ : IndexLLCT
  ic←∂ : IndexLLCT
  ic∂→ : IndexLLCT


expLLT : ∀{i u} → (ll : LinLogic i {u})  → IndexLLCT → (tll : LinLogic i {u}) → LinLogicI i {u}
expLLT {i} {u} ll ic←∧ tll = ll ∧ tll
expLLT {i} {u} ll ic∧→ tll = tll ∧ ll
expLLT {i} {u} ll ic←∨ tll = ll ∨ tll
expLLT {i} {u} ll ic∨→ tll = tll ∨ ll
expLLT {i} {u} ll ic←∂ tll = ll ∂ tll
expLLT {i} {u} ll ic∂→ tll = tll ∂ ll


data IndexLL {i : Size} {u} (rll : LinLogic i {u}) : LinLogic i {u} → Set (lsuc u) where
  ↓   :                             IndexLL rll rll
  ic : ∀{ll tll ict il} → IndexLL rll ll → {{eq : il ≡ (expLLT ll ict tll)}} → IndexLL rll il[ il ]


module _ where

  replLL : ∀{i u q ll} → (ind : IndexLL {i} {u} q ll) → LinLogic i {u} → LinLogic i {u}
  replLL ↓ c = c
  replLL (ic {ll = ll} {tll} {ict} ind) c = il[ expLLT (replLL ind c) ict tll ]


data IndU {i u il} (icta ictb : IndexLLCT) {lla llb tlla tllb : LinLogic i {u}} (eqa : il ≡ expLLT lla icta tlla) (eqb : il ≡ expLLT llb ictb tllb) : Set (lsuc u) where
  ictEq : (icteq : icta ≡ ictb) → (lleq : lla ≡ llb) → (tlleq : tlla ≡ tllb) → (eqeq : (icta , lla , tlla , eqa) ≡ (ictb , llb , tllb , eqb)) → IndU _ _ _ _
  ict¬Eq : (¬icteq : ¬ icta ≡ ictb) → (reqa : lla ≡ tllb) → (reqb : llb ≡ tlla) → IndU _ _ _ _




data _≤ᵢ_ {i u gll fll} : ∀{ll} → IndexLL {i} {u} gll ll → IndexLL {i} {u} fll ll → Set (lsuc u) where
  ≤ᵢ↓ : {ind : IndexLL fll gll} → ↓ ≤ᵢ ind
  ≤ᵢic : ∀{ll ict tll il eq} → {sind : IndexLL gll ll} → {bind : IndexLL fll ll} → (sind ≤ᵢ bind)
         → _≤ᵢ_ {ll = il[ il ]} (ic {ll = ll} {tll} {ict} sind {{eq}}) (ic {ll = ll} {tll} {ict} bind {{eq}})



data Orderedᵢ {i u gll fll ll} (a : IndexLL {i} {u} gll ll) (b : IndexLL {i} {u} fll ll) : Set (lsuc u) where
  a≤ᵢb : a ≤ᵢ b → Orderedᵢ a b
  b≤ᵢa : b ≤ᵢ a → Orderedᵢ a b



_-ᵢ_ : ∀ {i u pll cll ll} → (bind : IndexLL {i} {u} cll ll) → (sind : IndexLL pll ll) → (sind ≤ᵢ bind)
       → IndexLL cll pll
(bind -ᵢ .↓) ≤ᵢ↓ = bind
((ic bind) -ᵢ (ic sind)) (≤ᵢic lt) = (bind -ᵢ sind) lt


a≤ᵢb-morph : ∀{i u rll ll fll} → (emi : IndexLL {i} {u} fll ll)
             → (ind : IndexLL rll ll) → ∀ {frll} → (lt : emi ≤ᵢ ind)
             → IndexLL (replLL ((ind -ᵢ emi) lt) frll) (replLL ind frll) 
a≤ᵢb-morph .↓ ind ≤ᵢ↓ = ↓
a≤ᵢb-morph (ic {tll = tll} {ict = ict} emi) (ic ind) (≤ᵢic lt) = ic {tll = tll} {ict = ict} (a≤ᵢb-morph emi ind lt)


module _ where

  mutual

    lemma₁-¬ord-a≤ᵢb-abs : ∀{u i ll tll ict il eq llc tllc ictc fll rll pll ica icb ell} → ∀ a b c
               → ∀ {icc eqc}
               → ica ≡ ic {i} {u} {fll} {ll = ll} {tll} {ict} {il} a {{eq}}
               → icb ≡ ic {i} {u} {rll} {ll = ll} {tll} {ict} {il} b {{eq}}
               → icc ≡ ic {i} {u} {pll} {ll = llc} {tllc} {ictc} {expLLT (replLL b ell) ict tll} c {{eqc}}
               → ∀ lt
               → ¬ Orderedᵢ (ic {tll = tll} {ict} (a≤ᵢb-morph a b {ell} lt)) icc
               → IndU ict ictc refl {!eqc!}
               → IndexLL pll il[ il ]
    lemma₁-¬ord-a≤ᵢb-abs a b c iceqa iceqb iceqc lt nord eq = {!!}
```

**Comment by andreasabel** [comment] 2017-10-22 16:55
This is because some size variables have been instantiated to infinity where they shouldn't.  I guess it is a duplicate of #992.

**Closed as completed** 2017-10-23 02:11 UTC
Labels: type: bug, sized types, ux: interaction
