### ISSUE TITLE
Case splitting on datatype defined in parametrized modules produces invalid syntax

### ISSUE THREAD

**Issue by Snicksie** [agda/agda#2630] opened 2017-07-06 15:40 UTC
When doing a case split on the hole in the following example (two files), the generated syntax is invalid.

File 1:
```agda
module mwe-module-M (A : Set) where

data D : Set where
  C :  D

```

File 2:
```agda
module mwe-module-N (A : Set) where

open import mwe-module-M A

f : D → D
f x = {!!}
```

The following syntax is generated:

```agda
f : D → D
f .mwe-module-M.D.C = ?

```

When defining this in a single file, the correct syntax is generated.

**Comment by andreasabel** [comment] 2017-07-06 22:12
This is a duplicate of #2245 and #2378 and #1932.

**Closed as completed** 2018-05-31 14:26 UTC
Labels: status: duplicate, ux: case splitting, ux: printing, constructors
