### ISSUE TITLE
Bad syntax generated on case split when hole is not on the same line as the clause lhs

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2340] opened 2016-12-14 14:01 UTC
```agda
data ⊤ : Set where
  tt : ⊤

record ABC : Set where
  field
    a b c : ⊤

abc : ABC → ABC
abc record { a = a ; b = b ; c = c } =
  record {
      a = {!!}
    ; b = b
    ; c = c
    }
```

Case splitting on `a` here causes some bad syntax generation.

**Comment by andreasabel** [comment] 2016-12-14 16:13
This happens when the hole is not on the same line as the clause lhs.
```agda
test : ABC → ABC
test x =
  {!x!}  -- split on x
```
gives
```agda
test : ABC → ABC
test x =
  test record { a = a ; b = b ; c = c } = ?
```
with a parse error.

With the current infrastructure, there is no easy fix for this.  We would need to communicate positions (such as the position of the lhs) back to emacs.  But the user could have inserted some lines before, shifting the position.  Thus, all the emacs-mode can do when Agda instructs it to split is to guess where the lhs would be.

**Comment by UlfNorell** [comment] 2018-05-29 15:26
Duplicate of #1146.

**Closed as completed by UlfNorell** 2018-05-29 15:26 UTC
Labels: status: duplicate, type: bug, ux: emacs, ux: case splitting, ux: interaction
