### ISSUE TITLE
Change the semantics of open public in parameterised module

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#892] opened 2015-08-08 18:05 UTC
Using the current (2013-08-21) development version, I see the wrong type for 
`g` in the hole below:

```agda
module ReExport where

data D : Set where
  d : D

record R : Set where
  field f : D
  module M1 where
    g : D
    g = f
  module M2 where
    open M1 public

  open M2 public

-- C-C C-D says:  R.g : ( : R) → D
-- C-C C-D says:  R.M1.g : ( : R) → D
-- C-C C-D says:  R.M2.g : ( : R) → D

module R₁ (r : R) where
  open R r
  g₁ : D
  g₁ = {! g !}

-- for ``g'' in the hole, C-C C-. says, unexpectedly:
-- Goal: D
-- Have: ( : R) → D

-- for ``g r'' in the hole, C-C C-. says, unexpectedly:
-- Goal: D
-- Have: D

-- for ``R.g r'' in the hole, C-C C-. says, as expected:
-- Goal: D
-- Have: D


```

Original issue reported on code.google.com by `k...@cas.mcmaster.ca` on 30 Aug 2013 at 11:26

**Comment by Saizan** [comment] 2015-08-20 10:16
We could desugar 

```
  open M public
```

to

```
  module M' = M
  open M' public
```

There might be a performance problem, since it will generate more wrappers.

**Comment by andreasabel** [comment] 2015-10-08 07:25
@Saizan: Why not implement `open M public` so that it behaves as the desugaring?

**Comment by UlfNorell** [comment] 2015-10-08 08:37
There are the performance concerns. Module applications are expensive enough that we spent quite a bit of effort at the Agda meeting on various optimisations for them.

I'm also not sure that you would never want the current behaviour. If we do the proposed desugaring there would be no way of expressing the old behaviour.

**Comment by andreasabel** [comment] 2015-12-02 14:47
The new semantics would be (which strangely was the semantics of 2.4.2.2, but not 2.4.0 or 2.4.2.5):

``` agda
postulate
  U V W X Y Z : Set
  u : U
  v : V
  w : W
  x : X
  y : Y
  z : Z

module Top (u : U) where
  module A (v : V) where
    module M (w : W) where
      module O (x : X) where
  module B (y : Y) where
    open A public

module ShouldFail0 where
  module C = Top.B u y
  module D = C.M.O u v w x  -- u should not be there

module ShouldFail1 where
  module C (i g n o r i n g m e : Z) = Top.B u y
  module D = C.M.O u v w x  -- u should be 10*z

module ShouldFail2 where
  module C (y : Y) = Top.B u y
  module D = C.M.O u v w x -- u should be y

module ShouldSucceed where
  module C (z : Z) = Top.B u y
  module D = C.M.O z v w x -- Z !=< U of type Set
```

**Comment by asr** [comment] 2015-12-02 17:33
I created #1726 for discussing Andreas' test cases.

**Comment by UlfNorell** [comment] 2016-02-23 10:19
Since I fixed #1726, the only remaining issue here is whether we should make

``` agda
open M public
```

desugar to

``` agda
module M' = M
open M' public
```

The only reason for doing this would be to match the intuition that `module M' = M` is a no-op. I think this is a bad idea since it isn't a no-op. For instance,

``` agda
module M where
  postulate X : Set
module N (A : Set) where
  module M' = M
MX : Set
MX = M.X

NMX : Set → Set
NMX = N.M'.X
```

There's also the already mentioned performance concerns, and the problem that the old behaviour would be impossible to express under the new semantics (whereas the converse is not true).

**Comment by UlfNorell** [comment] 2016-02-24 13:32
Closing. Reopen if you have objections.

**Comment by andreasabel** [comment] 2016-06-01 23:43
Reopening because of #1985, which demonstrates that `open public` in parametrized modules is not understood.  I still think the semantics should change so that definition in a parametrized module carry the parameters, regardless of whether they entered the module by definitions or `open public`.

**Comment by UlfNorell** [comment] 2016-06-02 05:23
You can't say that `open public` is not understood every time there's a bug... My performance concerns still stand. You could make a branch with the changed behaviour and ask @WolframKahl to run his RATH library to see how bad it would be.

**Comment by UlfNorell** [comment] 2018-01-16 08:43
I'm closing this again. Reopen with experimental evidence that changing the behaviour of `open public`
- does not require a lot of work updating existing libraries
- does not cause non-trivial performance regressions

**Closed as completed by UlfNorell** 2018-01-16 08:43 UTC
Labels: type: enhancement, modules, open-public
