### ISSUE TITLE
Macros parameters of type `Term` do not properly type check

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2457] opened 2017-02-12 16:47 UTC
There are two parts below: the first few comments demonstrate that `Term` parameters to macros do not type check in the same way as parameters of any other type; the second part demonstrates why this is problematic.

```agda
open import Agda.Builtin.Unit
open import Agda.Builtin.Reflection
open import Agda.Builtin.List

macro
  accepts-⊤ : ⊤ → Type → TC ⊤
  accepts-⊤ _ t = unify (quoteTerm tt) t
  
  accepts-term : Term → Type → TC ⊤
  accepts-term _ t = unify (quoteTerm tt) t


-- `accepts-⊤` correctly yields type error saying String != ⊤
-- _ = accepts-⊤ "asdf"

-- `accepts-⊤` correctly accepts values of type ⊤
-- _ = accepts-⊤ tt

postulate
  t : Term

-- `accepts-⊤` correctly rejects this `t : Term`
-- _ = accepts-⊤ t


-- `accepts-term` correctly (well... more on that in a minute) accepts a value of `t : Term`
_ = accepts-term t


-- but `accepts-term` wrongly accepts the value `tt : ⊤` too!
_ = accepts-term tt



-- this weirdness results in the following anomaly:
macro
  reify : Term → Type → TC ⊤
  reify = unify

trivial : Term
trivial = reify t

-- so far so good... but

infixl 5 _>>=_
_>>=_ = bindTC

macro
  reflect : ∀ {t : Set} → t → Type → TC ⊤
  reflect x ty = quoteTC x >>= quoteTC >>= unify ty

realTerm : Term
realTerm = reflect tt -- ok

-- whaaaat?
-- trivial' : ⊤
-- trivial' = reify realTerm
```

**Comment by UlfNorell** [comment] 2017-02-12 19:27
I think this is working as intended. Did you read the [section on macros in the user manual](https://agda.readthedocs.io/en/latest/language/reflection.html#macros) that explains how macro arguments of type `Term` and `Name` are handled?

Closing, but reopen if needed.

**Closed as completed by UlfNorell** 2017-02-12 19:27 UTC

**Comment by identicalsnowflake** [comment] 2017-02-12 19:52
@UlfNorell That behavior is surprising to me. I encountered this while attempting to get the following via the macros `reflect` and `unreflect`:

```agda

term : Term
term = reflect something -- where something : t

original : t
original = unreflect term -- where original ≡ something

```

The `unreflect` is causing me problems. If I already have some `x : Term`, passing it to a macro messes it up by reflecting it again instead of using the term I'm trying to pass it.

**Comment by identicalsnowflake** [comment] 2017-02-12 20:06
I tried that `unquoteDef` instead of `unreflect`, but I think I'm doing something wrong:

```agda
trivial' : ⊤
unquoteDef trivial' = unify (quoteTerm ⊤) realTerm

```

Agda says `⊤ !=< Set of type Set`.

EDIT: Creating a type wrapper for `Term` allows me to pass it to `unreflect` cleanly. I'll use that.

**Comment by UlfNorell** [comment] 2017-02-12 21:02
`unify` takes two terms to unify. Typically one is the metavariable that you get passed to a macro.

If you desperately want to pass a `Term` to a macro you can wrap it in a datatype to avoid the special treatment kicking in.

**Comment by phile314** [comment] 2017-02-13 08:42
I think the current solution is not too bad, but I now see that it can be a bit surprising. Maybe adding a "newtype" for quoted terms/types could be a nice solution:

    record Quoted : (A : Set) -> Set where
      field quoted : A

    macro
      test : Term -> Quoted Term -> Quoted Name -> TC T

    f = test a b c
    -- desugars to
    f = unquote (test a (quoteTerm b) (quote c))

This would make the macro behavior more uniform, as only things inside ``Quoted`` would be automatically quoted. It would be more explicit at the cost of additional verbosity. Not sure if it's worth the effort?
