### ISSUE TITLE
Elements of a proposition needlessly reduced during occursCheck

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#4120] opened 2019-10-08 10:31 UTC
Another one of the same flavor as #4115 and #4118. The last message given is
`occursCheck _18 (WeaklyRigid) of  (a ab)`.

```agda
{-# OPTIONS --prop #-}

{-# TERMINATING #-}
makeloop : {P : Prop} → P → P
makeloop p = makeloop p

postulate
  A : Set
  B : A → Prop

record AB : Set where
  constructor _,_
  field
    a : A
    b : B a
open AB public

id : AB → AB
id ab = a ab , makeloop (b ab)

postulate
  f : (id* : AB → AB) → A → Set

C : A → Set
C = f id

postulate
  D : (C : A → Set) (a : A) (c : C a) → Set

-- Works if you either give the type of v (C u) or the second argument of D (u)
loops : (u : A) (v : _) → D C _ v
loops = {!!}
```

**Comment by jespercockx** [comment] 2019-10-08 12:13
This one is harder to fix because there is currently no type information available in the occurs check. 

It's also not 100% that the occurs check *shouldn't* do some reduction of (irrelevant) proofs. For example, suppose we have the following:
```agda
postulate
  A : Set
  B : Prop
  b : B

f : Bool -> A -> B
f true x = ... -- something relying on x
f false _ = b
```
and the constraint solver is trying to solve `_1 := f false (_2 x)` where `x` is not in scope of the metavariable `_1`. Then it really helps to reduce the application `f false (_2 x)` to `b`, *despite the fact that this is a proof of a `Prop`*. So maybe the ideal that 'we should never reduce elements of a `Prop`' is actually unattainable in practice.

**Comment by jespercockx** [comment] 2019-10-22 14:04
The current strategy for occurs checking is to first try the occurs check without reducing anything, and then if that fails try again with full normalization. This is certainly a good way to maximize our chances of passing the check, but is not very efficient.

I think it should be possible to do better than this:

1. When the first try results in a **hard** error (i.e. an illegal variable was encountered in a rigid position, internally represented as `MetaCannotDependOn`/`MetaIrrelevantSolution`/`MetaErasedSolution`) then there is no way to get rid of the error by reducing further, so the second try is pointless.
2. When the first try results in a **soft** error (i.e. an illegal variable was encountered in a flexible position, internally represented as `PatternErr`) then reducing might actually help. On the other hand, *not* reducing can only lead to unsolved constraints in the worst case, never to an actual type error.

When working with irrelevance/`Prop`, the second case is the most relevant since anything in an irrelevant position is counted as flexible. So there is a trade-off to be made between performance and maximally solving as many metavariables as possible. Maybe there should be a flag to turn the second step on or off.

**Comment by jespercockx** [comment] 2019-10-22 16:37
Ok, I changed the occurs check so it doesn't do the second run (the one with normalization) in two situations:

- When the first run finds a rigid occurrence (that cannot disappear through reduction)
- When the first run fails but the metavariable we are solving is irrelevant

The second change may lead in theory to more unsolved metavariables of implicit irrelevant arguments or implicit arguments with type in `Prop`, but I'm hoping this doesn't pose a problem in practice.

@guillaumebrunerie could you run your test once more to see if the time spent on occurs checking is more reasonable now?

**Comment by jespercockx** [comment] 2019-10-22 16:42
Ok, now I actually pushed the changes :)

**Comment by nad** [comment] 2019-10-23 08:46
> The second change may lead in theory to more unsolved metavariables of implicit irrelevant arguments or implicit arguments with type in `Prop`, but I'm hoping this doesn't pose a problem in practice.

The second change sounds like a bad idea to me. It happens that we change Agda so that it reduces terms less eagerly. Now such a change could lead to a regression. I think that the conversion checker should respect definitional equality.

**Comment by UlfNorell** [comment] 2019-10-23 09:11
> I think that the conversion checker should respect definitional equality.

Do you have an actual plan for making this happen in the presence of irrelevance? For instance, what do you propose for this example:

```agda
{-# OPTIONS --prop #-}

open import Agda.Builtin.Nat

data Squash (A : Set) : Prop where
  squash : A → Squash A

postulate
  T   : Squash Nat → Set
  F   : ∀ s → T s → Set
  mkT : ∀ s → T s
  unsolved : (let s : Squash Nat; s = _) (n : Nat) → F s (mkT (squash n))
  solved   : (let s : Squash Nat; s = _) (n : Nat) → F s (mkT (squash 0))
```
Here `squash n` and `squash 0` are definitionally equal so if we should either solve the meta in both cases or in neither?

**Comment by jespercockx** [comment] 2019-10-23 09:11
But the only way to make sure the conversion checker respects definitional equality is by *never* solving any irrelevant metavariables. This problem is actually the same for eta-unit types, irrelevant arguments, and terms of a type in `Prop` (collectively known as 'definitional subsingletons'). Every time Agda has to solve an equation between two elements of a definitional subsingleton, it has the option to just do nothing and declare the equation to be solved. Since there are at least *some* situations where this will happen, the only consistent thing would be to do it *always*.

However, I am pretty sure this is not the behaviour we actually want. When solving an equation `_x == p : P` where `P : Prop`, we do expect Agda to solve `_x := p` (see the example posted by @guillaumebrunerie in #4122). But as soon as we accept this very simple heuristic, we have opened the floodgates to any number of heuristics for solving irrelevant metas, up to and including proof search. 

For example, suppose we have `CollatzConjecture : Prop` with a variable `p : CollatzConjecture` and a constraint `_X == p` (where `p` is not in scope of the meta). Then Agda solves this constraint through irrelevance, leaving the meta `_X` unsolved. However, IF there exists a closed proof `collatzProof : CollatzConjecture` then `p` would be definitionally equal to this proof, so in order to respect definitional equality Agda would have to find this proof and solve `_X := collatzProof`.

 At some point we have to admit that there is a tradeoff between maximally solving irrelevant metavariables and having reasonable performance. My claim here is that in general it is a bad idea to reduce elements of types in `Prop` (as shown by the examples of @guillaumebrunerie).

**Comment by jespercockx** [comment] 2019-10-23 09:15
Maybe there should be an option to not apply any heuristics for solving irrelevant equations, but instead always chooses the principled option of discarding the equation. I can image this being used by someone who doesn't want to be surprised by unsolved irrelevant metavariables in future versions of Agda. (This option would essentially make it impossible to use implicit irrelevant/`Prop` arguments.)

**Comment by guillaumebrunerie** [comment] 2019-10-23 10:13
> @guillaumebrunerie could you run your test once more to see if the time spent on occurs checking is more reasonable now?

This did not actually fix the performance issue, the timing results are essentially the same as in https://github.com/agda/agda/issues/4122#issuecomment-544916614.

I’m not sure I completely understand how the occurs check works, but maybe this is because when doing the second step for a *relevant* term, then it gets normalized, and all irrelevant terms that it contains are normalized as well?

**Comment by nad** [comment] 2019-10-23 12:56
OK, if respecting definitional equality is undecidable, unless we cripple constraint solving, then I guess we shouldn't do it. I hope this doesn't lead to too many regressions in user code.

> This problem is actually the same for eta-unit types

Is this case also undecidable? Doesn't the strategy of always eta-expanding work? Doesn't Agda eta-expand when it would otherwise be stuck?

**Comment by jespercockx** [comment] 2019-10-23 16:02
> > This problem is actually the same for eta-unit types
> 
> Is this case also undecidable? Doesn't the strategy of always eta-expanding work? Doesn't Agda eta-expand when it would otherwise be stuck?

You're right, inhabitation of eta unit types is decidable, so don't share this problem. However, records where all fields are irrelevant and/or in `Prop` do have the problem.

**Comment by jespercockx** [comment] 2019-10-23 16:03
> I’m not sure I completely understand how the occurs check works, but maybe this is because when doing the second step for a _relevant_ term, then it gets normalized, and all irrelevant terms that it contains are normalized as well?

Ah yes, that could very well be the problem. I guess we could  refuse to normalize anything when we're in an irrelevant context, also during the second pass.

**Comment by jespercockx** [comment] 2019-10-23 16:40
Here is a test case that currently loops on the second pass in the occurs check, but would terminate (with unsolved constraints) if we didn't normalize in irrelevant contexts:
```agda
{-# OPTIONS --prop --show-irrelevant #-}

open import Agda.Builtin.Equality

postulate
  A : Set
  P : Prop
  f : P → A
  g : A → P

{-# TERMINATING #-}
loop : A → A
loop y = loop y

mutual
  X : A
  X = _

  test : ∀ y → X ≡ f (g (loop y))
  test y = refl
```

**Comment by jespercockx** [comment] 2019-10-23 16:48
And the fix is (a)live!

**Comment by guillaumebrunerie** [comment] 2019-10-24 08:40
> And the fix is (a)live!

Still no difference, unfortunately :/

**Comment by jespercockx** [comment] 2019-10-24 11:49
Damn, that's unfortunate. I could try to do some further optimization, but it would be good to know if the problem is actually related to `Prop` or if there is some more general performance problem with the occurs check. In the latter case, it doesn't make sense to focus specifically on elements of a `Prop`.

**Comment by jespercockx** [comment] 2021-01-21 14:01
As for #4274, it is unclear to me whether the remaining issue here is related to `Prop` in specific or just a general performance problem with the occurrence check. Since there have been some improvements and there hasn't been any activity here in over a year, I'm going to close this now.

**Closed as completed by jespercockx** 2021-01-21 14:01 UTC
Labels: type: bug, performance, occurs check, prop, documented-in-changelog
