### ISSUE TITLE
Emacs: interrupt highlighting process when reloading `C-c C-l`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3550] opened 2019-02-07 08:31 UTC
Since a couple of months I get the `Another command is currently in progress` when pressing my standard key sequence `C-x C-s C-c C-l` to save and reload the buffer.
Apparently `C-x C-s` now triggers a highlighting process which stops `C-c C-l` from working.
`C-c C-l` should abort the current highlighting process in favor of a reload.

**Comment by nad** [comment] 2019-02-07 14:45
The command `C-c C-l` first saves the buffer, so your problem can be fixed by simply typing less.

> Apparently `C-x C-s` now triggers a highlighting process

See #2794 and #3119. This feature goes back to Agda 2.5.4.

**Comment by guillaumebrunerie** [comment] 2019-02-07 15:21
I’m having a similar problem, although not related to `C-x C-s`.

I’m not exactly sure how to reproduce it, but typically I do `C-c C-l` on a file I’m working on, it fails because of a stupid typo so I fix the typo and then do `C-c C-l` immediately again, and this time I get the message `Another command is currently in progress`. Redoing `C-c C-l` once again works, so it’s not a huge problem, but it happens quite often so it is somewhat annoying.

**Comment by nad** [comment] 2019-02-08 10:33
@guillaumebrunerie, I think this sounds like a different problem. Can you create a reproducible test case? (Preferably using [`RunAgda`](https://github.com/agda/agda/blob/master/test/interaction/RunAgda.hs), see [`Issue3082.hs`](https://github.com/agda/agda/blob/master/test/interaction/Issue3082.hs) for an example of how it can be used.)

**Comment by UlfNorell** [comment] 2019-02-08 10:56
I think I've run into this as well.

Why do you think it sounds like a different problem? Are there no other situations where we kick off the background highlighting process than on saving the buffer?

**Comment by guillaumebrunerie** [comment] 2019-02-08 11:06
From what I understand, the highlighting is updated after 0.2s of inactivity. So my guess is that if one runs `C-c C-l` 0.201s after the last keypress, then there will be a clash.

**Comment by nad** [comment] 2019-02-08 12:24
> From what I understand, the highlighting is updated after 0.2s of inactivity.

Are you still using Agda 2.5.4?

> Are there no other situations where we kick off the background highlighting process than on saving the buffer?

I don't think so.

**Comment by guillaumebrunerie** [comment] 2019-02-08 12:50
> > From what I understand, the highlighting is updated after 0.2s of inactivity.
> 
> Are you still using Agda 2.5.4?

No, I’m using the master branch from a few weeks ago. I saw something about those 0.2s of inactivity in https://github.com/agda/agda/issues/2794#issuecomment-389426018, but it seems not to be the case anymore indeed.
I’ll try to find a way to reproduce it, but for now I haven’t figured out what triggers it.

**Comment by guillaumebrunerie** [comment] 2019-02-11 09:19
Actually my problem seems to be the exact same one as Andreas’ problem. After observing how I interact with emacs, it seems like I regularly do `C-x C-s` without even noticing it.

**Comment by andreasabel** [comment] 2019-02-18 16:19
`C-x C-s C-c C-l` is hardwired into my hands.  It evolved from the `C-x C-s C-c C-c` needed for LaTeX.  I think the SML mode I used 20 years ago also had `C-x C-s C-c C-l`.  I do not want to rewire my brain all the time.  More rationally, I prefer "safe" key sequences that are more context-insensitive.  If there is key sequence A that works in context C and key sequence B that works in context D, but key sequence X works in both contexts, then I adapt sequence X to not have to think needlessly about the context.

**Comment by nad** [comment] 2019-02-20 15:50
There is already a way to interrupt commands, perhaps we could invoke this procedure at the beginning of `C-c C-l` if an automatic highlighting command is currently running.

**Comment by nad** [comment] 2019-03-12 13:28
Another option: The backend puts incoming requests on a queue:

https://github.com/agda/agda/blob/6f3046e081ebfa40793c3a064e53bdbd83c82dcf/src/full/Agda/Interaction/InteractionTop.hs#L130-L138

In order to avoid confusing users the Emacs mode has been set up so that it (mostly) only sends one command at a time to the backend. In this case it should be fine to send a load command to the backend before the highlighting command has completed. (And perhaps the semantics of abort commands could be changed so that they abort all commands on the queue.)

**Comment by nad** [comment] 2019-03-14 09:03
> (And perhaps the semantics of abort commands could be changed so that they abort all commands on the queue.)

I've pushed such a change.

**Comment by nad** [comment] 2019-03-14 09:58
The Emacs mode is largely based on the assumption that only one command at a time is sent to the backend. Making it possible to send multiple commands to the backend without breaking anything might be nontrivial.

I noticed that `agda2-update` calls `agda2-go` with the `do-abort` argument set to `nil`. I wonder if that code is correct, `agda2-go` overwrites some variables that might be in use by a previous, still running, command.

**Comment by nad** [comment] 2019-03-14 20:51
I've made an attempt to fix this problem. If everything seems to work as it should, then you can close the ticket.

**Comment by nad** [comment] 2019-03-14 20:54
> I noticed that `agda2-update` calls `agda2-go` with the `do-abort` argument set to `nil`. I wonder if that code is correct, `agda2-go` overwrites some variables that might be in use by a previous, still running, command.

I also made an attempt to fix this potential problem (in the same commit).

**Comment by jespercockx** [comment] 2019-10-07 16:38
It seems the problem has not reappeared, so I'm closing this issue.

**Closed as completed by jespercockx** 2019-10-07 16:38 UTC
Labels: ux: emacs, ux: highlighting, regression on master
