### ISSUE TITLE
Add UHC backend tests to Travis

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1475] opened 2015-08-08 18:17 UTC
Move the tests from https://github.com/phile314/agda-compiler-tests into the 
Agda repository.

The tests target MAlonzo and the UHC backend. Executing the tests for the UHC backend requires that UHC is installed and the Agda UHC backend is enabled.

This will pull in the tasty-silver/tasty packages for executing this tests.

(Also, should this be enabled on travis? The 50min build limit is already reached sometimes...)

Original issue reported on code.google.com by `philipp....@gmail.com` on 31 Mar 2015 at 11:56

**Comment by asr** [comment] 2015-12-03 17:42
Following the instructions in http://agda.readthedocs.org/en/latest/tools/compilers.html#uhc-backend  I installed UHC and I also installed Agda using

``` bash
$ cabal install Agda -fuhc
```

Now, running `make compiler-test` I see

``` bash
$ make compiler-test
...
UHC
      simple
        Arith:                 DISABLED
...
```

Shouldn't be the UHC back-end enable after installing Agda using the `-fuhc` option?

**Comment by phile314** [comment] 2015-12-03 19:00
The problem is that the user manual says how to install Agda with the UHC backend to be able to just use it, and it is aimed solely at users of Agda, not developers of Agda itself.

If you are developing Agda, calling "make" should do trick. If the "uhc" binary exists and is in $PATH, it will automatically enable the UHC backend. You can try "uhc --version" to see if the binary is in $PATH.

I will add this text to the HACKING file as well.

**Comment by asr** [comment] 2015-12-03 20:20
> The problem is that the user manual says how to install Agda with the UHC backend to be able to just use it, and it is aimed solely at users of Agda, not developers of Agda itself.

I shouldn't mix users and developers stuff.

> If you are developing Agda, calling "make" should do trick. If the "uhc" binary exists and is in $PATH, it will automatically enable the UHC backend. You can try "uhc --version" to see if the binary is in $PATH.

You are right, after installing UHC running `make install-bin` (or `make`) fix the problem.

> I will add this text to the HACKING file as well.

Please mention that UHC should be installed before running `make install-bin` and also add the instructions for installing UHC.

**Comment by asr** [comment] 2015-12-03 20:29
> Please mention that UHC should be installed before running make install-bin and also add the instructions for installing UHC.

I just saw that you added this information. Thanks!

**Comment by asr** [comment] 2016-01-29 17:13
> I will investigate if I can make precompiled UHC binaries available for the Agda travis instance.
> 
> I plan to investigate if NIX can be used for the travis tests to get precompiled binaries for UHC. I will do this after the next NIXPKGS release, which should be in about a month from now I think.

Any news on this front? It is necessary to add the UHC tests to Travis.

@phile314 I'll assign you this issue.

**Comment by np** [comment] 2016-01-29 20:47
What are you waiting from the next nix version? I would say that nix-copy-closure should do most of the work for such a case.

**Comment by phile314** [comment] 2016-02-02 20:45
I hoped that UHC would be in the next Nixpkgs release, which would provide us with UHC binaries for free. UHC is in Nixpkgs now, but due some other issues (https://github.com/UU-ComputerScience/uhc/issues/69 , https://github.com/NixOS/nixpkgs/pull/12674 ) Nixpkgs doesn't provide binaries.

I can build the closure on my computer and upload it somewhere (e.g. dropbox) for Travis, but that is too fragile in my opinion.

**Comment by asr** [comment] 2016-02-16 23:32
Since it seems only @phile314 and me are testing the UHC back-end (please correct me if I'm wrong), I added the `2.5.1` milestone because we shouldn't release a new broken feature.

**Comment by phile314** [comment] 2016-02-17 07:45
I assume you mean that #1854 shows that we really should run the UHC tests on travis?

I fully agree, but I'm rather busy right now so it probably will take some time. I don't think this will make it in time for the 2.5.1 release.

**Comment by asr** [comment] 2016-02-17 14:55
> I assume you mean that #1854 shows that we really should run the UHC tests on travis?

Yes.

**Comment by UlfNorell** [comment] 2016-02-17 15:09
At least I'm also running the UHC backend tests now, which should help a lot since I'm responsible for around 98% of breakage.

**Comment by asr** [comment] 2016-02-17 15:16
Mmm... 98%? What am I missing? :-)

**Comment by asr** [comment] 2016-02-23 12:18
Travis doesn't support GHC 7.10.\* (#1502).  I removed the 2.5.1 milestone.

**Comment by asr** [comment] 2016-03-24 11:16
#1502 was fixed, so the Travis builds include GHC 7.10.3.

I'll try to install UHC on Travis...

**Comment by phile314** [comment] 2016-03-24 11:25
You have to compile UHC itself (~250 modules), UHC-light (~250 modules), Agda (~300 modules). I would be surprised if this is feasible in the travis time limit, but it might be worth a try. Don't let me stop you in any case. There is also no binary UHC distribution, so there is no easy way out.

I also heard rumors that Rackspace and Microsoft Azure offer some free resources for open source projects, but then we would have to setup our own CI environment. I'm rather reluctant to do that as it would require some maintenance effort.

**Comment by asr** [comment] 2016-03-24 11:42
> You have to compile UHC itself (~250 modules), UHC-light (~250 modules), Agda (~300 modules). I would be surprised if this is feasible in the travis time limit, but it might be worth a try. 

The time limit of 120 min (I couldn't find a reference for this information) should be enough...

**Comment by asr** [comment] 2016-03-24 20:34
The time limit of 120 min was barely enough (the Travis build needed 106 min). Since the times of the Travis builds are variables and since #1844 hasn't been fixed (to compile the standard library with UHC will require more time), we need a precompiled version of UHC for adding the UHC backend tests to Travis.

**Comment by asr** [comment] 2016-03-24 20:47
In addition, based on the last releases of GHC, I won't be surprised if the time required by GHC 8.0.1 is bigger.

**Comment by Blaisorblade** [comment] 2016-06-11 20:34
Isn't UHC indeed tested on Travis? Closing, please reopen if I'm wrong.

**Comment by asr** [comment] 2016-06-11 23:22
> Isn't UHC indeed tested on Travis?

No.

**Comment by UlfNorell** [comment] 2017-02-24 19:29
Due to #2431.

**Closed as completed** 2017-02-24 19:29 UTC
Labels: type: enhancement, infra: test suite, travis
