### ISSUE TITLE
Equality checking uses too much memory in 2.6.0 (compared to 2.5.4)

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#4044] opened 2019-08-29 13:53 UTC
The test below constructs two large identical trees (with dummy function types in each branch) and compare them for definitional equality. In Agda 2.5.4.1 it takes 49 seconds and a very small and constant amount of memory (42 MB), whereas in Agda 2.6.0.1 it takes 3 minutes and 42 seconds and memory usage peaks at 8 GB.

Without the `A → B → C → D → ` parts, Agda 2.6.0.1 does not use any excessive amount of memory.

Agda 2.6.1 as of today does not do any better than Agda 2.6.0.1 (peak memory usage at 10G).

```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality
open import Agda.Builtin.Unit

postulate
  A B C D : Set

data Tree : Set where
  leaf : Tree
  node : (A → B → C → D → Tree) → (A → B → C → D → Tree) → Tree

tree1 : Nat → Tree
tree1 zero = leaf
tree1 (suc n) = node (λ _ _ _ _ → tree1 n) (λ _ _ _ _ → tree1 n)

tree2 : Nat → Tree
tree2 zero = leaf
tree2 (suc n) = node (λ _ _ _ _ → tree2 n) (λ _ _ _ _ → tree2 n)

test : tree1 18 ≡ tree2 18
test = refl
```

**Comment by nad** [comment] 2019-08-31 20:19
You can perhaps track down a problematic commit by running the following command in a fresh clone of the Agda repository:
```
agda-bisect --good v2.5.4.1 --bad v2.6.0.1 --log log --timeout 80 --no-default-cabal-options Bug.agda
```
(If the code above is saved in `Bug.agda` and the GHC on your path can build both Agda 2.5.4.1 and 2.6.0.1. It might make sense to first try with `--dry-run agda-2.5.4.1` and `--dry-run agda-2.6.0.1`.)

**Comment by guillaumebrunerie** [comment] 2019-09-02 09:36
I did the bisection and the result is the following (@jespercockx):

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
b42ac7eb50eec4309fa9940f41af94ec5657bc7c
832dffbc8b0f25dd4ad658964748fb373210c580
e060f2d4eba82ed5cce2107e8b6e0862d4c8fdea
c487b8a2bea1244113e2d6d581ce0b6b76b50e9d

**Comment by guillaumebrunerie** [comment] 2019-09-02 11:23
So this is apparently related to #3446, and commit c487b8a is most likely the culprit (the other three are refactoring commits)

**Comment by nad** [comment] 2019-09-02 12:15
The following code looks suspicious to me:

https://github.com/agda/agda/blob/957f54f8405c0add88391fca543a71fe14c89795/src/full/Agda/TypeChecking/Monad/Context.hs#L191-L198

It seems as if every time this instance of `addCtx` is run something is done for all names in the context. This could lead to quadratic behaviour.

**Comment by nad** [comment] 2019-09-02 13:27
Commenting out lines 193-197 seems to fix the regression. (Now the example can be type-checked in roughly 50 s, using 1 MB of memory, on my machine.)

**Comment by UlfNorell** [comment] 2019-09-04 10:20
Specifically, it's this `addContext` in the conversion checker that is the culprit:
https://github.com/agda/agda/blob/96d0dd00b696b381d87972ec78c4de31ff20b414/src/full/Agda/TypeChecking/Conversion.hs#L316-L318
Changing `name` to `"_" :: String` makes the example check in constant memory.

**Comment by nad** [comment] 2019-09-04 10:39
This kind of construction, with `suggests` and `addContext`, is used in two other places as well:

https://github.com/agda/agda/blob/96d0dd00b696b381d87972ec78c4de31ff20b414/src/full/Agda/TypeChecking/Conversion.hs#L691-L692

https://github.com/agda/agda/blob/96d0dd00b696b381d87972ec78c4de31ff20b414/src/full/Agda/TypeChecking/CheckInternal.hs#L182-L183

**Comment by nad** [comment] 2019-09-04 10:43
But I see that `suggests` returns a `String`, so I guess the use of this function isn't so interesting.

**Comment by jespercockx** [comment] 2019-09-24 14:17
I am trying to find a way to fix this issue but I cannot think of a simple way to remove the quadratic behaviour. The problem is that the new machinery to avoid shadowing relies on `addContext` as a kind of 'lookahead' to predict which names are shadowing a given name. Ideally, this should be restricted to just the pretty-printer. However there are often many independent calls to `prettyTCM`, and each individual call does not have sufficient information to determine whether a variable is shadowed. 

I discussed the problem offline with @nad but we did not yet come to a conclusion as to what would be a good solution. One piste we discussed was to limit the extra work in `addContext` to apply only when actually pretty-printing. Another one was to find a better datastructure that can store the currently quadradic shadowing map in (quasi)linear space.

**Comment by nad** [comment] 2019-09-24 19:38
Some points based on our discussion:
* The renaming strategy is underspecified, and it might make sense to change it. (Not only because it is buggy. @jespercockx, could you report the bug that you encountered?)
* A partial specification:
  * There should be no shadowing in pretty-printed terms/contexts.
  * Free variables that are in scope should not be renamed.

  An example: Consider `λ x → (? , λ x → ?)`. In order to avoid shadowing this term could be pretty-printed as `λ x₁ → (? , λ x → ?)` or `λ x → (? , λ x₁ → ?)`. In either case at least one variable is renamed. When printing the context from the view of the first goal the outermost `x` should not be renamed, and when printing the context from the view of the second goal the innermost `x` should not be renamed.

**Comment by jespercockx** [comment] 2019-09-25 08:15
> @jespercockx, could you report the bug that you encountered?

Yes, I reported it here: https://github.com/agda/agda/issues/4107

**Closed as completed** 2019-10-07 12:10 UTC
Labels: performance, ux: printing, names, regression in 2.6.0
