### ISSUE TITLE
Standard library no longer checks on master

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#1784] opened 2016-01-18 20:08 UTC
I just pulled master, and I get the following error:

```
~/agda-stdlib/src/Data/Maybe/Base.agda:95,1-25
T (is-just nothing) should be empty, but that's not obvious to me
when checking that the clause to-witness-T nothing () has type
{p : Level} {P : Set p} (m : Maybe P) → T (is-just m) → P
```

The spot in question (in `Data/Maybe/Base.agda`) is here:

``` agda
to-witness-T : ∀ {p} {P : Set p} (m : Maybe P) → T (is-just m) → P
to-witness-T (just p) _  = p
to-witness-T nothing ()
```

To be honest, the current algorithm actually does make more sense to me here (it's not pattern-matchingly-obvious to me that `to-witness-T nothing ()` is a valid absurd pattern, though I can arrive at that conclusion if I dig for a minute), so perhaps it's the library which should be updated?

**Comment by UlfNorell** [comment] 2016-01-19 05:42
How is that not obviously absurd? `T (is-just nothing)` reduces to `⊥` doesn't it?

**Comment by jespercockx** [comment] 2016-01-19 10:13
Strange, I couldn't reproduce the problem with Agda at 9a1012a4123b1498ccd579f795cb34aaad9a13a1 and the standard library at e553454c42bc51ccf8e83c2144ad8a72d2cf2869. What version of the standard library are you using?

**Comment by identicalsnowflake** [comment] 2016-01-19 16:39
> How is that not obviously absurd? T (is-just nothing) reduces to ⊥ doesn't it?

You're right, I confused `is-just` with `Is-just` (defined in the preceding few lines). It does trivially reduce to bottom.

@jespercockx 

I made sure I had current Agda/std-lib versions just now and had the same problem, but after removing all `.agdai` files from my library directory and rebuilding, everything works fine now.

**Comment by andreasabel** [comment] 2016-01-19 22:41
Closing.  Please reopen if necessary.

**Closed as completed by andreasabel** 2016-01-19 22:41 UTC
