### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by nad** [agda/agda#5155] opened 2021-01-27 16:33 UTC
I have some code for which Agda runs out of memory on the first run, but is successful on the second run. This suggests that there is a memory leak. I think this should be investigated before the next release of Agda.

To reproduce (on my 32-bit system):
```
git clone https://github.com/agda/agda-stdlib.git
(cd agda-stdlib && git checkout cd0f00a797601bee5aa44e67cd6186b1805983b8)
git clone https://github.com/nad/equality.git
(cd equality && git checkout 2b0ec5fe3de5d3506e854300dd5fc5a854bdf794)
git clone https://github.com/nad/dependent-lenses.git
(cd dependent-lenses && git checkout a066b2aa7688c27030a272bfeff7de84ba430f1a)
printf "equality/equality.agda-lib\ndependent-lenses/dependent-lenses.agda-lib\nagda-stdlib/standard-library.agda-lib\n" > libraries
agda --no-default-libraries --library-file=libraries --library=dependent-lenses dependent-lenses/src/Lens/Non-dependent/Higher.agda +RTS -M1.7G
```
Agda runs out of memory, but the following invocation, where `1.7G` has been replaced by `1.5G`, succeeds:
```
agda --no-default-libraries --library-file=libraries --library=dependent-lenses dependent-lenses/src/Lens/Non-dependent/Higher.agda +RTS -M1.5G
```

**Comment by nad** [comment] 2021-01-29 11:54
I get the same behaviour for 55ab6e656ea794c718c4af2eec6825696c4b12fc. My code is not accepted by b5df4047e223b41f5273165adfe91bb3ca0b3acb.

**Comment by uncle-betty** [comment] 2021-02-14 12:06
I think that I might have found a way to reproduce this on 64-bit Ubuntu 18.04 with GHC 8.10.4 and Agda cba188d:

* We'll toy around with two modules: top-level `Higher` and one of `Higher`'s direct imports, `Traditional`.
* Type-check `Higher.agda` with a generous heap limit, so that it completes. I'm using a limit of 6.0G.
* Remove `Traditional.agdai` and type-check `Higher.agda` again, now with a heap limit of 3.0G. It completes (and recreates `Traditional.agdai`).
* Remove `Higher.agdai` and type-check `Higher.agda` again, again with a heap limit of 3.0G. It completes as well (and recreates `Higher.agdai`).
* Remove both, `Traditional.agdai` as well as `Higher.agdai` and type-check `Higher.agda` again, again with a heap limit of 3.0G. This runs out of memory (after having type-checked `Traditional.agda` and recreated `Traditional.agdai`).

So, I guess, type-checking `Traditional.agda` and thus recreating `Traditional.agdai` results in more retained heap memory than simply loading `Traditional.agdai`.

If this is so, then maybe I should take a look at what heap memory retainers could possibly leak outside through the isolation of `createInterfaceIsolated` when type-checking `Traditional.agda`.

**Comment by uncle-betty** [comment] 2021-02-14 16:47
I didn't see anything leaking out of `createInterfaceIsolated`, so I went on to look for unevaluated thunks that might be piling up.

And, actually, it seems like my out-of-memory situation is fixed by making the `stDecodedModules` field of the persistent state record (`PersistentTCState`) strict (i.e., change its type to `!DecodedModules`). Here's what led me to trying this:

* When provoking an out-of-memory crash by removing both, `Traditional.agdai` as well as `Higher.agdai`, the last two things that are done to `stDecodedModules` are:
  - `setDecodedModules` in `createInterfaceIsolated` (to set it to `newDecodedModules`)
  - `storeDecodedModule` in `alreadyVisited` (to add the interface for `Traditional` that was just created)
* In particular, these two things aren't followed by a `getDecodedModule` for a subsequent module, which would force the `stDecodedModules` field. (It would, wouldn't it?) `Traditional` is the last module imported by `Higher`, so subsequently there aren't any modules to be looked up in `stDecodedModules`. Hence no subsequent `getDecodedModule`.

That said, I'm a little reluctant to suggest making `stDecodedModules` strict, as I'm not sure that I understand all the implications this might have elsewhere. Maybe it would be preferable to manually force the field after a `storeDecodedModule`?

Also, let's maybe make sure that I'm actually reproducing the original issue. @nad, how far does the type-check proceed in your case before it runs out of memory? In my case, it finishes `Traditional` and then aborts while working on `Higher`. So, after the crash, `Higher.agdai` is the only missing interface file. Is this how far you get as well?

**Comment by uncle-betty** [comment] 2021-02-14 20:52
Actually, after poking around in the code a little more, I am more confident that `stDecodedModules` can be made strict without any adverse effects.

During a type-check, one import's `setDecodedModules` / `storeDecodedModule` is followed pretty much right away by the next import's `getDecodedModule`, which forces `stDecodedModules`. So, de facto, the field is pretty strict already.

The exception to this pattern is the last import, which isn't followed by a subsequent import's `getDecodedModule`. So, this is the only place where we'd make the field noticeably stricter. Which is exactly what we want, because the lack of strictness for the last import is what's causing all the trouble at the moment.

**Comment by uncle-betty** [comment] 2021-02-15 12:04
Just to obsess a little more about potential performance implications, I looked at build times for the standard library, with and without the proposed fix, two runs each:

* Without - 10:55 min, 11:13 min
* With - 11:03 min, 10:54 min

Identical within the margin of error, I'd say.

Alright, I think that it's safe to assume that the horse has passed away by now. :)

**Comment by UlfNorell** [comment] 2021-02-17 13:10
Is there a PR incoming for this?

**Comment by uncle-betty** [comment] 2021-02-17 14:10
Yes, absolutely. Let's just wait for @nad to say whether his observed symptoms match what I reproduced. If they don't then there must be another issue and I'll keep digging.

**Comment by nad** [comment] 2021-02-18 18:33
> @nad, how far does the type-check proceed in your case before it runs out of memory? In my case, it finishes `Traditional` and then aborts while working on `Higher`. So, after the crash, `Higher.agdai` is the only missing interface file. Is this how far you get as well?

Yes.

I think it would make sense to make many record fields (and other things) strict.

**Comment by uncle-betty** [comment] 2021-02-19 07:34
Thanks, @nad, for confirming. I'm preparing a pull request.

Just record fields? I think it would make sense to make the whole language strict! :-)

Kidding aside, I feel like I don't know enough about Agda internals to make an educated decision on which record fields to make strict. So, I'll just fix the issue at hand for now.

**Comment by jespercockx** [comment] 2021-02-19 08:40
I experimented with making some other fields strict on https://github.com/jespercockx/agda/tree/issue4521-more-strictness. While it didn't seem to make a difference for the issue I was trying to fix, I think it would generally be a good idea to make all fields of the global TCM state strict, and to use strict data structures for their types (otherwise adding the strictness doesn't do much).

**Comment by nad** [comment] 2021-02-19 10:22
> While it didn't seem to make a difference for the issue I was trying to fix

If it does not seem to affect performance, then it might be a good idea to keep these changes, to reduce the risk of problems like the one discussed in this ticket.

**Comment by jespercockx** [comment] 2021-02-19 10:40
What I meant was that it did not get rid of the memory leak; I did not do any other kind of benchmarks so I'm unsure how it impacts overall performance.

**Comment by uncle-betty** [comment] 2021-02-19 12:25
Just to add to @jespercockx's "otherwise the strictness doesn't do much": I *am* indeed a little surprised about just how effective my fix is, i.e., about just how much of a difference it makes to just make the field strict, without actually using a map that's strict in its values.

This is why:

* Suppose that the `stDecodedModules` field contains a map `m`.
* Suppose that the field is lazily set to a map `m'`. In my mental model, as long as the field isn't forced, there's now a thunk that references `m` as well as `m'`.
* When the field gets forced, the thunk is evaluated, its reference to `m` goes away, and `m` can be garbage-collected. Now we are left with only `m'` on the heap.
* The issue is that in certain cases the field never gets forced, because there aren't any subsequent map lookups that would force it. `m` thus can't be garbage-collected, taking up extra memory forever. That's why making the field strict fixes the issue: it ensures that the field is forced in all cases, i.e., that `m` always gets garbage-collected.
* What I don't understand: `m'` is just `m` with additional insertions. You'd think that `m'` and `m` share most of their structure, owing to persistent data structures. Why is it so much more expensive memory-wise to keep `m` around in addition to `m'`?

**Comment by nad** [comment] 2021-02-19 12:55
> * Suppose that the field is lazily set to a map `m'`. In my mental model, as long as the field isn't forced, there's now a thunk that references `m` as well as `m'`.

I guess you assume that `m'` is constructed using `m`.

> * What I don't understand: `m'` is just `m` with additional insertions. You'd think that `m'` and `m` share most of their structure, owing to persistent data structures. Why is it so much more expensive memory-wise to keep `m` around in addition to `m'`?

Perhaps the thunk contains pointers to other things as well (like lots of irrelevant data related to the recently type-checked module).

**Comment by uncle-betty** [comment] 2021-02-20 08:35
Oh, right. Yes. I guess it's not safe to assume that we're only keeping `m` around, i.e., to assume that the projection has already been evaluated. Maybe, instead, we're keeping the state around, of which `m` is a part.

Great! Now I feel good about the fix. A part of me was still a little worried that it just masked the actual root cause. Thanks!

**Comment by nad** [comment] 2021-02-25 15:04
Can we create a small test case for this issue?

**Comment by uncle-betty** [comment] 2021-02-26 15:55
I agree that this would be useful, but I am unable to come up with something that would be robust across GHC versions, build flags, or target platforms.

I was trying to come up with something along the lines of the #1829 test: figure out a way to run `setDecodedModules` / `storeDecodedModule` 1000 times without forcing `stDecodedModules`. Before the fix, this would make unevaluated thunks pile up and sooner or later - the exact number of required iterations probably depending on the GHC version, the build flags, or the target platform - we'd run into an OOM situation.

I can't find a way, though, to run said functions without a `getDecodedModule` in between, which forces `stDecodedModules`. So, we always have just one of the leaked unevaluated thunks before `getDecodedModule` ruins things. We can't pile up arbitrarily many of these tunks, AFAICS.

It looks like I need an `import` to modify `stDecodedModules`, but that `import` forces the modifications made by the previous `import`, because each `import` starts out by doing a `getDecodedModule`.

**Closed as completed** 2021-03-30 18:07 UTC
Labels: type: bug, performance, regression on master
