### ISSUE TITLE
internal error:  constructor Relation.Nullary.Dec.yes with fields [] projected by ...

### ISSUE THREAD

**Issue by mechvel** [agda/agda#1626] opened 2015-08-14 10:46 UTC
This is on  Development Agda of August 13, 2015,
            ghc-7.10.2.

Please, download the source from 

http://www.botik.ru/pub/local/Mechveliani/agdaNotes/bugRep-aug14-2015.zip

(~ 40 Kb).
(for I do not know how to attach  a code here).

> unzip bugRep-aug14-2015.zip
> agda $agdaLibOpt +RTS -K100m -M7G -RTS  List/AssocList0.agda

reports

---

...
...
Skipping List.L1 (/home/mechvel/doconA/0.04/reports/aug14-2015/List/L1.agdai).
conApp: constructor Relation.Nullary.Dec.yes with fields [] projected by 
Relation.Binary.DecSetoid.Carrier
An internal error has occurred. Please report this as a bug.

**Comment by asr** [comment] 2015-08-14 17:17
Duplicate of https://github.com/agda/agda/issues/1407.

**Comment by andreasabel** [comment] 2015-10-28 18:34
@mechvel can you please check whether this works after the fix of #1407?

**Comment by mechvel** [comment] 2015-10-28 19:08
Sadly, I have lost this file.
I have seen "duplicate of ..." and "closed", and after this I have deleteted my example from everywhere.
I think now that this deletion was erroneous. Because after #N is fixed, one has to try the issues that have been copied to #N.

**Comment by andreasabel** [comment] 2015-10-29 09:41
@mechvel, @asr: Because this `internal error in [...]Substitute.hs` points only to the violation of an internal invariant which can have many causes, one cannot conclude that the same cause triggered this message in different instances (and thus, is a duplicate).

So I am closing this issue.  Please do come back if you get a similar error again.

**Closed as completed by andreasabel** 2015-10-29 09:41 UTC
