### ISSUE TITLE
CI Windows: adding MSYS2 to PATH breaks cache action

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6501] opened 2023-02-12 09:00 UTC
This step:
https://github.com/agda/agda/blob/e018e58453a06e4c4a15c9b81396cbcd1e2c640f/src/github/workflows/cabal.yml#L124-L129

This consequence: https://github.com/agda/agda/actions/runs/4112460687/jobs/7097403370#step:21:2
```
"C:\Program Files\Git\usr\bin\tar.exe" --posix -cf cache.tzst --exclude cache.tzst -P -C D:/a/agda/agda --files-from manifest.txt --force-local --use-compress-program "zstd -T0"
/usr/bin/tar: cache.tzst: Cannot write: Broken pipe
/usr/bin/tar: Child returned status 127
/usr/bin/tar: Error is not recoverable: exiting now
Warning: Failed to save: "C:\Program failed with error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2
```

Refs:
- https://github.com/actions/cache/issues/1092
- https://github.com/actions/cache/issues/1073

**Comment by mmuetzel** [comment] 2023-02-12 09:52
One workaround until this is properly fixed in the cache action upstream would be to pin the cache action to `v3.2.2` (which is using Windows `tar` instead of the `tar` from Git for Windows).
That avoids the issue caused by the conflicting Cygwin derived runtime environments.

**Comment by andreasabel** [comment] 2023-02-12 19:58
@mmuetzel: Thanks for the hint about the pin!

I could actually solve this by a finer treatment of the MSYS2 PATH:
- `C:\msys64\mingw64\bin`: This one is benign so we can add it to the PATH globally.  We need it for the MSYS2-installed `pkg-config`, which is invoked  in several places, directly and from `cabal`.
- `C:\msys64\usr\bin`: This upsets the cache action. We need this only for `pacman`, so we can add it locally only to the ICU installation step.

Cost me many hours of fiddling with CI (as so often), but I gained some more (modest) insights into the woes of installing ICU on Windows.  Hopefully also a pinch of more robustness of the CI.

**Closed as completed** 2023-02-12 20:10 UTC
Labels: platform: windows, infra: github workflows
