### ISSUE TITLE
Allow unsolved metas in `where` clauses if they are not used with `--safe`

### ISSUE THREAD

**Issue by Trebor-Huang** [agda/agda#5782] opened 2022-02-09 08:27 UTC
Sometimes for illustration purposes (especially in literate Agda), I would like to leave holes in some parts of the program. They will not eventually be used, so it is probably safe. But `--allow-unsolved-metas` cannot coexist with `--safe`.

Of course, one ultimate workaround is to stop using `--safe`, or just make a copy of the file without the illustrative holes. But maybe we can relax the requirement of `--safe` so that if a hole can be seen to be definitely out of scope (more accurately, no expressions in other files may depend on this hole), it is not counted when checking for open interaction points. One situation is in simple `where` clauses. But probably we can work out an explicit list of allowed situations.

**Comment by nad** [comment] 2022-02-09 09:23
I don't think we should allow something like this. When you are using `--safe` and the file is checked successfully it should be clear that everything that you see is type-correct (if we ignore bugs).

**Comment by nad** [comment] 2022-02-14 15:57
There was no further input, so I'm closing this issue.

**Closed as completed by nad** 2022-02-14 15:57 UTC
Labels: status: duplicate

**Comment by andreasabel** [comment] 2022-02-19 16:48
A similar request is in 
- #5098.

I disagree that everything is _working as intended_.

**Comment by nad** [comment] 2022-02-20 15:47
You asked for something different in the other issue: "It should be an error to have an unsolved meta either if `--safe` is on or if `--allow-unsolved-metas` is off, but it should not be an error just to have both `--safe` and `--allow-unsolved-metas` in sight." If you want to support something along the lines of what is suggested in the OP, please either reopen this issue or add a note to the other issue.
