### ISSUE TITLE
Command to insert lowest Level a record / inductive type can live at

### ISSUE THREAD

**Issue by gallais** [agda/agda#3440] opened 2018-12-07 14:41 UTC
`C-c C-s` can't solve these because the solution is not unique. However there is
enough information around to generate the lowest level the definition can live at.
So we should add a command to ask Agda to fill that in.

```agda
open import Agda.Primitive

data Pair {a b : Level} (A : Set a) (B : Set b) : Set {!!} where
  _,_ : A → B → Pair A B


record Pair' {a b : Level} (A : Set a) (B : Set b) : Set {!!} where
  constructor _,_
  field fst : A
        snd : B
```

**Comment by jespercockx** [comment] 2019-11-18 09:19
Duplicate of #2427

**Closed as completed by jespercockx** 2019-11-18 09:19 UTC
Labels: status: duplicate, type: enhancement, ux: interaction, levels
