### ISSUE TITLE
Allow underscore pattern _ to stand for inaccessible pattern.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1605] opened 2015-08-08 18:19 UTC
See https://lists.chalmers.se/pipermail/agda/2015/007917.html

On 06.07.2015 09:33, Andreas Abel wrote:

> If you define transitivity of propositional equality without hiding
> value arguments, you have to explicitly choose where to put the dots:

``` agda
    transV1 : ∀{A : Set} (a b c : A) → a ≡ b → b ≡ c → a ≡ c
    transV1 _ ._ ._ refl refl = refl

    transV2 : ∀{A : Set} (a b c : A) → a ≡ b → b ≡ c → a ≡ c
    transV2 ._ _ ._ refl refl = refl

    transV3 : ∀{A : Set} (a b c : A) → a ≡ b → b ≡ c → a ≡ c
    transV3 ._ ._ _ refl refl = refl
```

> With hidden arguments, you need not care:

``` agda
    transH : ∀{A : Set}{a b c : A} → a ≡ b → b ≡ c → a ≡ c
    transH refl refl = refl
```

> Of course, when giving the hidden arguments, it is the same as for
> visible arguments:

``` agda
    transH1 : ∀{A : Set}{a b c : A} → a ≡ b → b ≡ c → a ≡ c
    transH1 {a = _}{b = ._}{c = ._} refl refl = refl
    ...
```

> The user has more flexibility when an argument is hidden.  When an argument is given, the user has to actively make a decision whether a pattern must be a dot pattern or must not be one.  There is no "I don't care, please figure it out for me" as there is for hidden arguments. This seems to be a mismatch.
> 
> I think it would be simpler for the user if pattern `_` stood for "don't care" rather than "unnamed variable".  The need for writing `._` would vanish.
> 
> Does anything speak against this change?  Is there a situation where it is essential to tell Agda not to let something be a dot pattern in order for type-checking to succeed?  (In the end this could still be done by writing a named variable instead of _!)
> 
> Internally, Agda has four kinds of trivial patterns:

```
    DotP       ._ is (DotP MetaVariable)
    VarP       x  is (VarP "x") where x cannot be "_"
    WildP      _  is WildP
    ImplicitP  the user wrote no pattern (argument is hidden)
```

> The change would be to let _ stand for ImplicitP, which can become either a dot pattern or a variable pattern (or a record pattern if issue 473 is fixed). 

On 06.07.2015 23:03, Ulf Norell wrote:

> I don't see any obvious problems with having _ mean ImplicitP. There might be something to be said for being explicit about the fact that a visible argument is dotted, but since it's clearly confusing people it's probably better to change it.
> 
> / Ulf

On Mon, Jul 6, 2015 at 11:02 AM, Andreas Abel wrote:

>  Agda only case splits when there is a literal, constructor or absurd pattern.  Variable and dot pattern do not induce splitting.
> 
>  Allowing _ to become a dot pattern would make it easier to explain hidden patterns, e.g. transH below could be said to simply mean 

``` agda
        transH {A = _}{a = _}{b = _}{c = _} refl refl = refl
```

> Currently, it is magic, meaning either of three things.

On 06.07.2015 10:33, Andrea Vezzosi wrote:

> The need for "._" is certainly something that puzzles people learning Agda, this change would help for that.
> 
> It makes "_" just a bit more special which might make it less intuitive in other ways, but as long as it's a backwards compatible change I think it's a good one.
> 
> Do the dot patterns affect the generated case splitting tree? If so some proofs might break.

On Mon, Jul 6, 2015 at 10:25 AM, Andreas Abel wrote:

> P.S.: The standard library checks fine if one let _ stand for ImplicitP.

Original issue reported on code.google.com by `andreas....@gmail.com` on 7 Jul 2015 at 8:38

**Comment by UlfNorell** [comment] 2015-08-19 07:01
The example above checks for me. Has this been fixed?

**Comment by andreasabel** [comment] 2015-08-19 09:36
Indeed, this works now, but the following fails:

``` agda
postulate
  C : Set
  anything : C

record I : Set where
  constructor c
  field
    f : C

data Wrap : (j : I) → Set where
  wrap : ∀ {j} → Wrap j

works1 : ∀ {j} → Wrap j → C
works1 {c ._} (wrap {c _}) with anything
... | z = z
```

```
Failed to infer the value of dotted pattern
when checking that the pattern ._ has type C
```

**Comment by UlfNorell** [comment] 2015-08-19 14:57
Is that really a problem? I'm assuming it works if you replace `._` by `_`, so you could argue that you shouldn't ever use `._`.

**Comment by andreasabel** [comment] 2016-01-07 11:06
Maybe this will eventually be fixed by @jespercockx new unifier.

**Comment by jespercockx** [comment] 2016-01-07 12:42
Well, AFAICT this _should_ be fixed by my new unifier, but there's still a problem when using dot patterns and with together. I think the problem is that when checking the child pattern, the dot pattern instantiations of the parent pattern are missing, so my `checkLeftoverDotPatterns` function doesn't have anything to work with.

**Comment by asr** [comment] 2016-02-04 13:30
@andreasabel why this issue has the 'regression' label?

**Comment by andreasabel** [comment] 2016-02-04 16:12
Because the last example worked on Agda prior to the changes for this issue.

**Comment by andreasabel** [comment] 2016-11-18 16:16
Maybe something can be done about this issue after fix of #2297 and #2303? @UlfNorell @jespercockx

**Comment by asr** [comment] 2016-12-07 13:03
I see the release of 2.5.2 is close :+1:. This issue is the only one labelled with 'regression' but without the 2.5.2 milestone. It would be great if this regression is fixed before the release.

**Comment by UlfNorell** [comment] 2016-12-07 13:38
This is a won't-fix. Making the unifier jump through hoops to respect where the user put the dots is not worth the effort. The user should just leave the dotting to the unifier.

**Comment by jespercockx** [comment] 2016-12-07 14:09
Well I was just taking another look at this issue. One way to fix it is to remove the check from `checkLeftoverDotPatterns` that ensures degenerate dot patterns of the form `._` or `.x` where `x` is a variable have indeed been instantiated by the unifier. But then we need a different way to ensure that each variable is bound *somewhere* in the pattern (perhaps at an implicit position). 

I agree that this isn't very high priority, but I'll see if I can get something to work quickly...

**Comment by UlfNorell** [comment] 2016-12-07 15:17
> But then we need a different way to ensure that each variable is bound somewhere in the pattern (perhaps at an implicit position).

Are you thinking of something like

```agda
bad : (x y : Nat) → x ≡ y → Set
bad ._ ._ refl = Nat
```

**Comment by jespercockx** [comment] 2016-12-07 15:36
Well, it could be argued that's a good case, since there is still a possible binding spot for the variable as an implicit argument to `refl`. On the other hand, the following should really be prohibited:
```
bad : (x y : Nat) → x ≡ y → Set
bad ._ ._ (refl {x = ._}) = Nat
```

**Comment by UlfNorell** [comment] 2016-12-07 15:39
Only if you use the doubly indexed equality. The `refl` from `Agda.Builtin.Equality` doesn't let you bind the `x` since it's a parameter.

**Comment by jespercockx** [comment] 2016-12-07 15:39
Right, I was too fast. If you use single-indexed equality then your `bad` should also be rejected.

**Comment by jespercockx** [comment] 2016-12-07 17:46
I've tried my proposed solution but it still doesn't work. Here my analysis:

First the definition of works1 gets expanded to
```
works1 : ∀ {j} → Wrap j → C
works1 {c ._} (wrap {c _}) with anything
works1 {c ._} (wrap {c _}) | z = z
```
Then, the parent clause is checked and translated to internal syntax with LHS `works1 {c _} (wrap {c ._})`. Note that the dot has been moved to the second underscore! After that the second clause `
works1 {c ._} (wrap {c _}) | z = z` is checked. Since this clause contains an underscore where the parent clause contains a dot pattern, Agda assumes that the user really meant to write a dot pattern, i.e. the resulting clause is `works1 {c ._} (wrap {c ._}) | z = z`. But now there are two dot patterns, and the unifier only instantiated one, so Agda complains.

So the underlying issue here is that when there's an underscore or variable in a child pattern where the parent has a dot pattern, it's impossible to tell whether the user intended to *move* the dot to another place or *name* the term inside the dot pattern. Currently Agda assumes the latter, but sometimes it's shuffling around dots itself and subsequently gets mad because the dots are moved.

Maybe we could just replace all dot patterns with `_` when expanding the ellipsis of a with clause, that would at least prevent Agda from yelling at itself.

**Comment by jespercockx** [comment] 2016-12-07 18:04
Even replacing dot patterns with underscores doesn't work because in the concrete syntax there is no distinction yet between dot patterns and postfix projections, but we don't want to replace *those* by underscores of course.

**Comment by UlfNorell** [comment] 2016-12-07 18:16
Wouldn't you do the replacement in abstract syntax though?

**Comment by jespercockx** [comment] 2016-12-08 13:09
Well, the ellipsis are already expanded in the concrete syntax, and after that there is no way to tell which part of the pattern was expanded from the ellipsis. Or do you mean to replace *all* the dot patterns in a child clause if they already occurred in the parent clause? That could maybe also work, though I'd be afraid that this would also allow definitions with too many dots, for example
```
works1 : ∀ {j} → Wrap j → C
works1 {c ._} (wrap {c _}) with anything
works1 {c ._} (wrap {c ._}) | z = z
```

**Comment by andreasabel** [comment] 2016-12-08 14:25
It might be beneficial maybe to keep the Ellipsis in the abstract syntax, or mark patterns as originating from an ellipsis (also in the abstract syntax).  Maybe the existing `Origin` machinery can be adapted to this purpose?

**Closed as completed** 2016-12-08 18:58 UTC
Labels: type: bug, pattern matching, dot patterns, unification, regression on master

**Comment by jespercockx** [comment] 2016-12-08 18:59
I fixed the problem when using ... by keeping track of the origins as Andreas proposed. The remaining problems (where the user repeats the parent dot patterns explicitly) are instances of #1608, so I propose we continue the discussion there.

**Comment by andreasabel** [comment] 2016-12-09 09:23
Thanks for fixing!!

(See my requests for documentation in the patch comments.)
