### ISSUE TITLE
Strange equation involving transp and postulate

### ISSUE THREAD

**Issue by jonsterling** [agda/agda#5331] opened 2021-04-20 00:51 UTC
I was a bit surprised by the following behavior, in which postulated type constants seem to exhibit some form of regularity:

```agda
{-# OPTIONS --cubical #-}

open import Cubical.Foundations.Prelude
open import Agda.Primitive

good : (A : Type) (ϕ : I) (a : A) → transp (λ _ → A) ϕ a ≡ a
good A ϕ a = {!!} -- good: can't fill this in with refl


postulate
  T : Type

strange : (ϕ : I) (a : T) → transp (λ _ → T) ϕ a ≡ a
strange ϕ a = refl -- surprising that this works
```

I would have expected that the definiens of `strange` wouldn't type check, based on my (limited) understanding of Agda's intended semantics. The reason I was surprised by this was I felt that in principle, it should be sound (in theory) to take a development in Agda and substitute for its postulates.

**Comment by Saizan** [comment] 2021-04-23 10:57
My approach was that it should only be fine to substitute postulates for closed terms/global elements that take the module parameters as arguments. This is how they interact with the `@flat` modality as well.

In that case T might as well be given a "regular" transport structure, right? But I guess it doesn't have to.

Anyway this regularity trips people up enough that I should change it, in fact this is a duplicate of #4365.

**Closed as completed by Saizan** 2021-04-23 10:57 UTC
Labels: status: duplicate, cubical, postulate
