### ISSUE TITLE
piApply fails when printing open metas

### ISSUE THREAD

**Issue by Twey** [agda/agda#1783] opened 2016-01-17 17:57 UTC
The attached file produces an error:

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Substitute.hs:368
```

[Categories.Functor.ProductPreserving.agda.txt](https://github.com/agda/agda/files/93532/Categories.Functor.ProductPreserving.agda.txt)

It seems that Agda (2.4.2.4) encounters an error when attempting to check the type of `map-obj`.

**Comment by asr** [comment] 2016-01-17 18:44
The same internal error (see #1725) was fixed in Agda 2.4.2.5. Can you reproduce the issue with this version of Agda?

**Comment by Twey** [comment] 2016-01-17 22:25
2.4.2.5 gives:

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Substitute.hs:374
```

**Comment by asr** [comment] 2016-01-17 22:36
I can't test your attached file because there are some missing modules.

**Comment by andreasabel** [comment] 2016-01-18 16:48
@Twey please submit a self-contained reproducible test case (does not have to be minimal, a big test case is better than none).

**Comment by Twey** [comment] 2016-01-19 02:48
Here's a ‘minimal’ working example with no external dependencies:
[error.agda.txt](https://github.com/agda/agda/files/95264/error.agda.txt)

I had difficulty getting it smaller than this.

**Comment by andreasabel** [comment] 2016-01-19 14:04
Thanks a lot!  Here a tiny variation:

``` agda
Rel : Set → Set₁
Rel A = A → A → Set

record Category : Set₁ where
  field
    Obj : Set
    _⇒_ : Rel Obj -- unfolding the definition of Rel removes the error

record Product (C : Category) (A B : Category.Obj C) : Set where
  field
    A×B : Category.Obj C

postulate
  anything : ∀{a}{A : Set a} → A

trivial : ∀ {C} → Category.Obj C → Set
trivial _ = anything

map-obj : ∀ {P : _} → trivial (Product.A×B P) -- Note: hole _ cannot be filled
map-obj = anything
```

The error could be somehow connected to the fact that the `_` has no solution!?  Writing `Product _ _ _` there makes the crash disappear and gives yellow.

**Comment by Twey** [comment] 2016-01-19 14:36
Yeah, it shouldn't succeed, but presumably also shouldn't give an internal error =P
The Rel thing is very odd, though. I assumed before that it was just map-obj that triggers the error, but substituting A → A → Set gets rid of the error, even though that Rel isn't used anywhere.

**Comment by andreasabel** [comment] 2016-01-19 16:42
What is happening is that during printing of open metas, a `piApply (Rel _) x` fails (for x being `var 0`).  This is because `piApply` expects `Rel _` to be already unfolded into `_ -> _ -> Set`.  Somewhere `piApply` is used without ensuring that the type is already reduced.

**Closed as completed** 2016-01-19 23:43 UTC
Labels: type: bug, type-checking
