### ISSUE TITLE
Internal error in clause compiler

### ISSUE THREAD

**Issue by nad** [agda/agda#1872] opened 2016-02-23 21:04 UTC
```
-- The code below is partly based on Conor McBride's "Outrageous but
-- Meaningful Coincidences: Dependent type-safe syntax and
-- evaluation".

data _≡_ {a} {A : Set a} (x : A) : A → Set a where
  refl : x ≡ x

record Σ (A : Set) (B : A → Set) : Set where
  constructor _,_
  field
    proj₁ : A
    proj₂ : B proj₁

open Σ

postulate
  I  : Set
  U  : I → Set
  El : ∀ {i} → U i → Set

data Ctxt : Set

Type : Ctxt → Set

Env : Ctxt → Set

data Ctxt where
  _▻_ : (Γ : Ctxt) → Type Γ → Ctxt

Type Γ = Σ I λ i → Env Γ → U i

Env (Γ ▻ σ) = Σ (Env Γ) λ γ → El (proj₂ σ γ)

Value : (Γ : Ctxt) → Type Γ → Set
Value Γ σ = (γ : Env Γ) → El (proj₂ σ γ)

_⇨_ : Ctxt → Ctxt → Set
Γ ⇨ Δ = Env Δ → Env Γ

_/_ : ∀ {Γ Δ} → Type Γ → Γ ⇨ Δ → Type Δ
(i , σ) / ρ = i , λ γ → σ (ρ γ)

record [Type] : Set where
  constructor [_]
  field
    {Γ} : Ctxt
    σ   : Type Γ

_≅-Type_ : ∀ {Γ₁} (σ₁ : Type Γ₁)
             {Γ₂} (σ₂ : Type Γ₂) → Set
σ₁ ≅-Type σ₂ = [ σ₁ ] ≡ [ σ₂ ]

record [Value] : Set where
  constructor [_]
  field
    {Γ} : Ctxt
    {σ} : Type Γ
    v   : Value Γ σ

_≅-Value_ : ∀ {Γ₁ σ₁} (v₁ : Value Γ₁ σ₁)
              {Γ₂ σ₂} (v₂ : Value Γ₂ σ₂) → Set
v₁ ≅-Value v₂ = [Value].[_] v₁ ≡ [ v₂ ]

record [⇨] : Set where
  constructor [_]
  field
    {Γ Δ} : Ctxt
    ρ     : Γ ⇨ Δ

_≅-⇨_ : ∀ {Γ₁ Δ₁} (ρ₁ : Γ₁ ⇨ Δ₁)
          {Γ₂ Δ₂} (ρ₂ : Γ₂ ⇨ Δ₂) → Set
ρ₁ ≅-⇨ ρ₂ = [⇨].[_] ρ₁ ≡ [ ρ₂ ]

Foo : ∀ {Γ₁ Δ₁ σ₁} {ρ₁ : Γ₁ ⇨ Δ₁} {v₁ : Value Δ₁ (σ₁ / ρ₁)}
        {Γ₂ Δ₂ σ₂} {ρ₂ : Γ₂ ⇨ Δ₂} {v₂ : Value Δ₂ (σ₂ / ρ₂)} →
      σ₁ ≅-Type σ₂ → ρ₁ ≅-⇨ ρ₂ → v₁ ≅-Value v₂ → Set₁
Foo refl refl refl = Set
```

Result:

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/CompiledClause/Compile.hs:228
```

@jespercockx, the offending patch seems to be 1b0a2d6a27fd1dc2f89b3c4a18100335ee037a31.

**Comment by UlfNorell** [comment] 2016-02-24 10:16
Slightly simplified

``` agda
data _≡_ {a} {A : Set a} (x : A) : A → Set a where
  refl : x ≡ x

record Σ (A : Set) (B : A → Set) : Set where
  constructor _,_
  field
    proj₁ : A
    proj₂ : B proj₁

open Σ

postulate
  I  : Set
  U  : I → Set
  El : ∀ {i} → U i → Set
  Ctxt : Set
  Env  : Ctxt → Set

Type : Ctxt → Set
Type Γ = Σ I λ i → Env Γ → U i

Value : (Γ : Ctxt) → Type Γ → Set
Value Γ σ = (γ : Env Γ) → El (proj₂ σ γ)

_/id : ∀ {Γ} → Type Γ → Type Γ
(i , σ) /id = i , σ

data [Type] : Set where
  [_] : ∀ {Γ} → Type Γ → [Type]

_≅-Type_ : ∀ {Γ} (σ₁ σ₂ : Type Γ) → Set
σ₁ ≅-Type σ₂ = [ σ₁ ] ≡ [ σ₂ ]

data [Value] : Set where
  [_] : ∀ {Γ σ} → Value Γ σ → [Value]

_≅-Value_ : ∀ {Γ σ} (v₁ v₂ : Value Γ σ) → Set
v₁ ≅-Value v₂ = [Value].[ v₁ ] ≡ [ v₂ ]

Foo : ∀ {Γ} {σ₁ σ₂ : Type Γ} {v : Value Γ (σ₁ /id)} →
      σ₁ ≅-Type σ₂ → v ≅-Value v → Set₁
Foo refl refl = Set
```

The coverage checker is generating a bad split tree:

```
split at r{1}
|
`- Issue1872.Σ._,_ -> split at r(5)
   |
   `- Issue1872._≡_.refl -> split at r(6)
      |
      `- Issue1872._≡_.refl -> done, 4 bindings
```

After the first split on `refl` the index for the second pattern is 4, not 6.

**Comment by UlfNorell** [comment] 2016-02-24 11:00
Or maybe the problem is that there's a missing split on `σ₂`... The patterns generated are

```
Γ (.i , σ) {i , .σ} v refl refl
```

where the curlies indicate an implicit match. The problem might be that there's no record of the implicit match in the split tree, confusing the clause compiler.

**Comment by jespercockx** [comment] 2016-02-24 12:34
This seems to be caused by the on-demand eta-expansion of flexible variables during unification: commenting out the etaExpandVarStrategy (line 440 in Unify.hs) makes the file typecheck. However, disabling this rule triggers Issue #473. The proper solution would be to make `compileClauses` aware of variables eta-expanded by the unifier somehow, but this could take some work.

**Comment by UlfNorell** [comment] 2016-02-24 13:26
It feels like there ought to be something in the `SplitTree` marking the eta-expansion.

**Comment by nad** [comment] 2016-03-10 13:27
Due to this bug some of my old code fails to type-check, so unless there is a simple workaround I really think it should be fixed before the next release.

**Comment by jespercockx** [comment] 2016-03-10 17:32
I agree that this should be fixed before the next release, I'll see what I can do to get the extra record-splits in the splittree.

**Comment by jespercockx** [comment] 2016-03-11 14:37
Fixed by https://github.com/agda/agda/commit/f895967e41aa01e194325a83a55fc3eb3f564875. In the future, I think it would be a good idea to have the SplitTree indices be relative to the clause telescope rather than the pattern, as this would prevent mistakes like this from happening in the first place.

**Closed as completed** 2016-03-11 14:37 UTC
Labels: type: bug, pattern matching, eta, regression on master

**Comment by nad** [comment] 2016-03-11 14:46
Thanks, now my old code is accepted again.
