### ISSUE TITLE
undefined in generated js code

### ISSUE THREAD

**Issue by cryogenian** [agda/agda#1661] opened 2015-09-21 20:25 UTC
``` agda
module Foo where

record Foo (t : Set) : Set where
  field
    foo : t
record Bar (t : Set) : Set where
  field
    bar : t
  baz = bar
  open Foo record{foo = bar} public
```

is compiled to

``` javascript
define(["exports"],function(exports) {
  exports["Bar"] = {};
  exports["Foo"] = {};
  exports["Foo"]["record"] = function (x0) {
      return {
        "foo": x0,
        "record": function (x1) {
          return x1["record"](x0);
        }
      };
    };
  exports["Bar"]["_24@206073956"] = {};
  exports["Bar"]["_24@206073956"]["foo"] = function () {
      return function (x0) {
        return exports["Bar"]["bar"](undefined)(x0);
      };
    };
  exports["Foo"]["foo"] = function (x0) {
      return x0["foo"];
    };
  exports["Bar"]["baz"] = function () {
      return function (x0) {
        return exports["Bar"]["bar"](undefined)(x0);
      };
    };
  exports["Bar"]["record"] = function (x0) {
      return {
        "bar": x0,
        "record": function (x1) {
          return x1["record"](x0);
        }
      };
    };
  exports["Bar"]["bar"] = function (x0) {
      return x0["bar"];
    };
  });
```

These `undefined`s make records almost useless.

**Comment by andreasabel** [comment] 2015-09-22 11:22
We do not have a maintainer for the JS backend at the moment.  Would you volunteer?

What do you expect instead of the `undefined`?

**Comment by np** [comment] 2015-09-22 14:12
The generated code seems wrong indeed. On the definition site Bar.bar does not take the implicit arguments (which corresponds to the parameters of the record type) but on the call site these are provided.

I recall having worked on this kind of situations before. I hope to have some time to polish some changes I have for the JS backend.

**Comment by cryogenian** [comment] 2015-09-22 14:18
I think it should be more or less equivalent with 

``` agda
module Bar where

module FooData where
  data FooData (t : Set) : Set where
    mkFoo : t -> FooData t

module FooModule {t : Set} (foo : FooData.FooData t) where
  open FooData
  fooExtracted : {t : Set} -> FooData t -> t
  fooExtracted (mkFoo f) = f


module BarData where
  data BarData (t : Set) : Set where
    mkBar : t -> BarData t

module BarModule {t : Set} (bar : BarData.BarData t) where
  open BarData
  barExtracted : {t : Set} -> BarData t -> t
  barExtracted (mkBar f) = f

  baz : t
  baz = barExtracted bar

  open FooData
  fooBar : FooData t
  fooBar = mkFoo baz
```

This compiles to 

``` javascript
define(["exports"],function(exports) {
  exports["FooData"] = {};
  exports["FooData"]["FooData"] = {};
  exports["BarData"] = {};
  exports["BarData"]["BarData"] = {};
  exports["FooModule"] = {};
  exports["FooModule"]["fooExtracted"] = function (x0) {
      return function (x1) {
        return function (x2) {
          return function (x3) {
            return x3({
              "mkFoo": function (x4) {
                return x4;
              }
            });
          };
        };
      };
    };
  exports["BarModule"] = {};
  exports["BarModule"]["barExtracted"] = function (x0) {
      return function (x1) {
        return function (x2) {
          return function (x3) {
            return x3({
              "mkBar": function (x4) {
                return x4;
              }
            });
          };
        };
      };
    };
  exports["FooData"]["FooData"]["mkFoo"] = function (x0) {
      return function (x1) {
        return x1["mkFoo"](x0);
      };
    };
  exports["BarModule"]["fooBar"] = function (x0) {
      return function (x1) {
        return exports["FooData"]["FooData"]["mkFoo"](exports["BarModule"]["baz"](x0)(x1));
      };
    };
  exports["BarData"]["BarData"]["mkBar"] = function (x0) {
      return function (x1) {
        return x1["mkBar"](x0);
      };
    };
  exports["BarModule"]["baz"] = function (x0) {
      return function (x1) {
        return exports["BarModule"]["barExtracted"](x0)(x1)(x0)(x1);
      };
    };
  });
```

I suggest that records should generate both module and data. 
I can try to fix it, but it will take an eternity and probably there will be no success. I have a very little experience with haskell and compilers.

**Comment by phile314** [comment] 2017-03-22 20:50
Could not reproduce this on current stable-2.5 and master branches. This seems to have been fixed by the JS Treeless backend rewrite.

**Closed as completed by phile314** 2017-03-22 20:50 UTC
Labels: backend: js
