### ISSUE TITLE
Feature request: an "--interval" OPTION

### ISSUE THREAD

**Issue by amp12** [agda/agda#4379] opened 2020-01-17 13:21 UTC
I have recently been experimenting with 
```
{-# OPTIONS --cubical --with-K  #-}
import Agda.Primitive.Cubical using (I; i0; i1; primIMin; primTransp)
import Agda.Builtin.Cubical.Path 
```
to make use of Cubical Agda's implementation of HITs in the presence of Axiom K. Using the fact that the BUILTIN Path and PathP can be shown to be in bijection with the usual homogeneous and heterogeneous inductively defined equality types (modulo Axiom K for the latter),  It seems to give a very nice approach to user-defined QITs; and I believe it is logically consistent :-) ...so long as I do not import and use Agda.Builtin.Cubical.Sub and Agda.Builtin.Cubical.Glue. 

So my feature request is for a new OPTION called --interval that just switches on the parts of Cubical Agda to do with the BUILTINS
  INTERVAL 
  IZERO    
  IONE  
  PATH
  PATHP
and the primitives 
  primIMin
  primTransp 
plus whatever magic is going on to allow datatypes constructors to return PATHs.

**Comment by jespercockx** [comment] 2020-01-17 14:30
This is a duplicate of https://github.com/agda/agda/issues/3750

**Closed as completed by jespercockx** 2020-01-17 14:30 UTC
Labels: status: duplicate, cubical
