### ISSUE TITLE
Overlapping literals are (wrongly) accepted

### ISSUE THREAD

**Issue by phile314** [agda/agda#2243] opened 2016-10-08 07:01 UTC
This typechecks on current stable:

``` agda
   open import Agda.Builtin.Char

   f : Char -> Char
   f 'x' = 'x'
   f 'x' = 'y'
   f _ = 's'
```

Also happens for `Float` patterns, probably other literals as well.

Discovered by asr, see https://github.com/agda/agda/issues/2194#issuecomment-251983600 .

**Comment by andreasabel** [comment] 2016-10-08 10:49
Seems to be a duplicate of #708.

**Closed as completed** 2016-10-08 21:29 UTC
Labels: type: bug, pattern matching, coverage, literals

**Comment by andreasabel** [comment] 2016-10-08 21:30
No, #708 is still open, I only fixed a part of it: unreported unreachable clauses.

**Comment by phile314** [comment] 2016-10-09 09:05
Thanks!
