### ISSUE TITLE
Snoc lists with inter-dependent elements drastically slow down type checker performance

### ISSUE THREAD

**Issue by caryoscelus** [agda/agda#3487] opened 2019-01-07 15:19 UTC
```agda
module SlowDown where

infixl 10 _∷′_

data Ctx : Set
data Expr : Ctx → Set

data Ctx where
  [] : Ctx
  _∷′_ : (Γ : Ctx) (x : Expr Γ) → Ctx

data Expr where
  nil : ∀ {Γ} → Expr Γ

slow : Ctx
slow = [] ∷′ nil ∷′ nil ∷′ nil ∷′ nil ∷′ nil ∷′ nil ∷′ nil ∷′ nil ∷′ nil ∷′ nil ∷′ nil ∷′ nil ∷′ nil ∷′ nil ∷′ nil ∷′ nil ∷′ nil ∷′ nil
```

Adding another nil seems to approximately double amount of memory consumed by agda (the code above takes ~1.8G for me) and slow down type-checking considerably.

**Comment by nad** [comment] 2019-01-07 18:30
When I profile your code (`-vprofile:7`) it looks as if both type-checking and serialisation take more than twice as long when another list element is added. This suggests to me that the problem is that large structures are built up by the unification machinery.

The following code is accepted quickly:
```agda
fast : Ctx
fast = fast₁₈
  where
  fast₀  = []
  fast₁  = fast₀  ∷′ nil
  fast₂  = fast₁  ∷′ nil
  fast₃  = fast₂  ∷′ nil
  fast₄  = fast₃  ∷′ nil
  fast₅  = fast₄  ∷′ nil
  fast₆  = fast₅  ∷′ nil
  fast₇  = fast₆  ∷′ nil
  fast₈  = fast₇  ∷′ nil
  fast₉  = fast₈  ∷′ nil
  fast₁₀ = fast₉  ∷′ nil
  fast₁₁ = fast₁₀ ∷′ nil
  fast₁₂ = fast₁₁ ∷′ nil
  fast₁₃ = fast₁₂ ∷′ nil
  fast₁₄ = fast₁₃ ∷′ nil
  fast₁₅ = fast₁₄ ∷′ nil
  fast₁₆ = fast₁₅ ∷′ nil
  fast₁₇ = fast₁₆ ∷′ nil
  fast₁₈ = fast₁₇ ∷′ nil
```
In this case there are names available for the explicit arguments to `nil`, and I guess this means that the large structures are not built up. Another option (for this simple example) is to turn the `Expr` index into a parameter:
```agda
data Expr (Γ : Ctx) : Set

data Expr Γ where
  nil : Expr Γ
```

**Comment by caryoscelus** [comment] 2019-01-07 23:05
Thanks. Making so much temporaries doesn't look as neat, so hopefully i can get away with parameter solution.

**Comment by UlfNorell** [comment] 2019-01-08 11:34
Each `nil` takes the entire preceding context as its `Γ` argument, effectively doubling the size of the expression. We currently don't have the machinery to share these expressions.

Duplicate of #3094.

**Closed as completed by UlfNorell** 2019-01-08 11:34 UTC
Labels: status: duplicate
