### ISSUE TITLE
Ambigous name error: generalisation conflicts module open

### ISSUE THREAD

**Issue by gallais** [agda/agda#4407] opened 2020-01-29 14:42 UTC
I would expect the following file to work just fine because I explicitly
open the module, meaning that I *do* want to bring these names in scope.

```agda
open import Agda.Builtin.Sigma

variable
  A : Set

module _ (P : Σ Set (λ A → A)) where

  open Σ P renaming (fst to A)

  a : A
  a = snd P
```

however I get an error:

> Ambiguous name A. It could refer to any one of
>  generalisation.fst bound at [loc]
>  generalisation.A bound at [loc]

If I use a pattern-matching telescope instead, I do get the behaviour
I expect:

```agda
open import Agda.Builtin.Sigma

variable
  A : Set

module _ (P@(A , B) : Σ Set (λ A → A)) where

  a : A
  a = snd P
```

**Comment by guillaumebrunerie** [comment] 2020-01-29 14:47
I would expect both to at least give a warning about a name being shadowed.

**Comment by gallais** [comment] 2020-01-29 14:49
We never warn about bound variables re-using a generalisable name.

**Comment by nad** [comment] 2020-01-29 14:53
Is this an instance of #3801?

**Comment by gallais** [comment] 2020-01-29 14:55
I don't think so. It's already perfectly valid to write:

```agda
variable
  A : Set

module _ (A : Set) where
```

**Comment by andreasabel** [comment] 2020-01-30 06:47
Bound variables such as module parameters overwrite previous bindings of the same name.  Imports do not overwrite previous bindings, they just add more interpretations.
One could say here "works as intended", but maybe folks do not expect `variable` declarations to behave like other declarations...
Anyway, I think it is fair to bump this issue.

**Comment by jespercockx** [comment] 2021-02-10 14:08
Closing as a duplicate of #3801

**Closed as completed by jespercockx** 2021-02-10 14:08 UTC
Labels: status: duplicate, scope, shadowing, type: discussion, generalize
