### ISSUE TITLE
Positivity: internal error with projection in constructor type

### ISSUE THREAD

**Issue by zraffer** [agda/agda#4447] opened 2020-02-15 09:01 UTC
```agda
record Wrap : Set₁ where
  constructor ↑
  field ↓ : Set
open Wrap public

data Unit : Set

𝕌nit = ↑ Unit

data Unit where
  unit : ↓ 𝕌nit

-- An internal error has occurred. Please report this as a bug.
-- Location of the error: src/full/Agda/TypeChecking/Positivity.hs:484
```

**Comment by gallais** [comment] 2020-02-15 10:23
The two types are mutually defined. So we need to make sure the inductive
definition is positive before convincing ourselves that it is safe to reduce
the definition. And we need to reduce the definition to check positivity.

Not clear how to fix this.

**Comment by andreasabel** [comment] 2020-02-15 11:57
And score!!
```agda
data ⊥ : Set where

data D : Set
D' = (D → ⊥) → D
data D where
  abs : D'

app : D → D → ⊥
app (abs f) = f

delta : D → ⊥
delta x = app x x

Omega : ⊥
Omega = delta (abs delta)
```

**Comment by andreasabel** [comment] 2020-02-15 12:14
Agda 2.5.2 still rejects `D`.  Also, the internal error first appears in 2.5.3.  Bisection could find the commit to blame. ea711d0a4faa1cc79d1bfdad15a4723f75c5679b (fixing #2495) is under suspicion.

See #3049 for another fatal positivity checker regression in 2.5.3.

**Comment by andreasabel** [comment] 2020-02-15 16:17
The positivity checker seems to be too gullible / not paranoid enough in one place:
https://github.com/agda/agda/blob/6134ea793401465ce428d406e77b04eb74b54d61/src/full/Agda/TypeChecking/Positivity.hs#L540-L542
Here, it should have checked that the `_` in `Def _ vs` is indeed the name of the data type the constructor belongs to.  In the present issue, this is not the case, thus, just positivity checking the "indices" (which are not indices then) is not sufficient.

The issue is fixed by allowing `UnconfirmedReductions` to get to the target of constructor types; this restores the invariant the positivity checker was counting on.

**Closed as completed** 2020-02-15 17:46 UTC
Labels: type: bug, positivity, projections, false, regression in 2.5.3
