### ISSUE TITLE
JS back-end hangs when compiling Data.Conat

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1072] opened 2015-08-08 18:09 UTC
```
agda --js -i ~/src/agda/agda-stdlib/src -i . Main.agda
```

gets to `Data.Conat` and hangs forever

happens on 2.3.2 and current darcs head.

Original issue reported on code.google.com by `t...@dysinger.net` on 1 Mar 2014 at 8:04

**Comment by asr** [comment] 2015-08-15 00:05
In maint-2.4.2.4, this example hangs

``` Agda
module Test where

open import Data.Conat
```

but in master, the error is

``` bash
$ agda-stdlib --js Test.agda
Not implemented: Compilation of copatterns
```

**Comment by phile314** [comment] 2016-09-28 21:48
Could be related to Coinduction which is not (yet) implemented in the JS backend.

**Comment by phile314** [comment] 2016-10-03 20:17
The problem is related to coinduction, but the actual problem lies elsewhere. The JS backend tries to get all definitions in def-before-use order, but code using coinduction (correctly) generates mutually recursive functions. The reorder function just loops forever in that case.

**Comment by phile314** [comment] 2017-03-22 19:29
Could not reproduce this, appears to be fixed by now.

**Closed as completed by phile314** 2017-03-22 19:29 UTC
Labels: type: bug, coinduction, backend: js
