### ISSUE TITLE
Parameterized modules export parameterized Set???

### ISSUE THREAD

**Issue by Blaisorblade** [agda/agda#1713] opened 2015-11-05 02:02 UTC
I got a suspicious error message while porting a codebase of mine from Agda 2.4.0 (before the fix to #892) to 2.4.2.4 — the same porting that lead to #1712. [I have a commit](https://github.com/inc-lc/ilc-agda/commit/f9a5a48e99c09031a5e1f8ca44047397007038d1) showing the surprising error:

```
Set != Set (Type.Structure.Type Base)
when checking that the expression Γ has type
.Data.List.Base.List (_30 Base Const Γ)
```

I might be missing something, but that looks like a builtin `Set` parameterized by my codebase's `Type Base`. I have tons of modules taking a parameter of that type; so any chance that the fix of #892 is parameterizing all reexports, including Set, in some strange edge case?

The offending location probably hits some unusual code path, and seems hard to trigger: it uses an operator `_•_` which is overloaded across `Data.List.::` and `Data.List.All.::`, with multiple conflicting reexports from parameterized modules. After improving the situation a bit, I got a conflict between multiple identical exports of the same `_::_` operator, renamed to `_•_`.

I also wonder if there's any relation to #1679.

**Comment by andreasabel** [comment] 2015-11-09 22:00
I can confirm this issue for agda-2.4.2.5.  
However, the test case needs shrinking before one can reasonably attempt a bug fix.

**Comment by andreasabel** [comment] 2015-12-02 18:48
On current master it checks now (please confirm!), so I guess this was a duplicate of #1701.

**Closed as completed by andreasabel** 2015-12-02 18:48 UTC
Labels: type: bug, regression on master

**Comment by Blaisorblade** [comment] 2015-12-03 11:52
> please confirm

I'm confirming (as much as I can — I can't test the exact same version since I never had time to minimize this, but I can't trigger that message in the closest variants).
