### ISSUE TITLE
Internal Error at "src/full/Agda/TypeChecking/Abstract.hs:138"

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#2763] opened 2017-09-19 05:52 UTC
Trying to compile [this](https://github.com/xekoukou/sparrow/blob/error/agda/LinFunContructw.agda#L41) returns : 

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Abstract.hs:138
```

It is almost at the same position as issue #2679 

My agda version : 
https://github.com/agda/agda/tree/8f487662589c3f5a813aa853383ccd03bc49491f

**Comment by nad** [comment] 2017-09-19 08:39
Have you tried constructing a smaller example that triggers this problem?

**Comment by xekoukou** [comment] 2017-09-19 08:57
I removed 3k lines of code but it is still too slow to typecheck. I added the .agdai files in case they are portable across computers.

We need a tool to remove non-dependent ,to the function, code automatically.

**Comment by xekoukou** [comment] 2017-09-20 07:08
An example in one file with all the functions as postulates:

```agda
module LinFunContructw where

open import Common
open import Relation.Binary.PropositionalEquality
open import Data.Product
open import Data.Vec
open import Function


data LinLogic (i : Size) {u} : Set (lsuc u) where
      -- When nothing is sent or received
  ∅    :                                       LinLogic i
      -- Contains a function that computes a dependent type.
  τ    : ∀{n} {dt : Vec (Set u) n} → genT dt → LinLogic i
      -- Both sub-trees need to be sent or received.
  _∧_  : LinLogic i {u} → LinLogic i {u}     → LinLogic i


data IndexLL {i : Size} {u} (rll : LinLogic i {u}) : LinLogic i {u} → Set u where
  ↓   :                             IndexLL rll rll
  _←∧ : ∀{li ri} → IndexLL rll li → IndexLL rll (li ∧ ri) 


-- A non-empty set of nodes in a Linear Logic tree.
data SetLL {i : Size} {u} : LinLogic i {u} → Set where
  ↓     : ∀{ll}                          → SetLL ll
  _←∧   : ∀{rs ls} → SetLL ls            → SetLL (ls ∧ rs)
  

-- A possibly empty set of nodes in a Linear Logic tree. 
data MSetLL {i : Size} {u} : LinLogic i {u} → Set where
  ∅   : ∀{ll}            → MSetLL {i} ll
  ¬∅  : ∀{ll} → SetLL {i} ll → MSetLL {i} ll


data hitsAtLeastOnce {i u} : ∀{ll rll} → SetLL {i} ll → (ind : IndexLL {i} {u} rll ll) → Set where
  hitsAtLeastOnce↓     : ∀{ll rll ind}                                 → hitsAtLeastOnce {ll = ll} {rll = rll} ↓ ind
  hitsAtLeastOnce←∧↓   : ∀{lll llr s}                                  → hitsAtLeastOnce {ll = lll ∧ llr} {rll = lll ∧ llr} (s ←∧) ↓
  hitsAtLeastOnce←∧←∧  : ∀{ll rll s q ind}    → hitsAtLeastOnce s ind  → hitsAtLeastOnce {ll = ll ∧ q} {rll = rll} (s ←∧) (ind ←∧)



data _≤ᵢ_ {i u gll fll} : ∀{ll} → IndexLL {i} {u} gll ll → IndexLL {i} {u} fll ll → Set where
  ≤ᵢ↓ : {ind : IndexLL fll gll} → ↓ ≤ᵢ ind
  ≤ᵢ←∧ : ∀{li ri} → {sind : IndexLL gll li} → {bind : IndexLL fll li} → (sind ≤ᵢ bind)
         → _≤ᵢ_ {ll = li ∧ ri} (sind ←∧) (bind ←∧)


data Orderedᵢ {i u gll fll ll} (a : IndexLL {i} {u} gll ll) (b : IndexLL {i} {u} fll ll) : Set where
  a≤ᵢb : a ≤ᵢ b → Orderedᵢ a b
  b≤ᵢa : b ≤ᵢ a → Orderedᵢ a b


postulate
  replLL : ∀{i u q} → (ll : LinLogic i {u}) → IndexLL {i} q ll → LinLogic i {u} → LinLogic i {u}
  complLₛ : ∀{i u ll} → SetLL {i} {u} ll → MSetLL {i} ll
  del : ∀{i u ll q} → SetLL {i} ll → (ind : IndexLL {i} {u} q ll) → (rll : LinLogic i)
        → MSetLL (replLL ll ind rll)
  ¬ho⇒del≡¬∅ : ∀{i u} → {rll ll fll : LinLogic i} → (s : SetLL {i} {u} ll) → (ind : IndexLL {i} rll ll) → ¬(hitsAtLeastOnce {i} s ind) → Σ (SetLL (replLL {i} ll ind fll)) (λ z → del s ind fll ≡ ¬∅ z)
  shrinkcms : ∀{i u} → ∀ ll → (s cms : SetLL {i} {u} ll) → ((MSetLL {i} {u} ll) ∋ complLₛ s) ≡ ¬∅ cms → LinLogic i {u}
  ¬ho-shr-morph : ∀{i u rll ll cs} → (s : SetLL {i} {u} ll) → (ceq : complLₛ s ≡ ¬∅ cs)
                  → (ind : IndexLL rll ll) → (¬ho : ¬ (hitsAtLeastOnce s ind))
                  → IndexLL rll (shrinkcms ll s cs ceq)
  ¬ord-morph : ∀{i u rll ll fll} → (emi : IndexLL {i} {u} fll ll)
               → (ind : IndexLL rll ll) → ∀ frll → .(nord : ¬ Orderedᵢ ind emi)
               → IndexLL fll (replLL ll ind frll)
  ¬ho-shr-morph-pres-¬ord : ∀{ i u ll pll ell cs} → ∀ s → (eq : complLₛ s ≡ ¬∅ cs) → (ind : IndexLL {i} {u} pll ll) → (lind : IndexLL ell ll) → ∀ ¬hob ¬hoh
        → let bind = ¬ho-shr-morph s eq ind ¬hob in
          let hind = ¬ho-shr-morph s eq lind ¬hoh in
          Orderedᵢ bind hind → Orderedᵢ ind lind
  flipOrdᵢ : ∀{i u gll fll ll} → {a : IndexLL {i} {u} gll ll} → {b : IndexLL {i} {u} fll ll}
             → Orderedᵢ a b → Orderedᵢ b a
  flipNotOrdᵢ : ∀{i u gll fll ll} → {a : IndexLL {i} {u} gll ll} → {b : IndexLL {i} {u} fll ll}
                → ¬ Orderedᵢ a b → ¬ Orderedᵢ b a
module _ where

  poo : ∀ {i u ll ell pll tll cs} → (s : SetLL ll) → (eq : complLₛ s ≡ ¬∅ cs) → (ind : IndexLL {i} {u} pll ll) → (lind : IndexLL tll ll)
        → (¬hob : ¬ hitsAtLeastOnce s ind)
        → (¬hoh : ¬ hitsAtLeastOnce s lind)
        → let mx = proj₁ (¬ho⇒del≡¬∅ s lind ¬hoh) in
        ∀{mcs}
        → (ceqi : complLₛ mx ≡ ¬∅ mcs)
        → let hind = ¬ho-shr-morph s eq lind ¬hoh in
        let bind = ¬ho-shr-morph s eq ind ¬hob in
        (nord : ¬ Orderedᵢ ind lind) →
        let nind = ¬ord-morph ind lind ell (flipNotOrdᵢ nord) in
        let hnord = ( λ z → nord (¬ho-shr-morph-pres-¬ord s eq ind lind ¬hob ¬hoh (flipOrdᵢ z))) in
        ¬ord-morph bind hind ell hnord ≡ ?
  poo ↓ () ind lind ¬hob ¬hoh ceqi nord
  poo (s ←∧) eq ↓ lind ¬hob ¬hoh ceqi nord = ⊥-elim (¬hob hitsAtLeastOnce←∧↓)
  poo {ell = ell} (s ←∧) eq (ind ←∧) lind ¬hob ¬hoh ceqi nord with complLₛ s | inspect complLₛ s | nhsm where
    nhsm = ¬ho-shr-morph (s ←∧) eq (ind ←∧) ¬hob
  ... | g | e | nhsm = {!!}


```

**Comment by nad** [comment] 2017-09-20 07:27
What is `Common`?

**Comment by xekoukou** [comment] 2017-09-20 07:36
Mostly imports from the standard library.

```agda
module LinFunContructw where

open import Relation.Binary.PropositionalEquality
open import Data.Product
open import Data.Vec
open import Function


open import Size
open import Data.Nat

open import Data.Empty
open import Relation.Binary.PropositionalEquality public using (_≡_ ; refl)
open import Relation.Binary.HeterogeneousEquality public using (_≅_ ; refl ; ≅-to-≡)
open import Relation.Nullary
open import Level public renaming (suc to lsuc ; _⊔_ to _l⊔_ ; zero to lzero) 


genT : ∀{u} {n : ℕ} -> Vec (Set u) n -> Set (lsuc u)
genT {u} [] = Set u
genT (x ∷ xs) =  x -> genT xs


data LinLogic (i : Size) {u} : Set (lsuc u) where
      -- When nothing is sent or received
  ∅    :                                       LinLogic i
      -- Contains a function that computes a dependent type.
  τ    : ∀{n} {dt : Vec (Set u) n} → genT dt → LinLogic i
      -- Both sub-trees need to be sent or received.
  _∧_  : LinLogic i {u} → LinLogic i {u}     → LinLogic i


data IndexLL {i : Size} {u} (rll : LinLogic i {u}) : LinLogic i {u} → Set u where
  ↓   :                             IndexLL rll rll
  _←∧ : ∀{li ri} → IndexLL rll li → IndexLL rll (li ∧ ri) 


-- A non-empty set of nodes in a Linear Logic tree.
data SetLL {i : Size} {u} : LinLogic i {u} → Set where
  ↓     : ∀{ll}                          → SetLL ll
  _←∧   : ∀{rs ls} → SetLL ls            → SetLL (ls ∧ rs)
  

-- A possibly empty set of nodes in a Linear Logic tree. 
data MSetLL {i : Size} {u} : LinLogic i {u} → Set where
  ∅   : ∀{ll}            → MSetLL {i} ll
  ¬∅  : ∀{ll} → SetLL {i} ll → MSetLL {i} ll


data hitsAtLeastOnce {i u} : ∀{ll rll} → SetLL {i} ll → (ind : IndexLL {i} {u} rll ll) → Set where
  hitsAtLeastOnce↓     : ∀{ll rll ind}                                 → hitsAtLeastOnce {ll = ll} {rll = rll} ↓ ind
  hitsAtLeastOnce←∧↓   : ∀{lll llr s}                                  → hitsAtLeastOnce {ll = lll ∧ llr} {rll = lll ∧ llr} (s ←∧) ↓
  hitsAtLeastOnce←∧←∧  : ∀{ll rll s q ind}    → hitsAtLeastOnce s ind  → hitsAtLeastOnce {ll = ll ∧ q} {rll = rll} (s ←∧) (ind ←∧)



data _≤ᵢ_ {i u gll fll} : ∀{ll} → IndexLL {i} {u} gll ll → IndexLL {i} {u} fll ll → Set where
  ≤ᵢ↓ : {ind : IndexLL fll gll} → ↓ ≤ᵢ ind
  ≤ᵢ←∧ : ∀{li ri} → {sind : IndexLL gll li} → {bind : IndexLL fll li} → (sind ≤ᵢ bind)
         → _≤ᵢ_ {ll = li ∧ ri} (sind ←∧) (bind ←∧)


data Orderedᵢ {i u gll fll ll} (a : IndexLL {i} {u} gll ll) (b : IndexLL {i} {u} fll ll) : Set where
  a≤ᵢb : a ≤ᵢ b → Orderedᵢ a b
  b≤ᵢa : b ≤ᵢ a → Orderedᵢ a b


postulate
  replLL : ∀{i u q} → (ll : LinLogic i {u}) → IndexLL {i} q ll → LinLogic i {u} → LinLogic i {u}
  complLₛ : ∀{i u ll} → SetLL {i} {u} ll → MSetLL {i} ll
  del : ∀{i u ll q} → SetLL {i} ll → (ind : IndexLL {i} {u} q ll) → (rll : LinLogic i)
        → MSetLL (replLL ll ind rll)
  ¬ho⇒del≡¬∅ : ∀{i u} → {rll ll fll : LinLogic i} → (s : SetLL {i} {u} ll) → (ind : IndexLL {i} rll ll) → ¬(hitsAtLeastOnce {i} s ind) → Σ (SetLL (replLL {i} ll ind fll)) (λ z → del s ind fll ≡ ¬∅ z)
  shrinkcms : ∀{i u} → ∀ ll → (s cms : SetLL {i} {u} ll) → ((MSetLL {i} {u} ll) ∋ complLₛ s) ≡ ¬∅ cms → LinLogic i {u}
  ¬ho-shr-morph : ∀{i u rll ll cs} → (s : SetLL {i} {u} ll) → (ceq : complLₛ s ≡ ¬∅ cs)
                  → (ind : IndexLL rll ll) → (¬ho : ¬ (hitsAtLeastOnce s ind))
                  → IndexLL rll (shrinkcms ll s cs ceq)
  ¬ord-morph : ∀{i u rll ll fll} → (emi : IndexLL {i} {u} fll ll)
               → (ind : IndexLL rll ll) → ∀ frll → .(nord : ¬ Orderedᵢ ind emi)
               → IndexLL fll (replLL ll ind frll)
  ¬ho-shr-morph-pres-¬ord : ∀{ i u ll pll ell cs} → ∀ s → (eq : complLₛ s ≡ ¬∅ cs) → (ind : IndexLL {i} {u} pll ll) → (lind : IndexLL ell ll) → ∀ ¬hob ¬hoh
        → let bind = ¬ho-shr-morph s eq ind ¬hob in
          let hind = ¬ho-shr-morph s eq lind ¬hoh in
          Orderedᵢ bind hind → Orderedᵢ ind lind
  flipOrdᵢ : ∀{i u gll fll ll} → {a : IndexLL {i} {u} gll ll} → {b : IndexLL {i} {u} fll ll}
             → Orderedᵢ a b → Orderedᵢ b a
  flipNotOrdᵢ : ∀{i u gll fll ll} → {a : IndexLL {i} {u} gll ll} → {b : IndexLL {i} {u} fll ll}
                → ¬ Orderedᵢ a b → ¬ Orderedᵢ b a
module _ where

  poo : ∀ {i u ll ell pll tll cs} → (s : SetLL ll) → (eq : complLₛ s ≡ ¬∅ cs) → (ind : IndexLL {i} {u} pll ll) → (lind : IndexLL tll ll)
        → (¬hob : ¬ hitsAtLeastOnce s ind)
        → (¬hoh : ¬ hitsAtLeastOnce s lind)
        → let mx = proj₁ (¬ho⇒del≡¬∅ {fll = ell} s lind ¬hoh) in
        ∀{mcs}
        → (ceqi : complLₛ mx ≡ ¬∅ mcs)
        → let hind = ¬ho-shr-morph s eq lind ¬hoh in
        let bind = ¬ho-shr-morph s eq ind ¬hob in
        (nord : ¬ Orderedᵢ ind lind) →
        let nind = ¬ord-morph ind lind ell (flipNotOrdᵢ nord) in
        let hnord = ( λ z → nord (¬ho-shr-morph-pres-¬ord s eq ind lind ¬hob ¬hoh (flipOrdᵢ z))) in
        ¬ord-morph bind hind ell hnord ≡ ?
  poo ↓ eq ind lind ¬hob ¬hoh ceqi nord = ?
  poo (s ←∧) eq ↓ lind ¬hob ¬hoh ceqi nord = ⊥-elim (¬hob hitsAtLeastOnce←∧↓)
  poo {ell = ell} (s ←∧) eq (ind ←∧) lind ¬hob ¬hoh ceqi nord with complLₛ s | inspect complLₛ s | nhsm where
    nhsm = ¬ho-shr-morph (s ←∧) eq (ind ←∧) ¬hob
  ... | g | e | nhsm = {!!}
```

**Comment by xekoukou** [comment] 2017-09-21 05:33
Is there a way to avoid this error ,for the moment, apart from not using "with'?

This error blocks me from continuing my work.

**Comment by nad** [comment] 2017-09-21 07:53
It happens that I discover a workaround when reducing a test case. You could try reducing the test case above further.

**Comment by UlfNorell** [comment] 2017-09-21 08:05
Self contained, shrunk test case:

```agda
open import Agda.Builtin.Equality

data ⊤ : Set where tt : ⊤

postulate
  IndexL        : Set
  Ordered       : IndexL → Set
  ¬ho-shr-morph : IndexL → IndexL
  pres-¬ord     : ∀ ind → Ordered (¬ho-shr-morph ind)
  ¬ord-morph    : ∀ ind → Ordered ind → Set

poo : ∀ ind → ¬ord-morph (¬ho-shr-morph ind) (pres-¬ord ind)
poo ind with tt | ¬ho-shr-morph ind
... | _ | _ = {!!}
```

I haven't analysed this in detail, but it seems like the problem is that abstracting the right-most with-expression creates an ill-formed type (abstracting over `¬ho-shr-morph ind`, but not `pres-¬ord ind`). The next with-abstraction then panics over this and throws an internal error.

If this is the case then there might be hope for you to work around the problem. Adding the necessary abstraction over `pres-¬ord ind` makes the example go through:

```agda
poo ind with tt | ¬ho-shr-morph ind | pres-¬ord ind
... | _ | _ | _ = {!!} -- works
```

**Edit**: more shrinking

**Comment by UlfNorell** [comment] 2017-09-21 08:23
I think this is a small as it gets:
```agda
data ⊤ : Set where tt : ⊤

postulate
  A : Set
  B : A → Set
  a : A
  b : B a
  G : ∀ x → B x → Set

poo : G a b
poo with tt | a
... | _ | _ = {!!}
```
The problem is that we use typed abstraction when abstracting over constructors (#745), but not when abstracting over other terms. Typed abstraction panics if the thing being abstracted over is not well-typed, which can absolutely happen if you're not careful in your with abstractions.

**Comment by UlfNorell** [comment] 2017-09-21 08:56
Fixed by removing the internal error and simply refusing to perform the abstraction if it's ill-typed. In that case you'll get an appropriate error message from the checking of the with-function type.

**Comment by andreasabel** [comment] 2017-09-21 09:31
Please improve your fix (see comment on commit).

**Comment by UlfNorell** [comment] 2017-09-21 09:44
> I do not see how the generated error message is useful in this case. It talks about a w1 which does not appear in the type of the generated with function.

This issue isn't about with-function error messages. Please open a new issue for that instead of reopening this one.

**Closed as completed by UlfNorell** 2017-09-21 09:44 UTC
Labels: type: bug, with

**Comment by xekoukou** [comment] 2017-09-21 14:24
I am still trying to figure out how to make it correctly typed. By the way, the error message for my example is this one : 

```
LinLogic ∞ !=< Level of type Set (lsuc u)
when checking that the type
{u : Level} {ls : LinLogic ∞} {i : Size} {rs pll : LinLogic i}
{cs : SetLL (ls ∧ rs)} (s : SetLL ls) (eq : complLₛ (s ←∧) ≡ ¬∅ cs)
(ind : IndexLL pll ls) (¬hob : hitsAtLeastOnce (s ←∧) (ind ←∧) → ⊥)
(w : MSetLL ls) (w₁ : Reveal complLₛ · s is w)
(w₂ : IndexLL cs (shrinkcms (i ∧ pll) (eq ←∧) s ind))
{ell tll : LinLogic rs} (lind : IndexLL tll (i ∧ pll))
(¬hoh : hitsAtLeastOnce (eq ←∧) lind → ⊥)
{mcs : SetLL (replLL (i ∧ pll) lind ell)}
(ceqi : complLₛ (proj₁ (¬ho⇒del≡¬∅ (eq ←∧) lind ¬hoh)) ≡ ¬∅ mcs)
(nord : Orderedᵢ (¬hob ←∧) lind → ⊥) →
¬ord-morph w₂ (¬ho-shr-morph (eq ←∧) ind lind ¬hoh) ell _ ≡
?0 (eq ←∧) ind (¬hob ←∧) lind w₁ ¬hoh ceqi nord
of the generated with function is well-formed
```

**Comment by UlfNorell** [comment] 2017-09-22 07:36
> I do not see how the generated error message is useful in this case. It talks about a `w₁` which does not appear in the type of the generated with function.

60787df0380c7 fixes the `w₁` problem.
