### ISSUE TITLE
Appears like ill-typed equality error

### ISSUE THREAD

**Issue by ajrouvoet** [agda/agda#5626] opened 2021-11-02 12:24 UTC
Today Agda produced the following error somewhere in a with-pattern:

```
zero != Type of type Set
when checking that the pattern Split?.split x₃ has type
Relation.Ternary.Construct.Add.Unit.Split?
(Relation.Ternary.Construct.Empty.empty-rel Type) (just x₁)
(just x₂) w
```

This error looks itself ill-typed to me, because `zero` is already not of type `Set`. Is such an error always a bug or are there cases where this is expected?

I don't know how to gather more interesting info about this potential bug. 
The last few lines of the debug log that produce the exception are:

```
{ compare Apply
  a    = {a : Level} {A : Set a} (div : Rel₃ A) →
         Maybe A → Maybe A → Maybe A → Set a
  v    = Relation.Ternary.Construct.Add.Unit.Split?
  arg1 = {_}
  arg2 = {_}
compareTerm zero = zero : Level
{ compareElims
compareElims
  a     = {A : Set} (div : Rel₃ A) →
          Maybe A → Maybe A → Maybe A → Set
  pols0 (truncated to 10) =
  fors0 (truncated to 10) =
  v     = Relation.Ternary.Construct.Add.Unit.Split?
  els01 = [$ {_}, $ Name, $ const Type, $ _≟_,
           $ Relation.Ternary.Construct.Empty.empty-rel (const Type k)]
  els02 = [$ {_}, $ Relation.Ternary.Construct.Empty.empty-rel Type]
{ compare Apply
  a    = {A : Set} (div : Rel₃ A) → Maybe A → Maybe A → Maybe A → Set
  v    = Relation.Ternary.Construct.Add.Unit.Split?
  arg1 = {_}
  arg2 = {_}
compareTerm zero = Type : Set
compareTerm (not syntactically equal) zero = Type : Set
{ compareTerm
compareTerm zero = Type : Set
{ compareAtom
compareAtom zero = Type : Set
} (exception)
} (exception)
} (exception)
} (exception)
} (exception)
} (exception)
{ compareElims
compareElims
  a     = {a : Level} {A : Set a} (div : Rel₃ A) →
          Maybe A → Maybe A → Maybe A → Set a
  pols0 (truncated to 10) =
  fors0 (truncated to 10) =
  v     = Relation.Ternary.Construct.Add.Unit.Split?
  els01 = [$ {_}, $ {_}, $ Name, $ const Type, $ _≟_,
           $ Relation.Ternary.Construct.Empty.empty-rel (const Type k)]
  els02 = [$ {_}, $ {_},
           $ Relation.Ternary.Construct.Empty.empty-rel Type]
{ compare Apply
  a    = {a : Level} {A : Set a} (div : Rel₃ A) →
         Maybe A → Maybe A → Maybe A → Set a
  v    = Relation.Ternary.Construct.Add.Unit.Split?
  arg1 = {_}
  arg2 = {_}
compareTerm zero = zero : Level
{ compareElims
compareElims
  a     = {A : Set} (div : Rel₃ A) →
          Maybe A → Maybe A → Maybe A → Set
  pols0 (truncated to 10) =
  fors0 (truncated to 10) =
  v     = Relation.Ternary.Construct.Add.Unit.Split?
  els01 = [$ {_}, $ Name, $ const Type, $ _≟_,
           $ Relation.Ternary.Construct.Empty.empty-rel (const Type k)]
  els02 = [$ {_}, $ Relation.Ternary.Construct.Empty.empty-rel Type]
{ compare Apply
  a    = {A : Set} (div : Rel₃ A) → Maybe A → Maybe A → Maybe A → Set
  v    = Relation.Ternary.Construct.Add.Unit.Split?
  arg1 = {_}
  arg2 = {_}
compareTerm zero = Type : Set
compareTerm (not syntactically equal) zero = Type : Set
{ compareTerm
compareTerm zero = Type : Set
{ compareAtom
compareAtom zero = Type : Set
} (exception)
} (exception)
} (exception)
} (exception)
} (exception)
} (exception)
```

**Comment by andreasabel** [comment] 2021-11-03 08:00
Since `with` abstracts over some terms in an untyped fashion, it is not unthinkable that it produces ill-typed terms.
We would need a reproducer to further investigate.

**Comment by jespercockx** [comment] 2022-08-25 14:26
I'm closing this for a lack of a MWE, feel free to reopen if you have a (small) example producing the issue.

**Closed as not planned by jespercockx** 2022-08-25 14:26 UTC
Labels: status: info-needed, with
