### ISSUE TITLE
Delete or reproduce a check for unsolved metas in Backend.hs

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#7482] opened 2024-09-09 19:50 UTC
This check lacks a reproducer:
https://github.com/agda/agda/blob/cfaf03fe423712878609c48070451e1d9aa9a946/src/full/Agda/Compiler/Backend.hs#L163-L169

In its current formulation it stems from the following PR, but has older roots (6698cc19cb87808b92311af3bf0698d8fe9a320a):
- #5082
- https://github.com/agda/agda/pull/5082/files#r1750835073

How to reproduce this? Any ideas @rwe @nad @UlfNorell ?

If we cannot reproduce it, we should just dispose of the check.

**Comment by UlfNorell** [comment] 2024-09-10 09:16
I can't reproduce it with modest effort, but even if it could be reproduced it doesn't make sense. It should be up to each backend to complain about unsolved metas if it can't handle them (and how is `crWarnings` being nonempty and indication of unsolved metas?).

I don't see any risk involved in deleting the check. Worst case scenario someone hits an impossible in a backend that was relying on this check at which point the backend should be fixed.

**Closed as completed** 2024-09-10 19:44 UTC
Labels: ux: error reporting, infra: test suite, type: task, backends
