### ISSUE TITLE
Destructuring leads to invalid premises

### ISSUE THREAD

**Issue by mrakgr** [agda/agda#3813] opened 2019-05-28 09:45 UTC
```
ℕ-≃-Can : ℕ ≃ ∃[ x ](Can x)
ℕ-≃-Can =
  record { to = to'
         ; from = from'
         ; from∘to = from∘to
         ; to∘from = λ { ⟨ a , b ⟩ → to∘from a b}
         }
  where
    to' : (x : ℕ) → Σ Bin Can
    to' = λ x → ⟨ to x , Can- (from-to-identity {x}) ⟩
    from' : (x : Σ Bin Can) → ℕ
    from' = λ { ⟨ x , x₁ ⟩ → from x}
    from∘to : (x : ℕ) → from (to x) ≡ x
    from∘to = λ x → from-to-identity
    to∘from : (a : Bin) → (b : Can a) → to' (from a) ≡ ⟨ a , b ⟩
    to∘from n prf = {!!}
```
```
Goal: to' (from n) ≡ ⟨ n , prf ⟩
————————————————————————————————————————————————————————————
prf : Can n
n   : Bin
```

If I try to destructure `prf` here this is what happens.

```
    to∘from : (a : Bin) → (b : Can a) → to' (from a) ≡ ⟨ a , b ⟩
    to∘from .(to _) (Can- x) = ?
```

```
E:\TheoremProving\plfa\Quantifiers.lagda:597,15-19
Failed to solve the following constraints:
  [1079] to _281 = to n : Bin
when checking that the given dot pattern to _ matches the inferred
value to n
```

When I try to fix that by replacing it with the following, I get ill typed premises.

```
    to∘from : (a : Bin) → (b : Can a) → to' (from a) ≡ ⟨ a , b ⟩
    to∘from n (Can- x) = {!!}
```
```
Goal: to' (from (to n)) ≡ ⟨ to n , Can- x ⟩
————————————————————————————————————————————————————————————
n : Bin
x : from (to n) ≡ n
n : ℕ  (not in scope)
```

Note that the type of `to : ℕ → Bin` whereas `n : Bin`. I am not sure what to do here. I'll try to pare down the example so it can be run in a single file.

**Comment by mrakgr** [comment] 2019-05-28 09:55
Here is the whole thing in a single file. I had to do some renaming by hand.

```agda
import Relation.Binary.PropositionalEquality as Eq
open Eq using (_≡_; refl; cong)

open import Data.Nat
open import Data.Nat.Properties

data Bin : Set where
  nil : Bin
  x0_ : Bin → Bin
  x1_ : Bin → Bin

inc : Bin → Bin
inc nil = x1 nil
inc (x0 x) = x1 x
inc (x1 x) = x0 (inc x)

to : ℕ → Bin
to zero = (x0 nil)
to (suc x) = inc (to x)

from-helper : ℕ → Bin -> ℕ
from-helper state nil = zero
from-helper state (x0 x) = from-helper (2 * state) x
from-helper state (x1 x) = state + from-helper (2 * state) x

from : Bin → ℕ
from x = from-helper 1 x

from-helper-distr : ∀ (y : ℕ) (x : Bin) → from-helper y (inc x) ≡ y + from-helper y x
from-helper-distr y nil = refl
from-helper-distr y (x0 x) = refl
from-helper-distr y (x1 x) rewrite
  +-identityʳ y
  | from-helper-distr (y + y) x
  | +-assoc y y (from-helper (y + y) x)
  = refl

from-inc≡suc-from : ∀ (x : Bin) → from (inc x) ≡ suc (from x)
from-inc≡suc-from nil = refl
from-inc≡suc-from (x0 x) = refl
from-inc≡suc-from (x1 x) rewrite from-helper-distr 2 x = refl

from-to-identity : ∀ {n : ℕ} -> from (to n) ≡ n
from-to-identity {zero} = refl
from-to-identity {suc n} rewrite from-helper-distr 1 (to n) | from-to-identity {n} = refl

data Can : Bin → Set where
  Can- : ∀ {n} → from (to n) ≡ n → Can (to n)

infix 0 _≃_
record _≃_ (A B : Set) : Set where
  field
    to'   : A → B
    from' : B → A
    from∘to : ∀ (x : A) → from' (to' x) ≡ x
    to∘from : ∀ (y : B) → to' (from' y) ≡ y
open _≃_

postulate
  extensionality : ∀ {A B : Set} {f g : A → B}
    → (∀ (x : A) → f x ≡ g x)
      -----------------------
    → f ≡ g

data Σ (A : Set) (B : A → Set) : Set where
  ⟨_,_⟩ : (x : A) → B x → Σ A B

Σ-syntax = Σ
infix 2 Σ-syntax
syntax Σ-syntax A (λ x → B) = Σ[ x ∈ A ] B

∃ : ∀ {A : Set} (B : A → Set) → Set
∃ {A} B = Σ A B

∃-syntax = ∃
syntax ∃-syntax (λ x → B) = ∃[ x ] B

ℕ-≃-Can : ℕ ≃ ∃[ x ](Can x)
ℕ-≃-Can =
  record { to' = to''
         ; from' = from''
         ; from∘to = from∘to'
         ; to∘from = λ { ⟨ a , b ⟩ → to∘from' a b}
         }
  where
    to'' : (x : ℕ) → Σ Bin Can
    to'' = λ x → ⟨ to x , Can- (from-to-identity {x}) ⟩
    from'' : (x : Σ Bin Can) → ℕ
    from'' = λ { ⟨ x , x₁ ⟩ → from x}
    from∘to' : (x : ℕ) → from (to x) ≡ x
    from∘to' = λ x → from-to-identity
    to∘from' : (a : Bin) → (b : Can a) → to'' (from a) ≡ ⟨ a , b ⟩
    to∘from' n prf = {!!}
```

**Comment by andreasabel** [comment] 2019-05-29 16:40
> Note that the type of `to : ℕ → Bin` whereas `n : Bin`.

Plese note that you also have hypothesis `n : ℕ` which salvages `to n`.  Only this other `n` is shadowed by `n : Bin`, so you cannot write it yourself.

The less confusing workaround might be to fix the Agda-generated clause towards:
```
to∘from _ (Can- x) = ?
```
i.e., just get rid of the dot pattern that chokes the unifier.

I don't think we will bring the case-splitting command towards a state where the generated clauses are guaranteed to type-check.  Thus, I am closing this issue here.  Feel free to reopen if needed.

**Comment by mrakgr** [comment] 2019-05-30 08:26
This might unchoke the unifier, but for some reason I cannot get the rewrite to work.

```
    to∘from : (a : Bin) → (b : Can a) → to' (from a) ≡ ⟨ a , b ⟩
    to∘from _ (Can- x) = {!!}
```
```
Goal: to' (from (to n)) ≡ ⟨ to n , Can- x ⟩
————————————————————————————————————————————————————————————
x : from (to n) ≡ n
n : ℕ  (not in scope)
```

...

```
    to∘from : (a : Bin) → (b : Can a) → to' (from a) ≡ ⟨ a , b ⟩
    to∘from _ (Can- x) rewrite x = {!!}
```
```
E:\TheoremProving\plfa\Quantifiers.lagda:597,5-40
w != from-helper 1 (to n) of type ℕ
when checking that the type
{n : ℕ} (x : from-helper 1 (to n) ≡ n) (w : ℕ) (w₁ : w ≡ n) →
⟨ to w , Can- from-to-identity ⟩ ≡ ⟨ to n , Can- w₁ ⟩
of the generated with function is well-formed
```

Why is this happening? If I could apply the rewrite here, the `refl` should then suffice to solve the exercise.

**Edit**: I thought that something like `to∘from t (Can- prf) = Eq.sym (Eq.subst (λ v → to' v ≡ ⟨ to n , Can- prf ⟩) (Eq.sym prf) refl)` might work, but I do not know how to get `n` into scope.

**Comment by jespercockx** [comment] 2019-05-30 08:58
> I don't think we will bring the case-splitting command towards a state where the generated clauses are guaranteed to type-check. Thus, I am closing this issue here. Feel free to reopen if needed.

I disagree here as a matter of principle. I think it is a very important goal for the code generated by interactive commands to be accepted by Agda. Failing that goal, it at least needs to be predictable when an interactive command might fail (e.g. currently when you case-split on a clause spread over multiple lines).

**Comment by jespercockx** [comment] 2019-05-30 09:00
Also, the printing of the context
```
Goal: to' (from (to n)) ≡ ⟨ to n , Can- x ⟩
————————————————————————————————————————————————————————————
n : Bin
x : from (to n) ≡ n
n : ℕ  (not in scope)
```
is definitely buggy: Agda should have renamed the out-of-scope `n` to something else to avoid the shadowing.

**Comment by mrakgr** [comment] 2019-06-02 14:32
Sorry to bring this up, but since I had not received an answer to my [earlier question](https://github.com/agda/agda/issues/3813#issuecomment-497249755) let me highlight it again. Is there a way to bring that implicit variable into scope somehow so I can do the substitution?

There seem to be several issues at play at once here:

1) Case splitting generating invalid code.
2) Buggy printing.
3) Not being able to apply the rewrite.

I am not sure how to interpret the silence with regards to that last one. Is that a compiler bug as well?

**Comment by jespercockx** [comment] 2019-06-03 09:15
I'm not a frequent user of `with` and `rewrite` because I find them quite unpredictable and hard to reason about. So I'm afraid I'm not sure whether this particular case is a problem with your code, a limitation of `rewrite`, or a bug in the typechecker. But in my experience these kind of error messages are quite common when using with/rewrite. Hopefully someone else has a better idea.

**Comment by gallais** [comment] 2019-06-03 09:28
> Is there a way to bring that implicit variable into scope

If I understand correctly this is what you want to write:

```agda
    to∘from' .(to n) (Can- {n} prf) = {!!}
```

The need to explicitly introduce a constructor's implicit variable is often a good
indicator that it should have been explicit in the first place. Here it very much
is the case because `Can` is a view: if you have a value of type `Can m`, by
pattern-matching on `Can- {n} eq` you reveal that `m = to n`. And the point of a
view for a function `f` is to get hold of the arguments to call `f` with in order
to obtain the given result.

**Comment by mrakgr** [comment] 2019-06-04 14:03
Yeah, that is exactly what I was asking for. I forgot that `Can-` had an implicit argument. I have a tendency to make dumb mistakes when I change frames from thinking about the problem to thinking about the compiler.

That having said, I've never underestimated a problem as much as this one. I thought I would be done in 5m with it, but now after more than a few hours of working on it, it seems pretty much unsolvable. I can't apply the rewrite `from (to n) ≡ n` no matter what I do.

I think I understand what the issue is now. Proving that `∀ {n : ℕ} -> from (to n) ≡ n` is easy, and I've done it in `from-to-identity`.

The problem starts when you want to prove something like...

```
    Can-eq : ∀ (n : ℕ) → from-to-identity (from (to n)) ≡ from-to-identity n
    Can-eq n = {!!}
```
```
E:\TheoremProving\plfa\Quantifiers.lagda:601,59-77
n != from-helper 1 (to n) of type ℕ
when checking that the expression from-to-identity n has type
from (to (from (to n))) ≡ from (to n)
```

The issue here is that `from-to-identity (from (to n))` and `from-to-identity n` are different types so just the type signature fails typechecking. Given that the above fails typechecking it is suspicious that `to∘from : (x : ∃[ x ] Can x ) → to' (from' x) ≡ x` passes.

Here is some more.

```
    Can-eq : ∀ (n : ℕ) → (Can- (from-to-identity (from (to n))) ≡ Can- (from-to-identity n))
    Can-eq n = {!!}
```
```
E:\TheoremProving\plfa\Quantifiers.lagda:601,67-91
n != from-helper 1 (to n) of type ℕ
when checking that the inferred type of an application
  Can (to n)
matches the expected type
  Can (to (from (to n)))
```

The type signature fails typechecking here. `Can- (from-to-identity (from (to n))` does not have the same type as `Can- (from-to-identity n))`.

```
    Can-eq : ∀ (n : ℕ) → ⟨ to (from (to n)) , Can- (from-to-identity (from (to n))) ⟩ ≡ ⟨ to n , Can- (from-to-identity n) ⟩
    Can-eq n = {!!}
```

This partially passes typechecking, but for some reason I get yellow highlighting indicating that some metavariables are not instantiated.

I am stuck on this problem right now. I managed to prove a simpler variant of it, namely that...

```
refl-eq : ∀ {X : Set} {a b : X} (x : a ≡ b) (y : a ≡ b) → x ≡ y
refl-eq refl refl = refl
```

```
    to∘from' : ∀ {n} {x : from (to n) ≡ n} → to' n ≡ ⟨ to n , Can- x ⟩
    to∘from' {n} {x} with refl-eq (from-to-identity n) x
    to∘from' {n} {.(from-to-identity n)} | refl = refl
```

I can't prove `to' (from (to n)) ≡ ⟨ to n , Can- x ⟩` as I cannot apply the rewrite even with `subst` which was my plan yesterday. What do you think?

**Comment by mrakgr** [comment] 2019-06-04 17:18
```
    to∘from' : ∀ {n} (x : from (to n) ≡ n) → to' n ≡ ⟨ to n , Can- x ⟩
    to∘from' {n} x with refl-eq (from-to-identity n) x
    to∘from' {n} .(from-to-identity n) | refl = refl

    to∘from : (x : ∃[ x ] Can x ) → to' (from' x) ≡ x
    to∘from q@(⟨ .(to n) , Can- {n} x ⟩) = subst (λ v → to' v ≡ q) (sym x) (to∘from' x)
```

Nevermind. `subst` works after all. It seems I've tried all the wrong things first.

I apologize for writing all of this, though I am still interested in why `rewrite` fails.

**Comment by jespercockx** [comment] 2019-11-15 14:46
Here's a standalone version of the problem in the OP (after performing the case split):

```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

cong : {A B : Set} (f : A → B)
     → {x y : A} → x ≡ y → f x ≡ f y
cong f refl = refl

+-identityʳ : (x : Nat) → x + 0 ≡ x
+-identityʳ zero    = refl
+-identityʳ (suc n) = cong suc (+-identityʳ n)

+-assoc : (x y z : Nat) → (x + y) + z ≡ x + (y + z)
+-assoc zero    _ _ = refl
+-assoc (suc m) n o = cong suc (+-assoc m n o)

data Bin : Set where
  nil : Bin
  x0_ : Bin → Bin
  x1_ : Bin → Bin

inc : Bin → Bin
inc nil = x1 nil
inc (x0 x) = x1 x
inc (x1 x) = x0 (inc x)

to : Nat → Bin
to zero = (x0 nil)
to (suc x) = inc (to x)

postulate
  from : Bin → Nat

data Can : Bin → Set where
  Can- : ∀ {n} → from (to n) ≡ n → Can (to n)

data Σ (A : Set) (B : A → Set) : Set where
  ⟨_,_⟩ : (x : A) → B x → Σ A B

postulate
  to'' : (x : Nat) → Σ Bin Can

to∘from' : (a : Bin) → (b : Can a) → to'' (from a) ≡ ⟨ a , b ⟩
to∘from' .(to _) (Can- x) = {!!}
```

The problem is that the unifier gets stuck on unifying `to _ =?= to n`. `to` is a function that might compute depending on the value of the `_`, so simplifying the constraint to `_ =?= n` might lose solutions.

The least thing we could do is to remove the hard error and leave an unsolved constraint instead. This would allow the user to continue interacting with Agda.

Then there's the question whether we can prevent Agda from generating dot patterns that lead to unsolved constraints. One radical solution would be to never generate dot patterns but instead put an underscore (or simply leave the variable). But I'm not sure if that would be the right thing to do in all cases.

**Comment by jespercockx** [comment] 2019-11-15 15:09
Here is a small example demonstrating the problem with shadowing variables in the context:
```agda
postulate
  A B : Set
  f : A → B

data D : B → Set where
  c : {n : A} → D (f n)

test : (x : B) → D x → Set
test n c = {!!}
```
The goal is:
```
Goal: Set
————————————————————————————————————————————————————————————
n : B
n : A  (not in scope)
```
It seems variables that have been instantiated are not considered to be shadowing other variables, but they are still printed in the context (and they are actually in scope, so really they *do* shadow).

**Comment by jespercockx** [comment] 2019-11-15 15:32
There is a general problem with the naming of let-bound variables in the context:
```agda

test2 : Set
test2 =
  let X = Set in
  let X = Set in
  {!!}
```
This produces the context:
```
Goal: Set
————————————————————————————————————————————————————————————
X : Set₁
X : Set₁
```

**Comment by jespercockx** [comment] 2019-11-17 11:07
Current status:

- The problem with printing let-bound variable names in the context was fixed in https://github.com/agda/agda/commit/273b080874d542ee4c15cbd726ba6fa241a49b83. 
- The case splitting in the OP no longer fails hard, but only produces unsolved constraints (https://github.com/agda/agda/commit/26df88889b890678e6a8e2aabf778689c2013e62).
- You can use the new `--keep-pattern-variables` flag (https://github.com/agda/agda/commit/9ed11be31f5627a264dc033cfa6485971602f7b7) to avoid the problem altogether.

It seems to me this fixes the problems in this issue. If there is a concrete problem with `rewrite` that you would like to see fixed, please open a new issue for that.

**Closed as completed by jespercockx** 2019-11-17 11:07 UTC
Labels: type: bug, dot patterns, ux: case splitting, ux: printing, unification
