### ISSUE TITLE
--interaction qualifies names wrong for parameterized modules

### ISSUE THREAD

**Issue by JoeyEremondi** [agda/agda#5159] opened 2021-01-30 19:45 UTC
Minimal working example:

File `Test1.agda`
```agda
module Test1 (x : Set) where

module Foo where
  data Bar : Set where
    Baz1 Baz2 : Bar
open Foo public
```
File `Test2.agda`
```agda
module Test2 (x : Set) where
open import Test1 x

myfun : Bar -> Bar
myfun x = {!x!}

```
Doing C-C (i.e. `agda2-make-case`) elaborates the definition to:

```agda
myfun Test1.Foo.Bar.Baz1 = ?
myfun Test1.Foo.Bar.Baz2 = ?
```
loading this file gives the error:

```
Cannot pattern match on non-constructor Test1.Foo.Bar.Baz1
when scope checking the left-hand side myfun Test1.Foo.Bar.Baz1 in
the definition of myfun
```

Using `Baz1` and `Baz2` unqualified gets rid of the error, but it's annoying to have to manually change this when there are a lot of case splits.

**Comment by jespercockx** [comment] 2021-01-31 20:53
I believe this is a duplicate of https://github.com/agda/agda/issues/3209

**Closed as completed** 2021-01-31 20:54 UTC
Labels: status: duplicate
