### ISSUE TITLE
Internal Error in Agda/TypeChecking/Serialise/Instances/Common.hs

### ISSUE THREAD

**Issue by turion** [agda/agda#2592] opened 2017-05-26 19:16 UTC
Very strangely, I'm getting an internal error for a file with these contents:
```
module Library where

open import Data.Empty public
```
The error message is:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Serialise/Instances/Common.hs:168
```
I'm using version 2.6.0-ba3762d.

The bug is not entirely consistently reproducible. The same file used to compile before, so maybe it's related to caching or `.agdai` files?

**Comment by andreasabel** [comment] 2017-05-26 20:24
I cannot reproduce it with the latest 2.6 and the latest std-lib.

Can you reproduce it on the latest development version?

**Comment by turion** [comment] 2017-05-26 20:42
Yes, that's what I'm using at the moment. My workflow currently looks like this:

* Edit file in Atom, reload after some
* After 3-5 reloads, the error occurs
* Restart Atom

So I'm guessing it must have to do with the modules agda keeps cached in memory somehow?

(I'm sorry that my reproducability ratio is around 0 in my open bugs :/ hopefully I can improve on that after TYPES...)

**Comment by andreasabel** [comment] 2017-05-27 07:12
@fredrikNordvallForsberg reported an internal error at the same location when he worked on serializing warnings.  But I think the problem then was reliably reproducible.

You could try `--no-caching` and see if the problem goes away.

**Comment by MatthewDaggitt** [comment] 2017-06-08 09:12
I am also getting this error when using Agda 2.6.0-0734717.

It's happening to me randomly as well. The only pattern that I can see is that it occurs after the following sequence of events:
1) I write some invalid code
2) I type check it and it spits back the "normal" error telling me why my code is wrong
3) I then fix the code.
4) I then try to type check it again and it gives the error @turion reports above.

Any future attempts to type check also result in the same error. Restarting Agda eliminates the error, allowing the same code to compile correctly.

It (occasionally) happens to me when compiling `Data.Vec.All.Properties` in the standard library.

**Comment by andreasabel** [comment] 2017-06-09 16:32
I also got it now with Agda 2.6.0 (and 2.5.3).  
In my situation, the file imports an old version of the standard library which produces warnings.
I get the error when I switch to another module in emacs and load it.

Do you also have warnings in your cases (in the imported modules)?

**Comment by andreasabel** [comment] 2017-06-09 16:37
@fredrikNordvallForsberg @gallais Could this be related to serialized warnings? (It seems like a recent bug.)

**Comment by andreasabel** [comment] 2017-06-09 16:44
Trace:
```
(agda2-info-action "*Type-checking*" "Checking PartialRecursiveFunctions (/home/abel/bib/authors/FuhsAlexander/PartialRecursiveFunctions.agda).\n" t)
(agda2-verbose "Starting scope checking.\n")
(agda2-verbose "Scope checking Level\n")
(agda2-verbose "  visited: Agda.Primitive\n")
(agda2-verbose "Scope checking Data.Nat.Base\n")
(agda2-verbose "  visited: Agda.Primitive, Level\n")
(agda2-info-action "*Type-checking*" " Checking Data.Nat.Base (/home/abel/agda/std-lib/src/Data/Nat/Base.agda).\n" t)
(agda2-info-action "*Type-checking*" "   Loading  Agda.Builtin.TrustMe (/home/abel/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.5.3/lib/prim/Agda/Builtin/TrustMe.agdai).\n" t)
(agda2-info-action "*Type-checking*" "  Loading  Relation.Binary.PropositionalEquality.TrustMe (/home/abel/agda/std-lib/src/Relation/Binary/PropositionalEquality/TrustMe.agdai).\n" t)
(agda2-info-action "*Type-checking*" "  Loading  Agda.Builtin.Nat (/home/abel/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.5.3/lib/prim/Agda/Builtin/Nat.agdai).\n" t)
(agda2-info-action "*Error*" "An internal error has occurred. Please report this as a bug.\nLocation of the error: src/full/Agda/TypeChecking/Serialise/Instances/Common.hs:169\n" nil)
(agda2-status-action "")
```

**Comment by fredrikNordvallForsberg** [comment] 2017-06-12 09:31
@andreasabel Is your instance reproducible? Sounds like it could be warning serialisation-related...

**Comment by andreasabel** [comment] 2017-06-12 11:45
It seems reproducible like this:
1. get old version `e3893da0ebca8f80ca2919426529b544503d2010` of the standard library.
2. Have two files A and B containing the following single import statement:
```agda
open import Relation.Binary.PropositionalEquality
```
3. Load A
4. Load B
5. Edit A (e.g., by adding a comment) and reload

This produces the error.
Once A gives the error, it will continue giving the error upon reload until Agda is restarted.

**Comment by fredrikNordvallForsberg** [comment] 2017-06-12 13:18
Thanks, will try to take a look. 

Incidentally, the dystopian Sci-Fi intro when checking out that standard library commit is great:
> HEAD is now at e3893da... the NO_SMASHING pragma has been removed

**Comment by fredrikNordvallForsberg** [comment] 2017-06-12 15:12
Shorter testcase:

A.agda:
```
{-# REWRITE #-}
```

B.agda and C.agda:
```
import A
```

Loading first B, then C gives the error when loading C, *as long as* A has not been loaded on its own.

Doing the same from the command-line (i.e. first run `agda B.agda`, then `agda C.agda`) does *not* trigger the error.

**Comment by andreasabel** [comment] 2017-06-12 19:15
Congratulations!  I tried to construct such a case myself but failed.

**Comment by nad** [comment] 2017-06-13 11:20
```
$ cat script
#!/bin/sh

AGDA=$1

$AGDA --interaction --no-libraries <<EOF
  IOTCM "Bug.agda" None Indirect (Cmd_load "B.agda" [])
  IOTCM "Bug.agda" None Indirect (Cmd_load "C.agda" [])
EOF
$ agda-bisect --compiler <ghc-7.10.3> --good v2.5.2 --bad HEAD --script ./script --no-internal-error
[...]
9f315a6fff45da373b357dc01b0ba0b97fc499f6 is the first bad commit
commit 9f315a6fff45da373b357dc01b0ba0b97fc499f6
Author: Fredrik Nordvall Forsberg <fredrik.nordvall-forsberg@strath.ac.uk>
Date:   Sat May 13 16:35:28 2017 +0200

    [ warnings ] serialising warnings

[...]
```

**Comment by andreasabel** [comment] 2017-08-21 19:34
This bug is undead, I saw it again while playing with issue #2711 and an outdated standard library.

Depend on this library (directory `src`):
[outdated-std-lib.zip](https://github.com/agda/agda/files/1239917/outdated-std-lib.zip)

Consider this file depending on the outdated library.
```agda
open import Level
open import Data.Empty

-- This could be a handy pattern synonym, in theory:
pattern nope = lift ()

-- This works.
lift-⊥-elim : ∀{i}{A : Set i}{ℓ} → Lift {ℓ = ℓ} ⊥ -> A
lift-⊥-elim = λ { (lift ()) }

-- Works:
lift-⊥-elim2 : ∀{i}{A : Set i}{ℓ} → Lift {ℓ = ℓ} ⊥ -> A
lift-⊥-elim2 nope

-- -- But this doesn't even parse!
-- lift-⊥-elim' : ∀{i}{A : Set i}{ℓ} → Lift {ℓ = ℓ} ⊥ -> A
-- lift-⊥-elim' = λ { nope }
```
- Load it.
- Move the commented-out function higher up (still commented out).
- Load again.
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Serialise/Instances/Common.hs:177
```

**Comment by fredrikNordvallForsberg** [comment] 2017-08-21 20:22
Hm, I can't reproduce this following the instructions above... (That is, I replace my standard library `src` with the one from the zip file, and follow the instructions, but I don't get the internal error.)

I'm assuming the problem comes from the warnings generated by the outdated `COMPILED_DATA` and `HASKELL` pragmas in the old `Data.Empty`. Do you have the same problem if you import just a local file containing a warning instead? Or a local (renamed) copy of `Data.Empty` and `Level`?

**Comment by andreasabel** [comment] 2017-08-21 20:31
No, if I copy `Data.Empty` into a local file, I do not get the internal error.  I might be that the old `Data/Empty.agdai` file is important here.
Did you unpack with preserving the timestamp?

**Comment by andreasabel** [comment] 2017-08-21 20:57
Inserting a debug message I get:
```
Panic while serializing absolute path 
/home/abel/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.5.3/lib/prim/Agda/Builtin/Size.agda
The path could not be found in the dictionary:
<HashTable>
```
Mmh, HashTable does not want to show its contents...

Ok, here it is:
```
[(/home/abel/agda/std-lib/src/Level.agda,5)
,(/home/abel/tmp/agda/test/bugs/Issue2592.agda,7)
,(/home/abel/agda/std-lib/src/Data/Empty.agda,3)
,(/home/abel/.cabal/share/x86_64-linux-ghc-7.10.3/Agda-2.5.3/lib/prim/Agda/Primitive.agda,1)
]
```
Why is `Agda.Builtin.Size` even referenced!?  Or, better, where?

**Comment by fredrikNordvallForsberg** [comment] 2017-08-21 21:11
If I remember correctly the solution last time was to not serialise the path in question, hence bypassing the problem. So why are we serialising absolute paths this time?

Still no luck getting the error myself. I did unpack preserving timestamps, and the old interface files stay after loading `Bug.agda`.

**Comment by andreasabel** [comment] 2017-08-21 21:35
I can consistently reproduce the problem in Agda 2.5.3.  `currentInterfaceVersion` is July 28th, and the `Data.Empty.agdai` file is from July 29th.

**Comment by fredrikNordvallForsberg** [comment] 2017-08-21 22:00
I'm not doubting you of course, just feeling left out :-)

**Comment by fredrikNordvallForsberg** [comment] 2017-08-22 23:51
I implemented generation of the warning message at the time of throwing the warning, instead of at the time of printing it, thus bypassing the need to serialise the state and the environment.

@andreasabel, does that commit https://github.com/agda/agda/commit/c82680b241ee2a13631e7aca79db9f53201a6d1a make this problem go away for you? (Potential problem in order to find out: this necessarily updated `currentInterfaceVersion`, so the old interface files will get rebuilt now.)

**Comment by andreasabel** [comment] 2017-08-23 07:57
Confirming that the problem went away.

**Comment by fredrikNordvallForsberg** [comment] 2017-08-23 08:10
Great! Then I'll close this again.

**Closed as completed by fredrikNordvallForsberg** 2017-08-23 08:10 UTC
Labels: type: bug, serialization, regression on master, release blocker, ux: warnings

**Comment by HuStmpHrrr** [comment] 2018-09-05 16:47
Having this issue on 2.5.4.1. Which version should I use to make this problem go away?
